{
  "hash": "3cbbe43c637dc108cc239ff9f62c7fc0",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Appendix A: simulation as a way of thinking\"\nbook: Stats Hours with Itchy\nchapter: A\ntype: book-chapter\nstatus: draft\ncreated: 2026-09-06\nengines: DRM.jl 0.7.1 (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)\ntags: [book, julia, simulation, bootstrap, coverage, DRM.jl, appendix]\ndeck: \"The thread every chapter has been pulling since Class 2 without naming it: draw new data from what the model claims, and watch how much an estimate can wander before you decide to trust it.\"\nstatus_tag: Draft\nstatus_note: \"All ten classes of version 1 run from start to finish, with Appendix A, the preface and the coda. Every number and figure on this page comes out of code that was run to make the page. The writing is still a draft.\"\nprovenance: \"Every code block and printed result below was run, start to finish, when this page was made; nothing is typed from memory.\"\ncaveat: \"From the second beat onward the data are the real 2012 sparrows (data/2012/MBodySize.csv, 171 house sparrows, Lundy Island, provenance in data/2012/README.md). The opening generator is a simulated flock of sparrows built to look like that file; it is here as the appendix's first worked example of what a seed does.\"\nfooter_note: \"Stats Hours with Itchy · Appendix A of a planned 13, ten in version 1, plus a coda · draft; all code run 2026-09-06\"\n---\n\n\n# Appendix A: simulation as a way of thinking\n\n> **A note on what this appendix is.** It is not a rung. It does not free a constant the way each\n> class does. It gathers a thread that runs through every class from Class 2 on, where the \"Julia\n> stuff\" ends with one cell that draws new data from the fitted model and refits it. Here the\n> thread gets a room of its own: what a seed actually promises, what it means to simulate what a\n> model claims, what \"coverage\" means as a property you can check by counting, and the parametric\n> bootstrap as an interval built the same way.\n\n---\n\n## Objectives\n\nBy the end of this appendix you should be able to:\n\n1. Say what a random seed actually promises, and what happens the moment you change one digit of it.\n2. Draw new data from a fitted model, refit, and watch a coefficient wander, without mistaking the wander for noise you introduced by hand.\n3. Define coverage as a property of a procedure, not of one interval, and attach a Monte Carlo standard error to any coverage fraction you report.\n4. Build a parametric bootstrap interval from a set of refits, and say in one sentence when it and the ordinary estimate-plus-or-minus-two-standard-errors interval part company.\n\n---\n\n## The class\n\n**Itchy's office, later in the week. TOTO has a laptop and a mug that says \"p < 0.05 or it didn't happen\", which nobody has had the heart to correct. MOMO is reading something on her phone. EDDIE is standing, because Eddie always stands.**\n\n**Itchy:** Before the real sparrows, I want a flock I built myself, because a flock you built is the one place you know the truth. Here is a recipe for one hundred and sixteen sparrows: wing from tarsus and sex, plus noise.\n\n**Toto:** Made-up birds.\n\n**Itchy:** Made-up on purpose, and made-up in a way I can repeat, which is the point of the next ten minutes. It is where a promise gets made that the rest of this appendix is about keeping, or breaking on purpose.\n\n**Momo:** Why one you can repeat?\n\n**Itchy:** Watch.\n\n\n\n### A seed is a promise\n\n**Itchy:** Here is the recipe. The first line, `Random.seed!(316)`, is the one to keep your eye on. Watch what comes back.\n\n::: {#cell-sparrow-generator-a .cell execution_count=2}\n``` {.julia .cell-code}\nRandom.seed!(316)\nn = 116\nsex    = rand([\"female\", \"male\"], n)\ntarsus = 18.5 .+ 0.62 .* randn(n) .+ 0.25 .* (sex .== \"male\")\nwing   = 78.0 .+ 1.70 .* (tarsus .- 18.5) .+ 1.45 .* (sex .== \"male\") .+ 2.4 .* randn(n)\nflock_a = DataFrame(BirdID = 1:n, Sex = sex,\n                     Tarsus = round.(tarsus, digits = 2),\n                     Wing   = round.(wing,   digits = 1))\nfirst(flock_a, 3)\n```\n\n::: {#sparrow-generator-a .cell-output .cell-output-display execution_count=3}\n```{=html}\n<div><div style = \"float: left;\"><span>3×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">BirdID</th><th style = \"text-align: left;\">Sex</th><th style = \"text-align: left;\">Tarsus</th><th style = \"text-align: left;\">Wing</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: left;\">male</td><td style = \"text-align: right;\">18.51</td><td style = \"text-align: right;\">80.6</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: left;\">male</td><td style = \"text-align: right;\">18.49</td><td style = \"text-align: right;\">79.7</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">18.12</td><td style = \"text-align: right;\">81.5</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Momo:** Those are the made-up birds.\n\n**Itchy:** Those are the made-up birds, and here is the point of them. Without looking at the first run, I am going to run the identical code again.\n\n::: {#cell-sparrow-generator-b .cell execution_count=3}\n``` {.julia .cell-code}\nRandom.seed!(316)\nsex2    = rand([\"female\", \"male\"], n)\ntarsus2 = 18.5 .+ 0.62 .* randn(n) .+ 0.25 .* (sex2 .== \"male\")\nwing2   = 78.0 .+ 1.70 .* (tarsus2 .- 18.5) .+ 1.45 .* (sex2 .== \"male\") .+ 2.4 .* randn(n)\nflock_b = DataFrame(BirdID = 1:n, Sex = sex2,\n                     Tarsus = round.(tarsus2, digits = 2),\n                     Wing   = round.(wing2,   digits = 1))\nflock_a.Wing == flock_b.Wing\n```\n\n::: {#sparrow-generator-b .cell-output .cell-output-display execution_count=4}\n```\ntrue\n```\n:::\n:::\n\n\n\n\n**Itchy:** true. Every one of 116 birds, identical to the decimal place. The first bird's wing was 80.6 mm both times. That is the whole promise a seed makes: not \"random\", but \"reproducible on purpose\". Anyone with this file, this Julia version and this line gets my exact flock back, forever.\n\n**Toto:** So it is not really random.\n\n**Itchy:** It is exactly as random as a shuffled deck someone photographed before they shuffled it. The shuffle is real. The photograph means we can all argue about the same deck. Now watch me break the promise on purpose, by changing one digit.\n\n::: {#cell-sparrow-generator-c .cell execution_count=5}\n``` {.julia .cell-code}\nRandom.seed!(317)\nsex3    = rand([\"female\", \"male\"], n)\ntarsus3 = 18.5 .+ 0.62 .* randn(n) .+ 0.25 .* (sex3 .== \"male\")\nwing3   = 78.0 .+ 1.70 .* (tarsus3 .- 18.5) .+ 1.45 .* (sex3 .== \"male\") .+ 2.4 .* randn(n)\nflock_c = DataFrame(BirdID = 1:n, Sex = sex3,\n                     Tarsus = round.(tarsus3, digits = 2),\n                     Wing   = round.(wing3,   digits = 1))\nflock_a.Wing == flock_c.Wing\n```\n\n::: {#sparrow-generator-c .cell-output .cell-output-display execution_count=7}\n```\nfalse\n```\n:::\n:::\n\n\n\n\n**Eddie:** `316` to `317`. One digit.\n\n**Itchy:** One digit, and false. The first bird went from 80.6 mm to 77.5 mm, and every bird after it is a different bird too, not a slightly adjusted version of the old one. There is no such thing as \"close\" here. A seed either reproduces a flock exactly, or it hands you a flock that shares nothing with the last one except the recipe that built it. That is the whole of what a seed is, and it is the fact this entire appendix depends on: I am about to draw two hundred flocks on purpose, and I need every one of you to be able to get the same two hundred back.\n\n---\n\n## Simulate what the model claims\n\n**Itchy:** Enough of the made-up birds. Load the real ones.\n\n::: {#cell-load-real-data .cell execution_count=7}\n``` {.julia .cell-code}\nraw = CSV.read(\"../data/2012/MBodySize.csv\", DataFrame)\nsparrows = select(raw, :BirdID, :Tarsus, :Wing)\nnrow(sparrows)\n```\n\n::: {#load-real-data .cell-output .cell-output-display execution_count=10}\n```\n171\n```\n:::\n:::\n\n\n**Momo:** This is `fit1` from Class 2.\n\n::: {#cell-fit-appA .cell execution_count=8}\n``` {.julia .cell-code}\nfit_appA = drm(bf(@formula(Wing ~ Tarsus)), Gaussian(); data = sparrows)\ntrue_slope = coef(fit_appA, :mu)[2]\ncoeftable(fit_appA)\n```\n\n::: {#fit-appa .cell-output .cell-output-display .cell-output-markdown execution_count=11}\n|                    |  Estimate | Std.Error |     z | Pr(>\\|z\\|) | Lower 95% | Upper 95% |\n|:-------------------|----------:|----------:|------:|:-----------|:----------|----------:|\n| mu: (Intercept)    | 55.4569   | 3.56377   | 15.56 |     <1e-53 | 48.472    | 62.4417 |\n| mu: Tarsus         |  1.20311  | 0.191294  |  6.29 |     <1e-09 |  0.828182 |  1.57804 |\n| sigma: (Intercept) |  0.631739 | 0.0540738 | 11.68 |     <1e-30 |  0.525757 |  0.737722 |\n:::\n:::\n\n\n\n\n**Itchy:** The tarsus slope is 1.203. In Class 2 we treated that as the answer and moved on. Here I want to treat it as a claim, and ask the model to defend it. If the model is right about how these birds were generated, and I draw brand-new birds from that same claim, refitting should give me back something close to 1.203, wobbling by an amount the model itself can tell me about.\n\n::: {#cell-refit-200 .cell execution_count=10}\n``` {.julia .cell-code}\nrng_sim = MersenneTwister(100100)   # a seed is a promise: anyone who runs this line gets the same draw\nsims = simulate(fit_appA; nsim = 200, rng = rng_sim)\n\nfunction refit_once(y)\n    d = DataFrame(Tarsus = sparrows.Tarsus, Wing = y)\n    f = drm(bf(@formula(Wing ~ Tarsus)), Gaussian(); data = d)\n    ci = confint(f)\n    (slope = coef(f, :mu)[2], lower = ci[2].lower, upper = ci[2].upper)\nend\n\nrefits = with_logger(NullLogger()) do\n    [refit_once(sims[:, k]) for k in 1:size(sims, 2)]\nend\n\nslopes = [r.slope for r in refits]\nlos    = [r.lower for r in refits]\nhis    = [r.upper for r in refits]\nlength(slopes)\n```\n\n::: {#refit-200 .cell-output .cell-output-display execution_count=14}\n```\n200\n```\n:::\n:::\n\n\n\n\n**Toto:** Two hundred fits from two hundred flocks that do not exist.\n\n**Itchy:** Two hundred flocks the model itself says could have existed, which is a different thing from not existing. Mean of the refitted slopes: 1.188. Spread of the refitted slopes: 0.196. That spread is not a mistake and not noise I introduced. It is what \"uncertainty in a slope\" actually looks like when you stop trusting one number and watch two hundred.\n\n::: {#cell-fig-slope-wander .cell execution_count=12}\n``` {.julia .cell-code}\nfig1 = Figure(size = (480, 360))\nax1 = Axis(fig1[1, 1]; xlabel = \"refitted tarsus slope\", ylabel = \"count\",\n    title = \"the slope, redrawn 200 times\")\nhist!(ax1, slopes; bins = 25)\nvlines!(ax1, [true_slope]; color = :black, linewidth = 2, label = \"fitted slope\")\naxislegend(ax1; position = :rt)\nfig1\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n![Tarsus slope refitted on 200 parametric draws from the fitted model; vertical line at the original fitted slope.](appendix-a-simulation_files/figure-html/fig-slope-wander-output-1.svg){#fig-slope-wander}\n:::\n:::\n\n\n**Eddie:** It is centred on the real fit.\n\n**Itchy:** It should be. The real fit *is* the generator. That is the whole trick of \"simulate what the model claims\": you are not testing whether the model is correct about the birds, you are testing whether the model is being consistent with itself, which is a smaller claim and a useful one on its own.\n\n### The trap, once\n\n**Toto:** *(comparing numbers)* The raw spread of one simulated column does not match σ.\n\n::: {#cell-subtraction-trap .cell execution_count=13}\n``` {.julia .cell-code}\nraw_spread = std(sims[:, 1])\ndev_spread = std(sims[:, 1] .- fitted(fit_appA))\ndev_all  = [std(sims[:, k] .- fitted(fit_appA)) for k in 1:size(sims, 2)]\ndev_mean = mean(dev_all)\n```\n\n::: {#subtraction-trap .cell-output .cell-output-display execution_count=18}\n```\n1.8793004431400513\n```\n:::\n:::\n\n\n\n\n**Itchy:** σ is 1.881. The raw spread of that one simulated column is 2.286, which looks nothing like it, and if you stopped there you would conclude the model cannot reproduce its own noise. It can. Each simulated column still carries `fit_appA`'s fitted mean, tarsus and all, so its raw spread is close to the *raw* wing spread, not σ. Subtract the fitted mean first, and only then are you looking at noise alone: 2.124. That is not σ to the decimal place, and it should not be: it is one column of two hundred, and a single column's spread wobbles around σ by chance. Do it for all two hundred and average, and it lands on 1.879, a hair from σ and no longer at the mercy of which column you happened to pick. One subtraction, one trap avoided, and I want you to feel where it bites: it looks exactly like a broken model until you remember what a simulated column actually contains.\n\n---\n\n## Coverage as a check on an interval\n\n**Momo:** Every refit came with a confidence interval. Two hundred of them, sitting there unused.\n\n**Itchy:** Not unused. About to earn their keep. A 95 percent interval is usually described to students as \"we are 95 percent confident the true value is in here\", which is not what it means and cannot be checked from one interval alone. Here is what it actually claims, and here is why we can check it: if I build this same kind of interval on flock after flock drawn from a known truth, the *procedure* should catch that truth about 95 times in 100. Not this interval. The procedure.\n\n<!-- eq: hand-typed -->\n\n> **coverage = (1/R) Σ 1[low_r ≤ β ≤ high_r],  SE(coverage) = sqrt( coverage · (1 − coverage) / R )**\n\n**Itchy:** *R* replicates, one indicator per replicate for \"did this interval catch the true slope\", averaged. We know the true slope here, because we chose it: it is `fit_appA`'s own slope, the thing every one of the two hundred flocks was drawn to be consistent with. The interval `confint` gives you is the plain kind, the estimate plus or minus about two standard errors; statisticians call it a Wald interval, that is the name you will meet in other people's methods sections, and we will meet a rival to it in a minute. \"Nominal\" in the printout is the rate the interval claims for itself.\n\n::: {#coverage-check .cell execution_count=15}\n``` {.julia .cell-code}\ncovered = [(lo <= true_slope <= hi) for (lo, hi) in zip(los, his)]\nnrep = length(covered)\ncoverage_rate = mean(covered)\nmcse_cov = sqrt(coverage_rate * (1 - coverage_rate) / nrep)\n\n@printf(\"replicates                         : %d\\n\", nrep)\n@printf(\"plain (Wald) interval covers slope : %.4f  +/- %.4f  (nominal: 0.9500)\\n\",\n        coverage_rate, mcse_cov)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nreplicates                         : 200\nplain (Wald) interval covers slope : 0.9350  +/- 0.0174  (nominal: 0.9500)\n```\n:::\n:::\n\n\n\n\n**Toto:** 0.935. That is not `0.95`.\n\n**Itchy:** It is not exactly `0.95`, and it should not be. That plus-or-minus is the Monte Carlo standard error: the wobble in the fraction that comes only from having used two hundred flocks rather than infinitely many. 0.935 with a Monte Carlo standard error of 0.0174 is what \"consistent with 95 percent\" looks like at two hundred replicates. Report a coverage fraction without its own standard error and you have handed someone a number with no way to tell noise from a real problem. That is a rule for the rest of this course, not only for today.\n\n**Eddie:** So a coverage study is just this, run at the scale of a real question.\n\n**Itchy:** Exactly this, at the scale of a real question, and usually asking \"does the interval still cover when I change something about the design\", not \"does it cover at all\". The rival to it I promised is next.\n\n---\n\n## The parametric bootstrap\n\n**Itchy:** The two hundred refits are also, quietly, an interval of their own. Not from the standard errors this time; from where the estimates themselves landed: the value that two and a half percent of the refitted slopes fall below, and the value that two and a half percent fall above. That is a bootstrap interval, and \"parametric\" because the new flocks came from the fitted model rather than from reshuffling the real rows.\n\n<!-- eq: hand-typed -->\n\n> **bootstrap interval = [ Q₀.₀₂₅(slope₁, …, slope_R),  Q₀.₉₇₅(slope₁, …, slope_R) ]**\n\n::: {#bootstrap-ci .cell execution_count=17}\n``` {.julia .cell-code}\nboot_lo, boot_hi = quantile(slopes, [0.025, 0.975])\nwald = confint(fit_appA)\nwald_lo, wald_hi = wald[2].lower, wald[2].upper\n\n@printf(\"plain (Wald) interval : [%.4f, %.4f]\\n\", wald_lo, wald_hi)\n@printf(\"bootstrap interval    : [%.4f, %.4f]\\n\", boot_lo, boot_hi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nplain (Wald) interval : [0.8282, 1.5780]\nbootstrap interval    : [0.8329, 1.5728]\n```\n:::\n:::\n\n\n\n\n::: {#cell-fig-wald-vs-boot .cell execution_count=19}\n``` {.julia .cell-code}\nfig2 = Figure(size = (480, 360))\nax2 = Axis(fig2[1, 1]; xticks = (1:2, [\"Wald\", \"bootstrap\"]),\n    ylabel = \"tarsus slope\", title = \"two ways to an interval\")\nrangebars!(ax2, [1], [wald_lo], [wald_hi]; whiskerwidth = 12, color = Cycled(1))\nscatter!(ax2, [1], [true_slope]; markersize = 10, color = Cycled(1))\nrangebars!(ax2, [2], [boot_lo], [boot_hi]; whiskerwidth = 12, color = Cycled(2))\nscatter!(ax2, [2], [mean(slopes)]; markersize = 10, color = Cycled(2))\nfig2\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n![Wald interval on the real fit against the parametric-bootstrap interval, both from the same 200 refits.](appendix-a-simulation_files/figure-html/fig-wald-vs-boot-output-1.svg){#fig-wald-vs-boot}\n:::\n:::\n\n\n**Momo:** Wald gives 0.828 to 1.578. Bootstrap gives 0.833 to 1.573. Those are almost the same interval.\n\n**Itchy:** They are, here, and that agreement is itself the finding, not a formality on the way to a more interesting one. One honest sentence, and hold on to it: the two intervals agree closely exactly when the thing being estimated is far from any boundary and its sampling distribution — the spread of values the estimate would take if you repeated the study over and over — is close to symmetric, the way a slope from a hundred and seventy-one birds is; they pull apart hardest for a parameter that is skewed, or pinned against a wall it cannot cross, and that is not a hypothetical case; it is what Class 8 asks you to estimate.\n\n---\n\n## Where this thread earns its keep\n\n**Toto:** So all of this was practice.\n\n**Itchy:** All of this was practice on a parameter with nowhere awkward to go. A slope can be negative, positive, anything on the real line, and its sampling distribution knows it. A variance component cannot be negative, and when the truth sits at or near zero the estimate piles up exactly on the boundary, and the naive test built for the easy case gets the wrong answer with total confidence. You already have the tool for that. It is the function `simulate` called on a fitted model, refit two hundred or two thousand times, and counted, exactly as above. Class 8 runs precisely this procedure on a variance component instead of a slope, and that is where a naive test would have quietly lied to you, and where the correction earns a whole class instead of an appendix.\n\n**Momo:** *(closing the laptop)* A seed, a refit loop and a count. That is most of what statistics turns out to be.\n\n**Itchy:** Most of what *checking* statistics turns out to be, which is not the same claim, but it is the one I actually believe.\n\n---\n\n## Summary\n\n### Stats stuff\n\n- **A seed is a promise, not an apology.** `Random.seed!(k)` fixes the sequence the computer's random-number recipe produces (it is a recipe, which is why it can be repeated); the same seed on the same code reproduces the same data exactly, anywhere, forever. Change one digit of the seed and every downstream number changes, with nothing \"close\" about the result.\n- **Simulate what the model claims.** Treat the fitted model as a generator of new data, draw from it, and refit. This checks the model's internal consistency, not whether it is the correct model for the world; a coefficient's spread across refits is what \"uncertainty in that coefficient\" concretely looks like.\n- **The fitted-subtraction trap.** A simulated response still carries the model's fitted mean structure. Its raw spread reflects that mean structure, not σ alone; subtract the fitted values first before comparing spreads, or a correct model will look broken.\n- **Coverage.** A property of a *procedure*, checked by repetition: across many draws from a known truth, what fraction of the resulting intervals actually contain that truth. Never report a coverage fraction without its own Monte Carlo standard error, `sqrt(p(1 − p)/R)`.\n- **The parametric bootstrap.** An interval built from where a set of refits actually land (empirical quantiles of the estimate), rather than from a standard error and a normal reference. It agrees closely with a Wald interval when the estimator is far from a boundary and roughly symmetric, and diverges from it when the estimator is not, which is exactly the situation Class 8's variance component is in.\n\n### Julia stuff\n\n- `Random.seed!(k)`: fixes the global random-number generator's state. Call it once, immediately before the code whose randomness you want reproducible. The book's own code, in every class, does not touch the global generator at all — they build an explicit `MersenneTwister(k)` and pass it as `rng` to `rand` and `simulate`, so a cell's reproducibility does not depend on what ran before it.\n- `rand(collection, n)`: `n` draws with replacement from a collection, here `[\"female\", \"male\"]`.\n- `simulate(fit; nsim = k)` (the keyword is spelled as in R): `k` fresh response draws from a fitted model, `nobs × k`, conditional on the fitted mean and dispersion structure.\n- `fitted(fit)`, `sigma(fit)`: the fitted mean vector and the residual scale, needed to check a simulated column against the model it came from.\n- `confint(fit)`: per-parameter `(lower, upper)` named tuples; index by parameter position within the relevant sub-model.\n- `with_logger(NullLogger()) do ... end`: run a block, here two hundred refits, without the repeated convergence chatter each one would otherwise print.\n- `mean`, `std`, `quantile(v, [p1, p2])`: from `Statistics`, the building blocks of both the coverage count and the bootstrap interval.\n- `@printf`: from `Printf`, for reporting a rate or an interval with a stated number of decimal places rather than whatever Julia's default show happens to choose.\n\n---\n\n## Further reading\n\n*Graded by depth.*\n\n1. **Sandve, G. K., Nekrutenko, A., Taylor, J. & Hovig, E. (2013) \"Ten simple rules for reproducible computational research\", *PLoS Computational Biology* 9(10):e1003285.** Start here, not with the mathematics. Rule 1 is essentially \"for every result, keep the seed\", which is the whole first half of this appendix in one sentence written for a much wider audience than statisticians.\n2. **Efron, B. (1979) \"Bootstrap methods: another look at the jackknife\", *The Annals of Statistics* 7(1).** The paper that invented the idea this appendix's fourth beat uses: build an interval from where resampled or resimulated estimates actually land, rather than from a formula and a normal reference. Read it for the original motivating examples, which are smaller and stranger than the method's later reputation suggests.\n3. **Davison, A. C. & Hinkley, D. V. (1997) *Bootstrap Methods and Their Application*, Cambridge University Press.** The standard book-length treatment, including the parametric case used here (resampling from a fitted model rather than from the data directly) and a careful account of when a bootstrap interval and a Wald interval should be expected to disagree.\n4. **Morris, T. P., White, I. R. & Crowther, M. J. (2019) \"Using simulation studies to evaluate statistical methods\", *Statistics in Medicine* 38(11):2074-2102.** How to turn \"simulate and refit\" from a demonstration into a real study: what to vary, what to record, and how to report a coverage fraction properly, with its Monte Carlo standard error, every time.\n\n---\n\n## Exercises\n\nUse your own organism where one is named. **For every question, paste your code and then explain in your own words what each line does**, as if to somebody who has read this appendix and nothing past it.\n\n1. **Break the promise carefully.** Run the appendix's sparrow generator with `Random.seed!(316)` and again with `Random.seed!(3160)`. Report whether the two flocks match. Then explain in one sentence why \"0\" appended to a seed is just as different a seed as any other digit, even though it looks like a small change.\n\n2. **Simulate your own model.** Fit `Wing ~ Tarsus + Sex` from Class 2 (`fit2`), simulate 200 new flocks from it, and refit each. Report the mean and spread of the refitted `Sex` coefficient. Is the spread bigger or smaller than the tarsus slope's spread in this appendix, and can you say why using the standard errors Class 2 already printed?\n\n3. **Coverage at a different level.** Using the same 200 refits from this appendix, compute the coverage of the 80 percent interval instead of the 95 percent one (you will need `confint` at a different level, or to build the interval from the standard error and a different critical value by hand). Report the coverage with its Monte Carlo standard error and say whether it is closer to nominal or further from it than the 95 percent case, and whether that surprises you.\n\n4. **Bootstrap versus Wald, on purpose.** Using `fit2` from Class 2, simulate and refit 200 times, then compare the Wald and bootstrap intervals for the `Sex` coefficient, the way this appendix did for the tarsus slope. Report both intervals. Are they closer together or further apart than the tarsus-slope pair, and does that match the \"far from a boundary, roughly symmetric\" rule this appendix gave for when the two should agree?\n\n5. **A seed of your own choosing.** Pick a seed using any rule you like (a birthday, a phone number, the current year), simulate 200 flocks from `fit_appA`, and report the coverage of the 95 percent interval you get. Then repeat with a different seed. Do the two coverage fractions agree to within their Monte Carlo standard errors? Write one sentence about what would have to be true for them not to.\n\n",
    "supporting": [
      "appendix-a-simulation_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}