{
  "hash": "86feeff4f0736e4b838701221a67d25a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Class 6: rows are not strangers\"\nbook: Stats Hours with Itchy\nchapter: 6\ntype: book-chapter\nstatus: draft\ncreated: 2026-09-06\nengines: DRM.jl 0.7.1 (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)\ntags: [book, julia, random-intercept, repeatability, ICC, DRM.jl]\ndeck: \"Four hundred and fifty-nine measurements, one hundred and seventy-one sparrows, and a standard error that was wrong by nearly a quarter until somebody noticed the same bird was in the file four times.\"\nstatus_tag: Draft\nstatus_note: \"All ten classes of version 1 run from start to finish, with Appendix A, the preface and the coda. Every number and figure on this page comes out of code that was run to make the page. The writing is still a draft.\"\nprovenance: \"Every block of Julia on this page was run, and its output printed, when the page was made — including the error. Nothing is pasted in from memory. The one block of R output was run once by hand, on 2026-09-06, on the same data file, and is labelled as such where it appears.\"\ncaveat: \"The data are real. These are the Lundy Island house sparrows of the author's 2012 course, read directly from the archived data/2012/BodySize.csv with its repeated measurements intact (provenance in data/2012/README.md). Nothing here is simulated.\"\nfooter_note: \"Stats Hours with Itchy · Class 6 of a planned 13, ten in version 1, plus a coda · draft; all code run 2026-09-06\"\n---\n\n\n# Class 6: rows are not strangers\n\n> **A note on the data, and it is a short one for once.** Class 2 used one row per bird. This\n> chapter uses the file that Class 2's file was made *from*, with every measurement still in\n> it, because the repeated measurements are the entire subject of the hour. They are real\n> house sparrows, really measured more than once. The only thing this chapter does to them\n> is drop the rows where the measurement of interest is missing, in a cell, in front of you.\n\n---\n\n## Objectives\n\nBy the end of this class you should be able to:\n\n1. Recognise, from the data file alone, when your rows are not independent, and say what independence was buying the model.\n2. Fit a random intercept with `(1 | group)` and read the second variance component it prints.\n3. Say what happens to a standard error when you stop pretending repeated measurements are separate individuals, and predict the direction before you fit.\n4. Compute a repeatability as a ratio of variance components, and say what it is a ratio *of*.\n5. Explain what a random intercept is by describing the shrinkage picture, without using the word \"random\".\n\n---\n\n## The class\n\n**Itchy's office, 9:00 am. TOTO has arrived with a laptop and an air of having already done the homework, which is always the dangerous state. MOMO is reading the data file itself rather than the output, which is the safe one. EDDIE is here because Class 6 is the week he has been waiting for.**\n\n**Itchy:** Class 2 gave you one line through a cloud of sparrows. Every bird was one dot. Today I am giving you the file that cloud was built from, and it has more rows in it than it has birds.\n\n**Toto:** More rows than birds.\n\n**Itchy:** Considerably more. We caught these birds more than once. Load it and look before you model, same as always.\n\n::: {#cell-setup .cell execution_count=1}\n``` {.julia .cell-code}\ninclude(\"../tools/figures.jl\")\nusing DRM, DataFrames, CSV, Statistics, LinearAlgebra, Random, Printf, CairoMakie\nset_theme!(theme_itchy(:light))\n\nraw = CSV.read(\"../data/2012/BodySize.csv\", DataFrame)\n\nprintln(\"rows, columns: \", size(raw))\nprintln(\"distinct birds: \", length(unique(raw.BirdID)))\nfirst(raw, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows, columns: (460, 8)\ndistinct birds: 171\n```\n:::\n\n::: {#setup .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div><div style = \"float: left;\"><span>6×8 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">BirdID</th><th style = \"text-align: left;\">Sex</th><th style = \"text-align: left;\">Tarsus</th><th style = \"text-align: left;\">BillL</th><th style = \"text-align: left;\">BillW</th><th style = \"text-align: left;\">Tail</th><th style = \"text-align: left;\">Wing</th><th style = \"text-align: left;\">Weight</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String7\" style = \"text-align: left;\">String7</th><th title = \"String1\" style = \"text-align: left;\">String1</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"String7\" style = \"text-align: left;\">String7</th><th title = \"String3\" style = \"text-align: left;\">String3</th><th title = \"String7\" style = \"text-align: left;\">String7</th><th title = \"String7\" style = \"text-align: left;\">String7</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">TA14502</td><td style = \"text-align: left;\">F</td><td style = \"text-align: right;\">18.8</td><td style = \"text-align: left;\">13.1</td><td style = \"text-align: left;\">6.5</td><td style = \"text-align: left;\">52.3</td><td style = \"text-align: left;\">72.7</td><td style = \"text-align: right;\">26.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">TA14502</td><td style = \"text-align: left;\">F</td><td style = \"text-align: right;\">18.2</td><td style = \"text-align: left;\">13.3</td><td style = \"text-align: left;\">6.6</td><td style = \"text-align: left;\">51</td><td style = \"text-align: left;\">71</td><td style = \"text-align: right;\">27.3</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">TA14502</td><td style = \"text-align: left;\">F</td><td style = \"text-align: right;\">18.3</td><td style = \"text-align: left;\">13.4</td><td style = \"text-align: left;\">6.5</td><td style = \"text-align: left;\">52</td><td style = \"text-align: left;\">71</td><td style = \"text-align: right;\">29.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">TA14505</td><td style = \"text-align: left;\">F</td><td style = \"text-align: right;\">18.1</td><td style = \"text-align: left;\">13</td><td style = \"text-align: left;\">6.3</td><td style = \"text-align: left;\">58</td><td style = \"text-align: left;\">75</td><td style = \"text-align: right;\">30.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">TA14505</td><td style = \"text-align: left;\">F</td><td style = \"text-align: right;\">18.0</td><td style = \"text-align: left;\">13.2</td><td style = \"text-align: left;\">6.1</td><td style = \"text-align: left;\">57</td><td style = \"text-align: left;\">77.5</td><td style = \"text-align: right;\">26.4</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">TA14505</td><td style = \"text-align: left;\">F</td><td style = \"text-align: right;\">18.2</td><td style = \"text-align: left;\">12.8</td><td style = \"text-align: left;\">6</td><td style = \"text-align: left;\">57</td><td style = \"text-align: left;\">77</td><td style = \"text-align: right;\">25.8</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Toto:** The first three rows are the same bird.\n\n**Itchy:** The first three rows are the same bird on three different days. Fit it anyway. I want you to make the mistake in public, because it is the most common mistake in the whole of behavioural ecology and you will not respect it until you have made it.\n\n::: {#first-attempt .cell execution_count=2}\n``` {.julia .cell-code}\ndrm(bf(@formula(Wing ~ Tarsus)), Gaussian(); data = raw)\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>MethodError: no method matching Float64(::String7)\n\nClosest candidates are:\n  Float64(<span class=\"ansi-bright-red-fg\">::IrrationalConstants.Sqrt4π</span>)\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-magenta-fg\">IrrationalConstants</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/IrrationalConstants/RokwY/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">macro.jl:111</span>\n  Float64(<span class=\"ansi-bright-red-fg\">::UInt8</span>)\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-bright-black-fg\">Base</span> <span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">float.jl:165</span>\n  Float64(<span class=\"ansi-bright-red-fg\">::IrrationalConstants.Quartπ</span>)\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-magenta-fg\">IrrationalConstants</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/IrrationalConstants/RokwY/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">macro.jl:111</span>\n  ...\n\n\nStacktrace:\n [1] <span class=\"ansi-bold\">_coerce_response_column</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">raw</span>::PooledArrays.PooledVector<span class=\"ansi-bright-black-fg\">{String7, UInt32, Vector{UInt32}}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_core.jl:313</span>\n [2] <span class=\"ansi-bold\">_design</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">response</span>::Symbol, <span class=\"ansi-bright-black-fg\">rhs</span>::StatsModels.Term, <span class=\"ansi-bright-black-fg\">data</span>::DataFrame<span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_core.jl:349</span>\n [3] <span class=\"ansi-bold\">drm</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">f</span>::DrmFormula, <span class=\"ansi-bright-black-fg\">fam</span>::Gaussian; <span class=\"ansi-bright-black-fg\">data</span>::DataFrame, <span class=\"ansi-bright-black-fg\">K</span>::Nothing, <span class=\"ansi-bright-black-fg\">A</span>::Nothing, <span class=\"ansi-bright-black-fg\">tree</span>::Nothing, <span class=\"ansi-bright-black-fg\">coords</span>::Nothing, <span class=\"ansi-bright-black-fg\">g_tol</span>::Float64, <span class=\"ansi-bright-black-fg\">algorithm</span>::Symbol, <span class=\"ansi-bright-black-fg\">method</span>::Symbol, <span class=\"ansi-bright-black-fg\">profile_ci</span>::Bool, <span class=\"ansi-bright-black-fg\">phylo_coupled</span>::Bool, <span class=\"ansi-bright-black-fg\">penalty</span>::Nothing, <span class=\"ansi-bright-black-fg\">sparse</span>::Nothing, <span class=\"ansi-bright-black-fg\">impute</span>::Nothing, <span class=\"ansi-bright-black-fg\">missing</span>::Nothing<span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_core.jl:473</span>\n [4] top-level scope\n<span class=\"ansi-bright-black-fg\">   @</span> <span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">In[3]:1</span></pre>\n```\n:::\n\n:::\n:::\n\n\n**Toto:** That is not the mistake I expected to make.\n\n**Itchy:** No, that is a different one, and it is real data teaching you its first lesson before you get to the statistics. Read the first line of the error and stop there: everything printed below it is Julia's own map of where inside the engine it stopped, written for the engine's authors and not for you. The first line says it wants a number and it was handed a piece of text. Momo, you were reading the file. Why is a wing length a piece of text?\n\n**Momo:** Because one of them is not a number. It says `NA`.\n\n**Itchy:** It says `NA`, in a file written in 2009, by a person, in a program that wrote missing values that way. Julia read the whole column as text because one cell in it was text, and then the model refused the column. Tell the reader what `NA` means and it becomes a number again.\n\n::: {#cell-read-clean .cell execution_count=3}\n``` {.julia .cell-code}\nraw = CSV.read(\"../data/2012/BodySize.csv\", DataFrame; missingstring = \"NA\")\nprintln(\"missing values per column:\")\nprintln(describe(raw, :nmissing))\n\nsparrows = dropmissing(raw, [:Tarsus, :Wing])\nmkpath(\"../data/ch6\")\nCSV.write(\"../data/ch6/sparrows-repeated.csv\", sparrows)\n\nn = nrow(sparrows)\nbirds = length(unique(sparrows.BirdID))\ndropped = nrow(raw) - n\n\n@printf(\"kept %d rows on %d birds; dropped %d row for a missing wing\\n\", n, birds, dropped)\ndescribe(sparrows[!, [:Tarsus, :Wing]], :mean, :std, :min, :max)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmissing values per column:\n8×2 DataFrame\n Row │ variable  nmissing \n     │ Symbol    Int64    \n─────┼────────────────────\n   1 │ BirdID           0\n   2 │ Sex              0\n   3 │ Tarsus           0\n   4 │ BillL            9\n   5 │ BillW            9\n   6 │ Tail            14\n   7 │ Wing             1\n   8 │ Weight           0\nkept 459 rows on 171 birds; dropped 1 row for a missing wing\n```\n:::\n\n::: {#read-clean .cell-output .cell-output-display execution_count=4}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">std</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Symbol\" style = \"text-align: left;\">Symbol</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Tarsus</td><td style = \"text-align: right;\">18.6336</td><td style = \"text-align: right;\">0.771438</td><td style = \"text-align: right;\">16.8</td><td style = \"text-align: right;\">20.8</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Wing</td><td style = \"text-align: right;\">77.863</td><td style = \"text-align: right;\">2.27455</td><td style = \"text-align: right;\">67.0</td><td style = \"text-align: right;\">88.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Itchy:** 459 rows. 171 birds. Momo, say the ratio out loud.\n\n**Momo:** Under three measurements per bird, on average.\n\n**Itchy:** And not the same number for every bird, which will matter in about forty minutes. Count them.\n\n::: {#per-bird .cell execution_count=4}\n``` {.julia .cell-code}\nper_bird = combine(groupby(sparrows, :BirdID), nrow => :k)\ncounts = sort(unique(per_bird.k))\n\nfor k in counts\n    @printf(\"%d birds measured %d times\\n\", count(==(k), per_bird.k), k)\nend\nmean_k = mean(per_bird.k)\n@printf(\"\\nmean measurements per bird: %.4f\\n\", mean_k)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n85 birds measured 2 times\n55 birds measured 3 times\n31 birds measured 4 times\n\nmean measurements per bird: 2.6842\n```\n:::\n:::\n\n\n**Toto:** So some birds are in the file twice and some four times.\n\n**Itchy:** Which means that if you treat rows as individuals, some sparrows get four votes and some get two. Look at what that actually looks like. A handful of birds, picked at even intervals through the range so I am not choosing my evidence, with each bird's own measurements joined up.\n\n::: {#cell-fig-by-bird .cell execution_count=5}\n``` {.julia .cell-code}\n# Birds at even intervals through the ordering by mean wing length, so the\n# choice of which to show is a rule and not a preference.\nbird_ids = sort(unique(sparrows.BirdID))\nbird_mean = [mean(sparrows.Wing[sparrows.BirdID .== b]) for b in bird_ids]\nshown = bird_ids[sortperm(bird_mean)][1:14:length(bird_ids)]\n\nfig = Figure(size = (520, 380))\nax = Axis(fig[1, 1]; xlabel = \"tarsus (mm)\", ylabel = \"wing (mm)\",\n    title = \"the same $(length(shown)) birds, measured again and again\")\nscatter!(ax, sparrows.Tarsus, sparrows.Wing; markersize = 5, color = (:grey, 0.35))\nfor (i, b) in enumerate(shown)\n    rows = sparrows.BirdID .== b\n    # dots and this bird's own line share one colour source (the 4-colour house\n    # cycle), so a bird's line is never a different hue from its own points\n    scatter!(ax, sparrows.Tarsus[rows], sparrows.Wing[rows];\n        markersize = 11, color = Cycled(mod1(i, 4)))\n    lines!(ax, sparrows.Tarsus[rows], sparrows.Wing[rows];\n        color = Cycled(mod1(i, 4)), alpha = 0.55, linewidth = 1)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n![Wing against tarsus for every measurement in grey, with a handful of birds picked at even intervals through the ordering by mean wing length highlighted in colour, each bird's own recaptures joined in order. A bird's joined points sit close together and move together — the repeated-measures structure the whole chapter is about, visible before any model is fitted.](wk6-random-intercepts_files/figure-html/fig-by-bird-output-1.svg){#fig-by-bird}\n:::\n:::\n\n\n**Eddie:** The joined-up points are tight. A bird stays roughly where it was.\n\n**Itchy:** A bird stays roughly where it was. Hold on to that sentence, because by the end of the hour we will have put a number on it and given the number a name.\n\n### The model that pretends\n\n**Itchy:** First, the model Class 2 taught you, on all 459 rows, as if they were 459 separate sparrows.\n\n::: {#cell-fit-lm .cell execution_count=6}\n``` {.julia .cell-code}\nlm_fit = drm(bf(@formula(Wing ~ Tarsus)), Gaussian(); data = sparrows)\nlm_fit\n```\n\n::: {#fit-lm .cell-output .cell-output-display execution_count=9}\n```\nDistributional regression fit (Gaussian)\n  nobs = 459   logLik = -988.6935   converged = true\n  Residual SD (response scale) = 2.0856   dof_residual = 456\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  56.0685     2.3560  23.7983  3.48e-125\n  Tarsus        1.1696     0.1263   9.2586  2.071e-20\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                Coef.  Std.Error        z    Pr(>|z|)\n  (Intercept)  0.7351     0.0330  22.2718  6.941e-110\n```\n:::\n:::\n\n\n**Toto:** It worked, and the slope looks sensible. The scale block has a *p*-value, and I am ignoring it on purpose, because the heading says its null is σ = 1 and Class 2 taught me that is a question about millimetres rather than about birds.\n\n**Itchy:** The slope *is* sensible. The slope is not the problem and it will barely move all morning. Momo, you have been quiet.\n\n**Momo:** My problem is the sentence underneath it. Class 2 said every wing is drawn from its own normal distribution, the centre slides along a line, the width is constant. That sentence has a fourth claim hiding in it that nobody said out loud.\n\n**Itchy:** Say it out loud, then.\n\n**Momo:** That the draws are independent. That knowing one row tells you nothing about the next one.\n\n**Itchy:** *(writes on the board)*\n\n> **μ is where the birds are. σ is how spread out they are. And every model so far has quietly added: and no two rows know each other.**\n\n**Itchy:** That is the constant this class frees. Not the link, not the variance function, not the slope. The **correlation between rows, which every model up to now has held at zero**. And in this file it is obviously not zero, because two rows from the same bird are two measurements of one wing.\n\n### The model that does not\n\n**Itchy:** Here is the whole change. One term.\n\n<!-- eq: hand-typed; replace with equations(fit) when Symbolizer.jl lands -->\n\n> **μ_ij = β0 + β1 x_ij + u_j, with u_j ~ N(0, σ_u²) and y_ij ~ N(μ_ij, σ²)**\n\n**Itchy:** Measurement *i* on bird *j*. β0 the intercept, β1 the slope on tarsus, and u_j the bird's own nudge up or down, drawn from a normal distribution centred on zero with spread σ_u. σ is the residual spread, doing the same job it has done since Class 2, except that now it is the spread *within* a bird rather than the spread of everything.\n\n**Itchy:** One housekeeping note, because these six symbols are the ones you keep. **β0, β1, u_j, σ_u, σ and R mean the same things for the rest of the book, and only the grouping changes.** Today *j* is a bird and the repeated thing is a recapture. In Class 8 Momo brings her tadpoles and *j* is a pond, with the tadpoles inside it playing the part today's recaptures play. Nothing in the algebra moves; you relabel *j* and carry on.\n\n**Eddie:** So u_j is a per-bird intercept.\n\n**Itchy:** u_j is a per-bird intercept that we do not estimate as 171 separate parameters. We estimate its *spread*. That distinction is the whole of Class 6 and I will come back to it when Eddie asks me the question he is about to ask. In code, one term in the formula.\n\n::: {#cell-fit-ri .cell execution_count=7}\n``` {.julia .cell-code}\nri_fit = drm(bf(@formula(Wing ~ Tarsus + (1|BirdID))), Gaussian(); data = sparrows)\nri_fit\n```\n\n::: {#fit-ri .cell-output .cell-output-display execution_count=11}\n```\nDistributional regression fit (Gaussian)\n  nobs = 459   logLik = -867.5915   converged = true\n  Residual SD (response scale) = 1.0969   dof_residual = 455\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  56.4795     3.0547  18.4893  2.519e-76\n  Tarsus        1.1481     0.1639   7.0049  2.472e-12\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                Coef.  Std.Error       z  Pr(>|z|)\n  (Intercept)  0.0925     0.0416  2.2241   0.02614\n\nRandom-effect SD (log σ_b):\n  H0: coefficient = 0 on log σ_b\n  NOT the σ_b = 0 boundary\n           Coef.  Std.Error       z   Pr(>|z|)\n  BirdID  0.5620     0.0626  8.9803  2.702e-19\n```\n:::\n:::\n\n\n**Toto:** Same verb, same box, same family. And a whole new block at the bottom.\n\n**Itchy:** A whole new block, and I want you to read its heading before you read its numbers, exactly as you did upstairs. It reports the bird-level spread on the log scale with a *z* and a *p*, and then it tells you what that test is **not**. Read that line out, Momo.\n\n**Momo:** \"NOT the σ_b = 0 boundary.\"\n\n**Itchy:** The engine calls the bird spread σ_b, for \"between\"; it is the σ_u on the board, and I will keep calling it σ_u. That heading is the engine warning you off the one question you were about to ask it. You want to know whether the birds differ at all, and that is a question about a variance being zero. A boundary here means the edge of the values a number is allowed to take: a variance can be zero but never less, so \"is it zero?\" is a question asked from the edge, and the usual test does not work there. The *p*-value printed on that line is not answering it. The engine will not stop you misreading it, but it will tell you, in the heading, that you are about to.\n\n**Toto:** So what do I do instead?\n\n**Itchy:** Today, nothing: you look at the two spreads and the ratio between them, which is what the hour is about, and you notice that a random intercept is worth having for reasons that have nothing to do with a *p*-value. Class 8 gives that boundary an hour of its own, and it is the reason the hour is needed. Now put the two fits side by side, and watch which numbers move.\n\n::: {#side-by-side .cell execution_count=8}\n``` {.julia .cell-code}\nb_lm, b_ri = coef(lm_fit, :mu), coef(ri_fit, :mu)\nse_lm, se_ri = stderror(lm_fit)[1:2], stderror(ri_fit)[1:2]\n\n@printf(\"%-14s %12s %12s %12s\\n\", \"\", \"no bird\", \"with bird\", \"ratio\")\n@printf(\"%-14s %12.4f %12.4f %12.4f\\n\", \"beta0\",    b_lm[1],  b_ri[1],  b_ri[1] / b_lm[1])\n@printf(\"%-14s %12.4f %12.4f %12.4f\\n\", \"beta1\",    b_lm[2],  b_ri[2],  b_ri[2] / b_lm[2])\n@printf(\"%-14s %12.4f %12.4f %12.4f\\n\", \"SE(beta0)\", se_lm[1], se_ri[1], se_ri[1] / se_lm[1])\n@printf(\"%-14s %12.4f %12.4f %12.4f\\n\", \"SE(beta1)\", se_lm[2], se_ri[2], se_ri[2] / se_lm[2])\n\nse_ratio = se_ri[2] / se_lm[2]\nse_shortfall = 1 - se_lm[2] / se_ri[2];\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    no bird    with bird        ratio\nbeta0               56.0685      56.4795       1.0073\nbeta1                1.1696       1.1481       0.9816\nSE(beta0)            2.3560       3.0547       1.2966\nSE(beta1)            0.1263       0.1639       1.2974\n```\n:::\n:::\n\n\n**Itchy:** A ratio in a table is a number you have to hold in your head. Here is the same comparison drawn, so you do not have to.\n\n::: {#cell-fig-se-widen .cell execution_count=9}\n``` {.julia .cell-code}\nci_lm_b1 = confint(lm_fit)[2]   # beta1's CI, the model that pretends\nci_ri_b1 = confint(ri_fit)[2]   # beta1's CI, the model that does not\n\nfig = Figure(size = (320, 360))\nax = Axis(fig[1, 1]; xticks = (1:2, [\"no bird\", \"with bird\"]),\n    ylabel = \"beta1 (mm wing per mm tarsus)\")\nxlims!(ax, 0.5, 2.5)\nrangebars!(ax, [1], [ci_lm_b1.lower], [ci_lm_b1.upper]; whiskerwidth = 8, color = Cycled(1))\nrangebars!(ax, [2], [ci_ri_b1.lower], [ci_ri_b1.upper]; whiskerwidth = 8, color = Cycled(2))\nscatter!(ax, [1], [b_lm[2]]; markersize = 10, color = Cycled(1))\nscatter!(ax, [2], [b_ri[2]]; markersize = 10, marker = :diamond, color = Cycled(2))\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n![beta1, the coefficient on tarsus, from the no-bird and with-bird fits: the same point estimate — circle for no-bird, diamond for with-bird — plus or minus about two standard errors, the Wald interval. The two points sit almost on top of each other; the interval around the with-bird fit is visibly wider, because it is paying for the recaptures the no-bird fit counted as independent birds.](wk6-random-intercepts_files/figure-html/fig-se-widen-output-1.svg){#fig-se-widen}\n:::\n:::\n\n\n**Toto:** The slope hardly changed.\n\n**Itchy:** The slope hardly changed. Now read the row underneath it.\n\n**Momo:** The standard error went up by a factor of 1.3.\n\n**Itchy:** It went up by a factor of 1.3, which is the same thing as saying the first model's standard error was 22\\.9% too small. Toto, what would you have done with the small one?\n\n**Toto:** Put it in a table. With a confidence interval around it.\n\n**Itchy:** With a confidence interval 22\\.9% too narrow, and a *p*-value to match, in a paper, about sparrows. That is what independence was buying you: confidence it had not earned.\n\n**Momo:** How much had it earned? If 459 rows are really 171 birds, the standard error should have been much further out than that.\n\n**Itchy:** Good, and that is the right instinct pushed one step too far. Turn the ratio back into a count.\n\n::: {#effective-n .cell execution_count=10}\n``` {.julia .cell-code}\n# A standard error scales like 1/sqrt(n), so a ratio of standard errors turns\n# back into the sample size the honest fit behaved as though it had.\nn_eff = n / se_ratio^2\nratio_if_birds = sqrt(n / birds)\n\n@printf(\"rows                                     : %d\\n\", n)\n@printf(\"birds                                    : %d\\n\", birds)\n@printf(\"effective sample size implied by the SEs : %.1f\\n\", n_eff)\n@printf(\"SE ratio we measured                     : %.4f\\n\", se_ratio)\n@printf(\"SE ratio if every bird counted once      : %.4f\\n\", ratio_if_birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows                                     : 459\nbirds                                    : 171\neffective sample size implied by the SEs : 272.7\nSE ratio we measured                     : 1.2974\nSE ratio if every bird counted once      : 1.6384\n```\n:::\n:::\n\n\n**Itchy:** The truth is **between the two counts**, and the arithmetic says where. Not 459 independent measurements, not 171 either, but about 273. If a bird really were one indivisible piece of evidence, the standard error would have gone up by a factor of 1.64 rather than 1.3.\n\n**Toto:** So the extra measurements were worth something after all.\n\n**Itchy:** They were worth something, and less than they looked. A fourth capture of a bird you have already measured three times adds a little information about that bird and none at all about how many birds there are. Which is a sentence worth keeping when somebody offers you more data from the same individuals.\n\n**Eddie:** Why up, though? I would like to be able to predict the direction next time rather than look it up.\n\n**Itchy:** Good. Predict it from the predictor. Ask how much of the variation in tarsus length sits *between* birds rather than *within* them.\n\n::: {#tarsus-structure .cell execution_count=11}\n``` {.julia .cell-code}\ntarsus_fit = drm(bf(@formula(Tarsus ~ 1 + (1|BirdID))), Gaussian(); data = sparrows)\ntarsus_between = repeatability(tarsus_fit).estimate\n\n@printf(\"share of tarsus variation that is between birds: %.4f\\n\", tarsus_between)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshare of tarsus variation that is between birds: 0.9288\n```\n:::\n:::\n\n\n**Eddie:** Almost all of it.\n\n**Itchy:** Almost all of it, because a tarsus is a leg bone and a grown sparrow's leg bone does not change much between captures. So the predictor is very nearly a *bird-level* quantity, and that is most of the reason the effective count we measured a moment ago sits closer to 171 than to 459. Only most of it, though: tarsus is 92\\.9% between-bird and not 100%, so a re-measured bird does carry a little fresh information about the slope, which is exactly why 273 is not 171. The rule to carry away: **when a predictor varies mostly between groups, ignoring the grouping makes its standard error too small.** When a predictor varies mostly *within* groups, the same neglect can make it too large, and Class 7 will show you one.\n\n### What the second variance component is for\n\n**Itchy:** Now the part you came for. The fit printed two spreads. Get them out.\n\n::: {#variance-components .cell execution_count=12}\n``` {.julia .cell-code}\nsigma_u = re_sd(ri_fit)[:BirdID]     # between-bird SD\nsigma_e = first(sigma(ri_fit))       # within-bird SD; also the fit's printed\n                                     # \"Residual SD (response scale)\", which for\n                                     # a mixed fit is the WITHIN-group number\n\n@printf(\"sigma_u (between birds) : %.4f mm\\n\", sigma_u)\n@printf(\"sigma_e (within a bird) : %.4f mm\\n\", sigma_e)\n@printf(\"sigma from the model that pretended: %.4f mm\\n\", first(sigma(lm_fit)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsigma_u (between birds) : 1.7541 mm\nsigma_e (within a bird) : 1.0969 mm\nsigma from the model that pretended: 2.0856 mm\n```\n:::\n:::\n\n\n**Momo:** The pretending model's σ is bigger than either of these.\n\n**Itchy:** Bigger than either, because it had to absorb both. One number was doing two jobs: how much birds differ from each other, and how much a single bird's wing measurement wobbles from day to day. Those are different quantities, they have different biology, and a model that reports their sum has told you neither. Now divide.\n\n::: {#repeatability .cell execution_count=13}\n``` {.julia .cell-code}\nR_manual = sigma_u^2 / (sigma_u^2 + sigma_e^2)\n\n# repeatability() defaults to method = :delta: the estimate plus or minus about two\n# standard errors, pushed back inside [0, 1]. Name the method: it is not the only one on offer.\nR = repeatability(ri_fit)                          # method = :delta, the default\nR_prof = repeatability(ri_fit; method = :profile)  # re-maximises the likelihood\n\n@printf(\"by hand                   : R = %.4f\\n\", R_manual)\n@printf(\"delta (the default)       : R = %.4f   SE %.4f   95%% CI %.4f to %.4f\\n\",\n        R.estimate, R.se, R.ci.lower, R.ci.upper)\n@printf(\"  bias estimate %.5f, bias-corrected point estimate %.4f\\n\",\n        R.bias, R.corrected)\n@printf(\"profile likelihood        : R = %.4f   %-11s95%% CI %.4f to %.4f\\n\",\n        R_prof.estimate, \"\", R_prof.ci.lower, R_prof.ci.upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nby hand                   : R = 0.7189\ndelta (the default)       : R = 0.7189   SE 0.0317   95% CI 0.6556 to 0.7800\n  bias estimate -0.00109, bias-corrected point estimate 0.7178\nprofile likelihood        : R = 0.7189              95% CI 0.6520 to 0.7764\n```\n:::\n:::\n\n\n**Momo:** Two intervals, and you did not tell us which one you were reporting until just now.\n\n**Itchy:** Which is the sin this whole book is about, committed by me, in a cell, on purpose. `repeatability` hands you one of two intervals and does not say which. The default is the quick one: take the ratio, take a standard error for it, go about two standard errors either way, and then push the ends back inside nought and one if they fall outside. Statisticians call an estimate-plus-or-minus-two-standard-errors interval a **Wald** interval, and the approximation that gets a standard error for a ratio out of two variances is the **delta method**. It is fast and it is the weaker of the two.\n\n**Toto:** And the other one?\n\n**Itchy:** `method = :profile` re-fits the model at each trial value of R and keeps the values the data cannot rule out. That takes longer, and it is the one documented to do what it says: ask for a 95 percent interval and you get one that contains the truth 95 times in 100, which is what **coverage** means. They differ here in the third decimal place at both ends, which is small, and they will not always be small: near zero or near one the pushing-back-inside does real damage. Report the one you asked for, by name.\n\n**Toto:** And the bias line?\n\n**Itchy:** A ratio of estimates is not the estimate of the ratio, so the point estimate is slightly off and the engine will tell you by how much if you look. It is tiny here. It will not be tiny in Class 10, on six families.\n\n**Itchy:** Now the substance. That is **repeatability**, and it is the first quantity in this book that is not a coefficient and not a *p*-value. It is a **ratio of variance components**: the between-bird variance over the total. Toto, read it as a sentence about birds.\n\n**Toto:** About 72% of the variation in wing length is differences between birds, and the rest is a bird varying from itself.\n\n**Itchy:** That is exactly right and I want you to notice how much more that tells you than any *p*-value in this chapter. Two warnings, both of which have papers behind them. First: this R is **adjusted**. It is conditional on tarsus, because tarsus is in the model, so it is repeatability of wing length *after taking size into account*. Drop the predictor and you get a different number.\n\n::: {#adjusted-vs-not .cell execution_count=14}\n``` {.julia .cell-code}\nplain_fit = drm(bf(@formula(Wing ~ 1 + (1|BirdID))), Gaussian(); data = sparrows)\nR_unadjusted = repeatability(plain_fit).estimate\n\n@printf(\"adjusted for tarsus : R = %.4f\\n\", R.estimate)\n@printf(\"unadjusted          : R = %.4f\\n\", R_unadjusted)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nadjusted for tarsus : R = 0.7189\nunadjusted          : R = 0.7565\n```\n:::\n:::\n\n\n**Momo:** They are close.\n\n**Itchy:** They are close *here*, and they are not always, and the two are answers to different questions. The unadjusted one asks how consistent a bird's wing length is. The adjusted one asks how consistent a bird is *once you know how big it is*. Nakagawa and Schielzeth (2010) is where that distinction is set out properly, and it is the paper to hand somebody who has just written \"repeatability\" in a manuscript without saying which one they mean.\n\n**Eddie:** And the second warning?\n\n**Itchy:** The second is the denominator, and it is the reason Class 8 exists. Look again at what you just divided by.\n\n> **R = σ_u² / (σ_u² + σ²). Two estimated quantities, over the sum of the same two estimated quantities, and not one coefficient of μ anywhere in it.**\n\n**Itchy:** Every number in that ratio is an estimate of a variance, and Class 2 already showed you that different people divide sums of squares by different things. In Class 8 you will find out that two correct implementations of *this exact model* disagree about σ_u, and therefore about R. Today I only want you to notice that the denominator is contested. Do not take the third decimal place of a repeatability seriously until Class 8.\n\n### Eddie's question\n\n**Eddie:** Here is the thing I have never had answered. You say we do not estimate 171 intercepts, we estimate their spread. But the model clearly knows something about individual birds, because it can predict them. So what *is* a random intercept?\n\n**Itchy:** That is the right question and the answer is a picture rather than a sentence. Ask the fit for its per-bird effects and put them next to what each bird's own data said, with nothing borrowed. The model's own prediction for each bird has an unlovely name, BLUP, for best linear unbiased predictor, and it is the name you will see in other people's output; I will say \"the model's prediction for the bird\", and you may say BLUP in papers.\n\n::: {#cell-fig-shrinkage .cell execution_count=15}\n``` {.julia .cell-code}\nblups = ranef(ri_fit)[:BirdID]         # the model's prediction for each bird (the BLUPs), straight from the fit\n\n# The unshrunk per-bird effect: the average residual from the fixed part alone.\n# fitted() here is MARGINAL (X * beta, every bird effect set to zero), which is\n# what makes averaging it within a bird the \"bird on its own evidence\" number.\nresid_fixed = sparrows.Wing .- fitted(ri_fit)\nraw_effect = [mean(resid_fixed[sparrows.BirdID .== b]) for b in bird_ids]\n\n# Birds at even intervals through the ordering, so the picture is a rule again;\n# 171 tick labels would be unreadable and choosing \"interesting\" birds would be\n# choosing the evidence.\nsel = sortperm(raw_effect)[1:14:length(bird_ids)]\nkept = blups ./ raw_effect\nk_j = [count(==(b), sparrows.BirdID) for b in bird_ids]\n\n@printf(\"birds shown: %d of %d\\n\", length(sel), length(bird_ids))\n@printf(\"fraction of its own signal a bird keeps: %.3f (k = %d) to %.3f (k = %d)\\n\",\n        minimum(kept), k_j[argmin(kept)], maximum(kept), k_j[argmax(kept)])\n\nfig_shrinkage(bird_ids[sel], raw_effect[sel], blups[sel])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbirds shown: 13 of 171\nfraction of its own signal a bird keeps: 0.836 (k = 2) to 0.911 (k = 4)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=24}\n![Shrinkage caterpillar for the sparrows: circles are each bird's own average residual from the random-intercept fit's marginal fitted values — what its own captures say about it, borrowing nothing; diamonds are the model's prediction (the BLUP) for the same bird. Every diamond sits closer to the middle than its circle, and by how much depends on how many times that bird was caught.](wk6-random-intercepts_files/figure-html/fig-shrinkage-output-2.svg){#fig-shrinkage}\n:::\n:::\n\n\n**Itchy:** Every circle is what a bird's own measurements said about it, on its own, borrowing nothing. Every diamond is what the model predicts for that bird. Eddie, describe the difference.\n\n**Eddie:** Every diamond is closer to the middle than its circle.\n\n**Itchy:** Every one, and that is what a random intercept *is*. It is the decision to treat the 171 birds as **draws from one population of birds** rather than as 171 unrelated strangers. Once you have done that, a bird with two noisy measurements is allowed to borrow strength from the fact that birds in general do not differ by very much, and gets pulled towards the average. A bird with more measurements has more of its own evidence and is pulled less than that, which you cannot see in the picture, because the birds drawn there were chosen by where they sit and not by how often we caught them. It is in the line printed above it: the fraction a bird keeps runs from 0.836 at the fewest captures to 0.911 at the most.\n\n**Momo:** So the model distrusts small samples on purpose.\n\n**Itchy:** The model distrusts small samples in exactly the proportion the data say it should, and that proportion is σ_u² over σ_u² plus σ² over *k*, which is repeatability again wearing a different hat. That fraction has a name, the Spearman–Brown weight, borrowed from the psychologists who first asked how much a test's reliability improves when you lengthen it: it is *k* σ_u² over *k* σ_u² plus σ², repeatability with the bird's own *k* measurements put on top. That is why the two ideas are one chapter. Now the same fit drawn the other way round, as lines.\n\n::: {#cell-fig-bird-lines .cell execution_count=16}\n``` {.julia .cell-code}\nfig = Figure(size = (520, 380))\nax = Axis(fig[1, 1]; xlabel = \"tarsus (mm)\", ylabel = \"wing (mm)\",\n    title = \"one slope, $(length(bird_ids)) intercepts\")\n\nxs = range(minimum(sparrows.Tarsus), maximum(sparrows.Tarsus), length = 50)\nscatter!(ax, sparrows.Tarsus, sparrows.Wing; markersize = 4, color = (:grey, 0.3))\nfor u in blups\n    lines!(ax, xs, b_ri[1] + u .+ b_ri[2] .* xs; color = (:grey, 0.20), linewidth = 0.6)\nend\nlines!(ax, xs, b_ri[1] .+ b_ri[2] .* xs; linewidth = 3)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n![One population line in bold, with a faint parallel line drawn at every bird's own predicted intercept. All the lines share exactly the same slope; only where they cross the y-axis differs, which is the constant a random intercept leaves untouched and Class 7 goes on to free.](wk6-random-intercepts_files/figure-html/fig-bird-lines-output-1.svg){#fig-bird-lines}\n:::\n:::\n\n\n**Toto:** They are all parallel.\n\n**Itchy:** All parallel, every one of them, because we freed the intercept and left the slope alone. Each bird gets to sit high or low; none of them gets its own steepness. That is precisely the constant Class 7 frees, and the fact that you can see the restriction in the picture is why I drew it.\n\n### Is the model any good?\n\n**Itchy:** Before anybody writes this down, look at the residuals. And be careful which residuals, because there are two kinds now and the software will hand you one of them without asking. The marginal residual is the distance from the population line, so it still has the bird's own shift inside it. The conditional residual subtracts that shift out, and it is the one σ is a claim about. The worm plot is the picture Class 2 showed you and Class 5 taught you to read: residuals against what a normal distribution would give, straight along the middle if all is well. Read it for shape only — Class 5 showed that the naive count of points outside the ±2SE band is too generous by about a factor of five, so it is not calibrated by eye.\n\n::: {#cell-fig-diagnostic .cell execution_count=17}\n``` {.julia .cell-code}\n# residuals(fit) is MARGINAL: it still contains the bird effect, so it is NOT the\n# thing sigma describes. Subtract each bird's own BLUP to get the CONDITIONAL\n# residual, which is what the within-bird spread is a claim about.\nidx = Dict(b => i for (i, b) in enumerate(bird_ids))\ncond_resid = residuals(ri_fit) .- [blups[idx[b]] for b in sparrows.BirdID]\n\n@printf(\"SD of marginal residuals    : %.4f  (should be near %.4f)\\n\",\n        std(residuals(ri_fit)), sqrt(sigma_u^2 + sigma_e^2))\n@printf(\"SD of conditional residuals : %.4f  (sigma_e is %.4f)\\n\",\n        std(cond_resid), sigma_e)\n\n# Standardise by the spread the residuals ACTUALLY have, not by sigma_e. Dividing\n# by sigma_e would guarantee an under-dispersed plot and hide the shape we came\n# to look at behind an error of scale we already know about.\nfig_diagnostic(cond_resid ./ std(cond_resid); title = \"within-bird residuals\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSD of marginal residuals    : 2.0880  (should be near 2.0689)\nSD of conditional residuals : 0.9039  (sigma_e is 1.0969)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=27}\n![Worm plot of the conditional residuals — the marginal residual with the model's own prediction for that bird subtracted out, standardised by their own spread rather than by sigma_e. Flat through the middle; a scatter of points sit outside the ±2SE band on both sides, which is the naive count the prose above already warned not to read as a defect tally. The single worst deviation in the whole file, not merely the nearest to the edge, is named in the text below.](wk6-random-intercepts_files/figure-html/fig-diagnostic-output-2.svg){#fig-diagnostic}\n:::\n:::\n\n\n**Itchy:** Read the shape, but do not let your eye average away the single worst row, the one that does not belong in an average even among the points already outside the band. Name it before we go on.\n\n::: {#named-outlier .cell execution_count=18}\n``` {.julia .cell-code}\nz = cond_resid ./ std(cond_resid)\nworst = argmin(z)\nbad_bird = sparrows.BirdID[worst]\nown_wings = sparrows.Wing[sparrows.BirdID .== bad_bird]\n\n@printf(\"points beyond +-2: %d below, %d above (of %d)\\n\",\n        count(z .< -2), count(z .> 2), length(z))\n@printf(\"furthest point: bird %s, standardised residual %.2f\\n\", bad_bird, z[worst])\n@printf(\"its own wing measurements: %s\\n\", string(own_wings))\n\nkeep = trues(n); keep[worst] = false\nrefit_drop = drm(bf(@formula(Wing ~ Tarsus + (1|BirdID))), Gaussian(); data = sparrows[keep, :])\n@printf(\"sigma_e, row in vs out    : %.4f vs %.4f\\n\", sigma_e, first(sigma(refit_drop)))\n@printf(\"R,       row in vs out    : %.4f vs %.4f\\n\", R.estimate, repeatability(refit_drop).estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npoints beyond +-2: 8 below, 6 above (of 459)\nfurthest point: bird TA14548, standardised residual -7.87\nits own wing measurements: [75.5, 75.0, 76.5, 67.0]\nsigma_e, row in vs out    : 1.0969 vs 1.0002\nR,       row in vs out    : 0.7189 vs 0.7531\n```\n:::\n:::\n\n\n**Itchy:** TA14548. Read the line above rather than take my word for it: three wings within a couple of millimetres of each other, and a fourth well short of them. It survived the missing-data filter because tarsus was recorded on all four captures, so it is sitting inside this fit whether we discuss it or not. Drop that one row and σ moves from 1.0969 to 1.0002, and R from 0.7189 to 0.7531 — one row out of 459, and not a small move. This bird, and a second one like it, get the full treatment next week: Class 7 names them both and sends them to an exercise. Here I am only asking you to read a worm plot honestly: flat through the middle, a scatter of points beyond the band on both sides exactly as the naive count above predicts, and this one sitting furthest out of all of them.\n\n**Momo:** The conditional one is smaller than σ. Is that the shrinkage?\n\n**Itchy:** It is not, and I am glad you guessed, because the guess is the common one and it points the wrong way. Work out where the shortfall comes from instead of attributing it.\n\n::: {#residual-accounting .cell execution_count=19}\n``` {.julia .cell-code}\nk_of = Dict(b => count(==(b), sparrows.BirdID) for b in bird_ids)\nks = sort(unique(values(k_of)))\n\n# lambda_k is the Spearman-Brown weight: the share of its own signal a bird with\n# k measurements keeps. It is also the shrinkage factor in the caterpillar.\nlambda(k) = k * sigma_u^2 / (k * sigma_u^2 + sigma_e^2)\n\nown_mean_only = sqrt(sum(count(==(k), values(k_of)) * k * sigma_e^2 * (1 - 1/k)\n                         for k in ks) / n)\nwith_shrinkage = sqrt(sum(count(==(k), values(k_of)) * k *\n                          (sigma_e^2 * (1 - 1/k) + (1 - lambda(k))^2 * (sigma_u^2 + sigma_e^2/k))\n                          for k in ks) / n)\n\n@printf(\"%-42s %.4f\\n\", \"sigma_e, and what you would see if each\", sigma_e)\n@printf(\"%-42s %s\\n\",   \"  bird's own mean were known exactly:\", \"(the same number)\")\n@printf(\"%-42s %.4f\\n\", \"after paying for each bird's own mean:\", own_mean_only)\n@printf(\"%-42s %.4f\\n\", \"that, plus what shrinkage adds back:\", with_shrinkage)\n@printf(\"%-42s %.4f\\n\", \"observed:\", std(cond_resid))\nprintln()\nfor k in ks\n    @printf(\"  k = %d: lambda = %.4f, sqrt(sigma_e^2 (1 - 1/k)) = %.4f\\n\",\n            k, lambda(k), sqrt(sigma_e^2 * (1 - 1/k)))\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsigma_e, and what you would see if each    1.0969\n  bird's own mean were known exactly:      (the same number)\nafter paying for each bird's own mean:     0.8689\nthat, plus what shrinkage adds back:       0.9029\nobserved:                                  0.9039\n\n  k = 2: lambda = 0.8365, sqrt(sigma_e^2 (1 - 1/k)) = 0.7756\n  k = 3: lambda = 0.8847, sqrt(sigma_e^2 (1 - 1/k)) = 0.8956\n  k = 4: lambda = 0.9109, sqrt(sigma_e^2 (1 - 1/k)) = 0.9499\n```\n:::\n:::\n\n\n**Itchy:** Read the ladder. The big step is the third line, and it is nothing to do with random effects: it is Class 2's divisor, wearing its oldest hat. Subtracting an estimated mean from 2 numbers leaves you residuals whose spread is short by a factor of the square root of one minus one over *k*, because one degree of freedom went into the mean. With 2 measurements that is a 29% shortfall on its own. Shrinkage then pushes the number **back up**, not down, because a shrunk BLUP removes slightly *less* than the bird's real effect and leaves a little of it behind in the residual.\n\n**Momo:** So my guess was not just wrong, it had the sign wrong.\n\n**Itchy:** The sign wrong, which is the useful kind of wrong. And it tells you what this plot can and cannot do. It **cannot** tell you whether σ is right, because the residuals it is drawn from are short of σ by an amount we have just computed rather than measured. It **can** tell you whether the within-bird wobble is symmetric and normal-ish and free of trend, which is the assumption the model actually makes. So the cell standardises by the spread the residuals have, not by σ, and you read the shape.\n\n### What repeatability is for\n\n**Itchy:** Last piece, and it is biology rather than arithmetic. Why would anyone want R at all?\n\n**Eddie:** Measurement error. If I measure the same wing twice and get different answers, R tells me how bad my ruler is.\n\n**Itchy:** That is one of the two uses and it is the one people forget. A repeatability puts a ceiling on any correlation you will ever measure with that trait, and I want you to get the ceiling right, because almost everybody gets it wrong the first time. Compute it.\n\n::: {#ceiling .cell execution_count=20}\n``` {.julia .cell-code}\n# R and h2 are both variance ratios over the SAME total. Under the STANDARD\n# PARTITION -- between-individual variance = additive genetic + permanent\n# environment, with no covariance between the two -- the additive part is a\n# share of the between-bird variance, never more than all of it, so h2 <= R.\n# Relax that partition and the bound can fail (Dohm 2002).\nV_between = sigma_u^2      # genes AND every other permanent thing about a bird\nV_within  = sigma_e^2\nV_total   = V_between + V_within\n\n@printf(\"between-bird variance (mm^2)  : %.4f\\n\", V_between)\n@printf(\"within-bird variance  (mm^2)  : %.4f\\n\", V_within)\n@printf(\"total                 (mm^2)  : %.4f\\n\\n\", V_total)\n@printf(\"R  = V_between / total        : %.4f\\n\", V_between / V_total)\n@printf(\"h2 = V_additive / total, and V_additive <= V_between, so h2 <= %.4f\\n\",\n        V_between / V_total)\nprintln(\"\\nestimator: maximum likelihood, adjusted for tarsus (the fit above)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbetween-bird variance (mm^2)  : 3.0770\nwithin-bird variance  (mm^2)  : 1.2032\ntotal                 (mm^2)  : 4.2802\n\nR  = V_between / total        : 0.7189\nh2 = V_additive / total, and V_additive <= V_between, so h2 <= 0.7189\n\nestimator: maximum likelihood, adjusted for tarsus (the fit above)\n```\n:::\n:::\n\n\n**Toto:** The two numbers are the same.\n\n**Itchy:** They are the same number, and that is not a coincidence, it is the theorem. **Repeatability is an upper bound on narrow-sense heritability — the additive-genetic share alone, as opposed to broad-sense, which would also count non-additive genetic effects — h² ≤ R.** Read the cell again and you have the proof: the two quantities are ratios over the *same* total, and the thing on top of h² is a *part* of the thing on top of R. Between-bird variance is everything permanent about a bird. Its genes are in there. So is the nest it grew up in, the territory it holds, and any damage it has taken, none of which its chicks inherit. Additive genetic variance is one slice of that pie, so h² can equal R only if every permanent difference between these birds is genetic, and it never is.\n\n**Momo:** So R is a free upper bound on heritability that costs no pedigree at all.\n\n**Itchy:** A free upper bound that costs you no pedigree, no relatives and no crossing design, which is why it is worth an hour of Class 6. Nakagawa and Schielzeth (2010) treat repeatability's relation to heritability as exactly this kind of upper bound, and review how to estimate the ratio properly. And the bound is often loose, sometimes very loose, because permanent environment effects can be large. Ours is 0.719, estimated by maximum likelihood and adjusted for tarsus, so what it caps is the heritability of wing length once size is accounted for. Match the conditioning when you quote it: an adjusted R bounds an adjusted h².\n\n**Momo:** You said \"under the standard partition\" in the cell comment. What happens if the partition is wrong?\n\n**Itchy:** Then the bound is not guaranteed, and I would rather you heard that from me than discovered it in a referee report. Everything I have just said rests on splitting the between-individual variance into an additive genetic part **plus** a permanent environment part, **with no covariance between them**, and on the measurements being exchangeable within an individual. Relax those and the inequality can fail. Dohm (2002) is a whole paper on this, and its title is the warning: repeatability estimates do not always set an upper limit to heritability. Genes and environment covarying, or maternal and early-life effects entering some measurements and not others, are the cases to know about.\n\n**Toto:** So is h² ≤ R a rule or not?\n\n**Itchy:** It is a rule under a stated model, which is what most useful statements in this field are. Use it as the free first check it is, quote the partition when you lean on it, and do not treat a violation as proof that somebody is wrong.\n\n**Eddie:** And if a paper reports an h² above its R?\n\n**Itchy:** Then there are three live possibilities and none of them is \"the authors cannot add up\". Either an estimate is off, which is easy on small pedigrees where both numbers carry wide intervals; or the design cannot separate genes from a permanent environment, so the two quantities are not estimating what their names say; or the standard partition genuinely fails for that trait, which is Dohm's case. Either way you have found the interesting sentence in that paper, and it is worth reading before you write to the authors. That is Class 10, and today's ratio is the thing it is built on.\n\n**Itchy:** One warning before we leave the ceiling, because you will meet the other one. **A correlation between two traits is capped by the square root of the repeatability, not by R itself, because a correlation lives on the standard-deviation scale.** Do not carry today's bound across to that problem; Class 10 comes back to it.\n\n**Itchy:** The other use of R is the interesting one, and it is that R is a real quantity about the animals. A trait that is repeatable is a trait an individual *has*, consistently, rather than a thing that happens to it on a given morning. That is the door into personality research, into heritability, and into Class 10.\n\n**Momo:** And the pitfalls, since you have mentioned two papers and a warning already.\n\n**Itchy:** Lessells and Boag (1987), which is one of the most useful two-page papers in ecology and is titled, correctly, \"Unrepeatable repeatabilities\". It exists because people were computing this ratio with the wrong denominator when their birds had different numbers of measurements, which is exactly our situation: 85 birds measured twice, and others three and four times. Which brings me to the one place I am going to show you R code today.\n\n### One box, and it is earned\n\n**Itchy:** An R-trained reader does not reach for a mixed model to get a repeatability. They reach for `aov`, and a formula out of Lessells and Boag. That route is not wrong and it does not give our number. Compute it here first, by hand, so the comparison is between two methods and not between two languages.\n\n::: {#anova-repeatability .cell execution_count=21}\n``` {.julia .cell-code}\ngrp = combine(groupby(sparrows, :BirdID), :Wing => mean => :m, nrow => :k)\ngidx = Dict(b => i for (i, b) in enumerate(grp.BirdID))   # groupby order, not sorted\ngrand = mean(sparrows.Wing)\na = nrow(grp)\n\nss_among  = sum(grp.k .* (grp.m .- grand) .^ 2)\nss_within = sum((sparrows.Wing .- [grp.m[gidx[b]] for b in sparrows.BirdID]) .^ 2)\nms_among, ms_within = ss_among / (a - 1), ss_within / (n - a)\n\n# Lessells & Boag's n0: the \"effective\" measurements per bird when the numbers differ.\nn0 = (n - sum(grp.k .^ 2) / n) / (a - 1)\ns2_among = (ms_among - ms_within) / n0\nR_anova = s2_among / (s2_among + ms_within)\n\n@printf(\"MS among birds %.4f   MS within %.4f   n0 %.4f  (mean k %.4f)\\n\\n\",\n        ms_among, ms_within, n0, mean_k)\n\n# There is a third answer, and pretending there are only two is how the gap gets\n# blamed on the wrong thing. What REML is, and why it moves the number, is Class\n# 8's whole hour; today we only need to see where it lands.\nreml_fit = drm(bf(@formula(Wing ~ 1 + (1|BirdID))), Gaussian();\n               data = sparrows, method = :REML)\nR_reml = repeatability(reml_fit).estimate\n\n@printf(\"%-28s %10s\\n\", \"repeatability, unadjusted\", \"R\")\n@printf(\"%-28s %10.4f\\n\", \"  maximum likelihood\", R_unadjusted)\n@printf(\"%-28s %10.4f\\n\", \"  REML\", R_reml)\n@printf(\"%-28s %10.4f\\n\\n\", \"  analysis of variance\", R_anova)\n\n# Split the gap on the variance scale, where the factors multiply.\nv_ml   = re_sd(plain_fit)[:BirdID]^2\nv_reml = re_sd(reml_fit)[:BirdID]^2\n\n@printf(\"between-bird VARIANCE, ratio to the ML estimate\\n\")\n@printf(\"  REML  / ML   : %.6f     <- the divisor step, Class 8's business\\n\", v_reml / v_ml)\n@printf(\"  ANOVA / REML : %.6f     <- moments against likelihood, unequal k\\n\", s2_among / v_reml)\n@printf(\"  ANOVA / ML   : %.6f     = the product of the two above\\n\", s2_among / v_ml)\n@printf(\"  J/(J-1)      : %.6f     (J = %d birds)\\n\", birds / (birds - 1), birds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMS among birds 11.8260   MS within 1.2468   n0 2.6829  (mean k 2.6842)\n\nrepeatability, unadjusted             R\n  maximum likelihood             0.7565\n  REML                           0.7577\n  analysis of variance           0.7598\n\nbetween-bird VARIANCE, ratio to the ML estimate\n  REML  / ML   : 1.006614     <- the divisor step, Class 8's business\n  ANOVA / REML : 1.012226     <- moments against likelihood, unequal k\n  ANOVA / ML   : 1.018921     = the product of the two above\n  J/(J-1)      : 1.005882     (J = 171 birds)\n```\n:::\n:::\n\n\n> **⚠ DISAGREE: three correct repeatabilities from one file, and the gap has two parts**\n>\n> Three routes to one number on these 459 measurements, and they disagree in the\n> third decimal place. None of them is a bug, and the gap is **not** one effect but two,\n> which the cell above separates on the variance scale, where the factors multiply.\n>\n> The **first** part is the step from maximum likelihood to REML, a factor of\n> 1.006614 here against *J*/(*J* − 1) =\n> 1.005882. That is Class 2's divisor argument\n> arriving at the between-bird level, and it is Class 8's subject: a maximum-likelihood\n> variance is estimated without paying for the fixed effects that were estimated first,\n> and REML makes it pay. Note which denominator it is. Class 2 met *n* against *n − p* at\n> the **residual** level; this is the same argument one level up, with *J* birds in place\n> of *n* rows, and Class 8 shows that a mixed model carries **one divisor per level**.\n>\n> The **second** part is larger here, a factor of 1.012226,\n> and it is not a divisor at all. The analysis-of-variance estimator matches expected mean\n> squares — the textbook formula for how much variance each level of the design should\n> contribute — which is a method of moments: set that formula equal to what you actually\n> observed and solve. And with an unequal number of measurements per\n> bird a method of moments is not REML: Lessells and Boag's `n0` is the best single number\n> to stand in for a *k* that is 2, 3 or\n> 4 depending on the bird, and no single number can do that job\n> exactly. Had every bird been caught the same number of times, this second factor would\n> collapse and the two estimators would agree.\n>\n> So: the ordering ML < REML < ANOVA is not luck, and the divisor explains about a third of\n> it. It is tempting to blame the whole gap on the divisor, because the divisor is the part\n> with a formula; the larger part is the unequal number of captures, and it only shows itself\n> when you split the gap on the variance scale as the cell did.\n>\n> The R output below was run once, by hand, on 2026-09-06, on the same data file this\n> chapter reads, and pasted here as it came out; it is not re-run when the page is made. It\n> is here to show that the classical route an R user would take gives the ANOVA number\n> above, so the gap is between two methods and not between two languages.\n\n```r\n# R output, run once by hand on 2026-09-06 and pasted here. Run with:\n#   R 4.6.0, reading data/2012/BodySize.csv, rows with a missing\n#   Wing or Tarsus dropped (459 rows, 171 birds)\n#   a <- anova(aov(Wing ~ factor(BirdID), data = d))\n\nAnalysis of Variance Table\n\nResponse: Wing\n           Df  Sum Sq Mean Sq F value    Pr(>F)\nBirdID    170 2010.42 11.8260  9.4853 < 2.2e-16 ***\nResiduals 288  359.07  1.2468\n\nn0 = 2.682942   MSa = 11.82599   MSw = 1.246777\nLessells & Boag ANOVA repeatability = 0.7597694\n```\n\n**Momo:** So which one do I report?\n\n**Itchy:** Whichever one you name. That is the entire answer, and if it sounds like a dodge, wait two weeks. What you may not do is report the third decimal place of a repeatability as though the method that produced it were a detail. Say \"repeatability, estimated by maximum likelihood from a mixed model, was\", and then the number, and then your reader can do arithmetic you did not do for them.\n\n**Toto:** So today's summary is: rows are not strangers.\n\n**Itchy:** Today's summary is: rows are not strangers, the correlation between them has a name and a number, and that number turns out to be a piece of biology rather than a nuisance.\n\n---\n\n## Summary\n\n### Stats stuff\n\n- **Non-independence.** Every model in Classes 2 to 5 assumed rows were independent draws. Repeated measurements on the same individual are not, and the assumption is not visible in any diagnostic plot; it is visible in the *data file*. Look at your identifier columns before you look at your residuals.\n- **Random intercept.** `(1 | group)` gives every group its own shift up or down, drawn from a normal distribution with spread σ_u. You do not estimate one intercept per group; you estimate the spread of the intercepts, which costs you one parameter rather than one per group.\n- **What it does to standard errors.** With a predictor that varies mostly *between* groups, ignoring the grouping makes standard errors too small, because you counted repeated measurements as independent evidence. Here the slope's standard error was understated by nearly a quarter. With a predictor that varies mostly *within* groups the neglect can go the other way, which is Class 7.\n- **Two spreads, not one.** σ_u is how much individuals differ from each other; σ is how much one individual varies from itself. The single-level model reports something between the two and calls it \"the\" residual standard deviation, which answers neither question.\n- **Repeatability, R = σ_u² / (σ_u² + σ²).** A ratio of variance components. Also called the intraclass correlation, because it *is* the correlation between two measurements on the same individual. Not a coefficient, not a *p*-value, and much more informative than either.\n- **Adjusted versus unadjusted R.** With a fixed effect in the model, R is conditional on it. State which one you computed (Nakagawa & Schielzeth 2010). The two answer different biological questions.\n- **The denominator is contested, and for two reasons.** Both terms in the ratio are estimated variances. Moving from maximum likelihood to REML is Class 2's divisor argument arriving one level up, with *J* groups in place of *n* rows, and Class 8 shows that a mixed model carries one divisor per level. Moving from REML to the analysis-of-variance estimator is a different thing again: a method of moments needs one effective *k* where the design has several, so the two part company whenever groups have unequal sizes. On this file the second effect is the larger. Name your estimator.\n- **Shrinkage.** Predicted group effects are pulled towards the population mean by the Spearman-Brown weight λ_k = kσ_u²/(kσ_u² + σ²), so a group with less data is pulled harder. That is not a defect of the estimate; it is the entire content of the phrase \"draws from a population\".\n- **Marginal versus conditional residuals.** `residuals` here is marginal, so it still contains the group effect and its spread is close to sqrt(σ_u² + σ²). Subtract the group's own predicted effect to get the conditional residual. R users should note that `lme4` hands them the conditional one by default.\n- **A conditional residual is not a draw from σ, and the shortfall is not shrinkage.** Removing an estimated group mean costs a degree of freedom, so the spread falls short of σ by a factor of sqrt(1 − 1/k) before anything else happens, which at *k* = 2 is a loss of nearly a third. Shrinkage then pushes the spread back **up**, because a shrunk prediction removes slightly less than the group's real effect. Standardise a residual plot by the spread the residuals have, not by σ, or the plot shows you an error of scale you already knew about instead of the shape you came to check.\n- **The effective sample size.** A standard error scales like 1/sqrt(n), so a ratio of standard errors converts back into a count. Here the honest fit behaved as though it had rather more evidence than the number of birds and far less than the number of rows. The truth is between the two counts, and the arithmetic says where.\n- **R is a free upper bound on heritability, h² ≤ R, under the standard partition.** Both are variance ratios over the same total, and if between-individual variance splits into additive genetic plus permanent environment with no covariance between them, the numerator of h² is a *part* of the numerator of R and the inequality is arithmetic. It costs no pedigree, and it is often loose, because permanent environment effects live inside R and outside h² (Nakagawa & Schielzeth 2010; Class 10). It is not unconditional: relax the partition, for instance by letting genetic and permanent environment effects covary, and the bound can fail (Dohm 2002). Match the conditioning: an adjusted R bounds an adjusted h². Separately, and do not confuse the two: a *correlation* with a trait of repeatability R is capped by sqrt(R), because a correlation lives on the standard-deviation scale.\n\n### Julia stuff\n\n- `CSV.read(path, DataFrame; missingstring = \"NA\")`: the keyword that turns a text column back into numbers when the file was written by a human in 2009. Without it, a single `NA` makes the whole column text and the model refuses it.\n- `dropmissing(df, [:a, :b])`: keep only rows complete on the columns you are about to model. Do it in a cell, in front of the reader, never in a spreadsheet.\n- `describe(df, :nmissing)`: how many missing values per column. The first thing to run on a real file.\n- `combine(groupby(df, :g), nrow => :k)`: rows per group. The second thing to run on a real file.\n- `@formula(y ~ x + (1|g))`: the random intercept. Everything else about the call is unchanged from Class 2, including the `bf` box and the positional family.\n- `re_sd(fit)`: a `Dict` of random-effect standard deviations by grouping term. `vc(fit)` gives the covariance blocks instead.\n- `sigma(fit)`: the residual SD, one value per observation; take `first(...)` when σ is constant.\n- `repeatability(fit)`: R with an interval, a standard error and a bias estimate, so you do not build the ratio by hand and lose the uncertainty. **It defaults to `method = :delta`**, the estimate plus or minus about two standard errors, pushed back inside [0, 1] if it strays. `repeatability(fit; method = :profile)` re-fits the model at each trial value of R and keeps the values the data cannot reject; that is the one documented as covering the truth as often as it claims to, and it is the one to report unless you have a reason not to. The `bias` and `corrected` fields exist because a ratio of estimates is not the estimate of a ratio.\n- `ranef(fit)`: the model's prediction for each group's shift, by grouping term. These are the BLUPs of the caterpillar; the documentation also calls them conditional modes, and the two names mean the same thing. Pair with `fitted(fit)`, which is the **marginal** (population-level) prediction, so `y - fitted(fit)` averaged within a group is the unshrunk group effect.\n- `fig_shrinkage(groups, raw, blups)` from `tools/figures.jl`: the caterpillar, circles for each group's own mean and diamonds for the model's prediction, with the legend drawn outside the axis so it never covers a group.\n- `Cycled(i)` and `Makie.wong_colors()`: how to colour by group without inventing a palette.\n- **Reading a `MethodError` from a real file.** Line one says a `Float64` was wanted; the argument type in the signature says a string arrived. When that happens on data you did not simulate, suspect the file before you suspect the model.\n- **The simulation thread.** From Class 2 onward, the last thing you do with a fit is ask it to invent data and see whether the data look like yours. Here is that cell for a random intercept, and it carries a trap worth meeting once.\n\n::: {#simulate-refit .cell execution_count=22}\n``` {.julia .cell-code}\n# simulate() draws new responses from the fit. Read what it promises: for a\n# random-effect model the draw is conditional on the random effects being ZERO,\n# so it gives population-level birds with no individual identity at all.\nrng_sim = MersenneTwister(600)   # a seed is a promise: anyone who runs this line gets the same draw\nysim = simulate(ri_fit; nsim = 100, rng = rng_sim)\ndev = ysim .- fitted(ri_fit)\n\n@printf(\"observed SD about the fixed line : %.4f\\n\", std(sparrows.Wing .- fitted(ri_fit)))\n@printf(\"simulated SD about the fixed line: %.4f\\n\",\n        mean(std(dev[:, k]) for k in 1:size(dev, 2)))\n@printf(\"sigma alone                      : %.4f\\n\", sigma_e)\n@printf(\"sqrt(sigma_u^2 + sigma_e^2)      : %.4f\\n\", sqrt(sigma_u^2 + sigma_e^2))\n\n# Refit one replicate and look at what the estimator concludes about birds when\n# the truth is that birds do not differ at all.\none_rep = DataFrame(BirdID = sparrows.BirdID, Tarsus = sparrows.Tarsus, Wing = ysim[:, 1])\nrefit = drm(bf(@formula(Wing ~ Tarsus + (1|BirdID))), Gaussian(); data = one_rep)\n\n@printf(\"\\nrefit on simulated data: sigma_u = %.4f, sigma = %.4f, R = %.4f\\n\",\n        re_sd(refit)[:BirdID], first(sigma(refit)), repeatability(refit).estimate)\n@printf(\"the fit it came from  : sigma_u = %.4f, sigma = %.4f, R = %.4f\\n\",\n        sigma_u, sigma_e, R.estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nobserved SD about the fixed line : 2.0880\nsimulated SD about the fixed line: 1.0995\nsigma alone                      : 1.0969\nsqrt(sigma_u^2 + sigma_e^2)      : 2.0689\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n┌ Warning: Hessian is numerically singular at the optimum — using a pseudo-inverse.\n│ The fit is at a variance/dispersion boundary, so standard errors for the\n│ flagged coordinates are NOT trustworthy. Prefer `confint(fit, method = :profile)`\n│ or the bootstrap entry points for those targets.\n│   context = \"\"\n│   flat_coordinates =\n│    1-element Vector{Int64}:\n│     4\n│   rcond = 4.2988383010350234e-19\n└ @ DRM ~/.julia/packages/DRM/WUZrp/src/vcov_guard.jl:87\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nrefit on simulated data: sigma_u = 0.0000, sigma = 1.1034, R = 0.0000\nthe fit it came from  : sigma_u = 1.7541, sigma = 1.0969, R = 0.7189\n```\n:::\n:::\n\n\nThe simulated spread matches σ and not sqrt(σ_u² + σ²), and the refit recovers a repeatability near zero rather than the one we started with, because the draws were made with every bird effect set to zero. The warning printed above the refit is the engine noticing that the refit has put σ_u at zero, the same edge Class 8 is about, and telling you not to trust the standard errors it would print for that number; the word Hessian names the curvature of the likelihood at its peak, and at an edge there is no peak. If a line at the bottom of the warning names a file inside the engine, that line is for the engine's authors, not for you. That is `simulate` doing exactly what it documents and nothing else. It makes this call the right way to generate a null in which individuals do not differ, and the wrong way to check whether a mixed model reproduces the spread of your data. Read what a function promises before you trust a hundred draws from it.\n\n---\n\n## Further reading\n\n*Graded by depth.*\n\n1. **Nakagawa, S. & Schielzeth, H. (2010) \"Repeatability for Gaussian and non-Gaussian data: a practical guide for biologists\", *Biological Reviews* 85:935–956.** doi:10.1111/j.1469-185X.2010.00141.x. The direct source for everything in the second half of this class: adjusted versus unadjusted repeatability, what to do when the response is not normal, and how to get an interval that is not a fiction. Read it before you report an R.\n2. **Lessells, C. M. & Boag, P. T. (1987) \"Unrepeatable repeatabilities: a common mistake\", *The Auk* 104:116–121.** doi:10.2307/4087240. Two pages, one formula, thirty years of citations. It is the source of the `n0` in the class cell, and the reason the analysis-of-variance route works at all when individuals have different numbers of measurements. Read it for the pleasure of watching a whole literature get corrected in half a morning's work.\n3. **Dohm, M. R. (2002) \"Repeatability estimates do not always set an upper limit to heritability\", *Functional Ecology* 16:273–280.** doi:10.1046/j.1365-2435.2002.00621.x. The counterweight to the bound this class hands you. It sets out when h² ≤ R fails, chiefly when additive genetic and permanent environment effects covary, or when maternal and early-environment effects enter some measurements and not others. Read it the first time you want to lean on the bound in print.\n4. **Nakagawa, S., Johnson, P. C. D. & Schielzeth, H. (2017) \"The coefficient of determination R² and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded\", *Journal of the Royal Society Interface* 14:20170213.** Where this chapter's ratio goes once the response stops being Gaussian, which is Class 9. Harder than item 1 and the natural sequel to it.\n5. **Zuur, A. F., Ieno, E. N. & Elphick, C. S. (2010) \"A protocol for data exploration to avoid common statistical problems\", *Methods in Ecology and Evolution*.** Recommended in Class 2 and earning its place again: the section on dependency is exactly today's lesson, written before you had a tool for it.\n6. **Gelman, A. & Hill, J. (2007) *Data Analysis Using Regression and Multilevel/Hierarchical Models*.** Chapter 12 for the shrinkage picture drawn about six different ways, which is the fastest route to it becoming obvious. Ignore the software.\n7. **DRM.jl documentation, the `(1|g)` rows of `capabilities`.** Which random-effect structures are tested and which are rejected, stated plainly. Worth a look before you assume a term will fit.\n\n---\n\n## Exercises\n\nUse your own organism where one is named. **For every question, paste your code and then explain in your own words what each line does**, as if to somebody who has done Class 2 and not Class 6.\n\n1. **Find the identifier.** Take a dataset of your own with repeated measurements. Report the number of rows, the number of individuals, and the distribution of measurements per individual, using `combine(groupby(...), nrow => :k)`. Then write one sentence naming what would have been counted as independent evidence if you had not looked.\n\n2. **Both fits, both standard errors.** Fit your response on one predictor with and without `(1 | id)`. Report both slopes and both standard errors. Before you look, predict whether the standard error will go up or down, using the between-versus-within argument from class, and say afterwards whether you were right and why.\n\n3. **Repeatability, by hand and from the fit.** Compute R from `re_sd` and `sigma` yourself, then check against `repeatability(fit)`. Report the interval too. Then write the one sentence you would put in a paper, including the words \"estimated by\".\n\n4. **Adjusted or not.** Fit the same random intercept with and without your fixed effect. Report both repeatabilities. Which of the two answers the question you actually care about? Two sentences.\n\n5. **Draw the shrinkage.** Produce the caterpillar for your own data, with a stated rule for choosing which groups to show if you have too many to plot. Then answer: which group moved furthest, and is that because it had the least data or because it started furthest from the middle? Both are legitimate answers; the numbers decide.\n\n6. **Toto's water fleas.** *(Daphnia)* If you have clonal lines, R is a heritability in disguise. Compute it, then say in one sentence why the same arithmetic gets a different name when the groups are genotypes rather than individuals, and what would have to be true of the design for that name to be earned.\n\n7. **Break the pretence deliberately.** Take the chapter's file and collapse it to one row per bird by averaging. Fit the single-level model to the averages. Compare its slope and standard error to both of today's fits. Explain in two sentences why averaging is not the same as modelling the individual, and name one thing you threw away.\n\n8. **The free upper bound.** Your repeatability from question 3 caps the narrow-sense heritability of that trait. State the cap, name the estimator that produced it and say whether it is adjusted or unadjusted, then write two sentences: one explaining why h² cannot exceed R, in terms of what is on top of each ratio, and one naming something permanent about your individuals that would sit inside R and outside h². Finally, find a paper in your field reporting a heritability for a trait like yours and check it against any repeatability the same paper reports. If it reports no repeatability, say what you would have to measure to get one.\n\n",
    "supporting": [
      "wk6-random-intercepts_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}