# Review: Class 1 — base camp (`book/wk1-base-camp.qmd`)

Reviewed at commit `e9a6d4a`. Source read via `git show e9a6d4a:book/wk1-base-camp.qmd`; executed
output read via `git show e9a6d4a:_freeze/book/wk1-base-camp/execute-results/html.json`. The
working tree was not touched (another agent may be re-rendering it); no file was edited except
this one.

## Review

Checked, in the order requested:

1. **Every output-bearing sentence against the frozen execution, plus an independent
   re-derivation.** Extracted the frozen `markdown` field from the freeze JSON and compared it
   line by line against the `.qmd` prose. Independently re-derived every count and mean from
   `git show e9a6d4a:data/2012/MBodySize.csv` with Python's `csv` module (no pandas needed), and
   independently re-ran the seeded coin-flip cell with a standalone Julia script
   (`MersenneTwister(20260907)` / `MersenneTwister(20260908)`, Julia 1.10.0, same as the chapter's
   engine line).

   | quantity | chapter text | frozen output | Python/Julia re-derivation |
   |---|---|---|---|
   | rows / columns | 171 / 8 | `rows: 171   columns: 8` | 171 rows, 8 columns |
   | mean wing | 77.85 mm | `77.8523` | 77.8523 |
   | SD wing | 2.09 | `2.0932` | 2.0932 (ddof=1) |
   | tarsus range | 16.9–20.55 | `16.9000` to `20.5500` | 16.9 / 20.55 |
   | males / females / total | 82 / 89 / 171 | `males  : 82` / `females: 89` / `total  : 171` | 82 / 89 / 171 |
   | mean wing M / F / gap | 79.25 / 76.57 / 2.68 | `79.2454` / `76.5688` | 79.2454 / 76.5688, gap 2.6766→2.68 |
   | females above male mean | 2 of 89 | (inline, `echo:false`) | 2 of 89 |
   | males below female mean | 5 of 82 | (inline, `echo:false`) | 5 of 82 |
   | birds in overlap band | 138 of 171 | (inline, `echo:false`) | 138 of 171 |
   | coin-flip proportions | 0.483, 0.483 (same seed), 0.484 (seed+1) | `0.4830` / `0.4830` (`identical draws: true`) / `0.4840` (`identical draws: false`) | 0.4830 / 0.4830 (identical) / 0.4840 (not identical) |
   | `first(sparrows,5)` BirdID min/max via `describe` | TA14502 / VX04500 | TA14502 / VX04500 | TA14502 / VX04500 |
   | `bf(f)` sigma slot | "holds `1`" | `:sigma => 1` | — (printed value, not recomputed) |

   Every number checks out exactly, including the three inline values (`n_f_above`, `n_m_below`,
   `n_band`) that are computed in an `echo:false`/`output:false` cell and never separately printed
   in the freeze — they only appear already substituted into Itchy's prose, and the independent
   Python re-derivation confirms all three.

   **The four error beats**, checked character-for-character against the frozen `.cell-output
   .cell-output-error` HTML:
   - Misspelled column: frozen `ArgumentError: column name "Wingg" not found in the data frame;
     existing most similar names are: "Wing"` — Itchy quotes `ArgumentError`, the `column name
     "Wingg" not found in the data frame` clause, and `existing most similar names are: "Wing"`
     verbatim, split into the "fact" and "answer" as claimed.
   - Missing package: frozen `ArgumentError: Package DataFrame not found in current path. - Run
     `import Pkg; Pkg.add("DataFrame")` to install the DataFrame package.` — Itchy's "Line two,
     `Run import Pkg; Pkg.add("DataFrame")`, is a **guess**" quotes the actual suggestion text, and
     correctly reports the stack trace contains no line of the reader's own code (all five frames
     are inside `Base`/`loading.jl`).
   - Type error: frozen candidates are `+(::Any, ::Any, ::Any, ::Any...)` (four-argument), and two
     `ChainRulesCore` methods (`NoTangent`, `NotImplemented`) — Itchy's "a four-argument version of
     `+`, and two from a package about automatic differentiation" is accurate (`ChainRulesCore` is
     indeed an AD-support package), and the red/`!Matched` markers in the frozen HTML
     (`ansi-bright-red-fg`) sit exactly where claimed: on arguments never supplied by the reader.
   - Argument-order error: frozen candidates are `filter(::Any, ::Attributes)`,
     `filter(::Any, ::BitArray)`, `filter(::Any, ::Array{T,N})` — the red marker is on the second
     argument in all three, first argument `::Any` in all three, exactly as Toto reads it aloud.

2. **Bare numerals in dialogue.** Grepped every `**Character:**` line for digits. Every hit is
   either (a) wrapped in inline `` `{julia} ... }` `` code, (b) a `Class N` / `Appendix A`
   cross-reference (permitted), or (c) part of a code identifier or literal being discussed as text
   (`::Float64`, `"0.5"`, `!Matched`) rather than a claimed output number. No violation found.

3. **`MersenneTwister` / no `Random.seed!`.** `grep -n "MersenneTwister\|Random.seed!\|rand("`
   shows three `MersenneTwister(...)` constructions (`rng_sim`, and the two comparison draws) and
   one `rand(rng, Bool, n)` call that always takes an explicit `rng`. `Random.seed!` appears only
   in the "Julia stuff" summary bullet, as the thing the book says to *never* use. Clean.

4. **Cross-references.** Checked every `Class N` pointer against `docs/the-climb.md` and, where the
   climb's one-line rung summary didn't obviously cover the claim, against the actual chapter file:
   - `Class 2` (linear model, `aic(fit)`, drawing the cloud again before fitting): rung 2 is "the
     linear model" and `book/wk2-linear-models.qmd` does call `aic(fit1)`, `aic(fit2)`, `aic(fit3)`
     repeatedly — correct.
   - `Class 3` ("a residual in Class 3"; `residuals(fit; type=:quantile, ...)` as "Class 3's
     diagnostic, which works for every family"): the climb's rung-3 one-liner is "the shape of the
     noise — GLMs", with residuals/diagnostics formally assigned to rung 5. This looked like a
     misattribution at first read, but `book/wk3-glms.qmd` line 344 does introduce **randomised
     quantile residuals** ("one diagnostic plot works for every chapter in this book") as the
     overdispersion check, and `book/wk5-diagnostics.qmd` explicitly calls back to "the one you
     were taught" in Class 3 before deepening it. So the pointer is correct — the climb's rung
     table is a compressed one-line-per-chapter summary and doesn't list every technique a chapter
     introduces in service of its own topic.
   - `Class 4` (the `sigma` slot): rung 4 is "the family lies about the spread... `sigma ~ x`" —
     correct.
   - `Class 5` ("more of my mistakes than any diagnostic in Class 5"): rung 5 is diagnostics —
     correct.
   - `Class 10` (the `Vector{Float64}` interop pattern persisting "all the way to Class 10"): rung
     10 is the last v1 chapter, and this is a non-specific narrative claim, not a technical
     attribution — fine.
   - `Appendix A`: referenced three times by name only (never as a markdown link), and
     `book/appendix-a-simulation.qmd` exists with a matching frozen result — correct.

5. **The six citations**, checked against OpenAlex by DOI (`curl` to
   `api.openalex.org/works/https://doi.org/<doi>`):
   - Bezanson et al. 2017, *SIAM Review* 59:65–98, doi:10.1137/141000671 — title, four authors,
     volume/pages all match.
   - Bouchet-Valat & Kamiński 2023, *JSS* 107(4), doi:10.18637/jss.v107.i04 — matches.
   - Barik et al. 2017, ICSE 2017, pp. 575–585, doi:10.1109/ICSE.2017.59 — matches, including the
     exact `raw_source_name` "2017 IEEE/ACM 39th International Conference on Software Engineering
     (ICSE)". Pulled the OpenAlex abstract and confirmed **56 participants**, eye-tracking,
     "difficulty reading these messages is comparable to... reading source code", "significantly
     predicts... task performance", "13%-25%" of task time — the chapter's annotation
     ("participants did read the messages, reading them was about as hard as reading source code,
     that difficulty predicted whether they solved the task, and it took 13–25% of their total
     time") is attributed no more narrowly than the abstract supports.
   - Becker et al. 2019, ITiCSE-WGR '19, pp. 177–210, doi:10.1145/3344429.3372508 — matches;
     `raw_source_name` is "Proceedings of the Working Group Reports on Innovation and Technology in
     Computer Science Education", i.e. ITiCSE's working-group-reports track, consistent with the
     citation's "ITiCSE-WGR '19".
   - Danisch & Krumbiegel 2021, *JOSS* 6(65):3349, doi:10.21105/joss.03349 — matches.
   - The Julia manual URL (`docs.julialang.org`) resolves (HTTP 200).

6. **The R translate box.** `data/ch1/ch1-r-box.R` reads the same
   `data/2012/MBodySize.csv`, and its captured `data/ch1/ch1-r-box.txt` matches what's pasted into
   the qmd's ```` ```r ```` block, line for line (mean wing 77.85234, males 82, F mean_wing 76.6/n=89,
   M mean_wing 79.2/n=82, Tarsus/Wing summary quantiles) — all consistent with the Julia numbers on
   the same page to the displayed precision. One cosmetic-only difference: the `.txt` file has
   `# A tibble: 2 × 3` (Unicode `×`) while the qmd's pasted block has `2 x 3` (ASCII); no numeric
   content is affected.

7. **The four SVG figures**, converted to PNG with `rsvg-convert` and viewed:
   - `fig-wing-hist`: caption "the six summary numbers cannot show you" — the histogram is
     unimodal, roughly bell-shaped, no missing-value spike at zero, dashed mean line near the
     visual centre. Teaches the claim. Minor: there is a small secondary local bump around 80–81 mm
     (about half the height of the main peak) that a very literal reading of "one hump" doesn't
     quite own — see suggestion below.
   - `fig-cloud`: caption "with nothing fitted to it" — a visibly positive, roughly linear-looking
     tarsus–wing relationship with real scatter, matching Toto's "there is obviously a line through
     it" and Itchy's "obviously *something*". Teaches the claim.
   - `fig-sexes`: caption "the two group means as dashed lines" — teal/orange points cleanly
     separated by colour and marker, teal and orange dashed horizontal lines at the two means,
     substantial visual overlap between the clouds. Matches Momo's "separated... also sitting in
     each other's laps" exactly.
   - `fig-coin`: caption "both wander, both settle, neither lands on a half" — both running
     proportions swing wildly in the first ~100 flips, converge toward but do not touch the dotted
     0.5 line by flip 1000. Teaches the claim.

## Verdict

**PASS.** No blocking or required findings. Every count, mean, seeded proportion, and quoted error
message matches the frozen execution and an independent re-derivation exactly; no bare numerals in
dialogue; every random draw is seeded via `MersenneTwister` with no `Random.seed!`; all `Class N`
cross-references check out against `docs/the-climb.md` and the actual chapters they point to; all
six citations are correctly attributed; the R box numbers match the Julia numbers; all four figures
teach what their captions claim.

## Findings

No blocking or required findings.

- **Suggestion.** `fig-wing-hist`'s caption/dialogue reading ("One hump, roughly symmetric, no
  second peak hiding out at the right-hand end") is defensible — the secondary bump around 80–81 mm
  is plainly visible rather than "hidden", and it's much smaller than the main peak — but a more
  cautious reader could call the histogram mildly bumpy rather than cleanly unimodal. Not worth
  blocking; flagging in case a future pass wants tighter language.
- **Suggestion.** The R box's pasted output in the qmd (`# A tibble: 2 x 3`, ASCII `x`) differs
  cosmetically from the actual captured `data/ch1/ch1-r-box.txt` (`2 × 3`, Unicode multiplication
  sign). No numeric or semantic difference; likely a deliberate ASCII substitution for the markdown
  source, but noting it since the box claims to be the file's contents pasted verbatim.

## Re-derivations

- CSV re-derivation script (Python, `csv` module, from `git show e9a6d4a:data/2012/MBodySize.csv`):
  reproduced 171/8, mean/SD wing (77.8523/2.0932), tarsus range (16.9/20.55), sex counts (82/89),
  per-sex means/gap (79.2454/76.5688/2.6766), the two "above/below the other sex's mean" counts
  (2/89, 5/82), the overlap-band count (138/171), and BirdID min/max (TA14502/VX04500) — all exact
  matches to the frozen output and the chapter prose.
- Seed re-derivation script (standalone Julia 1.10.0, `MersenneTwister`, no repo files touched):
  reproduced `p_a = 0.4830`, `p_b = 0.4830` with `run_a == run_b` true, `p_c = 0.4840` with
  `run_a == run_c` false — exact match to the frozen stdout and the chapter's rounded prose (0.483,
  0.483, 0.484).
- Citation re-derivation: five DOIs resolved via OpenAlex (`curl
  https://api.openalex.org/works/https://doi.org/<doi>`), title/authors/venue/volume/pages compared
  against the "Further reading" entries; the Barik et al. abstract was pulled in full to check the
  56-participants / 13–25%-of-time / reading-difficulty claims are not over-attributed.
- Figures: extracted the four SVGs from `git show
  e9a6d4a:docs/site/book/wk1-base-camp_files/figure-html/*.svg`, rasterised with `rsvg-convert`, and
  viewed each as an image (not just checked for file presence) against its caption and the
  surrounding dialogue.
