{
  "hash": "86877bcb58c3633cdd86cc2f941d9d00",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Class 3: the shape of the noise\"\nbook: Stats Hours with Itchy\nchapter: 3\ntype: book-chapter\nstatus: draft\ncreated: 2026-09-07\nengines: DRM.jl 0.7.1 at 4d9248f88 (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)\ntags: [book, julia, glm, logistic, poisson, DRM.jl]\ndeck: \"A model that gives a chick a better than hundred per cent chance of surviving is not slightly wrong. It is the wrong shape, and the family is how you fix it.\"\nstatus_tag: Draft\nstatus_note: \"All ten classes of version 1 are drafted and their code runs end to end (1–10), with Appendix A, the preface and the coda. Every number and figure on this page was produced when the site was built; the book itself is not written.\"\nprovenance: \"Every code block and printed result below was actually run when the site was built, and nothing is typed from memory. Every random draw is seeded in the cell that makes it, so the page comes out the same every time. The one R block was run once by hand, on the date shown, with R against the same files, and is labelled as such.\"\ncaveat: \"The data are real: the 2012 Lundy Island chick and female records, read directly from data/2012/ChickSurvival.csv and data/2012/FemaleSuccess.csv (provenance in data/2012/README.md). Nothing here is simulated except the one seeded cell that says so.\"\nfooter_note: \"Stats Hours with Itchy · Class 3 of a planned 13, ten in v1, plus a coda · draft, all code run, 2026-09-07\"\n---\n\n\n# Class 3: the shape of the noise\n\n> **What this chapter pretends.** These chicks come out of nests, and chicks from one nest are\n> not independent draws any more than the repeated measurements in Class 6 are. This chapter\n> fits fixed effects only and pretends that a brood is not a thing. It is the same pretence\n> Class 2 made, and **Class 9** is where it ends for a response like this one — Class 6 frees\n> the related constraint on repeated measures of one bird. Everything here about links and variance\n> functions survives that repair unchanged; the standard errors do not. Note what the repair\n> costs: this file records how *big* each brood was and never *which* brood a chick came from,\n> so ending the pretence here needs a dataset that carries the brood identifier, not a\n> different formula on this one.\n\n---\n\n## Objectives\n\nBy the end of this class you should be able to:\n\n1. Say why a linear model fitted to a yes-or-no response is the wrong **shape**, not merely inaccurate, and show it from the fitted values alone.\n2. Fit a logistic regression with `Binomial()` and say what a coefficient means on the log-odds scale.\n3. Turn that coefficient into an odds ratio, and turn the model into a probability for a named animal.\n4. Explain what the family decrees about the **variance**, and why a GLM prints no σ table as a result.\n5. Fit a Poisson model to counts, read a rate ratio, and run the one check that tells you the decree is about to fail.\n\n---\n\n## The class\n\n**Itchy's office, 9:00 am, and the whiteboard has been wiped for once. TOTO has a spreadsheet of dead and living chicks and the expression of somebody who has already tried something. MOMO has brought a different dataset entirely, which is not how this is supposed to work but is how it always goes.**\n\n**Itchy:** Class 2 gave you a line through a cloud. Every response was a length in millimetres and could be any number at all. Today both of you have brought me responses that cannot.\n\n**Toto:** Mine is whether a chick survived. It is a one or a zero.\n\n**Momo:** Mine is how many chicks a female fledged. It is a whole number and it is never negative.\n\n**Itchy:** And neither of those is a length in millimetres, so today we free the thing Class 2 held fixed without telling you: **the shape of the noise**. Load Toto's first.\n\n::: {#cell-setup .cell execution_count=1}\n``` {.julia .cell-code}\n# tools/figures.jl includes tools/theme_itchy.jl itself, so one include does both.\ninclude(\"../tools/figures.jl\")\nusing DRM, DataFrames, CSV, Statistics, Random, Printf, CairoMakie\nset_theme!(theme_itchy(:light))\n\nchicks = CSV.read(\"../data/2012/ChickSurvival.csv\", DataFrame)\n\nn_chicks = nrow(chicks)\nn_lived = sum(chicks.Survival)\np_lived = mean(chicks.Survival)\n\n@printf(\"rows: %d   survived: %d   overall survival: %.4f\\n\", n_chicks, n_lived, p_lived)\ndescribe(chicks, :mean, :std, :min, :max, :nmissing)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows: 1576   survived: 689   overall survival: 0.4372\n```\n:::\n\n::: {#setup .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div><div style = \"float: left;\"><span>5×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">std</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">nmissing</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Symbol\" style = \"text-align: left;\">Symbol</th><th title = \"Union{Nothing, Float64}\" style = \"text-align: left;\">Union…</th><th title = \"Union{Nothing, Float64}\" style = \"text-align: left;\">Union…</th><th title = \"Any\" style = \"text-align: left;\">Any</th><th title = \"Any\" style = \"text-align: left;\">Any</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Survival</td><td style = \"text-align: left;\">0.437183</td><td style = \"text-align: left;\">0.496196</td><td style = \"text-align: left;\">0</td><td style = \"text-align: left;\">1</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Sex</td><td style = \"font-style: italic; text-align: left;\"></td><td style = \"font-style: italic; text-align: left;\"></td><td style = \"text-align: left;\">F</td><td style = \"text-align: left;\">M</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Mass2</td><td style = \"text-align: left;\">3.62754</td><td style = \"text-align: left;\">1.18806</td><td style = \"text-align: left;\">1.2</td><td style = \"text-align: left;\">9.6</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">BroodSize</td><td style = \"text-align: left;\">3.77538</td><td style = \"text-align: left;\">1.01871</td><td style = \"text-align: left;\">1</td><td style = \"text-align: left;\">6</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">JulianDate</td><td style = \"text-align: left;\">79.4023</td><td style = \"text-align: left;\">30.3853</td><td style = \"text-align: left;\">22</td><td style = \"text-align: left;\">141</td><td style = \"text-align: right;\">0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Itchy:** 1576 chicks, of which 689 lived. Look before you model, always, and today look hardest at the response column.\n\n**Toto:** It is only ever zero or one.\n\n**Itchy:** It is only ever zero or one, and there is no third value hiding anywhere in it. Hold that thought for exactly as long as it takes you to ignore it, which I am now going to make you do on purpose.\n\n### The model that is the wrong shape\n\n**Itchy:** Fit it the Class 2 way. Same verb, same box, same family as last week.\n\n::: {#cell-fit-gaussian .cell execution_count=2}\n``` {.julia .cell-code}\nwrong = drm(bf(@formula(Survival ~ Mass2)), Gaussian(); data = chicks)\nwrong\n```\n\n::: {#fit-gaussian .cell-output .cell-output-display execution_count=4}\n```\nDistributional regression fit (Gaussian)\n  nobs = 1576   logLik = -1018.6237   converged = true\n  Residual SD (response scale) = 0.4618   dof_residual = 1573\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  -0.1159     0.0374  -3.0990   0.001942\n  Mass2         0.1525     0.0098  15.5655  1.249e-54\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                 Coef.  Std.Error         z  Pr(>|z|)\n  (Intercept)  -0.7726     0.0178  -43.3760         0\n```\n:::\n:::\n\n\n**Toto:** It worked. It gave me a slope and a *p*-value with a lot of zeros in it.\n\n**Itchy:** It worked, it converged, and nothing in that output is complaining. This is the most dangerous kind of wrong: the arithmetic is impeccable and the model is nonsense. Ask it what it believes. Not what it estimated, what it **believes** about an actual chick.\n\n::: {#gaussian-predictions .cell execution_count=3}\n``` {.julia .cell-code}\nlo, hi = extrema(fitted(wrong))\nn_impossible = count(x -> x < 0 || x > 1, fitted(wrong))\n\n@printf(\"fitted values run from %.4f to %.4f\\n\", lo, hi)\n@printf(\"fitted values outside [0, 1]: %d of %d chicks\\n\", n_impossible, n_chicks)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfitted values run from 0.0671 to 1.3477\nfitted values outside [0, 1]: 4 of 1576 chicks\n```\n:::\n:::\n\n\n**Toto:** The biggest one is bigger than one.\n\n**Itchy:** The biggest one is 1.348, and it is a probability. This model believes that a heavy chick has a 135% chance of surviving, which is a sentence about birds and it is not a true one. And 4 chicks are given a probability the world does not contain.\n\n**Momo:** But most of the fitted values are legal. It is 4 chicks out of 1576.\n\n**Itchy:** Then do not rest the case on those 4. The impossible predictions are the fault you can see; there is a worse one underneath, and it is wrong for every row rather than 4 of them. Class 2's σ was one number for every bird. Here the response is a coin flip, so its variance is p(1 − p) — biggest for a chick with an even chance, shrinking towards nothing at either extreme. Constant σ is violated **by construction**, before a single chick is weighed. That is why this model's standard errors are wrong at every mass, including the masses where its predictions are legal, and it is exactly the theme of today's class turned on today's wrong model.\n\n**Momo:** So the *p*-value was tiny and the model was still impossible.\n\n**Itchy:** The *p*-value was tiny and the model was still impossible, and I want that on the first page of your notes. **A small *p*-value is not evidence that the model is the right shape.** It cannot be, because it is computed *inside* the model. You have to look outside it, at the predictions, at your organism, and ask whether the model believes anything absurd. Draw it.\n\n::: {#cell-fig-two-shapes .cell execution_count=4}\n``` {.julia .cell-code}\n# A little vertical jitter so a thousand overlapping zeros and ones are visible\n# as a band rather than a line. Seeded, so the picture is the same every time the site is built.\nrng = MersenneTwister(20260907)\njitter = 0.03 .* randn(rng, n_chicks)\n\nxs = range(minimum(chicks.Mass2), maximum(chicks.Mass2), length = 200)\nb_wrong = coef(wrong, :mu)\n\nfig = Figure(size = (540, 380))\nax = Axis(fig[1, 1]; xlabel = \"mass at day 2 (g)\", ylabel = \"survived (0 / 1)\",\n    title = \"one straight line through a yes-or-no answer\")\nhlines!(ax, [0.0, 1.0]; color = (:grey, 0.5), linestyle = :dot)\nscatter!(ax, chicks.Mass2, chicks.Survival .+ jitter;\n    markersize = 4, color = (:grey, 0.35))\nlines!(ax, xs, b_wrong[1] .+ b_wrong[2] .* xs; linewidth = 2.5, label = \"Gaussian\")\n# legend outside the axis so it can never sit over a data point, matching tools/figures.jl\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n![Chick survival against mass at day two, jittered vertically so the overlapping zeros and ones separate into a band, with dotted lines at 0 and 1 marking the only two answers the world allows. The straight line from the Gaussian fit climbs off the top of that band for the heaviest chicks and would leave through the floor for chicks lighter than these — a shape free to promise a probability the world does not contain.](wk3-glms_files/figure-html/fig-two-shapes-output-1.svg){#fig-two-shapes}\n:::\n:::\n\n\n**Itchy:** The dotted lines are the only two answers the world allows. The straight line leaves through the ceiling on the right and would leave through the floor on the left if the chicks were lighter. That is not a line that fits badly. That is a line that is the **wrong shape** for the question, and no amount of extra data will bend it.\n\n### The model that is the right shape\n\n**Itchy:** Momo, you have been waiting to say something for ten minutes.\n\n**Momo:** In SPSS this was a menu item called logistic regression. What I never got told is what it actually changes.\n\n**Itchy:** Then that is the lesson, and it changes exactly two things. First, it puts the straight line somewhere the straight line is allowed to go, and then bends it back. The line lives on the **log-odds** scale, which runs from minus infinity to plus infinity like a proper linear predictor — the straight-line sum of intercept and slopes that every regression builds before anything bends it — and a function called the **link** squashes it back into nought-to-one before it meets a chick. Second, and this is the part almost nobody is taught, it changes what the model claims about the **noise**. Watch both. One word changes in the call.\n\n::: {#cell-fit-logistic .cell execution_count=5}\n``` {.julia .cell-code}\nlogit_fit = drm(bf(@formula(Survival ~ Mass2)), Binomial(); data = chicks)\nlogit_fit\n```\n\n::: {#fit-logistic .cell-output .cell-output-display execution_count=8}\n```\nDistributional regression fit (Binomial)\n  nobs = 1576   logLik = -968.7711   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error         z   Pr(>|z|)\n  (Intercept)  -2.8152     0.1968  -14.3035  2.081e-46\n  Mass2         0.6999     0.0514   13.6096  3.509e-42\n```\n:::\n:::\n\n\n**Toto:** Same verb, same box. The family is different and the numbers are bigger.\n\n**Itchy:** The family is different, the numbers are on a different scale, and something has **gone missing**. Momo, you were the one who complained about the second table in Class 2. Where is it?\n\n**Momo:** There is no σ table.\n\n**Itchy:** There is no σ table, and that absence is the whole second half of today. Park it for five minutes while we read the coefficient, because the coefficient is on a scale neither of you has met.\n\n::: {#logit-scale .cell execution_count=6}\n``` {.julia .cell-code}\nb_logit = coef(logit_fit, :mu)\nslope_logodds = b_logit[2]\nodds_ratio = exp(slope_logodds)\n\n@printf(\"slope on the log-odds scale : %.4f\\n\", slope_logodds)\n@printf(\"exp(slope), the odds ratio  : %.4f\\n\", odds_ratio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nslope on the log-odds scale : 0.6999\nexp(slope), the odds ratio  : 2.0135\n```\n:::\n:::\n\n\n**Itchy:** The number the model estimated is 0.7, and on its own it means nothing to a biologist, because nobody has ever had an intuition about log-odds. Exponentiate it and it becomes a sentence you can say to a bird person: **one extra gram of mass multiplies a chick's odds of surviving by 2.01.** Odds, not probability. They are not the same thing and I will make you say the difference out loud.\n\n**Toto:** Odds are the chance it happens divided by the chance it does not.\n\n**Itchy:** Exactly that, and the reason the model works in odds is that odds can be multiplied without ever leaving the space of legal answers. Double them, double them again, they never reach one. Probabilities do not behave: add ten per cent to ninety-five per cent twice and you have left the world. That is why the link exists.\n\n**Momo:** Then give me a probability. That is what I would put in the paper.\n\n**Itchy:** Then ask the model for one, at a mass you can point at.\n\n::: {#predict-probability .cell execution_count=7}\n``` {.julia .cell-code}\ngrid = (; Mass2 = [2.0, 3.5, 5.0])\np_hat = predict(logit_fit, grid)\np_mid = predict(logit_fit, (; Mass2 = [3.5]); se = true)\n\nfor (m, p) in zip(grid.Mass2, p_hat)\n    @printf(\"a %.1f g chick: probability of surviving %.4f\\n\", m, p)\nend\n@printf(\"\\nat 3.5 g, standard error on that probability (delta method): %.4f\\n\", p_mid.se[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\na 2.0 g chick: probability of surviving 0.1954\na 3.5 g chick: probability of surviving 0.4096\na 5.0 g chick: probability of surviving 0.6647\n\nat 3.5 g, standard error on that probability (delta method): 0.0134\n```\n:::\n:::\n\n\n**Itchy:** **A three-and-a-half gram chick has about a 41% chance of surviving.** A two-gram chick, 20%. A five-gram chick, 66%. Those are sentences about chicks, they are in the units the question was asked in, and not one of them is impossible. The last line puts a standard error on the middle one, and notice how it was made: the model's uncertainty lives on the log-odds scale, so the engine carries it through the squashing function onto the probability scale. That piece of arithmetic is called the **delta method**, and whenever this book says \"delta-method standard error\" that is all it means. Now put the two models on the same picture.\n\n::: {#cell-fig-curve .cell execution_count=8}\n``` {.julia .cell-code}\np_curve = predict(logit_fit, (; Mass2 = collect(xs)))\n\nfig = Figure(size = (540, 380))\nax = Axis(fig[1, 1]; xlabel = \"mass at day 2 (g)\", ylabel = \"probability of surviving\",\n    title = \"the same data, two shapes\")\nhlines!(ax, [0.0, 1.0]; color = (:grey, 0.5), linestyle = :dot)\nscatter!(ax, chicks.Mass2, chicks.Survival .+ jitter;\n    markersize = 4, color = (:grey, 0.35))\nlines!(ax, xs, b_wrong[1] .+ b_wrong[2] .* xs;\n    linewidth = 2, linestyle = :dash, label = \"Gaussian\")\nlines!(ax, xs, p_curve; linewidth = 2.5, label = \"Binomial, logit link\")\n# legend outside the axis so it can never sit over a data point, matching tools/figures.jl\n# (this legend used to sit inside the axis at top-left, over four real markers\n# from the jittered survival cloud — moved out after that was caught in review)\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n![The same jittered survival cloud, now with the Gaussian line dashed and the logistic curve solid over it. The curve never crosses either dotted bound and flattens at both ends, so an extra gram buys almost nothing near certain death or certain survival, and the most near the steepest point in between.](wk3-glms_files/figure-html/fig-curve-output-1.svg){#fig-curve}\n:::\n:::\n\n\n**Toto:** The curve flattens out at both ends.\n\n**Itchy:** Both ends, Toto, and keep the second half of that sentence, because it is the half people drop. The curve cannot go above one or below zero, so at either extreme it runs out of room and an extra gram buys almost nothing. Between the two ends there is a steepest point. Where that point falls is a number, not a feeling, so compute it before you say anything about birds.\n\n::: {#where-a-gram-matters .cell execution_count=9}\n``` {.julia .cell-code}\ngain_low  = p_hat[2] - p_hat[1]          # 2.0 g -> 3.5 g\ngain_high = p_hat[3] - p_hat[2]          # 3.5 g -> 5.0 g\ninflection = -b_logit[1] / b_logit[2]    # the mass at which the model says p = 1/2\nmean_mass = mean(chicks.Mass2)\nfrac_below = mean(chicks.Mass2 .< inflection)\n\n@printf(\"2.0 g -> 3.5 g buys         : %.4f of probability\\n\", gain_low)\n@printf(\"3.5 g -> 5.0 g buys         : %.4f of probability\\n\", gain_high)\n@printf(\"steepest point (p = 1/2) at : %.4f g\\n\", inflection)\n@printf(\"mean mass in these data     : %.4f g\\n\", mean_mass)\n@printf(\"proportion lighter than it  : %.4f\\n\", frac_below)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2.0 g -> 3.5 g buys         : 0.2142 of probability\n3.5 g -> 5.0 g buys         : 0.2551 of probability\nsteepest point (p = 1/2) at : 4.0224 g\nmean mass in these data     : 3.6275 g\nproportion lighter than it  : 0.6459\n```\n:::\n:::\n\n\n**Toto:** The second step buys *more* than the first.\n\n**Itchy:** It does. Two grams to three and a half buys 0.214 of survival probability; three and a half to five buys 0.255. Across the range where these chicks actually live, the curve is **accelerating**. Had I told you a gram matters most to the smallest chick, you would now be holding a sentence your own output contradicts.\n\n**Momo:** Why that way round?\n\n**Itchy:** Because a logistic curve is symmetric about a half, and the mass at which it reaches a half is minus the intercept over the slope: 4.02 g. The average chick in this file weighs 3.63 g, and 65% of them are lighter than that steepest point. The majority of this sample, the average chick included, is still climbing *towards* the steepest point rather than coming down the far side. So the honest sentence is the symmetric one: **a gram matters most to a middling chick — middling meaning near 4.02 g, where the model gives it an even chance — and least to a chick already nearly certain to live, or nearly certain to die.**\n\n**Momo:** I have read \"diminishing returns\" in a dozen papers about exactly this.\n\n**Itchy:** And it is true wherever the data sit above the inflection — the steepest point, where p = 1/2 — and false wherever they sit below it, which is why it is something you compute rather than something you say. What holds on both sides is that a gram is **not** worth the same everywhere, and the straight line insists that it is. When somebody asks you why not just use a linear model, that is the answer. Not \"the residuals are non-normal\". That.\n\n**Momo:** Can I put brood size in as well?\n\n**Itchy:** You can, and the sentence you get is the Class 2 sentence with one extra clause.\n\n::: {#cell-fit-two-predictors .cell execution_count=10}\n``` {.julia .cell-code}\nlogit2 = drm(bf(@formula(Survival ~ Mass2 + BroodSize)), Binomial(); data = chicks)\nlogit2\n```\n\n::: {#fit-two-predictors .cell-output .cell-output-display execution_count=16}\n```\nDistributional regression fit (Binomial)\n  nobs = 1576   logLik = -964.9841   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error         z   Pr(>|z|)\n  (Intercept)  -3.4561     0.3099  -11.1508  7.099e-29\n  Mass2         0.7204     0.0523   13.7828  3.236e-43\n  BroodSize     0.1495     0.0546    2.7402   0.006141\n```\n:::\n:::\n\n\n\n\n**Itchy:** Each coefficient is now \"what one more of this buys, **holding the other fixed**\", exactly as in Class 2, and the exponentials are odds ratios rather than millimetres. A gram of mass multiplies the odds by 2.06; a chick more in the brood multiplies them by 1.16. And AIC **fell by** 5.57 when we added it, so unlike the σ experiment at the end of Class 2, this one paid for itself.\n\n**Toto:** Bigger broods are *better* for a chick? I would have guessed the opposite.\n\n**Itchy:** So would I, and this is where you stop being a statistician and go back to being a biologist. A brood is big because a parent could afford a big one. The model has not told you that crowding is good; it has told you that, in these data, chicks in big broods survive better, and the reason for that is a question about territories and parents that no coefficient will answer. This is also exactly the point where Class 9 will tell you that the chicks in one brood are not independent, so that standard error is too small. Today we pretend — and on this file we would have to. It records `BroodSize`, how many chicks were in the nest, and it never records *which* nest. You cannot put a random effect on a grouping nobody wrote down, so the repair is a dataset that carries a brood identifier, not a cleverer formula on this one. Class 9 stops pretending, on a file that can.\n\n### The shape of the noise\n\n**Itchy:** Now the missing table, which is the actual title of this class. Momo, in Class 2 what did σ do?\n\n**Momo:** It said how far the birds scattered around the line, and it was the same number for every bird.\n\n**Itchy:** And it was a **free parameter**: the model estimated it from the data, and in Class 4 you will put predictors on it. Today it is gone, and it is gone because it is no longer free. Toto, a chick with a survival probability of one half. How much does it vary?\n\n**Toto:** ...it either lives or it dies.\n\n**Itchy:** And across many such chicks, the variance of that coin flip is p times one minus p, which for a half is a quarter. You did not estimate that. You did not get a choice about it. **The moment you said `Binomial()`, you decreed that the variance is p(1 − p)** — fixed by the mean, with no freedom left in it. Same for Momo's counts in twenty minutes: say `Poisson()` and you have decreed that the variance equals the mean. Show them.\n\n::: {#variance-decree .cell execution_count=12}\n``` {.julia .cell-code}\np_fit = fitted(logit_fit)\ndecreed = p_fit .* (1 .- p_fit)\np_lo, p_hi = extrema(p_fit)\nv_lo, v_hi = extrema(decreed)\n\n@printf(\"fitted probability     : %.4f to %.4f\\n\", p_lo, p_hi)\n@printf(\"decreed variance p(1-p): %.4f to %.4f\\n\", v_lo, v_hi)\nprintln(\"\\nblocks the fit carries: \", first.(logit_fit.blocks))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfitted probability     : 0.1218 to 0.9802\ndecreed variance p(1-p): 0.0194 to 0.2500\n\nblocks the fit carries: [:mu]\n```\n:::\n:::\n\n\n**Momo:** Numbers. You said \"show\", and I got two ranges.\n\n**Itchy:** Fair complaint. Here is the shape those numbers came from, not a description of it.\n\n::: {#cell-fig-variance-decree .cell execution_count=13}\n``` {.julia .cell-code}\np_grid = range(0, 1, length = 200)\nvar_grid = p_grid .* (1 .- p_grid)\n\nfig = Figure(size = (480, 360))\nax = Axis(fig[1, 1]; xlabel = \"p\", ylabel = \"Var(y) = p(1 - p)\",\n    title = \"the noise Binomial() decrees\")\n# fitted range shaded first, curve drawn on top so it is never hidden by it\nvspan!(ax, p_lo, p_hi; color = (:grey, 0.15), label = \"this fit's p_lo–p_hi\")\nlines!(ax, p_grid, var_grid; linewidth = 2.5, label = \"Var = p(1 - p)\")\nscatter!(ax, [0.5], [0.25]; markersize = 9, color = Cycled(2), label = \"peak: p = 1/2, Var = 1/4\")\n# legend outside the axis, matching tools/figures.jl\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n![The variance Binomial() decrees, Var = p(1-p), plotted across every probability the family allows — not fitted from data, but arithmetic: a coin that lands heads with probability p has this variance and no other is available to it. It peaks at 0.25 when p = 1/2, the coin with the most to be unsure about, and is pinned to zero at both ends. The shaded strip marks the p_lo–p_hi window this chapter's own logistic fit actually produced: nowhere near either end, so no chick in this file got the free ride of near-zero noise.](wk3-glms_files/figure-html/fig-variance-decree-output-1.svg){#fig-variance-decree}\n:::\n:::\n\n\n**Itchy:** That curve is not fitted to anything. It is what `Binomial()` commits you to the moment you say the word, for every p from zero to one, on every dataset that will ever exist. The shaded strip is where this chapter's own chicks actually live — 0.122 to 0.98 — and notice it sits well short of either wall, so nothing in this file was promised the near-zero noise the curve allows at its extremes. And notice what the picture cannot show you: no `Mass2` on either axis, no `BroodSize`, no predictor at all. The variance function does not know what moved the mean. It only knows the mean itself. One block, `mu`, and nothing else. There is no `sigma` block to print because there is no σ to estimate. That is not the engine being unhelpful; it is the engine refusing to invent a parameter the family has already spent.\n\n**Momo:** And if the decree is wrong?\n\n**Itchy:** For Toto's chicks it cannot be, and that is worth saying slowly, because it is the one place where the word \"assumption\" misleads. A response that is only ever zero or one has variance p(1 − p) as a matter of **arithmetic**: a coin that lands heads with probability p has that variance and no other is available to it. There is no overdispersed Bernoulli — the name for exactly that single coin flip — to go looking for. What *can* be wrong with binary data is the other thing — that the rows are not independent draws, because chicks from one nest share a pair of parents and a territory — and that is clustering, which is **Class 6**, not Class 4.\n\n**Momo:** And for my counts?\n\n**Itchy:** For your counts the variance really is a separate claim, and data can contradict it. Then you are in trouble, quietly, in the standard errors, and you will not see it in the coefficients. That is Class 4, and I am deliberately not teaching it today. What I *will* do is give you the check, at the end of the hour, on Momo's counts, where it fails in front of you. Before that, one glance at R, because R says the decree out loud and we do not.\n\n<!-- box: translate | id: glm-dispersion-line | ch: 03 | checked: 2026-09-07 -->\n\n> **↔ TRANSLATE: a sentence in R's output that ours does not print**\n>\n> `glm` in R reproduces this fit to every digit it prints, which is the boring and reassuring\n> part. The interesting part is a line R prints that we do not: **\"(Dispersion parameter for\n> binomial family taken to be 1)\"**. That is the decree, stated out loud, in the output, every\n> time. It is the assumption this whole section is about, and R puts it on the page where a\n> reader can see it and we leave it implicit in the absent σ table.\n>\n> Two things follow. First, when you read somebody else's R output, that line is not\n> boilerplate; it is the model's claim about the noise. For a 0/1 response it is a claim\n> arithmetic already guarantees; for counts, and for proportions out of a denominator, it is a\n> claim the data can contradict, and Class 4 is entirely about those times. Second, \"taken to be 1\" is phrased as an instruction rather than a finding for a\n> reason: nothing was estimated, and nothing was checked.\n>\n> The R block below was **run once, by hand**, with R on 2026-09-07 against the same archived\n> file this chapter reads. It is not run again when the site is built, which is why it carries a\n> date.\n\n```r\n# run once by hand on 2026-09-07; not re-run when the site is built. Produced with:\n#   R 4.6.0, reading data/2012/ChickSurvival.csv\n#   m <- glm(Survival ~ Mass2 + BroodSize, data = d, family = binomial)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)\n(Intercept) -3.45607    0.30994  -11.15  < 2e-16 ***\nMass2        0.72040    0.05227   13.78  < 2e-16 ***\nBroodSize    0.14953    0.05457    2.74  0.00614 **\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 2159.9  on 1575  degrees of freedom\nResidual deviance: 1930.0  on 1573  degrees of freedom\nAIC: 1936\n```\n\n### Is it any good?\n\n**Itchy:** Before anybody writes this down: residuals. And a plain residual is useless here, because \"observed minus fitted\" for a chick that lived is one minus a probability, and those cannot be normally distributed no matter how right the model is.\n\n**Toto:** So what do I plot?\n\n**Itchy:** **Randomised quantile residuals** (Dunn & Smyth 1996). The idea is beautiful and takes one sentence: ask the fitted model what probability it puts on a value at or below the one you saw; because a count lands on a whole number, that is an interval rather than a single number, so you draw uniformly inside it — that is the *randomised* part — and push the result through the inverse normal. If the model is right, the answers are standard normal draws whatever the family was, so one diagnostic plot works for every chapter in this book. They involve a random draw, so they get a seed.\n\n::: {#cell-fig-diagnostic .cell execution_count=14}\n``` {.julia .cell-code}\nqres = residuals(logit2; type = :quantile, rng = MersenneTwister(3))\n\n# An SD estimated from n standard normal draws has Monte Carlo SE 1/sqrt(2n).\n# Judge \"near 1\" against that, not against your eye.\nmcse_logit = 1 / sqrt(2 * length(qres))\nz_logit = abs(std(qres) - 1) / mcse_logit\n\n@printf(\"quantile residuals: mean %.4f, SD %.4f  (both should be near 0 and 1)\\n\",\n        mean(qres), std(qres))\n@printf(\"Monte Carlo SE of that SD : %.4f, so the SD sits %.2f SE from 1\\n\", mcse_logit, z_logit)\n\nfig_l = fig_diagnostic(qres; title = \"logistic fit, randomised quantile residuals\")\n# Fixed, shared y-limits so this panel and the Poisson one below are on the\n# same vertical scale — both panels' real extent (checked at build time) sits\n# well inside ±1.2, so nothing is clipped by fixing the window.\nylims!(fig_l.content[1], -1.2, 1.2)\nfig_l\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nquantile residuals: mean -0.0188, SD 1.0201  (both should be near 0 and 1)\nMonte Carlo SE of that SD : 0.0178, so the SD sits 1.13 SE from 1\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=22}\n![Worm plot of the two-predictor logistic fit's randomised quantile residuals: the residuals lined up from smallest to largest, each compared with where a perfect standard-normal draw would sit, so a good model gives a flat scatter near zero and a bad one wriggles. Here the scatter sits close to the zero line and inside the pale band — the shape a diagnostic takes when there is nothing left to find. The vertical scale is fixed and shared with the Poisson worm plot below, so the two are honestly comparable by eye rather than each stretched to fill its own axis.](wk3-glms_files/figure-html/fig-diagnostic-output-2.svg){#fig-diagnostic}\n:::\n:::\n\n\n**Momo:** That looks like nothing much is happening.\n\n**Itchy:** \"Nothing much is happening\" is what a passing diagnostic looks like, and you should be suspicious of how often the plots in papers look more interesting than this. The spread is 1.02. A spread computed from a random draw has its own wobble, and that wobble has a name — the **Monte Carlo standard error** — so judge the spread against it rather than against your eye: this one sits 1.1 of those from one, which is nothing. But award the model very few marks for it. On a 0/1 response a spread near one is close to automatic, because p(1 − p) is arithmetic rather than a promise the data could break. Treat this plot as the **baseline**: it is what the diagnostic looks like when there is nothing in it to find. Remember the picture in twenty minutes, when Momo's counts give it something.\n\n### Momo's counts\n\n**Itchy:** Right. Momo has been patient. Different file, different question, same two changes.\n\n::: {#cell-read-females .cell execution_count=15}\n``` {.julia .cell-code}\nfemales = CSV.read(\"../data/2012/FemaleSuccess.csv\", DataFrame)\n\nn_fem = nrow(females)\n@printf(\"rows: %d\\n\", n_fem)\ndescribe(females, :mean, :std, :min, :max, :nmissing)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows: 163\n```\n:::\n\n::: {#read-females .cell-output .cell-output-display execution_count=24}\n```{=html}\n<div><div style = \"float: left;\"><span>3×6 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">std</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th><th style = \"text-align: left;\">nmissing</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Symbol\" style = \"text-align: left;\">Symbol</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Fledglings</td><td style = \"text-align: right;\">3.20859</td><td style = \"text-align: right;\">2.33189</td><td style = \"text-align: right;\">0</td><td style = \"text-align: right;\">10</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">EggNo</td><td style = \"text-align: right;\">9.77914</td><td style = \"text-align: right;\">4.32624</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">23</td><td style = \"text-align: right;\">0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">Age</td><td style = \"text-align: right;\">1.88344</td><td style = \"text-align: right;\">0.870594</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Momo:** 163 females, and how many chicks each one got out of the nest.\n\n**Itchy:** And the response is a **count**. Never negative, never a half, and there is no upper limit written anywhere. That is a different shape again, and it gets a different family and a different link.\n\n::: {#cell-fit-poisson .cell execution_count=16}\n``` {.julia .cell-code}\npois_fit = drm(bf(@formula(Fledglings ~ Age)), Poisson(); data = females)\npois_fit\n```\n\n::: {#fit-poisson .cell-output .cell-output-display execution_count=26}\n```\nDistributional regression fit (Poisson)\n  nobs = 163   logLik = -367.9932   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                Coef.  Std.Error       z   Pr(>|z|)\n  (Intercept)  0.7067     0.1081  6.5379  6.241e-11\n  Age          0.2325     0.0478  4.8667  1.135e-06\n```\n:::\n:::\n\n\n::: {#poisson-scale .cell execution_count=17}\n``` {.julia .cell-code}\nb_pois = coef(pois_fit, :mu)\nrate_ratio = exp(b_pois[2])\n\n@printf(\"slope on the log scale : %.4f\\n\", b_pois[2])\n@printf(\"exp(slope), rate ratio : %.4f\\n\", rate_ratio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nslope on the log scale : 0.2325\nexp(slope), rate ratio : 1.2618\n```\n:::\n:::\n\n\n**Itchy:** The link here is the logarithm rather than the logit, for the same reason: a count's mean must stay positive, and a log keeps it there while the linear predictor roams. Exponentiate and you get a **rate ratio**: **each extra year of age multiplies a female's expected number of fledglings by 1.262.** Not \"adds\", multiplies. Every log link in this book makes coefficients multiplicative, and reading one additively is the commonest mistake in the literature.\n\n**Toto:** And no σ table again.\n\n**Itchy:** No σ table again, and now the decree is even stronger than the binomial one. **Poisson says the variance equals the mean.** One number for both. That is an extremely strong claim about a real animal and it is testable in one line, so test it.\n\n::: {#mean-vs-variance .cell execution_count=18}\n``` {.julia .cell-code}\nm_counts = mean(females.Fledglings)\nv_counts = var(females.Fledglings)\n\n@printf(\"mean of the counts     : %.4f\\n\", m_counts)\n@printf(\"variance of the counts : %.4f\\n\", v_counts)\n@printf(\"variance / mean        : %.4f   (Poisson decrees 1)\\n\", v_counts / m_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmean of the counts     : 3.2086\nvariance of the counts : 5.4377\nvariance / mean        : 1.6947   (Poisson decrees 1)\n```\n:::\n:::\n\n\n**Momo:** It is not one.\n\n**Itchy:** It is not one, it is 1.69, and the counts are scattering considerably more than the family says they may. That is called **overdispersion**, it is the single most common thing wrong with a Poisson model in ecology, and it is Class 4's entire subject. I am not going to fix it today. I am going to make sure you can *see* it, from two directions, because seeing it is the skill.\n\n**Toto:** Two directions?\n\n**Itchy:** The crude one you just ran, on the raw counts, which mixes up real variation with variation the predictors explain. And the honest one, on the residuals of the actual fit, where anything the model explained has already been taken out.\n\n::: {#cell-fig-diagnostic-poisson .cell execution_count=19}\n``` {.julia .cell-code}\nqres_pois = residuals(pois_fit; type = :quantile, rng = MersenneTwister(4))\n\nmcse_pois = 1 / sqrt(2 * length(qres_pois))\nz_pois = abs(std(qres_pois) - 1) / mcse_pois\n\n@printf(\"logistic fit, quantile residual SD : %.4f  (%.2f Monte Carlo standard errors from 1)\\n\", std(qres), z_logit)\n@printf(\"Poisson fit,  quantile residual SD : %.4f  (%.2f Monte Carlo standard errors from 1)\\n\", std(qres_pois), z_pois)\n\nfig_p = fig_diagnostic(qres_pois; title = \"Poisson fit, randomised quantile residuals\")\n# Same fixed window as fig-diagnostic above (see the comment there); both\n# panels' real extent sits well inside it, so this is a shared display\n# window, not a number pulled from nowhere.\nylims!(fig_p.content[1], -1.2, 1.2)\nfig_p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlogistic fit, quantile residual SD : 1.0201  (1.13 Monte Carlo standard errors from 1)\nPoisson fit,  quantile residual SD : 1.2981  (5.38 Monte Carlo standard errors from 1)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=31}\n![Worm plot of the Poisson fit's randomised quantile residuals, on the same fixed vertical scale as the logistic worm plot above. The tilt is the overdispersion the variance-to-mean ratio already showed: the residuals are spread wider than a standard normal, so the line of sorted residuals climbs from left to right instead of lying flat inside the pale band — and because both panels now share one axis, that extra spread is something the eye can see, not only the printed standard deviations.](wk3-glms_files/figure-html/fig-diagnostic-poisson-output-2.svg){#fig-diagnostic-poisson}\n:::\n:::\n\n\n**Itchy:** Compare the two lines, and compare each against its own error bar, because a spread is an estimate like anything else. There is a formula for the wobble in an SD computed from random draws — its Monte Carlo standard error — and it is one over the square root of twice the sample size: 0.0178 for the chicks, 0.0554 for the females. The logistic SD is 1.1 of those from one, which is noise. The Poisson SD is 5.4 of them, which is not. And the Poisson residuals are wide *after* age has been accounted for, so it is not something age can explain. Two different checks, one verdict, and the verdict is that the family is claiming a tidiness these females do not have.\n\n**Momo:** So the model is wrong and you are telling me to leave it.\n\n**Itchy:** I am telling you that you now know something specific and testable about how it is wrong, which is a great deal better than most published models, and that the repair has a name, a chapter and a one-line change in the same `bf` box. Draw the fit before you go.\n\n::: {#cell-fig-fledglings .cell execution_count=20}\n``` {.julia .cell-code}\nage_grid = range(minimum(females.Age), maximum(females.Age), length = 100)\nrate_curve = predict(pois_fit, (; Age = collect(age_grid)))\n\nrng2 = MersenneTwister(99)\nage_jit = females.Age .+ 0.06 .* randn(rng2, n_fem)\n\nfig = Figure(size = (540, 380))\nax = Axis(fig[1, 1]; xlabel = \"age (years)\", ylabel = \"fledglings\",\n    title = \"counts, and the rate the model expects\")\nscatter!(ax, age_jit, females.Fledglings; markersize = 6, color = (:grey, 0.5))\nlines!(ax, age_grid, rate_curve; linewidth = 2.5, label = \"Poisson, log link\")\n# legend outside the axis, for the same reason as fig-curve and fig-two-shapes above\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n![Fledgling counts against female age, jittered horizontally, with the Poisson fit's rate curve laid over them bending gently upward on the log scale. The vertical scatter at each age is wider than that curve's own decree allows — the overdispersion the chapter has already shown by two other routes.](wk3-glms_files/figure-html/fig-fledglings-output-1.svg){#fig-fledglings}\n:::\n:::\n\n\n**Itchy:** The curve bends upward because a log link makes it, and gently, because the coefficient is small. And look at the vertical scatter at each age: that is what 1.69 looks like. The line is defensible. The claim about the spread around it is not, and you can say precisely which is which. That is the whole difference between using a model and believing one.\n\n**Toto:** So today's summary is: pick the family.\n\n**Itchy:** Today's summary is: the family picks two things for you, and only one of them is the shape of the curve. The other is the shape of the noise, you did not choose it, and Class 4 is what happens when it is wrong.\n\n---\n\n## Summary\n\n### Stats stuff\n\n- **A GLM changes two things, not one.** The **link** puts the linear predictor somewhere it is allowed to roam and squashes it back into the legal range; the **variance function** says how much the response scatters around that mean. Both are decided by the family, together, the moment you name it.\n- **Wrong shape is not the same as bad fit.** A Gaussian model on a 0/1 response converges, reports tiny *p*-values, and predicts probabilities outside zero and one. No amount of data fixes that, because nothing about a straight line stops at one. Look at the fitted values before you look at the coefficients — and note that the impossible predictions are only the visible fault. Constant σ is violated by construction on a 0/1 response, whose variance p(1 − p) moves with the mean, so the Gaussian model's standard errors are wrong at every value of the predictor, including the ones where its predictions are legal.\n- **Log-odds, odds ratios, probabilities.** The coefficient is on the log-odds scale, where it is additive and uninterpretable. `exp` of it is an **odds ratio**, which is multiplicative and speakable. `predict` gives a **probability**, which is what a biologist actually wanted. Report at least one of the last two, never only the first.\n- **Odds are not probabilities.** Odds are p/(1 − p), and they can be multiplied for ever without leaving the legal range, which is the reason the model works in them.\n- **The curve flattens at both ends and is steepest in the middle.** A logistic curve is symmetric about p = ½, which it reaches at −b₀/b₁ on the predictor's own scale. An extra unit is therefore worth **most** to an individual sitting near that point and least to one already nearly certain either way. Whether your own data show diminishing or *increasing* returns depends on which side of that point they lie: most of these chicks sit below it, the mean among them, so over the bulk of the data an extra gram buys more as a chick gets heavier, not less. Compute the inflection; do not assume the shape of the story. What holds on both sides is that a unit is not worth the same everywhere, and the straight line insists that it is.\n- **The variance is decreed, which is why there is no σ table.** Binomial says the variance is p(1 − p); Poisson says it equals the mean. Neither is estimated, so neither is printed. R states this out loud as \"dispersion parameter taken to be 1\"; our engine states it by having nothing to print. Read the two decrees differently, though: for a 0/1 response, p(1 − p) is an **identity** and there is no overdispersed Bernoulli to find, so what can go wrong in binary data is the independence of the rows (Class 6), not the variance function. For counts, the Poisson decree is a real claim that data can contradict, and that is Class 4.\n- **Rate ratios are multiplicative.** With a log link, a coefficient exponentiates into a factor, not an increment. Reading one additively is a common and serious error.\n- **Check the decree in two places, and put an error bar on the check.** The crude check is the variance-to-mean ratio of the raw counts. The honest check is the spread of randomised quantile residuals from the fitted model, which is standard normal if the family is right whatever the family is (Dunn & Smyth 1996). Judge that spread against its own Monte Carlo standard error, 1/√(2n), rather than against your eye: ours came out about one SE from one for the survivals and several SEs above it for the counts. Overdispersion, and Class 4 — and only the counts can have it.\n- **This chapter pretends rows are independent.** Chicks share broods; Class 6 frees the correlation between rows on repeated measures of one bird, and Class 9 is where this pretence ends, on a file that records the brood. The link and the variance function survive the repair; the standard errors printed here do not. Note what ending the pretence takes: this file records brood *size* but carries no brood *identifier*, so the repair needs a dataset that records the grouping, not a different formula on this one.\n\n### Julia stuff\n\n- `drm(bf(@formula(y ~ x)), Binomial(); data = df)`: logistic regression. Same verb, same box, same positional family and keyword data as Class 2. The response is a plain 0/1 column.\n- `drm(bf(@formula(y ~ x)), Poisson(); data = df)`: counts with a log link. Everything else is unchanged.\n- **No `sigma` block.** `fit.blocks` carries only `mu` for these families. There is no σ to print because the family has already spent it. Do not go looking for `sigma(fit)` here.\n- `coef(fit, :mu)`: coefficients on the **link** scale, which is log-odds for `Binomial()` and log for `Poisson()`. `exp` them for an odds ratio or a rate ratio.\n- `predict(fit, newdata)`: response-scale predictions, so probabilities for a logistic fit and expected counts for a Poisson one. `newdata` is a **NamedTuple or column table**, not a `DataFrame`: write `(; Mass2 = [3.5])`. Add `se = true` for a standard error on that prediction (by the delta method: the uncertainty carried from the link scale onto the response scale) and the call returns `(; prediction, se)`; add `type = :link` to stay on the link scale.\n- `fitted(fit)`: in-sample response-scale predictions. On a Gaussian fit to 0/1 data, `extrema(fitted(fit))` is the fastest proof that the model is the wrong shape.\n- `residuals(fit; type = :quantile, rng = MersenneTwister(seed))`: randomised quantile residuals, standard normal under a correct model for every family DRM.jl supports. **Pass the `rng`.** It defaults to the global generator, which would give you a different picture every time you ran it.\n- `aic(fit)`: unchanged from Class 2, and still what decides whether a new predictor earned its place.\n- `fig_diagnostic(resid)` from `tools/figures.jl`: the worm plot, which is the right picture for quantile residuals because they are standard normal when the model is right — so a flat scatter near zero means there is nothing left to find, and a tilt or a curve names what is.\n- **Seeding.** Every random draw in this chapter — the jitter in two figures, both sets of quantile residuals, and the simulation below — is made from an explicit `MersenneTwister` handed to the function as `rng`, never from the global generator. That is what makes the page reproducible rather than merely repeatable.\n- **The simulation thread.** From Class 2 onward, the last thing you do with a fit is ask it to invent data and see what a refit makes of them. Here it is for a logistic model, where the invention is a coin flip per chick. `simulate(fit; nsim = k, rng = MersenneTwister(seed))` takes the same `rng` keyword `residuals` does, and for the same reason.\n\n::: {#simulate-refit .cell execution_count=21}\n``` {.julia .cell-code}\n# Ask the fitted model for new chicks: one Bernoulli draw per row, at that\n# row's fitted probability. Then refit and see how far the slope wanders when\n# nothing at all has changed except the coin flips.\nrng_sim = MersenneTwister(20260907)\nysim = simulate(logit_fit; nsim = 200, rng = rng_sim)\n\nfunction refit_slope(y)\n    d = DataFrame(Survival = y, Mass2 = chicks.Mass2)\n    coef(drm(bf(@formula(Survival ~ Mass2)), Binomial(); data = d), :mu)[2]\nend\n\nslopes = [refit_slope(ysim[:, k]) for k in 1:size(ysim, 2)]\n\n@printf(\"the slope we fitted            : %.4f\\n\", slope_logodds)\n@printf(\"its reported standard error    : %.4f\\n\", stderror(logit_fit)[2])\n@printf(\"mean slope over %d refits     : %.4f\\n\", length(slopes), mean(slopes))\n@printf(\"SD of slopes over those refits : %.4f\\n\", std(slopes))\n@printf(\"simulated responses seen       : %s\\n\", sort(unique(ysim)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nthe slope we fitted            : 0.6999\nits reported standard error    : 0.0514\nmean slope over 200 refits     : 0.7032\nSD of slopes over those refits : 0.0487\nsimulated responses seen       : [0.0, 1.0]\n```\n:::\n:::\n\n\nThe simulated responses are only ever zero and one, because `simulate` draws from the family the fit was given rather than adding normal noise. And the spread of the refitted slopes lands close to the standard error the single fit reported, which is what a standard error **is**: a prediction about how much your estimate would move if the world ran again. When those two numbers disagree badly, believe the simulation. That comparison is most of what Class 5 does for a living.\n\n---\n\n## Further reading\n\n*Graded by depth. Details checked on 2026-09-07 against OpenAlex, an open catalogue of research papers.*\n\n1. **Warton, D. I. & Hui, F. K. C. (2011) \"The arcsine is asinine: the analysis of proportions in ecology\", *Ecology* 92:3–10.** doi:10.1890/10-0340.1 (published online in 2010). Start here. It is the ecology-specific case for doing exactly what this class did, aimed squarely at readers who were taught to transform a proportion and fit a linear model to it instead. Short, pointed, and it will change what you do on Monday.\n2. **Bolker, B. M. (2008) *Ecological Models and Data in R*, Princeton University Press.** doi:10.1515/9781400840908. The best book-length route from \"I know what a linear model is\" to \"I know what a likelihood is and why the family matters\". Chapters 4 and 6 are the ones that pay for the rest of this course.\n3. **Zuur, A. F., Ieno, E. N., Walker, N. J., Saveliev, A. A. & Smith, G. M. (2009) *Mixed Effects Models and Extensions in Ecology with R*, Springer.** doi:10.1007/978-0-387-87458-6. The chapters on Poisson regression and on overdispersion are the natural bridge from today into Class 4, and they are written for biologists with real, awkward data.\n4. **Dunn, P. K. & Smyth, G. K. (1996) \"Randomized quantile residuals\", *Journal of Computational and Graphical Statistics* 5:236–244.** doi:10.1080/10618600.1996.10474708. The source of the diagnostic this class used twice. Worth reading once so that \"it is normal if the model is right, whatever the family\" stops being a slogan you repeat and becomes a thing you can derive.\n5. **McCullagh, P. & Nelder, J. A. (1989) *Generalized Linear Models*, 2nd edition, Chapman & Hall.** The book that made all of this one framework rather than a list of tricks, and the place the words \"link function\" and \"variance function\" come from. Hard, and the right thing to own. Read chapter 2 when you want to know why the family determines both at once.\n\n---\n\n## Exercises\n\nUse your own organism where one is named. **For every question, paste your code and then explain in your own words what each line does**, as if to somebody who has done Class 2 and not Class 3.\n\n1. **Break it on purpose, then look outside.** Fit a Gaussian model to any 0/1 response of your own. Report `extrema(fitted(fit))` and the number of fitted values outside zero and one. Then write one sentence saying what the model believes that the world does not allow, in the units of your organism.\n\n2. **Log-odds to biology.** Refit it with `Binomial()`. Report the slope, the odds ratio, and a predicted probability at a value of the predictor you can point at in the field. Then write the single sentence you would put in a paper, and underline the part a reader could check.\n\n3. **Where the curve is steep.** Using your logistic fit, predict at three values of the predictor: near the minimum, near the mean, and near the maximum. Compute the change in probability between the first two and between the last two. Then compute `-b[1] / b[2]` from `coef(fit, :mu)`: the value of the predictor at which your model says the probability is exactly one half. Say where each of your three values sits relative to it, and explain which of the two changes is the larger and why — without using the word \"nonlinear\". The answer is a statement about distance from that one point.\n\n4. **Eddie's dunnocks.** Take any yes-or-no outcome in Eddie's data and fit it against two predictors. Report both odds ratios and both AICs, with and without the second predictor. Then answer: is the smaller AIC enough to make you believe the second predictor matters biologically? Two sentences.\n\n5. **Momo's tadpoles.** Count something per pond and fit a Poisson model against a predictor of your choice. Report the rate ratio, and write its meaning as a multiplication rather than an addition.\n\n6. **Run the check, both ways.** For question 5, report the variance-to-mean ratio of the raw counts, and the standard deviation of `residuals(fit; type = :quantile, rng = MersenneTwister(1))` together with its Monte Carlo standard error, `1 / sqrt(2 * nobs)`. Say what each check is measuring that the other is not, how many of those standard errors your SD sits from one, and which you would trust if they disagreed.\n\n7. **The decree, out loud.** Fit the same Poisson model in R with `glm` and find the dispersion line in the summary. Quote it. Then answer in one sentence: given your answer to question 6, is that line a finding or an instruction?\n\n8. **Simulate and refit.** Adapt the chapter's last cell to your own logistic fit, with your own seed. Report the reported standard error and the standard deviation of the refitted slopes. If they differ by more than about a tenth of the estimate, say what you would check first.\n\n9. **The pretence.** Name the grouping in your own data that this chapter would be pretending away: the nest, the pond, the individual, the site. Then find the *column* that identifies it, and say whether your file actually has one — the chapter's own `ChickSurvival.csv` carries `BroodSize` but no brood identifier, so on that file the pretence cannot be ended at all until somebody supplies a version that records which nest each chick came from. Finish with one sentence saying which number on your output you expect Class 9 to change, and in which direction.\n\n",
    "supporting": [
      "wk3-glms_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}