{
  "hash": "c5d5540de7639657f2a11143adc5fc2c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Class 4: when the family lies about the spread\"\nbook: Stats Hours with Itchy\nchapter: 4\ntype: book-chapter\nstatus: draft\ncreated: 2026-09-07\nengines: DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)\ntags: [book, julia, overdispersion, exposure, beta-binomial, negative-binomial, location-scale, DRM.jl]\ndeck: \"Class 3 let the family decree the spread. Today the decree turns out to be false — but only after the column nobody looked at has been ruled out, and the repair is then the same one verb in three families: a second formula in the box.\"\nstatus_tag: Draft\nstatus_note: \"All ten classes of version 1 are drafted and their code runs end to end (1–10), with Appendix A, the preface and the coda. Every number and figure on this page was produced when the site was built; the book itself is not written.\"\nprovenance: \"Every code block and printed result below was actually run when the site was built, and nothing is typed from memory. Every random draw is seeded where it is made, so the page comes out the same every time.\"\ncaveat: \"The data are real: the 2012 Lundy Island female-breeding and sparrow-morphology records, read directly from data/2012/FemaleSuccess.csv and data/2012/MBodySize.csv (where the files came from is recorded in data/2012/README.md). Nothing here is simulated except the one block of invented refits at the end, which says so and carries its seed.\"\nfooter_note: \"Stats Hours with Itchy · Class 4 of a planned 13, ten in v1, plus a coda · draft, all code run, 2026-09-07\"\n---\n\n\n# Class 4: when the family lies about the spread\n\n## Objectives\n\nBy the end of this class you should be able to:\n\n1. State, in one sentence, what a family decrees about the variance, and compare a crude variance-to-mean ratio against the ratio the fitted model actually implies, rather than against one.\n2. Look for an **exposure** — a denominator already sitting in your data — before you blame the family, and say what an offset is.\n3. Fit a grouped binomial and its overdispersed cousin `BetaBinomial()`, and say why *n*·p(1 − p) is a claim data can break where p(1 − p) is not.\n4. Fit `NegBinomial2()`, say what the dispersion parameter θ means in the units of the variance, and predict what admitting the extra spread will and will not change: the estimate barely, the standard errors a lot.\n5. Judge a ±1 SD band against the coverage — the share of data such a band is meant to hold — that the model itself claims for it.\n6. Put a second formula on σ in a Gaussian model and report a **not detected** honestly — with the smallest difference the design could have seen. Then say why that is the same move as changing the family.\n\n---\n\n## The class\n\n**Itchy's office, 9:00 am. MOMO has arrived early with the fledgling file already open, which is new. TOTO is eating breakfast and has not yet decided to be here.**\n\n**Itchy:** Momo, you have been waiting a week to say something.\n\n**Momo:** You told me my Poisson model was wrong, showed me exactly how wrong, and then made me leave it wrong.\n\n**Itchy:** I did, and today we fix it. Load it back.\n\n::: {#setup .cell execution_count=1}\n``` {.julia .cell-code}\n# tools/figures.jl includes tools/theme_itchy.jl itself, so one include does both.\ninclude(\"../tools/figures.jl\")\nusing DRM, DataFrames, CSV, Statistics, Random, Printf, CairoMakie\nimport Distributions          # qualified: DRM exports its own Poisson, Binomial, …\nset_theme!(theme_itchy(:light))\n\n# confint(fit) returns one row per coefficient, each with .estimate, .lower and\n# .upper. This picks a row by block and name, so no table is ever read by column number.\nfunction ci_row(fit, block, name)\n    rows = confint(fit; parm = block)\n    rows[findfirst(r -> r.coef == name, rows)]\nend\n\nfemales = CSV.read(\"../data/2012/FemaleSuccess.csv\", DataFrame)\n\nn_fem = nrow(females)\nm_counts = mean(females.Fledglings)\nv_counts = var(females.Fledglings)\nratio_raw = v_counts / m_counts\n\n@printf(\"rows: %d   columns: %s\\n\", n_fem, join(names(females), \", \"))\n@printf(\"mean of the counts     : %.4f\\n\", m_counts)\n@printf(\"variance of the counts : %.4f\\n\", v_counts)\n@printf(\"variance / mean        : %.4f\\n\", ratio_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows: 163   columns: Fledglings, EggNo, Age\nmean of the counts     : 3.2086\nvariance of the counts : 5.4377\nvariance / mean        : 1.6947\n```\n:::\n:::\n\n\n**Momo:** Same 163 females, same ratio of 1.69, which is still not one.\n\n**Itchy:** Still not one. Hold on to that number and hold on to your annoyance with it, because both are going to be worth less than you think by half past nine. First, the thing that is genuinely different from last week. Toto, in Class 3 the Gaussian model on a yes-or-no response was the wrong **shape**. Its predictions were impossible. Is this one impossible?\n\n**Toto:** *(mouth full)* No. The counts it predicts are all positive and it never predicts a half.\n\n**Itchy:** For now. What is false is a claim the model never printed and you never agreed to: **the variance equals the mean**. That is the whole of today, and it has a name.\n\n### The decree, stated as an equation\n\n> **y_i ~ Poisson(μ_i),  log μ_i = β0 + β1 x_i,  Var(y_i | x_i) = μ_i**\n\n**Itchy:** Three lines, and the third one is not something the Poisson family estimated. It is something the Poisson family *is*. Now read the third line carefully, because it has a bar in it that Momo's crude ratio does not.\n\n::: {#cell-fit-poisson .cell execution_count=2}\n``` {.julia .cell-code}\npois = drm(bf(@formula(Fledglings ~ Age)), Poisson(); data = females)\npois\n```\n\n::: {#fit-poisson .cell-output .cell-output-display execution_count=4}\n```\nDistributional regression fit (Poisson)\n  nobs = 163   logLik = -367.9932   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                Coef.  Std.Error       z   Pr(>|z|)\n  (Intercept)  0.7067     0.1081  6.5379  6.241e-11\n  Age          0.2325     0.0478  4.8667  1.135e-06\n```\n:::\n:::\n\n\n::: {#right-benchmark .cell execution_count=3}\n``` {.julia .cell-code}\nmu_p = fitted(pois)\n# What a CORRECT Poisson regression implies for the MARGINAL variance-to-mean ratio:\n# E[Var(y|x)] + Var(E[y|x]), all over E[y].\nratio_implied = (mean(mu_p) + var(mu_p)) / mean(mu_p)\n\n@printf(\"crude, from the raw counts            : %.4f\\n\", ratio_raw)\n@printf(\"what this fitted Poisson implies      : %.4f\\n\", ratio_implied)\n@printf(\"what a Poisson decrees CONDITIONALLY  : %.4f\\n\", 1.0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncrude, from the raw counts            : 1.6947\nwhat this fitted Poisson implies      : 1.1491\nwhat a Poisson decrees CONDITIONALLY  : 1.0000\n```\n:::\n:::\n\n\n**Momo:** So the benchmark for my number was never one.\n\n**Itchy:** The benchmark for your number was never one, and I let you believe it was for a week. A Poisson *regression* says the variance equals the mean **at a given age**. The raw counts also carry the variation that age itself creates, so even a perfectly correct Poisson model would show a **marginal** ratio — marginal meaning averaged over every age, not held fixed at one — of 1.149 here, not one. **Compare like with like or you will convict an innocent model.** Your 1.69 is still too big — but against 1.149, not against one, and the gap is smaller than you were told.\n\n**Toto:** Then how do you check the thing with the bar in it?\n\n**Itchy:** On the residuals of the fit, where age has already been taken out. Two ways, built on different arithmetic. The classical one takes each bird's squared distance from its own fitted mean, divides by the variance the model claims *there*, adds them up and divides by the residual degrees of freedom. The other is the worm plot's statistic from Class 3.\n\n::: {#checks-poisson .cell execution_count=4}\n``` {.julia .cell-code}\nX2_pois = sum((females.Fledglings .- mu_p) .^ 2 ./ mu_p)\ndisp_pois = X2_pois / dof_residual(pois)\n\nqres_pois = residuals(pois; type = :quantile, rng = MersenneTwister(4))\n\n@printf(\"Pearson X2 %.3f on %d df  ->  X2/df = %.4f\\n\", X2_pois, dof_residual(pois), disp_pois)\n@printf(\"quantile residual SD %.4f\\n\", std(qres_pois))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPearson X2 252.424 on 161 df  ->  X2/df = 1.5679\nquantile residual SD 1.2981\n```\n:::\n:::\n\n\n**Itchy:** 1.57 and 1.3, both well above one. Two checks, different arithmetic, same verdict. Note that I did not call them *independent*: they are two functions of one fitted model on one residual vector, and a pair of checks that share a model can be wrong together.\n\n**Momo:** Good. Give me the negative binomial.\n\n**Itchy:** No.\n\n**Momo:** You said we were fixing it today.\n\n**Itchy:** We are. Open the file first. Not the model — the **file**.\n\n### Suspect the mean before you blame the family\n\n::: {#the-ceiling .cell execution_count=5}\n``` {.julia .cell-code}\nn_under = count(females.Fledglings .<= females.EggNo)\negg_lo, egg_hi = extrema(females.EggNo)\n\n@printf(\"rows where Fledglings <= EggNo : %d of %d\\n\", n_under, n_fem)\n@printf(\"EggNo runs from %d to %d, with SD %.2f\\n\", egg_lo, egg_hi, std(females.EggNo))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows where Fledglings <= EggNo : 163 of 163\nEggNo runs from 1 to 23, with SD 4.33\n```\n:::\n:::\n\n\n**Itchy:** Column two. `EggNo`, the number of eggs she laid. `Fledglings` is at most `EggNo` in 163 of 163 rows — which is to say all of them, because a female cannot fledge a chick she did not lay. And `EggNo` runs from 1 to 23.\n\n**Momo:** *(silence)*\n\n**Itchy:** A female who laid 1 egg and a female who laid 23 are not being asked the same question, and the model you have been carrying around for a week asks them the same question. That is called an **exposure**: an amount of opportunity that differs between rows and belongs in the mean structure. Look at what the model believes without it.\n\n::: {#cell-fig-ceiling .cell execution_count=6}\n``` {.julia .cell-code}\nsd_p = sqrt.(mu_p)\nband_lo, band_hi = minimum(mu_p .- sd_p), maximum(mu_p .+ sd_p)\n\n# Jitter the eggs axis only, and only rightward, so that neither invariant this\n# figure is about can be broken by the jitter: no drawn point falls below zero\n# fledglings, and none is drawn above the ceiling.\nrng_jit = MersenneTwister(20260907)\negg_jit = females.EggNo .+ 0.45 .* rand(rng_jit, n_fem)\n\nfig = Figure(size = (560, 400))\nax = Axis(fig[1, 1]; xlabel = \"eggs laid\", ylabel = \"fledglings\",\n    title = \"the column the model never saw\")\nband!(ax, [egg_lo - 0.5, egg_hi + 0.5], fill(band_lo, 2), fill(band_hi, 2);\n    color = (:grey, 0.28), label = \"Age-only Poisson, mean ± 1 SD\")\nlines!(ax, [egg_lo - 0.5, egg_hi + 0.5], [egg_lo - 0.5, egg_hi + 0.5];\n    linewidth = 2, linestyle = :dash, label = \"ceiling: fledglings = eggs\")\nscatter!(ax, egg_jit, females.Fledglings; markersize = 6, color = (:grey, 0.6), label = \"a female\")\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n![Fledglings against eggs laid. Markers are jittered **horizontally only**, and only to the right, by up to 0.45 of an egg, so that repeated (eggs, fledglings) pairs separate; the vertical position is the exact count, so no marker can be drawn below zero or above the ceiling. The diagonal is that ceiling: no bird can sit above it. The horizontal band is everything the Age-only Poisson thinks is ordinary — its fitted mean ± 1 SD, over every female of every age — and it does not know that the ceiling exists, let alone where each bird's own ceiling is.](wk4-overdispersion_files/figure-html/fig-ceiling-output-1.svg){#fig-ceiling}\n:::\n:::\n\n\n**Toto:** The band goes straight through the line.\n\n**Itchy:** The band goes straight through the line, and where it does, the model is assigning ordinary probability to birds that cannot exist. Put a number on it: for each female, ask the fitted Poisson how much probability it puts above her own `EggNo`, and add those up.\n\n::: {#impossible-mass .cell execution_count=7}\n``` {.julia .cell-code}\nover_pois = sum(1 - Distributions.cdf(Distributions.Poisson(mu_p[i]), females.EggNo[i])\n                for i in 1:n_fem)\n@printf(\"expected rows with more fledglings than eggs, under this Poisson: %.2f\\n\", over_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nexpected rows with more fledglings than eggs, under this Poisson: 8.88\n```\n:::\n:::\n\n\n**Itchy:** About 8.9 females' worth of impossibility — which is why I said *for now* rather than *correct* when Toto told me the predictions were all legal. **This model commits exactly the crime Class 3 convicted the Gaussian of**, and it hid it better, because a prediction of four chicks is only impossible if you know how many eggs there were. Two words on the cell before we move: `sum(... for i in 1:n_fem)` is a comprehension without its square brackets, a **generator**, handed straight to `sum` so nothing is stored on the way; and `Distributions.Poisson(...)`, written with its package name in front, is the probability distribution, because a bare `Poisson()` is DRM's family and the two share a word. Now put the exposure in.\n\n**Momo:** As an offset. I have read ahead.\n\n**Itchy:** As a covariate first, and I will tell you why in a minute. The right scale is the log one, because the link is a log: if a female's expected brood is proportional to her eggs, then log μ carries log `EggNo` with a coefficient of one. Adding the column is one assignment — `females.logEgg = log.(females.EggNo)` writes a new column into the frame, the dot taking the log of every egg count — and the formula can then name it.\n\n::: {#cell-fit-exposure .cell execution_count=8}\n``` {.julia .cell-code}\nfemales.logEgg = log.(females.EggNo)\n\npoe = drm(bf(@formula(Fledglings ~ Age + logEgg)), Poisson(); data = females)\npoe\n```\n\n::: {#fit-exposure .cell-output .cell-output-display execution_count=14}\n```\nDistributional regression fit (Poisson)\n  nobs = 163   logLik = -323.4104   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  -1.1695     0.2546  -4.5931  4.366e-06\n  Age           0.0852     0.0507   1.6798    0.09299\n  logEgg        0.9503     0.1102   8.6213  6.622e-18\n```\n:::\n:::\n\n\n::: {#exposure-paid .cell execution_count=9}\n``` {.julia .cell-code}\nmu_e = fitted(poe)\nX2_poe = sum((females.Fledglings .- mu_e) .^ 2 ./ mu_e)\ndisp_poe = X2_poe / dof_residual(poe)\nd_aic_exposure = aic(pois) - aic(poe)\n\negg = ci_row(poe, :mu, \"logEgg\")      # the log(EggNo) row: estimate, lower, upper\n\nover_poe = sum(1 - Distributions.cdf(Distributions.Poisson(mu_e[i]), females.EggNo[i])\n               for i in 1:n_fem)\n\n@printf(\"AIC, Age only        : %.4f\\n\", aic(pois))\n@printf(\"AIC, Age + log(EggNo): %.4f   (drop of %.4f for one parameter)\\n\",\n        aic(poe), d_aic_exposure)\n@printf(\"Pearson X2/df        : %.4f  ->  %.4f\\n\", disp_pois, disp_poe)\n@printf(\"log(EggNo) coefficient: %.4f  [%.4f, %.4f]\\n\", egg.estimate, egg.lower, egg.upper)\n@printf(\"expected impossible rows: %.2f  ->  %.2f\\n\", over_pois, over_poe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC, Age only        : 739.9864\nAIC, Age + log(EggNo): 652.8208   (drop of 87.1656 for one parameter)\nPearson X2/df        : 1.5679  ->  1.1064\nlog(EggNo) coefficient: 0.9503  [0.7343, 1.1664]\nexpected impossible rows: 8.88  ->  0.63\n```\n:::\n:::\n\n\n**Momo:** That is a much bigger number than I was expecting.\n\n**Itchy:** **87.2 AIC, for one parameter, from a column that was already in your file.** The Pearson statistic falls from 1.57 to 1.11 — that is most of the way to a met assumption — and the impossible mass falls from about 8.9 birds to about 0.6. Now look at the coefficient itself, because it is the answer to your offset question. It came out at 0.95, with an interval of 0.73 to 1.17.\n\n**Toto:** That interval contains one.\n\n**Itchy:** That interval contains one, and **an offset is precisely this coefficient pinned at one instead of estimated**. It is the stronger, cheaper model when the proportionality really holds, and fitting the coefficient free first is how you find out whether it does: had it come back at a half, the offset would have been a bad model confidently stated. Here the data have no complaint. This engine has no offset term yet, so the free coefficient is the model we keep, which is the one you should fit first in any case ([Where the engine stops](appendix-b-engine.html)). Now the part that should frighten you. Momo, what happened to your biology?\n\n::: {#biology-moved .cell execution_count=10}\n``` {.julia .cell-code}\nage_p = ci_row(pois, :mu, \"Age\")\nage_e = ci_row(poe, :mu, \"Age\")\n\nrr_naive = exp(age_p.estimate)\nrr_expos = exp(age_e.estimate)\n\n@printf(\"rate ratio on Age, Age only         : %.4f  [%.4f, %.4f]\\n\",\n        rr_naive, exp(age_p.lower), exp(age_p.upper))\n@printf(\"rate ratio on Age, Age + log(EggNo) : %.4f  [%.4f, %.4f]\\n\",\n        rr_expos, exp(age_e.lower), exp(age_e.upper))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrate ratio on Age, Age only         : 1.2618  [1.1490, 1.3857]\nrate ratio on Age, Age + log(EggNo) : 1.0889  [0.9859, 1.2027]\n```\n:::\n:::\n\n\n**Momo:** It went from 1.26 to 1.09 and the interval covers one.\n\n**Itchy:** It did. An extra year of age multiplied expected fledglings by 1.26 when age was the only thing in the model, and by 1.09 once we allowed that older females lay more eggs — and that second interval is consistent with no effect at all *per egg*. Both statements are true and they are about different things. The first is the total effect of age on fledgling production; the second is what age does once you have conditioned on the clutch. Neither is a lie. But if you had gone straight to the negative binomial, you would have kept the first number, an interval that excluded one, and a story about ageing females that was mostly a story about eggs.\n\n**Toto:** So the lesson is not about the family at all.\n\n**Itchy:** The lesson today has a first half and a second half, and this is the first half. **Check the exposure before you blame the family.** Overdispersion is what a missing mean structure looks like from the residuals, and a missing mean structure is much commoner and much cheaper to fix.\n\n### The ceiling, taken seriously\n\n**Itchy:** Second half. We got the impossible mass down to about 0.6 birds, which is small, and I want it at zero, because it is zero in the world. What stops it being zero is that we are still modelling a **count** — a quantity with no upper limit written anywhere — when the response is a count *out of a known number of tries*.\n\n**Toto:** Chicks out of eggs.\n\n**Itchy:** Chicks out of eggs. Toto, you fitted this family in Class 3, on a response that was only ever zero or one. This is the same family with the trials counted.\n\n::: {#cell-fit-binomial .cell execution_count=11}\n``` {.julia .cell-code}\nfemales.Failures = females.EggNo .- females.Fledglings\n\nbin = drm(bf(@formula(cbind(Fledglings, Failures) ~ Age)), Binomial(); data = females)\nbin\n```\n\n::: {#fit-binomial .cell-output .cell-output-display execution_count=19}\n```\nDistributional regression fit (Binomial)\n  nobs = 163   logLik = -333.1155   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  -0.9542     0.1324  -7.2085  5.655e-13\n  Age           0.1175     0.0595   1.9752    0.04824\n```\n:::\n:::\n\n\n**Momo:** Two columns on the left.\n\n**Itchy:** Two columns on the left: successes and failures, so the engine can count the trials. And now the decree changes in a way that matters more than it looks. In Class 3 I told you the binomial says the variance is p(1 − p). For a single trial that is an **identity** — there is nothing there for data to contradict, which is why Class 3's logistic diagnostic was a baseline rather than a test. For *n* trials the variance is **n·p(1 − p)**, and that extra factor is a real claim: it says a female's chicks succeed or fail independently of one another. Test it.\n\n::: {#check-binomial .cell execution_count=12}\n``` {.julia .cell-code}\np_bin = fitted(bin)                       # success probabilities\nm_bin = females.EggNo .* p_bin            # expected fledglings\nv_bin = females.EggNo .* p_bin .* (1 .- p_bin)\n\ndisp_bin = sum((females.Fledglings .- m_bin) .^ 2 ./ v_bin) / dof_residual(bin)\n\n@printf(\"Binomial: Pearson X2/df = %.4f\\n\", disp_bin)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBinomial: Pearson X2/df = 1.6417\n```\n:::\n:::\n\n\n**Toto:** That is worse than the Poisson one was.\n\n**Itchy:** Do not say that, and I am going to forbid the same move for AIC in about twenty minutes, so let me forbid it here first. Those two statistics are computed on **different responses** — at the same fitted mean the binomial divides the same squared deviations by something smaller, so it *must* come out bigger — and a Pearson statistic is never compared across responses. Read 1.64 on its own terms: this model already knows about the eggs, and its own variance claim is still rejected by its own residuals. **This is the overdispersion the chapter is named for.** A brood is not `EggNo` independent coin flips: a good territory, a good mate or a good year moves all of a female's chicks together, and the binomial has no way to say so. So free the variance, exactly as before — one verb, a second formula in the box, a different family.\n\n::: {#cell-fit-betabinomial .cell execution_count=13}\n``` {.julia .cell-code}\nbbin = drm(bf(@formula(cbind(Fledglings, Failures) ~ Age), @formula(sigma ~ 1)),\n           BetaBinomial(); data = females)\nbbin\n```\n\n::: {#fit-betabinomial .cell-output .cell-output-display execution_count=22}\n```\nDistributional regression fit (BetaBinomial)\n  nobs = 163   logLik = -319.6302   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  -0.9677     0.1751  -5.5269  3.259e-08\n  Age           0.1241     0.0803   1.5461     0.1221\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                 Coef.  Std.Error        z  Pr(>|z|)\n  (Intercept)  -1.2312     0.1440  -8.5491  1.24e-17\n```\n:::\n:::\n\n\n**Momo:** The σ table came back.\n\n**Itchy:** The σ table came back, and that is the sentence I want you to leave the room with. In Class 3 there was nothing to print because the family had already spent the parameter. Say `BetaBinomial()` — or `NegBinomial2()`, in a minute — and the family hands it back, so the engine has something to estimate and something to print. **The absent table in Class 3 and the present table today are the same fact seen from two sides.** The beta-binomial lets each female have her own success probability, drawn from a beta distribution with mean p and precision φ. The σ slot carries that precision: the engine reports log σ, and φ = 1/σ², so φ = exp(−2 log σ), which is the first line of the next cell. θ will come out of the negative binomial's σ by the same arithmetic.\n\n::: {#betabinomial-paid .cell execution_count=14}\n``` {.julia .cell-code}\nphi = exp(-2 * coef(bbin, :sigma)[1])\np_bb = fitted(bbin)\nm_bb = females.EggNo .* p_bb\n# beta-binomial variance: n p (1 - p) inflated by (1 + (n - 1) / (phi + 1))\nv_bb = m_bb .* (1 .- p_bb) .* (1 .+ (females.EggNo .- 1) ./ (phi + 1))\n\ndisp_bb = sum((females.Fledglings .- m_bb) .^ 2 ./ v_bb) / dof_residual(bbin)\nd_aic_bb = aic(bin) - aic(bbin)\n\n@printf(\"phi = 1 / sigma^2 : %.4f\\n\", phi)\n@printf(\"AIC, Binomial     : %.4f\\n\", aic(bin))\n@printf(\"AIC, BetaBinomial : %.4f   (drop of %.4f for one parameter)\\n\", aic(bbin), d_aic_bb)\n@printf(\"Pearson X2/df     : %.4f  ->  %.4f\\n\", disp_bin, disp_bb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nphi = 1 / sigma^2 : 11.7329\nAIC, Binomial     : 670.2311\nAIC, BetaBinomial : 645.2604   (drop of 24.9706 for one parameter)\nPearson X2/df     : 1.6417  ->  1.0160\n```\n:::\n:::\n\n\n**Itchy:** 25.0 AIC for one parameter, and a Pearson statistic of 1.016, which is where a met assumption sits — off a φ of 11.73, and the smaller φ is, the more a female's chicks move together rather than succeeding or failing independently. **And before anybody puts 645 next to 653:** you may not. AIC compares models of the *same* data, and \"how many chicks did she fledge\" and \"how many of *these* eggs hatched into fledglings\" are different responses with different likelihoods. The comparison you are allowed is binomial against beta-binomial, and Poisson against Poisson.\n\n**Momo:** How do I choose between the two responses, then?\n\n**Itchy:** By what you are asking, not by AIC. If the biology is about production — how many chicks come out of this female — model the count and put the eggs in as an exposure. If it is about **success rate given the attempt**, model the proportion, and then the ceiling is built in rather than negotiated.\n\n### A band is not a promise that the dots are inside it\n\n**Itchy:** Everybody draws mean ± 1 SD and then says \"look, the dots are inside\". Count them instead, and count them against what the model itself says the answer should be.\n\n::: {#honest-coverage .cell execution_count=15}\n``` {.julia .cell-code}\n# How many birds sit outside their own model's mean ± 1 SD, and how often does the\n# model itself expect a bird to sit inside? (Sum the fitted pmf over the band.)\noutside(y, m, v) = count(abs.(y .- m) .> sqrt.(v))\n\nfunction claimed_coverage(dists, m, v)\n    mean(sum(Distributions.pdf(dists[i], k)\n             for k in 0:females.EggNo[i] if abs(k - m[i]) <= sqrt(v[i]))\n         for i in eachindex(dists))\nend\n\ndist_bin = [Distributions.Binomial(females.EggNo[i], p_bin[i]) for i in 1:n_fem]\ndist_bb = [Distributions.BetaBinomial(females.EggNo[i], p_bb[i] * phi, (1 - p_bb[i]) * phi)\n           for i in 1:n_fem]\n\nout_bin, out_bb = outside(females.Fledglings, m_bin, v_bin), outside(females.Fledglings, m_bb, v_bb)\ncov_bin, cov_bb = 1 - out_bin / n_fem, 1 - out_bb / n_fem\nclaim_bin, claim_bb = claimed_coverage(dist_bin, m_bin, v_bin), claimed_coverage(dist_bb, m_bb, v_bb)\n\n@printf(\"Binomial     : %3d of %d outside  ->  coverage %.3f, model claims %.3f\\n\",\n        out_bin, n_fem, cov_bin, claim_bin)\n@printf(\"BetaBinomial : %3d of %d outside  ->  coverage %.3f, model claims %.3f\\n\",\n        out_bb, n_fem, cov_bb, claim_bb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBinomial     :  77 of 163 outside  ->  coverage 0.528, model claims 0.672\nBetaBinomial :  56 of 163 outside  ->  coverage 0.656, model claims 0.670\n```\n:::\n:::\n\n\n**Toto:** So a lot of the birds are outside both bands.\n\n**Itchy:** A lot of the birds are outside both bands, **and that is not a criticism** — a ±1 SD band is not supposed to contain the data. Its **coverage** is simply the share of birds it actually holds, and the number to compare it with is the share the model says it should hold. For these counts the binomial's own band should hold about 0.67 of the birds and holds 0.53, a shortfall of 14 percentage points. The beta-binomial claims 0.67 and delivers 0.66. **Compare a band with its own claim, never with your intuition about what a band should hold.** Now the plot from Class 3, on the repaired model.\n\n::: {#cell-fig-diagnostic .cell execution_count=16}\n``` {.julia .cell-code}\nqres_bin = residuals(bin; type = :quantile, rng = MersenneTwister(6))\nqres_bb = residuals(bbin; type = :quantile, rng = MersenneTwister(7))\n\n@printf(\"Binomial     : quantile residual SD %.4f\\n\", std(qres_bin))\n@printf(\"BetaBinomial : quantile residual SD %.4f\\n\", std(qres_bb))\n\nfig_diagnostic(qres_bb; title = \"beta-binomial fit\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBinomial     : quantile residual SD 1.2883\nBetaBinomial : quantile residual SD 1.0722\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=27}\n![A **detrended** worm plot of the beta-binomial fit: each randomised quantile residual minus the normal quantile it should have been, against that quantile, inside a pointwise ±2 SE envelope. A correct model gives a flat scatter about **zero** — not a diagonal — so read the horizontal line, not a 45° one.](wk4-overdispersion_files/figure-html/fig-diagnostic-output-2.svg){#fig-diagnostic}\n:::\n:::\n\n\n**Momo:** From 1.29 down to 1.07.\n\n**Itchy:** Near one, which is as much as the SD of 163 random draws can tell you; the picture is the better judge. Put it next to the Poisson worm plot at the end of Class 3, which left the envelope for most of its length in a systematic S. **A scattered few outside a pointwise envelope is what an envelope is for; a long one-sided run down the plot is a diagnosis.**\n\n**Toto:** But it is not flat. It sags on the left and bulges in the middle.\n\n**Itchy:** It does, and the sag is where the few escaping points are: one short stretch on the left flank. Report that as a shape rather than as a pass. What it is not is the S that convicted the Poisson. Class 5 is where you learn to count what is outside, and to decide whether a shape is a finding.\n\n**Toto:** So this model is right?\n\n**Itchy:** This model has stopped complaining about the things I know how to ask it, which is a much weaker sentence and the only one I am entitled to. It still pretends these females are strangers to one another, and no diagnostic on this file can see that, because the file does not record who is who.\n\n### So where does the negative binomial come in\n\n**Itchy:** Momo has been patient for the second time this morning. The negative binomial is the repair everyone reaches for first, it is the one Class 3 promised you, and it deserves ten minutes rather than an hour. It changes exactly one line of the decree:\n\n> **y_i ~ NegBinomial2(μ_i, θ),  log μ_i = β0 + β1 x_i,  Var(y_i | x_i) = μ_i + μ_i²/θ**\n\n**Itchy:** Same first line, same second line, and a third line with a free parameter in it. θ is estimated from the data like any other parameter, and it buys the variance permission to exceed the mean. When θ is enormous, μ²/θ vanishes and you are back in Class 3 with the Poisson. When θ is small, the extra term dominates. **θ is the price of the lie**, and the smaller it is the bigger the lie was — which is backwards from what everybody expects, so say it out loud twice. Large θ, tidy counts. Small θ, messy counts.\n\n::: {#cell-fit-nb2 .cell execution_count=17}\n``` {.julia .cell-code}\nnb = drm(bf(@formula(Fledglings ~ Age), @formula(sigma ~ 1)),\n         NegBinomial2(); data = females)\nnb\n```\n\n::: {#fit-nb2 .cell-output .cell-output-display execution_count=29}\n```\nDistributional regression fit (NegBinomial2)\n  nobs = 163   logLik = -356.5665   converged = true\n\nMean model (μ):\n  H0: coefficient = 0\n                Coef.  Std.Error       z   Pr(>|z|)\n  (Intercept)  0.7044     0.1441  4.8901  1.008e-06\n  Age          0.2337     0.0663  3.5235   0.000426\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  -0.6914     0.1520  -4.5487  5.397e-06\n```\n:::\n:::\n\n\n::: {#theta .cell execution_count=18}\n``` {.julia .cell-code}\ntheta = exp(-2 * coef(nb, :sigma)[1])\nd_aic_nb = aic(pois) - aic(nb)\n\nse_pois = stderror(pois)\nse_nb = stderror(nb)\nse_ratio = se_nb[2] / se_pois[2]\nquasi_ratio = sqrt(disp_pois)\n\n@printf(\"theta = 1 / sigma^2 : %.4f\\n\", theta)\n@printf(\"AIC, Poisson %.4f  ->  NB2 %.4f   (drop of %.4f)\\n\", aic(pois), aic(nb), d_aic_nb)\n@printf(\"slope on Age  : %.4f  ->  %.4f\\n\", coef(pois, :mu)[2], coef(nb, :mu)[2])\n@printf(\"its SE        : %.4f  ->  %.4f   (a factor of %.4f)\\n\",\n        se_pois[2], se_nb[2], se_ratio)\n@printf(\"quasi-Poisson would have inflated it by sqrt(X2/df) = %.4f\\n\", quasi_ratio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntheta = 1 / sigma^2 : 3.9864\nAIC, Poisson 739.9864  ->  NB2 719.1331   (drop of 20.8533)\nslope on Age  : 0.2325  ->  0.2337\nits SE        : 0.0478  ->  0.0663   (a factor of 1.3880)\nquasi-Poisson would have inflated it by sqrt(X2/df) = 1.2521\n```\n:::\n:::\n\n\n**Itchy:** **θ is 3.99**, the AIC drops by about 20.9 for one parameter, the slope on age moves by nothing anybody would notice, and **the standard error goes up by a factor of 1.39**. Toto, name what just happened.\n\n**Toto:** The Poisson was lying about the error bar, not the answer.\n\n**Itchy:** Written on the board. **Overdispersion is a disease of standard errors** — and it is not a coincidence, it is a theorem. The equations a Poisson fit solves to find β have the right answer as their solution, on average, *whatever* the true variance is, so the estimate stays trustworthy even when the variance model is wrong; the only thing the wrong variance corrupts is the standard error. Note the direction, too: the Poisson model does not shrink the interval because of overdispersion, it shrinks it because it refuses to admit the overdispersion, which is the worst possible failure mode. Nobody rejects a paper for being too confident.\n\n**Momo:** And the quasi-Poisson? My old software offered me that.\n\n**Itchy:** One line, and it is why Ver Hoef and Boveng are first on the reading list. The quasi-Poisson keeps the Poisson mean and multiplies every standard error by the square root of the Pearson statistic: 1.252 here, against the negative binomial's 1.388. They are close and they are not the same, because they weight the birds differently — the quasi-Poisson inflates every bird equally, the negative binomial downweights the big-mean birds. On another dataset they disagree about which coefficient matters.\n\n**Momo:** The line above the σ table says σ = 1 is unit-dependent.\n\n**Itchy:** For the Gaussian sparrows in twenty minutes it will be. Here σ is dimensionless, σ = 1 means θ = 1, and the z on that row is a real test of it, which rejects; the header is a habit of the engine, not a fact about the family ([Where the engine stops](appendix-b-engine.html)).\n\n**Momo:** Can I see the assumption itself rather than its consequences?\n\n**Itchy:** You can, and this is the picture I would put in a lecture if I were allowed only one. Bin the females by age, and for each bin plot the observed mean against the observed variance. Then draw what each family claims that relationship must be.\n\n::: {#cell-bin-by-age .cell execution_count=19}\n``` {.julia .cell-code}\nbyage = combine(groupby(females, :Age),\n    nrow => :n,\n    :Fledglings => mean => :m,\n    :Fledglings => var => :v)\nsort!(byage, :Age)\nbyage\n```\n\n::: {#bin-by-age .cell-output .cell-output-display execution_count=32}\n```{=html}\n<div><div style = \"float: left;\"><span>4×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Age</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">m</th><th style = \"text-align: left;\">v</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: right;\">1</td><td style = \"text-align: right;\">65</td><td style = \"text-align: right;\">2.53846</td><td style = \"text-align: right;\">3.8149</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: right;\">2</td><td style = \"text-align: right;\">59</td><td style = \"text-align: right;\">3.25424</td><td style = \"text-align: right;\">5.43425</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: right;\">3</td><td style = \"text-align: right;\">32</td><td style = \"text-align: right;\">4.09375</td><td style = \"text-align: right;\">7.37802</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: right;\">4</td><td style = \"text-align: right;\">7</td><td style = \"text-align: right;\">5.0</td><td style = \"text-align: right;\">2.66667</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n::: {#cell-fig-mean-variance .cell execution_count=20}\n``` {.julia .cell-code}\nmgrid = collect(range(0.9 * minimum(byage.m), 1.1 * maximum(byage.m), length = 100))\n\nfig = Figure(size = (560, 400))\nax = Axis(fig[1, 1]; xlabel = \"observed mean count\", ylabel = \"observed variance\",\n    title = \"what each family says the variance must be\")\nlines!(ax, mgrid, mgrid; linewidth = 2, linestyle = :dash,\n    label = \"Poisson: var = mean\")\nlines!(ax, mgrid, mgrid .+ mgrid .^ 2 ./ theta; linewidth = 2.5,\n    label = \"NB2: var = mean + mean²/θ\")\nscatter!(ax, byage.m, byage.v; markersize = 3 .* sqrt.(byage.n),\n    color = (:grey, 0.75), label = \"observed (age bin), area ∝ n\")\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n![Observed mean against observed variance, females binned by age, with marker area showing how many females are in each bin. The Poisson line is the identity; the negative-binomial curve bends above it, and how far it bends is set by 1/θ — the smaller θ, the further the curve climbs above the identity line.](wk4-overdispersion_files/figure-html/fig-mean-variance-output-1.svg){#fig-mean-variance}\n:::\n:::\n\n\n::: {#read-the-bins .cell execution_count=21}\n``` {.julia .cell-code}\n# Count what the prose would otherwise assert, so the sentence cannot go stale.\nnb_curve = byage.m .+ byage.m .^ 2 ./ theta\nn_bins = nrow(byage)\nn_above = count(byage.v .> byage.m)\nn_nearer = count(abs.(byage.v .- nb_curve) .< abs.(byage.v .- byage.m))\nn_below_both = count((byage.v .< byage.m) .& (byage.v .< nb_curve))\ni_small = argmin(byage.n)\n\n@printf(\"bins above the identity line : %d of %d\\n\", n_above, n_bins)\n@printf(\"bins nearer the NB2 curve    : %d of %d\\n\", n_nearer, n_bins)\n@printf(\"bins below both              : %d of %d\\n\", n_below_both, n_bins)\n@printf(\"smallest bin: age %d, n = %d, mean %.3f, variance %.3f\\n\",\n        byage.Age[i_small], byage.n[i_small], byage.m[i_small], byage.v[i_small])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbins above the identity line : 3 of 4\nbins nearer the NB2 curve    : 3 of 4\nbins below both              : 1 of 4\nsmallest bin: age 4, n = 7, mean 5.000, variance 2.667\n```\n:::\n:::\n\n\n**Itchy:** 3 of the 4 bins sit above the line and 3 sit nearer the curve. 1 sits below both, and before anybody builds a theory about it, look at how few birds are in it: 7. A variance estimated from 7 numbers is a very unstable thing. That point is not counter-evidence; it is the reason we fit a model over all 163 females instead of eyeballing four dots, and it is why the marker sizes are on the plot at all. A figure that hides its sample sizes will let you believe anything.\n\n**Momo:** So I *should* have used the negative binomial.\n\n**Itchy:** Put it on top of the exposure model and find out.\n\n::: {#nb2-on-exposure .cell execution_count=22}\n``` {.julia .cell-code}\nnbe = drm(bf(@formula(Fledglings ~ Age + logEgg), @formula(sigma ~ 1)),\n          NegBinomial2(); data = females)\ntheta_e = exp(-2 * coef(nbe, :sigma)[1])\n\n@printf(\"theta, Age only          : %.4f\\n\", theta)\n@printf(\"theta, Age + log(EggNo)  : %.4f\\n\", theta_e)\n@printf(\"AIC, Poisson + exposure  : %.4f\\n\", aic(poe))\n@printf(\"AIC, NB2     + exposure  : %.4f   (difference %.4f)\\n\",\n        aic(nbe), aic(nbe) - aic(poe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntheta, Age only          : 3.9864\ntheta, Age + log(EggNo)  : 29.2025\nAIC, Poisson + exposure  : 652.8208\nAIC, NB2     + exposure  : 654.1004   (difference 1.2796)\n```\n:::\n:::\n\n\n**Itchy:** θ goes from 4.0 to 29.2 — a number that large is the negative binomial telling you it has nothing to do — and the extra parameter makes AIC **worse** by about 1.3. The family repair earned about 21 AIC against a model with a missing covariate, and earns nothing at all once the covariate is there. **That is the whole of the first half of today, in one comparison.** The negative binomial is a good family and it was not what was wrong.\n\n### The same move, in a family that never lied\n\n**Itchy:** Right. Toto, you have been quiet, and you are about to see why this chapter is not called \"the negative binomial\".\n\n**Toto:** Because you are going to do it to the sparrows.\n\n**Itchy:** Because I am going to do it to the sparrows, and the sparrows have a **Gaussian** response, where nobody ever said the variance was a function of the mean. Load Class 2 back.\n\n::: {#cell-sparrows .cell execution_count=23}\n``` {.julia .cell-code}\nraw = CSV.read(\"../data/2012/MBodySize.csv\", DataFrame)\nraw.Sex = ifelse.(raw.Sex .== \"F\", \"female\", \"male\")\nsparrows = select(raw, :BirdID, :Sex, :Tarsus, :Wing)\n\nn_sp = nrow(sparrows)\n@printf(\"rows: %d\\n\", n_sp)\ncombine(groupby(sparrows, :Sex), nrow => :n, :Wing => std => :wing_sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrows: 171\n```\n:::\n\n::: {#sparrows .cell-output .cell-output-display execution_count=38}\n```{=html}\n<div><div style = \"float: left;\"><span>2×3 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">Sex</th><th style = \"text-align: left;\">n</th><th style = \"text-align: left;\">wing_sd</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String\" style = \"text-align: left;\">String</th><th title = \"Int64\" style = \"text-align: left;\">Int64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">89</td><td style = \"text-align: right;\">1.54432</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">male</td><td style = \"text-align: right;\">82</td><td style = \"text-align: right;\">1.68234</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Itchy:** Two lines of housekeeping first, since you will do this to your own files. `ifelse.(raw.Sex .== \"F\", \"female\", \"male\")` is the dot on a three-argument function: for every row, *if* it is F write female, else male. `select(raw, :BirdID, ...)` keeps the named columns and drops the rest. Now: Class 2 fitted wing on tarsus and sex, and printed a single residual standard deviation for every bird on the island. Here is that model and here is the same model with a second formula in the box.\n\n> **y_i ~ N(μ_i, σ_i²),  μ_i = β0 + β1 tarsus_i + β2 male_i,  log σ_i = γ0 + γ1 male_i**\n\n::: {#cell-fit-sparrows .cell execution_count=24}\n``` {.julia .cell-code}\nfit_const = drm(bf(@formula(Wing ~ Tarsus + Sex)), Gaussian(); data = sparrows)\nfit_ls = drm(bf(@formula(Wing ~ Tarsus + Sex), @formula(sigma ~ Sex)),\n             Gaussian(); data = sparrows)\nfit_ls\n```\n\n::: {#fit-sparrows .cell-output .cell-output-display execution_count=39}\n```\nDistributional regression fit (Gaussian)\n  nobs = 171   logLik = -301.6513   converged = true\n  Residual SD (response scale) varies with the σ model: 1.3757 to 1.4528   dof_residual = 166\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z    Pr(>|z|)\n  (Intercept)  57.8574     2.6912  21.4985  1.609e-102\n  Tarsus        1.0097     0.1450   6.9630   3.332e-12\n  Sex: male     2.5015     0.2183  11.4614   2.063e-30\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                Coef.  Std.Error       z   Pr(>|z|)\n  (Intercept)  0.3190     0.0750  4.2549  2.092e-05\n  Sex: male    0.0545     0.1083  0.5034     0.6147\n```\n:::\n:::\n\n\n**Momo:** That is the same shape of call as the beta-binomial.\n\n**Itchy:** It is the identical shape of call, and that is the sentence this whole class was built to earn. Three families, three very different-looking problems, **one verb and a second formula in the same box**. `BetaBinomial()` freed a variance the family had pinned to *n*·p(1 − p). `NegBinomial2()` freed one pinned to the mean. `sigma ~ Sex` frees one pinned to a single number. Same constant, freed three times, from three directions.\n\n**Toto:** And the header changed.\n\n**Itchy:** Read it out. Where Class 2 printed one residual SD, this prints a **range**, because with `Sex` in σ there is no single number to print. This kind of model has a name — **location-scale**: a formula on the mean, which is the location, and a second formula on σ, which is the scale. Compute the ends by hand once, so that the header means something to you.\n\n::: {#sigma-by-sex .cell execution_count=25}\n``` {.julia .cell-code}\ns_hat = exp.(coef(fit_ls, :sigma))\nsigma_f = s_hat[1]\nsigma_m = s_hat[1] * s_hat[2]\nsd_range = extrema(sigma(fit_ls))\n\n@printf(\"sigma, females : %.4f mm\\n\", sigma_f)\n@printf(\"sigma, males   : %.4f mm\\n\", sigma_m)\n@printf(\"constant-sigma model, one number : %.4f mm\\n\", sigma(fit_const)[1])\n@printf(\"location-scale model, the range  : %.4f to %.4f mm\\n\", sd_range[1], sd_range[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsigma, females : 1.3757 mm\nsigma, males   : 1.4528 mm\nconstant-sigma model, one number : 1.4132 mm\nlocation-scale model, the range  : 1.3757 to 1.4528 mm\n```\n:::\n:::\n\n\n**Itchy:** Females scatter by about 1.38 mm around their line, males by about 1.45 mm. Males a little **more**, which is not what I would have guessed. Now the verdicts. One line in the next cell, the one that computes `se_g1`, is plumbing: it finds the standard error of the σ slope by its name rather than by its position in the table, and you may skip it.\n\n::: {#sparrow-verdicts .cell execution_count=26}\n``` {.julia .cell-code}\ng = ci_row(fit_ls, :sigma, \"Sex: male\")   # log of the male/female sigma ratio\n# By name, not position: same route as ci_row (match the sigma block's own name\n# vector), so this keeps working if a parameter is ever added after sigma.\nse_g1 = stderror(fit_ls)[only(idx for ((p, r), (_, nms)) in zip(fit_ls.blocks, fit_ls.coefnames)\n                                   if p === :sigma for (idx, nm) in zip(r, nms) if nm == \"Sex: male\")]\nz_sex = g.estimate / se_g1\np_sex = 2 * Distributions.ccdf(Distributions.Normal(), abs(z_sex))\nd_aic_sp = aic(fit_ls) - aic(fit_const)\n\nratio_sex = exp(g.estimate)\nratio_lo, ratio_hi = exp(g.lower), exp(g.upper)\n\n# Smallest sigma ratio this design could have detected at 80% power, alpha = 0.05.\nz_a = Distributions.quantile(Distributions.Normal(), 0.975)\nz_b = Distributions.quantile(Distributions.Normal(), 0.80)\nmdr = exp((z_a + z_b) * se_g1)\n\n@printf(\"AIC, constant sigma  : %.4f\\n\", aic(fit_const))\n@printf(\"AIC, sigma ~ Sex     : %.4f\\n\", aic(fit_ls))\n@printf(\"difference           : %.4f  (positive means the extra term did not pay)\\n\", d_aic_sp)\n@printf(\"\\nsigma: Sex: male   z = %.4f   p = %.4f\\n\", z_sex, p_sex)\n@printf(\"male/female sigma ratio : %.4f  [%.4f, %.4f]\\n\", ratio_sex, ratio_lo, ratio_hi)\n@printf(\"smallest ratio detectable at 80%% power : %.4f\\n\", mdr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC, constant sigma  : 611.5563\nAIC, sigma ~ Sex     : 613.3026\ndifference           : 1.7464  (positive means the extra term did not pay)\n\nsigma: Sex: male   z = 0.5034   p = 0.6147\nmale/female sigma ratio : 1.0560  [0.8541, 1.3057]\nsmallest ratio detectable at 80% power : 1.3544\n```\n:::\n:::\n\n\n**Toto:** It got worse.\n\n**Itchy:** AIC got worse by about 1.75, and the σ table's own row agrees: a z of 0.5 and a p of 0.61. Now say what that means, carefully, because this is where papers go wrong. The estimated ratio is 1.056 — males scattering about 6% more — with an interval from 0.854 to 1.306. These birds are consistent with males varying rather less than females and with males varying rather more.\n\n**Momo:** So the answer is not \"no\".\n\n**Itchy:** The answer is **not detected**, and the two are not the same sentence. With 171 birds, the smallest ratio this design could have caught four times out of five is 1.35. Anything smaller than that was never going to show up, whether or not it is there. **\"We could not tell them apart, and we could only have seen a 35% difference\" is the honest report; \"the answer is no\" is an accepted null wearing a lab coat.**\n\n**Momo:** So one of your repairs worked and the other did not.\n\n**Itchy:** One worked, one did not pay, and I am keeping both, because a chapter where every experiment succeeds is teaching you a superstition. The method is the same, the verdict is data, and the only thing that would have been wrong was not asking. Look at what \"did not pay\" actually looks like.\n\n::: {#cell-fig-sparrow-bands .cell execution_count=27}\n``` {.julia .cell-code}\nb = coef(fit_ls, :mu)          # [intercept, Tarsus, Sex: male]; female is the baseline\ntg = collect(range(minimum(sparrows.Tarsus), maximum(sparrows.Tarsus), length = 100))\nmu_f = b[1] .+ b[2] .* tg\nmu_m = b[1] .+ b[2] .* tg .+ b[3]\n\nis_m = sparrows.Sex .== \"male\"\n\nfig = Figure(size = (560, 400))\nax = Axis(fig[1, 1]; xlabel = \"tarsus (mm)\", ylabel = \"wing (mm)\",\n    title = \"two lines, two widths, one of them unearned\")\n# Bands and lines share one colour per sex (accent = female, warn = male) so a\n# reader can match a band to its line by hue, not only by which one sits\n# higher; the near-equal alpha keeps the WIDTH comparison — the point of this\n# figure — the thing that reads as similar, not the shading. Data drawn LAST\n# so no bird is ever painted over by the model on top of it.\nband!(ax, tg, mu_f .- sigma_f, mu_f .+ sigma_f; color = (LIGHT.accent, 0.22),\n    label = \"females, ±σ\")\nband!(ax, tg, mu_m .- sigma_m, mu_m .+ sigma_m; color = (LIGHT.warn, 0.22),\n    label = \"males, ±σ\")\nlines!(ax, tg, mu_f; linewidth = 2.5, color = LIGHT.accent, label = \"female mean\")\nlines!(ax, tg, mu_m; linewidth = 2.5, linestyle = :dash, color = LIGHT.warn, label = \"male mean\")\nscatter!(ax, sparrows.Tarsus[.!is_m], sparrows.Wing[.!is_m];\n    markersize = 6, color = (:grey, 0.6), label = \"female\")\nscatter!(ax, sparrows.Tarsus[is_m], sparrows.Wing[is_m];\n    markersize = 6, marker = :diamond, color = (:grey, 0.6), label = \"male\")\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=44}\n![Wing on tarsus, with a ±1σ band per sex from the location-scale fit. The bands differ, and not by enough to earn their parameter — nor by enough for this design to have detected the difference if it were real.](wk4-overdispersion_files/figure-html/fig-sparrow-bands-output-1.svg){#fig-sparrow-bands}\n:::\n:::\n\n\n**Itchy:** Two bands of very nearly the same width. That picture is what a p of 0.61 looks like before anybody computes a p, and you should learn to see it, because the picture is available to you before the test is.\n\n**Toto:** So when *is* modelling σ worth it?\n\n**Itchy:** When the spread is genuinely a function of something you measured, and that is a chapter of its own — **rung 11, modelling the spread itself, which is held for version two of this book**. Today you have seen the syntax and one honest not-detected, which is the right amount for a Tuesday. Class 5 is next and is about nothing but diagnostics, which is where the worm plot and the coverage arithmetic get done properly. And every model on this page is still fixed effects only. Class 6 is where rows stop being strangers, on a file that records who is who.\n\n---\n\n## Summary\n\n### Stats stuff\n\n- **Compare like with like.** A Poisson *regression* decrees Var(y | x) = μ(x); it says nothing about the variance-to-mean ratio of the raw counts, which also carries the variation the predictors create. Here the raw ratio is 1.69 and a perfectly correct Poisson would still imply 1.15. Check overdispersion on residuals, not on the marginal moments.\n- **Look for an exposure before you blame the family.** A denominator sitting unused in your data is the commonest cause of \"overdispersion\" and the cheapest to fix: here `log(EggNo)` bought about 87 AIC for one parameter and moved the age rate ratio from 1.26 to 1.09, interval covering one. **A missing covariate and a wrong variance function look identical in a residual plot.**\n- **An offset is a covariate with its coefficient pinned at one.** Fit it free first: if the interval covers one, the offset is the better model; if it does not, the offset would have been a confident mistake.\n- **Successes out of trials is not a count.** For *n* > 1 the binomial variance is *n*·p(1 − p), a real claim — the trials within a row are independent — that data can break. For *n* = 1 it is an identity, which is why Class 3's logistic diagnostic could not fail.\n- **The beta-binomial frees that claim with one parameter**, as the negative binomial frees Var = μ with θ. Here it bought about 25 AIC and took the Pearson statistic from 1.64 to 1.02.\n- **AIC compares models of the same response.** Counts and proportions-out-of-a-denominator are different data; choose between them by the question you are asking, not by the smaller number. The same goes for a Pearson statistic.\n- **Overdispersion is a disease of standard errors, and that is a theorem.** The Poisson point estimate stays trustworthy whatever the true variance; only its standard error was wrong, here by a factor of 1.39, against the quasi-Poisson's 1.25 — close, not identical, because the two weight observations differently.\n- **Judge a band against its own claim.** A ±1 SD band is not supposed to contain the data. Ask the model what coverage it claims and compare: 0.53 against 0.67 for the binomial, 0.66 against 0.67 for the beta-binomial.\n- **\"Not detected\" is not \"no\".** The sparrows' σ ratio is 1.06 with an interval of 0.85 to 1.31, and the smallest ratio this design could have caught at 80% power is 1.35. Report the interval and the detectable size, not a verdict.\n- **A model comparison that goes against you is a result.** The counts earned their beta-binomial parameter and the sparrows lost their σ term by about 1.7 AIC. Reporting only the one that worked is how a literature goes wrong.\n- **Plot the assumption, not only its consequences.** Mean against variance, binned, with the family's claim drawn as a curve and marker area showing sample size.\n- **What this chapter still pretends.** Every model here treats its rows as strangers, and these files cannot stop it: `FemaleSuccess.csv` carries no female identifier, and `MBodySize.csv` is one row per bird. Class 6 ends the pretence on a file that repeats birds, and the standard errors printed here will move when it does.\n\n### Julia you used\n\n- **`df.logEgg = log.(df.EggNo)`.** Assigning to a column that does not exist creates it. The dot takes the log of every element.\n- **`sum(f(i) for i in 1:n)`.** A **generator**: a comprehension without its square brackets, consumed as it goes. `sum(... for k in 0:n if cond)` filters it with an `if`, and a second `for` nests one inside another.\n- **`ifelse.(cond, a, b)`.** The dot on a three-argument function: for each element, `a` where the condition holds, otherwise `b`.\n- **`.&`, `.|`, `.!`.** *And*, *or* and *not*, element by element, for combining true/false vectors; `count(v)` counts the trues.\n- **`import Distributions` and `Distributions.Poisson(μ)`.** A package loaded without its names spilled into yours, so DRM's `Poisson()` family and the distribution can coexist; the dot after the package name reaches inside it.\n- **`findfirst(r -> r.coef == name, rows)`.** The position of the first element for which the function is true; `argmin(v)` is the position of the smallest value.\n- **`function refit_pair(y) ... (a, b) end`.** A function returning two values as a pair; `first.(pairs)` and `last.(pairs)` split a vector of pairs into two vectors.\n- **`join(names(df), \", \")`.** Glues strings together with a separator.\n- **`sort!(byage, :Age)`.** The `!` again: sorts the frame in place.\n\n### Calls you used\n\n- `drm(bf(@formula(cbind(k, n - k) ~ x)), Binomial(); data = df)`: a **grouped** binomial; `cbind` is DRM's own marker for successes and failures, not R's function.\n- `drm(bf(@formula(y ~ x), @formula(sigma ~ 1)), BetaBinomial(); data = df)` and `NegBinomial2()`: the overdispersed versions, with the second formula in the box. `coef(fit, :sigma)` is log σ, and φ or θ is `exp(-2 * coef(fit, :sigma)[1])`.\n- `drm(bf(@formula(y ~ x + g), @formula(sigma ~ g)), Gaussian(); data = df)`: a location-scale fit; `exp.(coef(fit, :sigma))` for millimetres.\n- `sigma(fit)`, `dof_residual(fit)`, `stderror(fit)`: response-scale σ per observation, residual degrees of freedom for a Pearson statistic, and standard errors in coefficient order.\n- `confint(fit; parm = :sigma)`: one row per coefficient of that block, each with `.estimate`, `.lower`, `.upper` on the link scale; `ci_row` above picks a row by name.\n- `residuals(fit; type = :quantile, rng = MersenneTwister(seed))`: as before. Which `rng` you pass moves the SD's second decimal, so do not read its digits.\n- `markersize = 3 .* sqrt.(n)` in a binned plot: area, not radius, is what the eye reads.\n- **The simulation thread.** Ask the negative-binomial fit to invent two hundred new sets of females, refit each, and watch which parameter is well pinned down and which is not.\n\n::: {#simulate-refit .cell execution_count=28}\n``` {.julia .cell-code}\n# Draw new counts from the fitted NB2 model, refit the same model to each,\n# and collect two things: the slope on Age, and the dispersion theta.\nrng_sim = MersenneTwister(20260907)\nysim = simulate(nb; nsim = 200, rng = rng_sim)\n\nfunction refit_pair(y)\n    d = DataFrame(Fledglings = y, Age = females.Age)\n    f = drm(bf(@formula(Fledglings ~ Age), @formula(sigma ~ 1)),\n            NegBinomial2(); data = d)\n    (coef(f, :mu)[2], exp(-2 * coef(f, :sigma)[1]))\nend\n\npairs_out = [refit_pair(ysim[:, k]) for k in 1:size(ysim, 2)]\nslopes = first.(pairs_out)\nthetas = last.(pairs_out)\n\n@printf(\"slope on Age    : fitted %.4f, reported SE %.4f\\n\", coef(nb, :mu)[2], se_nb[2])\n@printf(\"                  refits: mean %.4f, SD %.4f\\n\", mean(slopes), std(slopes))\n@printf(\"\\ntheta           : fitted %.4f\\n\", theta)\n@printf(\"                  refits: mean %.4f, median %.4f, SD %.4f\\n\",\n        mean(thetas), median(thetas), std(thetas))\n@printf(\"                  refits: 10th pct %.4f, 90th pct %.4f, max %.4f\\n\",\n        quantile(thetas, 0.1), quantile(thetas, 0.9), maximum(thetas))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nslope on Age    : fitted 0.2337, reported SE 0.0663\n                  refits: mean 0.2361, SD 0.0678\n\ntheta           : fitted 3.9864\n                  refits: mean 4.2842, median 4.0946, SD 1.2401\n                  refits: 10th pct 2.8967, 90th pct 5.9290, max 9.2220\n```\n:::\n:::\n\n\nThe numbers above say \"strongly asymmetric\" several ways; here is the shape itself, so you can see it rather than assemble it from percentiles.\n\n::: {#cell-fig-theta-refits .cell execution_count=29}\n``` {.julia .cell-code}\nfig = Figure(size = (560, 360))\nax = Axis(fig[1, 1]; xlabel = \"θ (refit)\", ylabel = \"count of refits (of 200)\",\n    title = \"two hundred refits of one parameter\")\nhist!(ax, thetas; bins = 25, color = (:grey, 0.55))\nvlines!(ax, [theta]; linewidth = 2.5, linestyle = :dash, color = LIGHT.accent,\n    label = \"fitted θ\")\nvlines!(ax, [median(thetas)]; linewidth = 2.5, linestyle = :dot, color = LIGHT.warn,\n    label = \"median of refits\")\nLegend(fig[1, 2], ax; framevisible = false)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=47}\n![The sampling distribution of θ across the 200 parametric refits: two hundred counts of a single fitted parameter, from data the fitted model itself generated. The dashed line marks the θ the one real fit reported; the dotted line marks the median of the 200 refits. A symmetric standard error would draw a bell centred on the dashed line — this is not that.](wk4-overdispersion_files/figure-html/fig-theta-refits-output-1.svg){#fig-theta-refits}\n:::\n:::\n\n\n`refit_pair` is Class 3's refit function returning two things at once, a pair in brackets, and `first.(pairs_out)` and `last.(pairs_out)` pull the two halves apart with the dot on a function: one vector of slopes, one of thetas. The slope behaves itself: the spread of refitted slopes lands close to the standard error the single fit reported, which is what a standard error promises. θ does not. Its refits are strongly **asymmetric** — the mean printed above sits higher than the median, the largest refit is 2.3 times the estimate, and the tenth and ninetieth percentiles are nowhere near symmetric about 3.99. So quote θ to one decimal, and prefer an interval read off the likelihood itself to the plain estimate-plus-or-minus-two-standard-errors kind — the **Wald** interval, which assumes the uncertainty is the same size on both sides. Appendix A takes that apart properly.\n\n---\n\n## Further reading\n\n*Graded by depth. Details checked on 2026-09-07 against OpenAlex, an open catalogue of research papers.*\n\n1. **Ver Hoef, J. M. & Boveng, P. L. (2007) \"Quasi-Poisson vs. negative binomial regression: how should we model overdispersed count data?\", *Ecology* 88:2766–2772.** doi:10.1890/07-0043.1. Start here, and read it before you choose. It sets the negative binomial against the other standard repair, the quasi-Poisson, and the difference is not cosmetic: they weight observations differently, so they can disagree about which coefficient matters. This class computed both inflation factors in one line; the paper is why they are not the same number.\n2. **Lindén, A. & Mäntyniemi, S. (2011) \"Using the negative binomial distribution to model overdispersion in ecological count data\", *Ecology* 92:1414–1421.** doi:10.1890/10-1831.1. The ecologist's companion to the equation on the board, and the paper that would have caught Momo's first mistake: its abstract is about the **mechanisms** that generate overdispersion — sampling, flocking, aggregation, environmental variability — which is exactly the question \"is the family wrong, or is something missing from the mean?\".\n3. **Harrison, X. A. (2014) \"Using observation-level random effects to model overdispersion in count data in ecology and evolution\", *PeerJ* 2:e616.** doi:10.7717/peerj.616. The repair this chapter deliberately did not use, because it needs machinery from Class 6. Read it after Class 6 and then come back: it is a third route to the same problem, and knowing three routes is what stops you believing any one of them is the definition of the problem.\n4. **Rigby, R. A. & Stasinopoulos, D. M. (2005) \"Generalized additive models for location, scale and shape\", *Journal of the Royal Statistical Society Series C* 54:507–554.** doi:10.1111/j.1467-9876.2005.00510.x. The framework the last part of this class belongs to, and where rung 11 goes. This is the paper that says out loud that every parameter of a distribution can have a linear predictor, not only the mean. Long, and the introduction alone repays the afternoon.\n5. **Hilbe, J. M. (2011) *Negative Binomial Regression*, 2nd edition, Cambridge University Press.** doi:10.1017/cbo9780511973420. The reference book, for when you need the parameterisation you were handed rather than the one you like. Own it if counts are your day job; borrow it otherwise, and read the chapters on model selection and on the varieties of negative binomial.\n\n---\n\n## Exercises\n\nGraded by depth: the first three take ten minutes each. Every exercise names a file under `data/` that exists; do it on your own organism as well where you have one. A *check* is a number computed from that file when this page was built — match it before going on. **For every question, paste your code and then explain in your own words what each line does**, as if to somebody who has done Class 3 and not Class 4.\n\n\n\n1. **Read the file before the model.** `data/2012/EPPSuccess.csv` records, for 76 male sparrows, `EPP`, the number of extra-pair young each sired, and his `Age` in years. Before fitting anything, answer for each column other than `EPP`: predictor, exposure, or neither? An exposure is anything that changes how much *opportunity* a row had — area searched, hours observed, eggs laid, individuals at risk. Then say what column this file would need for an exposure to be payable, and compute the variance-to-mean ratio of `EPP` as the crude sign of what is coming. *Check:* the ratio is 5.05.\n\n2. **Pay the price.** Fit `EPP ~ Age` with `Poisson()`, then with `NegBinomial2()` and `@formula(sigma ~ 1)` in the box. Report the coefficient on `Age`, its standard error and the rate ratio under each family in a four-row table, and report θ. Then write one sentence naming what changed and one naming what did not. *Check:* θ = 0.391; AIC drops by 76.1 for one parameter; the standard error grows by a factor of 2.62; the rate ratio moves from 2.05 to 2.84, which is the part the chapter did not warn you about.\n\n3. **The referee.** For the repair you kept in question 2, report the AIC difference. Then answer: if it had gone the other way, what would you have done, and would you have reported the comparison at all? Two sentences, and be honest in the second one.\n\n4. **Out of how many?** `data/2012/SparrowSurvival.csv` has one row per chick, and on each row the brood's `HatchingSuccess` (eggs that hatched) and `EggNo` (eggs laid). Two things this chapter has not needed: the file marks missing values two ways, so read it with `missingstring = [\"NA\", \"\"]`, and drop rows with holes in the three columns you need with `dropmissing(df, [:HatchingSuccess, :EggNo, :JulianDate])`; Classes 6 and 9 explain them. Then collapse to one row per brood with `combine(groupby(df, :BroodNo), :HatchingSuccess => first => :hatched, :EggNo => first => :eggs, :JulianDate => first => :date)`, and fit hatching success as `cbind(hatched, eggs - hatched)` on `date` with `Binomial()`, then with `BetaBinomial()`. Report both AICs, the Pearson X²/df under the binomial, and φ. Then answer in one sentence why you may not compare either AIC with the count models of question 2. *Check:* 544 broods; X²/df = 1.34 under the binomial; φ = 8.26; the beta-binomial's AIC is lower by 35.6.\n\n5. **The same move on mass.** On `data/2012/MBodySize.csv` fit `Weight ~ Tarsus + Sex`, then add `@formula(sigma ~ Sex)` to the box. Report both AICs, the z and p on the σ slope row, **the σ ratio with its interval**, and the smallest ratio this sample could have detected at 80% power, `exp((1.96 + 0.84) * se)`. Then write the result as a \"not detected, and we could only have seen X\" sentence rather than a \"no\". *Check:* the male-to-female σ ratio is 0.94, interval 0.76 to 1.17; the extra parameter raises AIC by 1.7; the smallest detectable ratio is 1.35.\n\n6. **The two faces.** Write one paragraph, no code, explaining to a labmate why `BetaBinomial()`, `NegBinomial2()` and `sigma ~ x` are the same move. Your paragraph must contain the phrase \"held fixed\" and must name what is held fixed in each case. *Check:* there are three answers to \"what is held fixed\", and questions 2, 4 and 5 each produced one of them.\n\n",
    "supporting": [
      "wk4-overdispersion_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}