{
  "hash": "a983c18b1b13ceebbab7cccd223bf2d5",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Class 2: the linear model\"\nbook: Stats Hours with Itchy\nchapter: 2\ntype: book-chapter\nstatus: draft\ncreated: 2026-09-05\nengines: DRM.jl 0.7.1, development snapshot 4d9248f88 (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)\ntags: [book, julia, linear-model, DRM.jl, drmTMB]\ndeck: \"The linear model, taught in one engine — and the morning a student notices that Julia and R disagree about a number.\"\nstatus_tag: Draft\nstatus_note: \"Draft. Every number and figure on this page comes from code that was actually run when the site was built; the prose is still being written.\"\nprovenance: \"Everything printed below came from running this chapter's code from top to bottom when the site was built; nothing is typed from memory. The three errors are real errors, left in on purpose. The R output in the grey boxes was run once by hand, in R, on 2026-09-06, on the same birds, and pasted in.\"\ncaveat: \"The data are real: 171 house sparrows measured on Lundy Island in the author's 2012 course, read from data/2012/MBodySize.csv through a copy, data/ch2/sparrows.csv, with the sex column spelled out as female/male (where the file came from is recorded in data/2012/README.md).\"\nfooter_note: \"Stats Hours with Itchy · Class 2 of a planned 13 (ten in version 1, plus a coda) · draft · code last run 2026-09-07\"\n---\n\n\n# Class 2: one line through a cloud of sparrows\n\n> **The data are real.** The 2012 sparrow morphology file (`data/2012/MBodySize.csv`) is the one the\n> original 2012 R-book course used — 171 house sparrows measured on Lundy Island, recovered from the\n> author's own archive folder. This chapter reads a copy of it, `data/ch2/sparrows.csv`, with the sex\n> column spelled out as female/male and only the four columns it needs kept. Where the file came from,\n> and how to check that your copy is the same, is recorded in `data/2012/README.md`. Every number in\n> this chapter, spoken or printed, comes from that file.\n\n---\n\n## Objectives\n\nBy the end of this class you should be able to:\n\n1. Say what a linear model actually claims about your data, in one sentence, without the word \"significant\".\n2. Fit a simple regression in Julia with `drm` and read every line of what it prints back.\n3. Add a second predictor, and say what the first coefficient now means that it did not mean before.\n4. Compare two models, one inside the other, by likelihood — how well each explains the data you actually saw — and know when that comparison is legitimate.\n5. Explain why the model prints a **second table you did not ask for**, and read the null hypothesis — the \"nothing is going on\" value being tested — that it states above each row of it.\n6. Recognise that R's `lm()` and our engine disagree about one number, and say exactly why.\n\n---\n\n## The class\n\n**Itchy's office, 9:00 am. Dunedin, and it is doing that thing where the rain arrives sideways. TOTO is early, dripping. MOMO arrives at 9:00 exactly, which for Momo counts as early. Two laptops open. Itchy is drawing a cloud of dots on the whiteboard.**\n\n**Itchy:** Julia time. Toto, you are damp.\n\n**Toto:** I cycled.\n\n**Itchy:** You cycled in that. Good. Then you already understand today's lesson: things vary, and some of the variation has a reason. Look at this cloud. Each dot is a house sparrow. Along the bottom, tarsus length; the bony part of the foot, and the standard way we say \"how big is this bird\" without arguing about how fat it is. Up the side, wing length.\n\n**Momo:** And you want a line through it.\n\n**Itchy:** I want a line through it. But I want you to say what the line *is* before we draw one, because the line is not the model. Toto, what is a linear model?\n\n**Toto:** ...the best-fitting straight line?\n\n**Itchy:** That is what it looks like. It is not what it is. Here is what it is, and I want you to learn this sentence properly because you will re-use it for the next ten weeks. **A linear model says: every sparrow's wing is drawn from its own normal distribution — the familiar bell-shaped curve, symmetric around its centre; the centre of that distribution slides along a straight line as tarsus increases; and the width of that distribution is the same for every bird.**\n\n**Momo:** That is three claims.\n\n**Itchy:** It is three claims, and only the middle one gets a *p*-value in most software, which is a scandal we will spend the whole course fixing. Say them back.\n\n**Momo:** Normal. Centre moves in a line. Width fixed.\n\n**Itchy:** *(writes on the board)*\n\n> **μ = where the birds are.  σ = how spread out they are.**\n\n**Itchy:** Every model in this course is those two letters. Today μ gets a predictor and σ does not. In Class 4 σ gets predictors too, and you will find you already know how to write it, because we never change tools. Right. Load the data.\n\n\n\n::: {#f2513aa4 .cell execution_count=2}\n``` {.julia .cell-code}\nusing DRM, DataFrames, CSV, Statistics\nsparrows = CSV.read(\"../data/ch2/sparrows.csv\", DataFrame);\n```\n:::\n\n\n::: {#c5f673ca .cell execution_count=3}\n``` {.julia .cell-code}\nfirst(sparrows, 6)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div><div style = \"float: left;\"><span>6×4 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">BirdID</th><th style = \"text-align: left;\">Sex</th><th style = \"text-align: left;\">Tarsus</th><th style = \"text-align: left;\">Wing</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"String7\" style = \"text-align: left;\">String7</th><th title = \"String7\" style = \"text-align: left;\">String7</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">TA14502</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">18.4333</td><td style = \"text-align: right;\">71.5667</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">TA14505</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">18.1</td><td style = \"text-align: right;\">76.5</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">3</td><td style = \"text-align: left;\">TA14506</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">18.45</td><td style = \"text-align: right;\">75.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">4</td><td style = \"text-align: left;\">TA14507</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">18.15</td><td style = \"text-align: right;\">75.0</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">5</td><td style = \"text-align: left;\">TA14509</td><td style = \"text-align: left;\">male</td><td style = \"text-align: right;\">18.2</td><td style = \"text-align: right;\">78.25</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">6</td><td style = \"text-align: left;\">TA14513</td><td style = \"text-align: left;\">female</td><td style = \"text-align: right;\">17.3667</td><td style = \"text-align: right;\">74.4</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n**Itchy:** 171 birds. Look before you model, always. Toto, means and spreads.\n\n::: {#f0b65f7d .cell execution_count=4}\n``` {.julia .cell-code}\ndescribe(sparrows[!, [:Tarsus, :Wing]], :mean, :std, :min, :max)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div><div style = \"float: left;\"><span>2×5 DataFrame</span></div><div style = \"clear: both;\"></div></div><div class = \"data-frame\" style = \"overflow-x: scroll;\"><table class = \"data-frame\" style = \"margin-bottom: 6px;\"><thead><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\">Row</th><th style = \"text-align: left;\">variable</th><th style = \"text-align: left;\">mean</th><th style = \"text-align: left;\">std</th><th style = \"text-align: left;\">min</th><th style = \"text-align: left;\">max</th></tr><tr class = \"columnLabelRow\"><th class = \"stubheadLabel\" style = \"font-weight: bold; text-align: right;\"></th><th title = \"Symbol\" style = \"text-align: left;\">Symbol</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th><th title = \"Float64\" style = \"text-align: left;\">Float64</th></tr></thead><tbody><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">1</td><td style = \"text-align: left;\">Tarsus</td><td style = \"text-align: right;\">18.6146</td><td style = \"text-align: right;\">0.75411</td><td style = \"text-align: right;\">16.9</td><td style = \"text-align: right;\">20.55</td></tr><tr class = \"dataRow\"><td class = \"rowLabel\" style = \"font-weight: bold; text-align: right;\">2</td><td style = \"text-align: left;\">Wing</td><td style = \"text-align: right;\">77.8523</td><td style = \"text-align: right;\">2.09324</td><td style = \"text-align: right;\">71.5667</td><td style = \"text-align: right;\">84.0</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n\n\n**Itchy:** Wing lengths sit around 78 mm and wander by about 2.09 mm. Hold on to 2.09. It is the number the model has to explain away, and in twenty minutes I am going to ask you how much of it we managed to explain.\n\n::: {#cell-fig-cloud .cell execution_count=6}\n``` {.julia .cell-code}\nfig_data_cloud(sparrows.Tarsus, sparrows.Wing;\n    xlabel = \"Tarsus (mm)\", ylabel = \"Wing (mm)\", title = \"Wing vs Tarsus\")\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n![Wing length against tarsus length, 171 house sparrows (Lundy Island, 2012).](wk2-linear-models_files/figure-html/fig-cloud-output-1.svg){#fig-cloud}\n:::\n:::\n\n\n### The fit\n\n**Itchy:** Here is the whole thing. One line.\n\n::: {#99f0acaf .cell execution_count=7}\n``` {.julia .cell-code}\nfit1 = drm(bf(@formula(Wing ~ Tarsus)), Gaussian(); data = sparrows);\n```\n:::\n\n\n**Momo:** Stop. Why is there a `bf` in the way? In R I write `lm(Wing ~ Tarsus, sparrows)` and I am done. You have added two words and a semicolon.\n\n**Itchy:** Correct, and I am going to defend the two words rather than pretend they are not there. `bf` stands for \"**b**ig **f**ormula\", and it is a box that can hold **more than one formula at a time**: one for μ, one for σ, later one for the correlation between two traits. Today the box holds one formula, so it looks like packaging with nothing in it.\n\n**Momo:** So it is overhead I pay now for a feature I get in Class 4.\n\n**Itchy:** Yes. That is exactly the deal, and you should be annoyed about it for about two more weeks. What you get for it: from here to the summit of the mountain, **you never change the verb**. Not when the data are counts, not when the birds are siblings, not when we model the spread itself. It is always `drm`, always `bf`, always a family — here `Gaussian()`, which just means the normal distribution I described a minute ago. You will meet people who learn six packages to climb the same hill and spend their evenings translating between them. Let us see what came out.\n\n::: {#94cee965 .cell execution_count=8}\n``` {.julia .cell-code}\nfit1\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\nDistributional regression fit (Gaussian)\n  nobs = 171   logLik = -350.6659   converged = true\n  Residual SD (response scale) = 1.8809   dof_residual = 168\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  55.4569     3.5638  15.5613  1.334e-54\n  Tarsus        1.2031     0.1913   6.2893  3.188e-10\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                Coef.  Std.Error        z   Pr(>|z|)\n  (Intercept)  0.6317     0.0541  11.6829  1.559e-31\n```\n:::\n:::\n\n\n<details class=\"drmtmb\">\n<summary>Same fit in drmTMB, the same engine in R</summary>\n\n```r\n# Run once by hand in R on 2026-09-06 (drmTMB 0.7.0, R 4.6.0) and pasted in;\n# not re-run with the page. The same 171 Lundy Island sparrows, read from\n# data/ch2/sparrows.csv.\n> sp <- read.csv(\"data/ch2/sparrows.csv\")\n> summary(drmTMB(bf(Wing ~ Tarsus), data = sp))\n<summary.drmTMB>\nestimator: ML\n                    estimate  std_error\nmu:(Intercept)    55.4568660 3.56377203\nmu:Tarsus          1.2031120 0.19129417\nsigma:(Intercept)  0.6317395 0.05407379\nDistributional, random-effect, scale, and correlation parameters:\n                 component  dpar       term estimate std_error    scale\nsigma distributional-scale sigma (constant) 1.880879 0.1017063 response\nlogLik: -350.7\nconvergence: 0\n```\n\n</details>\n\n**Toto:** There are two tables. I only asked for one.\n\n**Itchy:** You asked for one and you were given the model. Sit down, this is the moment the engine looks strangest to somebody arriving from R, so let me pay for it properly instead of hurrying past.\n\nTwo tables came back because I told you there were always two letters. **μ is where the birds are; σ is how spread out they are.** R prints both too, it just hides σ at the bottom of the page under \"Residual standard error\" and hopes you will not ask questions about it. Ours puts it in a table, because in two weeks you will be putting predictors in it.\n\n**Toto:** Why \"log σ\"?\n\n**Itchy:** Because a spread cannot be negative, and an optimiser — the search routine that hunts for the best-fitting numbers — that wanders freely over the number line would eventually try a negative one and fall over. So the engine works with the logarithm, which is allowed to be any number at all, and you undo it at the end.\n\n::: {#8041178b .cell execution_count=9}\n``` {.julia .cell-code}\ncoef(fit1, :sigma)\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\n1-element Vector{Float64}:\n 0.6317394537001391\n```\n:::\n:::\n\n\n\n\n::: {#9c4421b7 .cell execution_count=11}\n``` {.julia .cell-code}\nexp(coef(fit1, :sigma)[1])\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\n1.8808794381239688\n```\n:::\n:::\n\n\n**Itchy:** There it is: **1.88 mm.** That is the residual standard deviation, in millimetres, on the natural scale. Now look back at the top of the fit, where it says **Residual SD (response scale)** — the same spread, in millimetres — next to `dof_residual`, the number of birds left over after the model has used up what it needs: 171 birds, minus an intercept, a slope and one number for the spread, leaves 168. The engine prints that number for you. I made you compute it by hand once so that the header means something when you read it, and so that you never mistake the `sigma:` row, which is on the log scale, for the millimetres it is not. And now answer my earlier question, Toto. The raw wing lengths wandered by 2.09 mm. After we account for tarsus, they wander by 1.88. Was tarsus worth it?\n\n**Toto:** ...a bit? It went down but not loads.\n\n**Itchy:** \"A bit\" is the honest answer and I want you to notice how much less exciting it is than a vanishingly small *p*-value. The *p*-value says the slope is not zero. It does not say the slope is *useful*. Those are different questions, and only one of them is about sparrows.\n\n**Momo:** The σ row has a *p*-value of its own, and it is tiny.\n\n**Itchy:** It is, and I want you suspicious of it rather than impressed by it. Every *p*-value answers a question of the form \"how surprised would I be if this number were really **zero**?\" For the slope, zero is a real, interesting hypothesis: tarsus tells us nothing about wing. Fine. Now: what would it mean for that σ row to be zero?\n\n**Momo:** ...zero log-sigma. Which is sigma equal to one.\n\n**Itchy:** Which is a residual spread of **exactly one millimetre**. Not \"no spread\". One millimetre. Why on earth would anyone want to test that?\n\n**Momo:** Nobody would.\n\n**Itchy:** Nobody would, and that is exactly why the engine prints the null *above* the table instead of leaving you to reconstruct it from a column of stars. Read the two lines under **Scale model (log σ)**. The `z` column is the estimate divided by its standard error — its uncertainty — so it counts how many standard errors from zero the estimate sits, and `Pr(>|z|)` is the *p*-value made from it. For the intercept, zero means σ = 1, and whether that is true depends entirely on whether you measured in millimetres or metres. Measure the same sparrows in centimetres and that *p*-value changes while nothing whatever about the birds does. A unit-dependent null is almost never a question about your organism.\n\n**Toto:** So I ignore it.\n\n**Itchy:** You ignore *that* one, and the same heading tells you when not to. The second line is about a σ **slope**, where zero means \"these groups vary by the same amount\", and that is a real question about real animals. We will ask it before you go home. The rule is: read the null, then decide whether you care. A number the software is willing to compute is not automatically a number you should report.\n\n**Toto:** Can I see all of it in one table?\n\n::: {#bdf0f418 .cell execution_count=12}\n``` {.julia .cell-code}\ncoeftable(fit1)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=16}\n|                    |  Estimate | Std.Error |     z | Pr(>\\|z\\|) | Lower 95% | Upper 95% |\n|:-------------------|----------:|----------:|------:|:-----------|:----------|----------:|\n| mu: (Intercept)    | 55.4569   | 3.56377   | 15.56 |     <1e-53 | 48.472    | 62.4417 |\n| mu: Tarsus         |  1.20311  | 0.191294  |  6.29 |     <1e-09 |  0.828182 |  1.57804 |\n| sigma: (Intercept) |  0.631739 | 0.0540738 | 11.68 |     <1e-30 |  0.525757 |  0.737722 |\n:::\n:::\n\n\n\n\n**Itchy:** Better. Confidence intervals included, and I want you reading the interval before the *p*-value from now on. **A sparrow with a tarsus one millimetre longer has a wing about 1.2 mm longer, and the data are consistent with anything from 0.83 to 1.58.** That is a sentence about birds. Notice it contains no asterisks.\n\n**Momo:** The intercept is 55.46. A sparrow with a tarsus of zero has a 55 mm wing.\n\n**Itchy:** A sparrow with a tarsus of zero is not a sparrow, it is a tragedy. The intercept is where the line crosses a place your data never went; tarsus ranges from 16.9 to 20.6. It is a bookkeeping number, not biology. You can make it biology by centring tarsus on its mean, and then the intercept becomes \"the wing of an average-sized sparrow\", which is a thing that exists. That is one of your exercises.\n\n::: {#cell-fig-fit1-ribbon .cell execution_count=14}\n``` {.julia .cell-code}\nfig_fit_ribbon(sparrows.Tarsus, sparrows.Wing, fitted(fit1), sigma(fit1);\n    xlabel = \"Tarsus (mm)\", ylabel = \"Wing (mm)\", title = \"Fitted μ ± σ\")\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n![Fitted mean wing length as a function of tarsus, ±σ band.](wk2-linear-models_files/figure-html/fig-fit1-ribbon-output-1.svg){#fig-fit1-ribbon}\n:::\n:::\n\n\n### Two errors, kept in\n\n**Toto:** *(typing)* I wanted to check something and I got a wall of red.\n\n::: {#bff93099 .cell execution_count=15}\n``` {.julia .cell-code}\ndrm(@formula(Wing ~ Tarsus), Gaussian(); data = sparrows)\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>MethodError: no method matching drm(::StatsModels.FormulaTerm{StatsModels.Term, StatsModels.Term}, ::Gaussian; data::DataFrame)\n\nClosest candidates are:\n  drm(<span class=\"ansi-bright-red-fg\">::DrmFormula</span>, ::Gaussian; data, K, A, tree, coords, g_tol, algorithm, method, profile_ci, phylo_coupled, penalty, sparse, impute, missing)\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_core.jl:436</span>\n  drm(<span class=\"ansi-bright-red-fg\">::BivariateDrmFormula</span>, ::Gaussian; data, tree, K, A, coords, spatial_range, g_tol, q4_g_tol, q4_iterations, q4_n_newton, q4_vcov, method, V)\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_bivariate.jl:150</span>\n\n\nStacktrace:\n [1] top-level scope\n<span class=\"ansi-bright-black-fg\">   @</span> <span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">In[20]:1</span></pre>\n```\n:::\n\n:::\n:::\n\n\n**Itchy:** Good. Everybody look at this, because Julia's error messages are the thing that makes R users give up in week one, and they are actually the most useful errors in any language I use once you know the shape.\n\nRead it as three parts. **What you asked for**, on the first line: you handed `drm` a `FormulaTerm`. **What it knows how to do**, underneath: it takes a `DrmFormula`, or a `BivariateDrmFormula`. And the mismatched argument is printed **in red** in each candidate — the same marker appears as the word `!Matched` where there is no colour — so you do not have to guess which of the four things you typed was the problem.\n\n**Toto:** So it is telling me I forgot the `bf`.\n\n**Itchy:** It is telling you exactly that, in five hundred characters and one exclamation mark. Momo, this is the honest cost of the `bf` wrapper: forget it and you get a method error rather than a fit. It is a one-token mistake with a loud, informative failure, and I will take that over a quiet one every time.\n\n**Toto:** *(typing)* And this one is just me.\n\n::: {#8e2b3f9f .cell execution_count=16}\n``` {.julia .cell-code}\ndrm(bf(@formula(Wing ~ Tarsis)), Gaussian(); data = sparrows)\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>ArgumentError: There isn't a variable called 'Tarsis' in your data; the nearest names appear to be: Tarsus\n\nStacktrace:\n  [1] <span class=\"ansi-bold\">concrete_term</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">t</span>::StatsModels.Term, <span class=\"ansi-bright-black-fg\">dt</span>::@NamedTuple<span class=\"ansi-bright-black-fg\">{BirdID::Vector{String7}, Sex::PooledArrays.PooledVector{String7, UInt32, Vector{UInt32}}, Tarsus::Vector{Float64}, Wing::Vector{Float64}}</span>, <span class=\"ansi-bright-black-fg\">hints</span>::Dict<span class=\"ansi-bright-black-fg\">{Symbol, Any}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/StatsModels/OasXV/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">schema.jl:184</span>\n  [2] <span class=\"ansi-bold\">(::StatsModels.var\"#62#63\"{@NamedTuple{BirdID::Vector{String7}, Sex::PooledArrays.PooledVector{String7, UInt32, Vector{UInt32}}, Tarsus::Vector{Float64}, Wing::Vector{Float64}}, Dict{Symbol, Any}})</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">t</span>::StatsModels.Term<span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">./</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">none:0</span>\n  [3] <span class=\"ansi-bold\">iterate</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-bright-black-fg\">./</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">generator.jl:47</span><span class=\"ansi-bright-black-fg\"> [inlined]</span>\n  [4] <span class=\"ansi-bold\">Dict{StatsModels.Term, StatsModels.AbstractTerm}</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">kv</span>::Base.Generator<span class=\"ansi-bright-black-fg\">{Vector{StatsModels.Term}, StatsModels.var\"#62#63\"{@NamedTuple{BirdID::Vector{String7}, Sex::PooledArrays.PooledVector{String7, UInt32, Vector{UInt32}}, Tarsus::Vector{Float64}, Wing::Vector{Float64}}, Dict{Symbol, Any}}}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-bright-black-fg\">Base</span> <span class=\"ansi-bright-black-fg\">./</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">dict.jl:85</span>\n  [5] <span class=\"ansi-bold\">Schema</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/StatsModels/OasXV/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">schema.jl:37</span><span class=\"ansi-bright-black-fg\"> [inlined]</span>\n  [6] <span class=\"ansi-bold\">schema</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">ts</span>::Vector<span class=\"ansi-bright-black-fg\">{StatsModels.Term}</span>, <span class=\"ansi-bright-black-fg\">dt</span>::@NamedTuple<span class=\"ansi-bright-black-fg\">{BirdID::Vector{String7}, Sex::PooledArrays.PooledVector{String7, UInt32, Vector{UInt32}}, Tarsus::Vector{Float64}, Wing::Vector{Float64}}</span>, <span class=\"ansi-bright-black-fg\">hints</span>::Dict<span class=\"ansi-bright-black-fg\">{Symbol, Any}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/StatsModels/OasXV/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">schema.jl:124</span>\n  [7] <span class=\"ansi-bold\">schema</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">ts</span>::Vector<span class=\"ansi-bright-black-fg\">{StatsModels.Term}</span>, <span class=\"ansi-bright-black-fg\">data</span>::DataFrame, <span class=\"ansi-bright-black-fg\">hints</span>::Dict<span class=\"ansi-bright-black-fg\">{Symbol, Any}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/StatsModels/OasXV/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">schema.jl:120</span>\n  [8] <span class=\"ansi-bold\">schema</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">f</span>::StatsModels.FormulaTerm<span class=\"ansi-bright-black-fg\">{StatsModels.Term, StatsModels.Term}</span>, <span class=\"ansi-bright-black-fg\">data</span>::DataFrame, <span class=\"ansi-bright-black-fg\">hints</span>::Dict<span class=\"ansi-bright-black-fg\">{Symbol, Any}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/StatsModels/OasXV/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">schema.jl:128</span>\n  [9] <span class=\"ansi-bold\">schema</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">f</span>::Union<span class=\"ansi-bright-black-fg\">{Tuple{StatsModels.AbstractTerm, Vararg{StatsModels.AbstractTerm}}, StatsModels.AbstractTerm}</span>, <span class=\"ansi-bright-black-fg\">data</span>::Any, <span class=\"ansi-bright-black-fg\">hints</span>::Dict<span class=\"ansi-bright-black-fg\">{Symbol}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-magenta-fg\">StatsModels</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/StatsModels/OasXV/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">schema.jl:131</span><span class=\"ansi-bright-black-fg\"> [inlined]</span>\n [10] <span class=\"ansi-bold\">_design</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">response</span>::Symbol, <span class=\"ansi-bright-black-fg\">rhs</span>::StatsModels.Term, <span class=\"ansi-bright-black-fg\">data</span>::DataFrame<span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_core.jl:356</span>\n [11] <span class=\"ansi-bold\">drm</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">f</span>::DrmFormula, <span class=\"ansi-bright-black-fg\">fam</span>::Gaussian; <span class=\"ansi-bright-black-fg\">data</span>::DataFrame, <span class=\"ansi-bright-black-fg\">K</span>::Nothing, <span class=\"ansi-bright-black-fg\">A</span>::Nothing, <span class=\"ansi-bright-black-fg\">tree</span>::Nothing, <span class=\"ansi-bright-black-fg\">coords</span>::Nothing, <span class=\"ansi-bright-black-fg\">g_tol</span>::Float64, <span class=\"ansi-bright-black-fg\">algorithm</span>::Symbol, <span class=\"ansi-bright-black-fg\">method</span>::Symbol, <span class=\"ansi-bright-black-fg\">profile_ci</span>::Bool, <span class=\"ansi-bright-black-fg\">phylo_coupled</span>::Bool, <span class=\"ansi-bright-black-fg\">penalty</span>::Nothing, <span class=\"ansi-bright-black-fg\">sparse</span>::Nothing, <span class=\"ansi-bright-black-fg\">impute</span>::Nothing, <span class=\"ansi-bright-black-fg\">missing</span>::Nothing<span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">    @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">gaussian_core.jl:473</span>\n [12] top-level scope\n<span class=\"ansi-bright-black-fg\">    @</span> <span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">In[21]:1</span></pre>\n```\n:::\n\n:::\n:::\n\n\n**Itchy:** *(delighted)* It spelled it for you. It looked at your typo, went through your column names, found the closest one, and handed it back. Toto, you have been misspelling things all year and I have never been so pleased about it.\n\n### A second predictor\n\n**Itchy:** Now. Males are bigger. Does that matter?\n\n**Momo:** In the model or in general?\n\n**Itchy:** In the model. In general it matters a great deal to a female sparrow. Add it.\n\n::: {#d9dcde86 .cell execution_count=17}\n``` {.julia .cell-code}\nfit2 = drm(bf(@formula(Wing ~ Tarsus + Sex)), Gaussian(); data = sparrows)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\nDistributional regression fit (Gaussian)\n  nobs = 171   logLik = -301.7781   converged = true\n  Residual SD (response scale) = 1.4132   dof_residual = 167\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z    Pr(>|z|)\n  (Intercept)  57.8218     2.6855  21.5310  7.986e-103\n  Tarsus        1.0116     0.1447   6.9917   2.717e-12\n  Sex: male     2.5012     0.2178  11.4854   1.562e-30\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                Coef.  Std.Error       z   Pr(>|z|)\n  (Intercept)  0.3458     0.0541  6.3958  1.597e-10\n```\n:::\n:::\n\n\n<details class=\"drmtmb\">\n<summary>Same fit in drmTMB, the same engine in R</summary>\n\n```r\n# Run once by hand in R on 2026-09-06 (drmTMB 0.7.0, R 4.6.0) and pasted in;\n# not re-run with the page. The same 171 Lundy Island sparrows, read from\n# data/ch2/sparrows.csv.\n> sp <- read.csv(\"data/ch2/sparrows.csv\")\n> summary(drmTMB(bf(Wing ~ Tarsus + Sex), data = sp))\n<summary.drmTMB>\nestimator: ML\n                   estimate  std_error\nmu:(Intercept)    57.821818 2.68551932\nmu:Tarsus          1.011631 0.14469114\nmu:Sexmale         2.501172 0.21776962\nsigma:(Intercept)  0.345846 0.05407379\nDistributional, random-effect, scale, and correlation parameters:\n                 component  dpar       term estimate std_error    scale\nsigma distributional-scale sigma (constant) 1.413185 0.07641626 response\nlogLik: -301.8\nconvergence: 0\n```\n\n</details>\n\n\n\n**Itchy:** One term added. Same verb, same wrapper, same family. Notice what the engine did without being asked: `Sex` arrived as text, and it worked out that \"female\" comes first alphabetically, made it the baseline, and gave you a coefficient for `male` measured **relative to female**. Males have wings about 2.5 mm longer than females of the same tarsus length.\n\n**Momo:** Tarsus dropped. It was 1.2, now it is 1.01.\n\n**Itchy:** *(pleased)* That is the most important observation anyone has made this morning, and if you take one thing home take this. **The tarsus coefficient did not change because the birds changed. It changed because the question changed.**\n\nIn `fit1` it answered: *pick two sparrows differing by one millimetre of tarsus; how much do their wings differ?* Some of that difference was really about sex, because males have longer tarsi **and** longer wings, so tarsus was quietly carrying sex's luggage.\n\nIn `fit2` it answers: *pick two sparrows of the same sex differing by one millimetre of tarsus.* Sex is now carrying its own bag. The slope is smaller because it is doing less work.\n\n**Toto:** So the first one was wrong?\n\n**Itchy:** No, and I want to be careful here because this is where people get superstitious. The first one was **a different question, correctly answered**. Neither is wrong. But if you are trying to say something about growth, the second is almost certainly the question you meant. A coefficient without the rest of the model attached to it means nothing; that is why you never report one on its own.\n\n::: {#cell-fig-diagnostic .cell execution_count=19}\n``` {.julia .cell-code}\nfig_diagnostic(residuals(fit2; type = :quantile); title = \"fit2 diagnostic\")\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n![The residuals from fit2, plotted against what a normal distribution would predict. Class 3 explains what these residuals are and Class 5 explains how to read this picture; for now, a flat scatter is what you want.](wk2-linear-models_files/figure-html/fig-diagnostic-output-1.svg){#fig-diagnostic}\n:::\n:::\n\n\n### Is the second model better?\n\n**Momo:** Prove it is worth the extra term.\n\n::: {#62d5dc74 .cell execution_count=20}\n``` {.julia .cell-code}\naic(fit1), aic(fit2)\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\n(707.3318715214452, 611.5562817546105)\n```\n:::\n:::\n\n\n::: {#e70a4365 .cell execution_count=21}\n``` {.julia .cell-code}\nlrtest(fit1, fit2)\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```\n(statistic = 97.77558976683474, dof = 1, pvalue = 4.685886499453756e-23)\n```\n:::\n:::\n\n\n\n\n**Itchy:** AIC — the Akaike information criterion, a score that rewards fit and charges for every extra parameter; lower is better — drops by about 96, which is enormous — this is not the polite few-points improvement you learn to shrug at; the likelihood-ratio test, which asks how much more likely the data are under the bigger model than under the smaller, costs one parameter and returns a *p* so small the printer basically gives up on decimal places: 4.7e-23. Both say the same thing, loudly: sex earns its place.\n\nTwo warnings, and they are not decoration. **One:** that test is only legal because `fit1` is *nested* inside `fit2`; you get `fit1` by setting the sex coefficient to zero. Compare two models that are not nested this way and the number you get is nonsense with a *p*-value stapled to it. **Two:** this comparison is honest here because both fits used the same recipe for turning data into numbers, on the same birds. In Class 8 you will meet a situation where two perfectly correct fits use *different* likelihoods and this comparison silently becomes illegal. I am flagging it now so that when I say \"you cannot do that\" in Class 8 you will remember I warned you.\n\n**Momo:** *(typing quietly)* I ran it in R while you were talking. R says my residual standard error is `1.426` — I have the printout here. I exponentiated your 0.3458 and got 1.413.\n\n**Itchy:** *(stops, genuinely happy)* Say that again, louder, so Toto hears it.\n\n**Momo:** Your engine and R disagree.\n\n**Itchy:** Good. Everybody stop typing. This is the best thing that has happened this term.\n\n---\n\n<!-- box: disagree | id: lm-sigma-divisor | ch: 02 | checked: 2026-09-06 -->\n\n::: {.disagree}\n\n**⚠ DISAGREE — the same regression, two residual SDs**\n\nMomo fits the identical model in R with `lm()`. Every slope agrees to five decimal places. The\nresidual spread does not, and neither does the standard error on the slope. Nobody has made a\nmistake.\n\n```r\n# Run once by hand in R on 2026-09-06 (R 4.6.0, stats::lm) and pasted in;\n# not re-run with the page. The same sparrows, from data/ch2/sparrows.csv.\nlm(Wing ~ Tarsus + Sex, data = sparrows)                                # R\n```\n```julia\ndrm(bf(@formula(Wing ~ Tarsus + Sex)), Gaussian(); data = sparrows)     # Julia\n```\n\n| quantity | R `lm()` | DRM.jl `drm` | ratio |\n|---|---|---|---|\n| Tarsus slope | 1.011631 | 1.011631 | 1.000000 |\n| Sex (male) | 2.501172 | 2.501172 | 1.000000 |\n| residual SD | **1.425747** | **1.413185** | **1.008889** |\n| SE of Tarsus slope | **0.145977** | **0.144691** | **1.008889** |\n| log-likelihood | −301.778141 | −301.778141 | 1.000000 |\n| reference distribution | *t* on 168 degrees of freedom | *z* (normal) | |\n\n**The mechanism.** Both fits maximise the same likelihood and land on the same coefficients.\nThey then divide the squared residuals by different numbers. `lm()` divides by **n − p**, where\n*p* counts only the mean coefficients (here\n171 − 3 = 168 —\nnot the 167 in fit2's own header above, which also charges for σ),\nwhich makes the variance estimate — the SD squared — unbiased: its average across repeated samples lands on the true value rather than drifting to one side. Our engine reports the **maximum likelihood** estimate,\nwhich divides by **n** (171). The ratio is therefore exactly\n√(n / (n − p)) = √(171/168) =\n1.008889, which is\nprecisely what you see, to six decimal places, in both the SD and the standard error. It is one\narithmetic choice, not a bug in either package.\n\n::: {#cell-fig-disagree .cell execution_count=23}\n``` {.julia .cell-code}\n# fit2's mu coefficients are [Intercept, Tarsus, Sex:male]; female is the\n# baseline. A smooth grid at Sex = female avoids the zigzag that\n# plotting fitted() at each observation would give once Sex is in the model.\nb = coef(fit2, :mu)\nxs = range(minimum(sparrows.Tarsus), maximum(sparrows.Tarsus); length = 100)\nmu2 = b[1] .+ b[2] .* xs\np_mu = length(b)                                      # 3: intercept, Tarsus, Sex\nsigma_ours = sigma(fit2)[1]                           # ÷n   (DRM.jl, ML)\nsigma_r = sigma_ours * sqrt(nobs(fit2) / (nobs(fit2) - p_mu))  # ÷(n−p) (R lm())\n\nfig = Figure(size = (480, 360))\nax = Axis(fig[1, 1]; xlabel = \"Tarsus (mm)\", ylabel = \"Wing (mm)\",\n    title = \"Same μ, two residual SDs\")\nscatter!(ax, sparrows.Tarsus, sparrows.Wing; markersize = 6, color = (:grey, 0.5))\nband!(ax, xs, mu2 .- sigma_r, mu2 .+ sigma_r; label = \"R lm(): ÷(n−p)\")\nband!(ax, xs, mu2 .- sigma_ours, mu2 .+ sigma_ours; label = \"DRM.jl: ÷n\")\nlines!(ax, xs, mu2; linewidth = 2, color = :black, label = \"fitted μ\")\naxislegend(ax; position = :rt)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n![The same fitted line (females, fit2), two residual-SD divisors: ÷n (ours) vs ÷(n−p) (R's lm()).](wk2-linear-models_files/figure-html/fig-disagree-output-1.svg){#fig-disagree}\n:::\n:::\n\n\n**When it stops mattering.** The gap is √(n/(n − p)), so it shrinks as your sample grows relative\nto the number of things you are estimating: about 0.89%\nhere, and it would fall further still with more birds at the same three parameters — enormous if\nyou ever fit twenty coefficients to thirty birds. It bites hardest exactly where beginners work.\nR also judges each slope against a *t* distribution (slightly wider tails, to allow for having\nestimated the spread) where we use the plain normal; that difference pushes the same way as the\nlarger standard error, not against it, so both make R's *p*-value the larger one — on the Tarsus\nslope, R's own printout gives `Pr(>|t|)` = 8.59e-11 against our\n2.72e-12, on a slope neither package doubts.\n\n**Why this is worth a page in Class 2.** This is the small, tame version of the argument that\ntakes a whole chapter later. Divide by n, or divide by something that accounts for the other\nnumbers you also had to estimate: that same choice, in the models of Class 6 onward — where birds\ncome in families or sites — is the difference between plain maximum likelihood (ML) and restricted\nmaximum likelihood (REML), and there the disagreement is not under one percent on a number you\nnever wanted; it is the spread between groups, the number you came for. Our engine uses ML in both\nlanguages. `lme4`, the usual R package for those models, uses REML. Neither told you. That is Class 8.\n\n<p class=\"provenance\">DRM.jl 0.7.1 (Julia 1.10.0) · R 4.6.0 `stats::lm` and drmTMB 0.7.0 · R numbers\nrun once by hand on 2026-09-06 on the same 171 Lundy Island sparrows and pasted in; the Julia numbers\nare computed with the page</p>\n\n:::\n\n---\n\n**Toto:** So which one is right?\n\n**Itchy:** Both. They answer slightly different questions about the same fit, and if you had not looked you would never have known there was a question. That is what I want you frightened of: not software that disagrees, but software that agrees for reasons you cannot name.\n\n**Momo:** And R prints an R-squared and you do not.\n\n\n\n**Itchy:** It does — R² is the share of the variation in wing that the model accounts for, on a scale from 0 to 1 — and before I give you ours I am going to make you compute it, because the computing is where the lesson is. Your raw wing spread was 2.093, your residual spread is 1.413, so the model has taken out 1 − 1.413²/2.093², which is 0.544. Your R printout says 0.5415. **And no, before you ask, that gap is not the one we just spent ten minutes on.** I got 2.093 from `describe`, which divides by *n* − 1, and 1.413 from the engine, which divides by *n*. I mixed them. R never has to choose, because R² compares two sums of squares and the divisors cancel before they can argue. Put the same divisor on both of mine and you get 0.5415 — R's actual answer. *(Beat.)* Two different divisor mistakes in one morning, and the second one was mine.\n\n**Momo:** And the button?\n\n**Itchy:** Now you may have the button.\n\n::: {#daa44299 .cell execution_count=25}\n``` {.julia .cell-code}\nr2_constant_sigma(fit2)\n```\n\n::: {.cell-output .cell-output-display execution_count=34}\n```\n0.5415360294417806\n```\n:::\n:::\n\n\n**Itchy:** 0.5415, which is R's `lm` R² to every digit R prints. I made you do it the long way first because the long way is where the divisor lives and the button will not teach you that. Two things before we move on. R-squared causes at least as much trouble as it prevents once we get above this rung, and I will show you why in Class 5. And the function is called `r2_constant_sigma` and not `r2`, which is not fussiness. You will find out why in about four minutes.\n\n### One glance up the mountain\n\n**Itchy:** Last thing, and it is a peek, not a lesson. Look at the σ table one more time. It has been sitting there all morning with a single intercept in it, doing nothing.\n\n**Momo:** You are going to put `Sex` in it.\n\n::: {#63e46c18 .cell execution_count=26}\n``` {.julia .cell-code}\nfit3 = drm(bf(@formula(Wing ~ Tarsus + Sex), @formula(sigma ~ Sex)),\n          Gaussian(); data = sparrows)\n```\n\n::: {.cell-output .cell-output-display execution_count=36}\n```\nDistributional regression fit (Gaussian)\n  nobs = 171   logLik = -301.6513   converged = true\n  Residual SD (response scale) varies with the σ model: 1.3757 to 1.4528   dof_residual = 166\n\nMean model (μ):\n  H0: coefficient = 0\n                 Coef.  Std.Error        z    Pr(>|z|)\n  (Intercept)  57.8574     2.6912  21.4985  1.609e-102\n  Tarsus        1.0097     0.1450   6.9630   3.332e-12\n  Sex: male     2.5015     0.2183  11.4614   2.063e-30\n\nScale model (log σ):\n  H0: coefficient = 0 on log σ\n  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion\n                Coef.  Std.Error       z   Pr(>|z|)\n  (Intercept)  0.3190     0.0750  4.2549  2.092e-05\n  Sex: male    0.0545     0.1083  0.5034     0.6147\n```\n:::\n:::\n\n\n::: {#0a5d4874 .cell execution_count=27}\n``` {.julia .cell-code}\nexp.(coef(fit3, :sigma))\n```\n\n::: {.cell-output .cell-output-display execution_count=37}\n```\n2-element Vector{Float64}:\n 1.3757070292392783\n 1.056016793235814\n```\n:::\n:::\n\n\n**Itchy:** By hand, as before, and then look at the header. **Residual SD (response scale) varies with the σ model**, and it prints the range rather than a single number, because with `Sex` in σ there is no single number to print.\n\n::: {#e7d717c3 .cell execution_count=28}\n``` {.julia .cell-code}\naic(fit3)\n```\n\n::: {.cell-output .cell-output-display execution_count=38}\n```\n613.3026370614464\n```\n:::\n:::\n\n\n\n\n\n\n**Itchy:** One extra formula in the same box, and this time I want you to watch me lose the argument. Females vary by about 1.38 mm around their line; males by about 1.45 mm — a little *more*, not less. But look at the AIC: 613.3 against fit2's 611.56. Adding `Sex` to σ made the AIC *worse*, by about 1.75. The third assumption I made you recite at nine o'clock — the one about the width being the same for every bird — is technically false in these data, sex-in-σ is not the story that pays for itself here.\n\n**Toto:** So the whole thing was pointless?\n\n**Itchy:** No — it was the *correct* thing to try, and it just did not survive contact with real sparrows. That is a better lesson than the one I was expecting to teach you. AIC is not a formality you run to confirm what you already believed; it is the referee, and today it overruled me. We added seven characters, asked a real question, and the honest answer was not \"no\" — it was *not detected*, and those are different claims.\n\n**Itchy:** And now the row I promised you this morning. Look at `Sex: male` in the σ table. It has a z of 0.503 and a *p* of 0.61, and the null printed above it is the one that is worth testing: equal dispersion, males and females varying by the same amount. Read the coefficient as a ratio and the claim gets sharper: males vary 1.056× as much as females, 95% interval [0.854, 1.306] — an interval that sits on both sides of 1. And at 171 sparrows, the smallest ratio this sample would have caught four times out of five — that is what \"80% power\" means — is 1.354-fold; ours is nowhere near that. That is not a unit-dependent curiosity like the intercept's σ = 1. That is a question about sparrows, and the honest answer is not disproved, it is not detected: the interval includes 1, and this sample could not have told us about a sex difference smaller than 1.354-fold even if one were sitting right there in the birds. Two referees, arriving from different directions, agreeing.\n\n**Momo:** Then give me the R² for this one and I will go home.\n\n**Itchy:** Try it.\n\n::: {#4dd42d74 .cell execution_count=31}\n``` {.julia .cell-code}\nr2_constant_sigma(fit3)\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>ArgumentError: r2_constant_sigma refuses a MODELLED σ: the `sigma` block carries 1 non-intercept term(s) (Sex: male). The total variance then changes with the covariates, so R² has no single denominator — variance at the mean covariate, averaged over the sample, and at σ's intercept all give different answers. Fit `sigma ~ 1` if you want the ordinary R².\n\nStacktrace:\n [1] <span class=\"ansi-bold\">r2_constant_sigma</span><span class=\"ansi-bold\">(</span><span class=\"ansi-bright-black-fg\">fit</span>::DrmFit<span class=\"ansi-bright-black-fg\">{Gaussian}</span><span class=\"ansi-bold\">)</span>\n<span class=\"ansi-bright-black-fg\">   @</span> <span class=\"ansi-yellow-fg\">DRM</span> <span class=\"ansi-bright-black-fg\">~/.julia/packages/DRM/WUZrp/src/</span><span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">r2.jl:94</span>\n [2] top-level scope\n<span class=\"ansi-bright-black-fg\">   @</span> <span style=\"text-decoration:underline\" class=\"ansi-bright-black-fg\">In[42]:1</span></pre>\n```\n:::\n\n:::\n:::\n\n\n**Toto:** It refused.\n\n**Itchy:** It refused, and read what it says, because it is the best sentence in the package. The total variance now **changes with the covariates** — the predictors, Tarsus and Sex — so R² has no single denominator: males and females have different spreads, so \"the variance of the data\" is several different quantities and the function will not pick one and pretend. That is what the name has been telling you since four minutes ago. `r2_constant_sigma` computes R² where R² means one thing, and declines everywhere else.\n\n**Momo:** So R would have given me a number here.\n\n**Itchy:** R would not have been asked, because `lm` cannot fit this model. Something else in R would give you a number, and you would have to find out for yourself which denominator it picked. One caution, and then we really are done: that refusal is what the function does **today**, not a promise for ever. The package's own documentation marks `r2_constant_sigma` as **experimental**, and is precise about which half is which: the number is settled, and it is the refusals that may widen later. The 0.5415 you got for the last model is not going to move. What the function declines to answer might.\n\n**Momo:** *(packing up)* AIC said no and you are still pleased about it.\n\n**Itchy:** I am. A model that only ever confirms the story you walked in with is not doing any work. Ask me again in Class 4, once there are more sparrows in the room.\n\n**Toto:** Do water fleas have tarsi?\n\n**Itchy:** Toto, water fleas have *carapace length*, and you are going to regress something on it before Thursday. Off you go.\n\n**Toto and Momo leave into the horizontal rain. Itchy stays, rereads the two nulls printed above the σ table, and does not close the laptop for some time.**\n\n---\n\n## Summary\n\n### Stats stuff\n\n- **Linear model.** Three claims, not one: the response is normally distributed around its own mean; that mean is a straight-line function of the predictors; the spread is constant. Only the second is usually tested; today we tested the third for the first time.\n- **μ and σ.** The two halves of every model in this book. μ says where the values sit, σ says how far they scatter. R prints σ as \"Residual standard error\"; we print it as a table because we will later give it predictors.\n- **Intercept.** The fitted mean when every predictor is zero. Often outside the data and therefore not biology. Centre a predictor on its mean and the intercept becomes interpretable.\n- **Slope.** The expected change in the response for a one-unit change in a predictor, **holding the other predictors fixed**. The last clause is why a slope changes when you add a term, and why a coefficient reported without its model is meaningless.\n- **How a text column becomes a number (dummy coding).** A text predictor with two levels becomes one coefficient measured against the alphabetically first level (here, female). More levels means more coefficients, all against the same baseline.\n- **Confidence interval.** The range of parameter values the data are consistent with. Read it before the *p*-value; it is in the units of your organism.\n- **Nested models.** Model A is nested in B if you can get A by fixing some of B's parameters (usually to zero). Likelihood-ratio tests and, in spirit, AIC comparisons require this.\n- **AIC.** Log-likelihood penalised for the number of parameters. Lower is better; differences of a few points are worth attending to, differences below about two are not — and a *worse* AIC after adding a term is a real answer, not a failed attempt.\n- **Maximum likelihood (ML) versus the unbiased variance.** Maximum likelihood divides the squared residuals by *n* (the number of birds); the unbiased version divides by *n − p* (birds minus the number of coefficients). This is the whole of today's disagreement box, and the seed of Class 8, where the same choice is called ML versus REML.\n- **Residual standard deviation as an effect size.** Raw spread versus residual spread tells you whether a model is *useful*, which no *p*-value does — and here it also tells you, honestly, when a fancier model was not worth the extra parameter.\n\n### Julia stuff\n\n- `using DRM, DataFrames, CSV, Statistics`: the four packages this chapter needs.\n- `CSV.read(\"file.csv\", DataFrame)`: read a table. Text columns arrive as `String7` and similar; that is Julia being efficient, not a different type of text.\n- `first(df, 6)`, `describe(df[!, [:a, :b]], :mean, :std, :min, :max)`: look before you model.\n- `@formula(y ~ x)`: the formula. **Required**; `drm` will not accept a formula written any other way.\n- `bf(...)`: the \"big formula\" box. Holds one formula today, several later (`bf(@formula(y ~ x), @formula(sigma ~ z))`). **Required, even when it holds only one.**\n- `drm(bf(...), Gaussian(); data = df)`: the fit. Verb, box, family, data. This exact shape carries every model in the book. Note the family is **positional** and the data is a **keyword**.\n- `coef(fit, :mu)`, `coef(fit, :sigma)`: the coefficients of one sub-model, as a plain vector.\n- `exp(coef(fit, :sigma)[1])`: the residual SD in the units of your response. The fit's header prints the same number as \"Residual SD (response scale)\"; do it by hand once so you know what the header means.\n- `coeftable(fit)`: everything, with 95% intervals. `summary(fit)` gives the same table.\n- `confint(fit)`: the intervals as named tuples, if you want them programmatically.\n- `loglik(fit)`, `aic(fit)`, `bic(fit)`, `nobs(fit)`, `dof_residual(fit)`: the log-likelihood, AIC, BIC (the Bayesian information criterion, AIC's stricter cousin, which charges more for each parameter), the number of birds and the residual degrees of freedom. Note the Julia spellings; there is no `logLik` or `AIC`.\n- `lrtest(fit_small, fit_big)`: likelihood-ratio test for nested models.\n- **Reading a `MethodError`.** Line one is what you asked for; the candidates below are what exists; the argument that was wrong is printed **in red** (the same marker appears as `!Matched` where there is no colour). It is verbose because it is complete.\n- **Reading an `ArgumentError` from a formula.** Misspell a column and the engine suggests the nearest real name. Use it.\n\n**Simulating from a fitted model.** Every model in this book can generate data as easily as it can fit it, and doing so is the fastest way to check you understand what you fitted.\n\n::: {#a3b41d61 .cell execution_count=32}\n``` {.julia .cell-code}\nusing Random, Distributions\n\nrng_sim = MersenneTwister(2012)\nmu_hat = coef(fit1, :mu)[1] .+ coef(fit1, :mu)[2] .* sparrows.Tarsus\nsigma_hat = exp(coef(fit1, :sigma)[1])\nwing_sim = [rand(rng_sim, Normal(m, sigma_hat)) for m in mu_hat]\nsim_df = DataFrame(BirdID = sparrows.BirdID, Sex = sparrows.Sex,\n                    Tarsus = sparrows.Tarsus, Wing = wing_sim)\nfit1_sim = drm(bf(@formula(Wing ~ Tarsus)), Gaussian(); data = sim_df);\n```\n:::\n\n\n::: {#3620467a .cell execution_count=33}\n``` {.julia .cell-code}\ncoef(fit1, :mu)[2], coef(fit1_sim, :mu)[2]\n```\n\n::: {.cell-output .cell-output-display execution_count=45}\n```\n(1.2031120353871703, 1.1875405568706943)\n```\n:::\n:::\n\n\nBy hand, one draw at a time: `rand(Normal(μ̂, σ̂))` for each bird's fitted mean, refit the same\nmodel, and the tarsus slope above wanders from `fit1`'s to a slightly different number — same\ndata-generating process (the same recipe for making wing lengths), different noise, different estimate. That wander *is* sampling\nvariability, made visible instead of assumed.\n\n::: {#4316dff3 .cell execution_count=34}\n``` {.julia .cell-code}\nrng_sim = MersenneTwister(200)   # a seed is a promise: the same draw every time this is run\nsims = simulate(fit1; nsim = 200, rng = rng_sim);\n```\n:::\n\n\n::: {#4255a593 .cell execution_count=35}\n``` {.julia .cell-code}\nmean(std.(eachcol(sims .- fitted(fit1)))), mean(std.(eachcol(sims)))\n```\n\n::: {.cell-output .cell-output-display execution_count=47}\n```\n(1.8703085195848685, 2.0840219108107236)\n```\n:::\n:::\n\n\n`simulate(fit; nsim = n)` (exported — meaning DRM makes it public, so you can call it directly after `using DRM` — `nsim` matching R's own keyword) does the same thing two\nhundred times at once, returning a birds-by-simulations matrix. The trap: each simulated column\nstill carries fit1's fitted mean structure, so its raw spread is close to the *raw* wing spread,\nnot `sigma_hat`. Subtract `fitted(fit1)` from each column first — the first number above, near\n1.88 — and only then does it match the model's own σ; the second number, without the\nsubtraction, does not, and looks like the model cannot reproduce its own residual spread when it\ncan. Appendix A takes this idea further and simulates whole sparrow datasets from a fitted model.\n\n---\n\n## Further reading\n\n*Graded by depth. References checked 2026-09-07.*\n\n1. **Crawley, M. J. (2007) *The R Book*. Wiley, Chichester.** Itchy's own teacher's book, and the reason there was a 2012 sparrow manual at all. Read the linear-models chapter for the sheer density of worked examples; ignore the software, keep the statistics.\n2. **Zuur, A. F., Ieno, E. N. & Elphick, C. S. (2010) \"A protocol for data exploration to avoid common statistical problems\", *Methods in Ecology and Evolution* 1:3–14.** doi:10.1111/j.2041-210X.2009.00001.x. Eight pages on the things you should look at before you fit anything. If you only read one item on this list, read this one; it is the paper version of \"look before you model\".\n3. **Gelman, A. & Hill, J. (2007) *Data Analysis Using Regression and Multilevel/Hierarchical Models*. Cambridge University Press.** Chapters 3 and 4 are the best plain-language account I know of what a regression coefficient means and how badly people misread the intercept. It is also the on-ramp to Class 4.\n4. **Rigby, R. A. & Stasinopoulos, D. M. (2005) \"Generalized additive models for location, scale and shape\", *Journal of the Royal Statistical Society: Series C (Applied Statistics)* 54:507–554.** doi:10.1111/j.1467-9876.2005.00510.x. The paper that made \"put a model on σ too\" a respectable thing to do. Hard, and worth knowing exists; `fit3` at the end of class is a one-line child of this idea.\n5. **DRM.jl documentation, `getting-started` and `capabilities`.** The capability page is unusually honest about what the package cannot do and where its own arithmetic is less exact than it would like. Read the warning boxes; they are the interesting part.\n6. **The StatsModels.jl `@formula` documentation.** Everything the formula grammar can express, including interactions, transformations and how contrasts are chosen. This grammar is shared across the Julia statistics ecosystem, so learning it once pays everywhere.\n\n---\n\n## Exercises\n\nUse your own organism where one is named. **For every question, paste your code and then explain in your own words what each line does**, as if to somebody who has done Class 1 and not Class 2.\n\n1. **Centre the intercept.** Add a column `TarsusC = Tarsus - mean(Tarsus)` and refit `Wing ~ TarsusC`. Which numbers changed and which did not? Write one sentence saying what the new intercept means, in millimetres, about a real sparrow.\n\n2. **Predict a bird.** Using `fit2`, compute by hand (from the coefficients, not with a function) the expected wing length of a male sparrow with a 19.0 mm tarsus. Then compute it for a female with the same tarsus. Explain in one sentence what the difference between your two answers is, and why it does not depend on the tarsus value you chose.\n\n3. **Break it deliberately.** Fit `Wing ~ Sex` alone, then `Wing ~ Tarsus + Sex`. The sex coefficient changes. Explain why, using the same reasoning Itchy used for the tarsus slope. Which of the two numbers would you put in a paper about sexual size dimorphism, and why?\n\n4. **Toto's water fleas.** *(Daphnia)* Regress body length on carapace length. Report the slope with its 95% interval, and the residual SD on the natural scale using `exp`. Then answer: was the predictor worth it? Compare the residual SD to the raw SD of body length and say so in one sentence with numbers in it.\n\n5. **Momo's tadpoles.** Fit a model with a categorical predictor of **three** levels (for example, three ponds). You will get two coefficients, not three. Explain what happened to the third pond, and write down how you would get the mean of each pond from the coefficients you were given.\n\n6. **Eddie's dunnocks.** Fit `Wing ~ Tarsus` and then the same model with `@formula(sigma ~ Tarsus)` added to the `bf`. Report both AICs. Does the spread of dunnock wing lengths change with body size? Write two sentences: one about the statistics, one about the birds.\n\n7. **The disagreement, on your own data.** Fit your model both in Julia with `drm` and in R with `lm`. Confirm the coefficients match and the residual SDs do not. Verify numerically that the ratio equals √(n/(n − p)) for your *n* and *p*. Then answer in one sentence: if a referee asked you to report \"the residual standard deviation\", which of the two would you give them, and would you say which one it was?\n\n8. **Simulate the σ~Sex question yourself.** Simulate 200 new wing-length datasets from `fit2` (constant σ, no `Sex` in the σ formula) with `simulate(fit2; nsim = 200, rng = MersenneTwister(1))`, refit `fit3`'s σ~Sex model to each, and record the AIC difference each time. Where does today's actual AIC difference (fit3 minus fit2) fall in that distribution? Write one sentence about whether today's result looks like ordinary sampling noise or a real signal.\n\n",
    "supporting": [
      "wk2-linear-models_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}