<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 10: not even the groups are strangers – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 10: not even the groups are strangers</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 10</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>Not even the groups are strangers</h1>
    <p class="deck">A one-generation pedigree, a matrix of ones and halves and quarters, and a heritability that lost most of itself the moment somebody put the nest the chick grew up in into the model.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>Every number and figure on this page was produced when the site was built.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Every Julia cell in this chapter was run when the site was built and its output printed.<br>
      <b>Caveat</b> The data are real: 1950 Lundy Island house-sparrow chick records with their sire and dam, of which the 1675 that carry a mass are used here, read from data/2012/SparrowSurvival.csv (provenance in data/2012/README.md). The simulated quantities are drawn from models fitted to that file, from stated seeds, in cells you can read.
    </p>
  </div>
</header>

<div class="wrap">
<blockquote>
<p><strong>What this chapter is not.</strong> It is not a course in quantitative genetics, and it is not the chapter on phylogenetic comparative methods or meta-analysis, which belong together in another book. This is the last rung of version 1’s climb, and it frees one thing: the assumption that random effects are independent <strong>of each other</strong>.</p>
</blockquote>
<hr>
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>Say what a relatedness matrix is, fill it in for a one-generation pedigree, and check a few of its entries by hand.</li>
<li>Fit an animal model with <code>animal(1 | id)</code> and a supplied <code>A</code>, and read the additive genetic variance off the fit.</li>
<li>Compute a narrow-sense heritability as a ratio of variance components, with an interval, and say what the denominator contains.</li>
<li>Name the thing full sibs share that is not genes, fit it, and report what happens to h².</li>
<li>Decide, by simulation rather than by hope, whether your design can tell those two apart at all.</li>
<li>Recognise that a pedigree, a phylogeny and a map of sites are the same model with a different matrix in it.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, 9:00 am. It is the last hard week, so JARO is here, with
coffee and a printed pedigree. TOTO has brought a laptop and a
hypothesis. MOMO has brought the data file. EDDIE has read ahead, and
today it will cost him.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Class 6 said rows are not strangers, and gave every bird its own nudge.
Class 7 let the nudges have slopes. Class 9 let them live inside a coin
flip. Every one of those chapters made the same quiet promise, and today
we break it. Momo, you have the file open. Read me the promise.</p></div>
<div class="line"><span class="who momo">Momo</span><p><code>u_j ~ N(0, σ_u²)</code>, independently for each <em>j</em>.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Independently for each <em>j</em>. Every group drawn fresh, knowing
nothing about any other group. That is a lie about sparrows, about
species and about places, and today we replace it with a matrix.</p></div>
<div id="cell-setup" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Random</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/figures.jl includes tools/theme_itchy.jl itself, so one include does both.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">include</span>(<span class="st">"../tools/figures.jl"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span>, <span class="bu">LinearAlgebra</span>, <span class="bu">Printf</span>, <span class="bu">CairoMakie</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> <span class="bu">Distributions</span>          <span class="co"># qualified: DRM exports its own Poisson, Binomial, …</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set_theme!</span>(<span class="fu">theme_itchy</span>(<span class="op">:</span>light))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/SparrowSurvival.csv"</span>, DataFrame; missingstring <span class="op">=</span> [<span class="st">"NA"</span>, <span class="st">""</span>])</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"rows, columns: "</span>, <span class="fu">size</span>(raw))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="fu">describe</span>(raw, <span class="op">:</span>nmissing, <span class="op">:</span>eltype))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">first</span>(raw, <span class="fl">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows, columns: (1950, 12)
12×3 DataFrame
 Row │ variable         nmissing  eltype                  
     │ Symbol           Int64     Type                    
─────┼────────────────────────────────────────────────────
   1 │ ChickNo                 0  String7
   2 │ Sex                     0  String1
   3 │ Survival               75  Union{Missing, Int64}
   4 │ Mass2                 275  Union{Missing, Float64}
   5 │ BroodSize             135  Union{Missing, Int64}
   6 │ HatchingSuccess        80  Union{Missing, Int64}
   7 │ EggNo                  97  Union{Missing, Int64}
   8 │ JulianDate             74  Union{Missing, Int64}
   9 │ Dad                     0  String7
  10 │ Mum                     0  String7
  11 │ BroodNo                 0  String7
  12 │ Year                    0  Int64</code></pre>
</div>
<div id="setup" class="cell-output cell-output-display" data-execution_count="2">
<div><div style="float: left;"><span>6×12 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">ChickNo</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Survival</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mass2</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">BroodSize</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HatchingSuccess</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">EggNo</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">JulianDate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Dad</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mum</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">BroodNo</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Year</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String7">String7</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String1">String1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, Int64}">Int64?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, Float64}">Float64?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, Int64}">Int64?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, Int64}">Int64?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, Int64}">Int64?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Missing, Int64}">Int64?</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String7">String7</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String7">String7</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String7">String7</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">CC0002</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: left;">TA14526</td>
<td style="text-align: left;">TA14525</td>
<td style="text-align: left;">C001</td>
<td style="text-align: right;">2003</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">CC0005</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">1</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: left;">VX04326</td>
<td style="text-align: left;">VX04473</td>
<td style="text-align: left;">C003</td>
<td style="text-align: right;">2003</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">CC0006</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">1</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: left;">VX04326</td>
<td style="text-align: left;">VX04473</td>
<td style="text-align: left;">C003</td>
<td style="text-align: right;">2003</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">CC0007</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: left;">VX04326</td>
<td style="text-align: left;">VX04473</td>
<td style="text-align: left;">C003</td>
<td style="text-align: right;">2003</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">CC0008</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">1</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: left;">VV78215</td>
<td style="text-align: left;">TA14530</td>
<td style="text-align: left;">C004</td>
<td style="text-align: right;">2003</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">CC0009</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">1</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: right; font-style: italic;">missing</td>
<td style="text-align: left;">VV78215</td>
<td style="text-align: left;">TA14530</td>
<td style="text-align: left;">C004</td>
<td style="text-align: right;">2003</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>There is a <code>Dad</code> column and a <code>Mum</code> column.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>There is, and that is the whole chapter. Every one of these chicks has a
named sire and a named dam, so the file does not merely tell you which
chicks are in a group; it tells you <strong>how much</strong> any two of
them are related. Drop the rows with no mass and count what is left.</p></div>
<div id="cell-clean" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>chicks <span class="op">=</span> <span class="fu">dropmissing</span>(raw, [<span class="op">:</span>Mass2])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>chicks.Cohort <span class="op">=</span> <span class="fu">string</span>.(chicks.Year)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>n       <span class="op">=</span> <span class="fu">nrow</span>(chicks)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>n_sire  <span class="op">=</span> <span class="fu">length</span>(<span class="fu">unique</span>(chicks.Dad))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>n_dam   <span class="op">=</span> <span class="fu">length</span>(<span class="fu">unique</span>(chicks.Mum))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>n_brood <span class="op">=</span> <span class="fu">length</span>(<span class="fu">unique</span>(chicks.BroodNo))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>n_pair  <span class="op">=</span> <span class="fu">nrow</span>(<span class="fu">unique</span>(chicks[!, [<span class="op">:</span>Dad, <span class="op">:</span>Mum]]))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mkpath</span>(<span class="st">"../data/ch10"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>CSV.<span class="fu">write</span>(<span class="st">"../data/ch10/chicks.csv"</span>, chicks)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"chicks with a mass : %d  (of %d rows)</span><span class="sc">\n</span><span class="st">"</span>, n, <span class="fu">nrow</span>(raw))</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sires %d, dams %d, sire-dam pairs %d, broods %d</span><span class="sc">\n</span><span class="st">"</span>, n_sire, n_dam, n_pair, n_brood)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"cohorts            : %s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">join</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(chicks.Year)), <span class="st">", "</span>))</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(chicks[!, [<span class="op">:</span>Mass2]], <span class="op">:</span>mean, <span class="op">:</span>std, <span class="op">:</span>min, <span class="op">:</span>max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>chicks with a mass : 1675  (of 1950 rows)
sires 126, dams 127, sire-dam pairs 208, broods 503
cohorts            : 2003, 2004, 2005, 2006
</code></pre>
</div>
<div id="clean" class="cell-output cell-output-display" data-execution_count="3">
<div><div style="float: left;"><span>1×5 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">std</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">Mass2</td>
<td style="text-align: right;">3.62191</td>
<td style="text-align: right;">1.191</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">9.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>1675 chicks, 126 fathers, 127 mothers. Nobody is missing a parent, which
is rarer than it sounds and is why we are using this file. Toto, what is
the response?</p></div>
<div class="line"><span class="who toto">Toto</span><p><code>Mass2</code>. Chick mass, in grams, at the standard early
weighing.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Chick mass, and the question is the oldest question in the room:
<strong>how much of the difference between one chick and another is
inherited?</strong> Not “is there a difference” — how much. Count the
sibships first, because the answer lives entirely in them.</p></div>
<div id="sibships" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fam <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, [<span class="op">:</span>Dad, <span class="op">:</span>Mum]), nrow <span class="op">=&gt;</span> <span class="op">:</span>k)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort!</span>(fam, <span class="op">:</span>k, rev <span class="op">=</span> <span class="cn">true</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"full-sib families (a sire-dam pair): %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">nrow</span>(fam))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"  largest %d chicks, median %d, %d singletons</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">maximum</span>(fam.k), <span class="fu">round</span>(<span class="dt">Int</span>, <span class="fu">median</span>(fam.k)), <span class="fu">count</span>(<span class="op">==</span>(<span class="fl">1</span>), fam.k))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>sire_mates <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>Dad), <span class="op">:</span>Mum <span class="op">=&gt;</span> (m <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(m))) <span class="op">=&gt;</span> <span class="op">:</span>n)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>dam_mates  <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>Mum), <span class="op">:</span>Dad <span class="op">=&gt;</span> (d <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(d))) <span class="op">=&gt;</span> <span class="op">:</span>n)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sires with more than one mate: %d of %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">count</span>(<span class="fu">&gt;</span>(<span class="fl">1</span>), sire_mates.n), <span class="fu">nrow</span>(sire_mates))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"dams  with more than one mate: %d of %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">count</span>(<span class="fu">&gt;</span>(<span class="fl">1</span>), dam_mates.n),  <span class="fu">nrow</span>(dam_mates))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>full-sib families (a sire-dam pair): 208
  largest 48 chicks, median 5, 12 singletons
sires with more than one mate: 59 of 126
dams  with more than one mate: 55 of 127</code></pre>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>So there are half sibs as well as full sibs.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>There are, and that matters more than the counts suggest. A design with
nothing but full-sib families gives you one number — how alike siblings
are — and asks you to believe that all of it is genetic. Half sibs give
you a second number at a different relatedness, and two numbers at two
relatednesses is the beginning of an argument rather than an assumption.</p></div>
<h3 id="the-matrix-that-says-who-is-related-to-whom" class="anchored">The matrix that says who is related to whom</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Here is the object. It is called the <strong>additive relationship
matrix</strong> and it is written <em>A</em>. One row and one column per
individual. The entry <em>A</em>ᵢⱼ is twice the probability that a gene
drawn at random from <em>i</em> and a gene drawn at random from
<em>j</em> are copies of the same ancestral gene. Jaro, give them the
recursion, because it is one line and it generates everything.</p></div>
<div class="line"><span class="who jaro">Jaro</span><p><em>A</em>ᵢⱼ = ½(<em>A</em>ᵢ,ₛᵢᵣₑ₍ⱼ₎ + <em>A</em>ᵢ,dam₍ⱼ₎), and
<em>A</em>ᵢᵢ = 1 + <em>F</em>ᵢ, with <em>F</em> the <strong>inbreeding
coefficient</strong> — the chance that an individual’s two copies of a
gene are copies of one ancestral gene.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One line, and every number falls out of it once you say what the
founders are. Ours are the parents — the file gives us no parents of
parents — so we assume they are unrelated and not inbred. Toto, turn the
crank for two full sibs.</p></div>
<div class="line"><span class="who toto">Toto</span><p>They have the same sire and the same dam, so it is a half of a half plus
a half of a half.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Which is a half. And two chicks who share a sire only?</p></div>
<div class="line"><span class="who toto">Toto</span><p>A half of a half, plus a half of nothing. A quarter.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p class="aside">(writes on the board)</p></div>
<blockquote>
<p class="scene">With unrelated, non-inbred founders and one generation: A_ij = ¼·1[same
sire] + ¼·1[same dam] for i ≠ j, and A_ii = 1. Full sibs ½, half sibs ¼,
strangers 0.</p>
</blockquote>
<div class="line"><span class="who itchy">Itchy</span><p>That is not an approximation to the recursion, it is the recursion
evaluated. Build it, and then — this is the part nobody does and
everybody should — <strong>check it</strong>.</p></div>
<div id="build-a" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A_ij = 1/4 * [same sire] + 1/4 * [same dam] off the diagonal, 1 on it: the general</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># recursion evaluated for ONE generation with unrelated, non-inbred founders.</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>sire, dam <span class="op">=</span> chicks.Dad, chicks.Mum</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> [i <span class="op">==</span> j ? <span class="fl">1.0</span> <span class="op">:</span> <span class="fl">0.25</span> <span class="op">*</span> (sire[i] <span class="op">==</span> sire[j]) <span class="op">+</span> <span class="fl">0.25</span> <span class="op">*</span> (dam[i] <span class="op">==</span> dam[j])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>     for i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n, j <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n]</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>offdiag <span class="op">=</span> [A[i, j] for i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n for j <span class="kw">in</span> (i <span class="op">+</span> <span class="fl">1</span>)<span class="op">:</span>n]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>n_full  <span class="op">=</span> <span class="fu">count</span>(<span class="op">==</span>(<span class="fl">0.5</span>),  offdiag)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>n_half  <span class="op">=</span> <span class="fu">count</span>(<span class="op">==</span>(<span class="fl">0.25</span>), offdiag)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>n_none  <span class="op">=</span> <span class="fu">count</span>(<span class="op">==</span>(<span class="fl">0.0</span>),  offdiag)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"A is %d x %d, symmetric: %s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">size</span>(A, <span class="fl">1</span>), <span class="fu">size</span>(A, <span class="fl">2</span>), <span class="fu">string</span>(A <span class="op">==</span> A<span class="op">'</span>))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"pairs at 1/2 (full sibs)  : %d</span><span class="sc">\n</span><span class="st">"</span>, n_full)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"pairs at 1/4 (half sibs)  : %d</span><span class="sc">\n</span><span class="st">"</span>, n_half)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"pairs at 0   (unrelated)  : %d</span><span class="sc">\n</span><span class="st">"</span>, n_none)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"distinct off-diagonal values: %s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">string</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(offdiag))))</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"smallest eigenvalue: %.4f  (a legal covariance, i.e. positive definite: %s)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">minimum</span>(<span class="fu">eigvals</span>(<span class="fu">Symmetric</span>(A))), <span class="fu">string</span>(<span class="fu">isposdef</span>(<span class="fu">Symmetric</span>(A))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>A is 1675 x 1675, symmetric: true
pairs at 1/2 (full sibs)  : 11423
pairs at 1/4 (half sibs)  : 9911
pairs at 0   (unrelated)  : 1380641
distinct off-diagonal values: [0.0, 0.25, 0.5]
smallest eigenvalue: 0.5000  (a legal covariance, i.e. positive definite: true)</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Three values and nothing else, which is what the board says there should
be.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Three values and nothing else. The last line checks that the matrix can
be a covariance at all: a covariance may never say some combination of
the chicks has <em>negative</em> variance, and a positive smallest
eigenvalue rules that out. A matrix that is <em>shaped</em> right can
still be <em>indexed</em> wrong, though, and no eigenvalue will tell
you. So check entries against the file, by name.</p></div>
<div id="check-a" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find a chick that has all three kinds of relative in the file, then read A at</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># each pair BY NAME.</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">full_sib</span>(i, j) <span class="op">=</span> j <span class="op">!=</span> i <span class="op">&amp;&amp;</span> sire[j] <span class="op">==</span> sire[i] <span class="op">&amp;&amp;</span> dam[j] <span class="op">==</span> dam[i]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">half_sib</span>(i, j) <span class="op">=</span> j <span class="op">!=</span> i <span class="op">&amp;&amp;</span> (sire[j] <span class="op">==</span> sire[i]) <span class="op">+</span> (dam[j] <span class="op">==</span> dam[i]) <span class="op">==</span> <span class="fl">1</span>   <span class="co"># exactly one parent shared</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stranger</span>(i, j) <span class="op">=</span> sire[j] <span class="op">!=</span> sire[i] <span class="op">&amp;&amp;</span> dam[j] <span class="op">!=</span> dam[i]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>i0 <span class="op">=</span> <span class="fu">findfirst</span>(i <span class="op">-&gt;</span> <span class="fu">any</span>(j <span class="op">-&gt;</span> <span class="fu">full_sib</span>(i, j), <span class="fl">1</span><span class="op">:</span>n) <span class="op">&amp;&amp;</span> <span class="fu">any</span>(j <span class="op">-&gt;</span> <span class="fu">half_sib</span>(i, j), <span class="fl">1</span><span class="op">:</span>n), <span class="fl">1</span><span class="op">:</span>n)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>picks <span class="op">=</span> ((<span class="st">"self"</span>, i0),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>         (<span class="st">"full sib"</span>,  <span class="fu">findfirst</span>(j <span class="op">-&gt;</span> <span class="fu">full_sib</span>(i0, j), <span class="fl">1</span><span class="op">:</span>n)),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>         (<span class="st">"half sib"</span>,  <span class="fu">findfirst</span>(j <span class="op">-&gt;</span> <span class="fu">half_sib</span>(i0, j), <span class="fl">1</span><span class="op">:</span>n)),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>         (<span class="st">"unrelated"</span>, <span class="fu">findfirst</span>(j <span class="op">-&gt;</span> <span class="fu">stranger</span>(i0, j), <span class="fl">1</span><span class="op">:</span>n)))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (label, j) <span class="kw">in</span> picks</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"%-10s %s (sire %s, dam %s) vs %s (sire %s, dam %s) -&gt; A = %.2f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>            label, chicks.ChickNo[i0], sire[i0], dam[i0],</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>            chicks.ChickNo[j], sire[j], dam[j], A[i0, j])</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>self       CC0188 (sire TA14523, dam TA14549) vs CC0188 (sire TA14523, dam TA14549) -&gt; A = 1.00
full sib   CC0188 (sire TA14523, dam TA14549) vs CC0189 (sire TA14523, dam TA14549) -&gt; A = 0.50
half sib   CC0188 (sire TA14523, dam TA14549) vs CC0352 (sire VX04390, dam TA14549) -&gt; A = 0.25
unrelated  CC0188 (sire TA14523, dam TA14549) vs CC0182 (sire VX04364, dam TA14608) -&gt; A = 0.00</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Read the parent codes across each line and satisfy yourself. Same pair
of parents, a half. One parent shared, a quarter. Nothing shared,
nothing. Now look at it.</p></div>
<div id="cell-fig-relatedness" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>busy_sire <span class="op">=</span> <span class="fu">first</span>(<span class="fu">sort</span>(sire_mates, <span class="op">:</span>n, rev <span class="op">=</span> <span class="cn">true</span>).Dad)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>rows_shown <span class="op">=</span> <span class="fu">findall</span>(<span class="op">==</span>(busy_sire), sire)[<span class="fl">1</span><span class="op">:</span><span class="fu">min</span>(<span class="kw">end</span>, <span class="fl">18</span>)]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>Ablock <span class="op">=</span> A[rows_shown, rows_shown]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>codes <span class="op">=</span> chicks.ChickNo[rows_shown]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">560</span>, <span class="fl">480</span>))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"chick"</span>, ylabel <span class="op">=</span> <span class="st">"chick"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"relatedness among </span><span class="sc">$</span>(<span class="fu">length</span>(rows_shown))<span class="st"> chicks of one sire"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    xticks <span class="op">=</span> (<span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(codes), codes), yticks <span class="op">=</span> (<span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(codes), codes),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    xticklabelrotation <span class="op">=</span> <span class="cn">pi</span> <span class="op">/</span> <span class="fl">2</span>, xticklabelsize <span class="op">=</span> <span class="fl">8</span>, yticklabelsize <span class="op">=</span> <span class="fl">8</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    yreversed <span class="op">=</span> <span class="cn">true</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>hm <span class="op">=</span> <span class="fu">heatmap!</span>(ax, <span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(rows_shown), <span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(rows_shown), Ablock<span class="op">'</span>;</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    colorrange <span class="op">=</span> (<span class="fl">0</span>, <span class="fl">1</span>))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">Colorbar</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], hm; label <span class="op">=</span> <span class="st">"A"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div id="fig-relatedness" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-relatedness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk10-relatedness_files/figure-html/fig-relatedness-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-relatedness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Heatmap of the additive relatedness matrix A, restricted to the chicks fathered by one busy sire, coloured from 0 to 1. The bright diagonal is each chick with itself, the blocks off it are full sibs sharing both parents at one-half, and the fainter wash everywhere else is half sibs by a different mother at one-quarter — there is no zero anywhere in this slice, because every chick shown shares the same father.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>Blocks on the diagonal, and a faint wash everywhere else.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The blocks are the offspring of one female by this male — full sibs, one
half. The wash is every other chick he fathered with a
<em>different</em> female — half sibs, one quarter. There is no zero
anywhere, because every chick shown has the same father. That picture
<em>is</em> the covariance the model is about to assume, and if it looks
wrong to you now, it will look wrong in the estimate later and you will
not know why.</p></div>
<h3 id="one-term-and-a-matrix" class="anchored">One term, and a matrix</h3>
<div class="line"><span class="who itchy">Itchy</span><p>The model. It is Class 6’s model with one word changed.</p></div>
<blockquote>
<p class="scene">y = Xβ + a + ε, with a ~ N(0, σ_A² A) and ε ~ N(0, σ² I).</p>
</blockquote>
<div class="line"><span class="who itchy">Itchy</span><p><em>a</em> is the vector of <strong>breeding values</strong>, one per
chick: the part of a chick’s mass that its genes are responsible for,
summed over every locus. In Class 6 the random effect was
<code>N(0, σ_u² I)</code> and the <code>I</code> was invisible because
nobody writes it. Today it is an <code>A</code> and it is the whole
content of the model. σ_A² is the <strong>additive genetic
variance</strong>. Momo, before you see the code, what has actually
changed?</p></div>
<div class="line"><span class="who momo">Momo</span><p>Nothing about the shape. The random effect is still normal, still
centred on zero, still has one variance. Only the levels are now
correlated with each other, by a matrix I supplied rather than anything
the model estimated.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>By a matrix you supplied, which is the sentence to keep. <strong>The
model does not learn who is related to whom; you tell it, and it
estimates one number: how much that relatedness is worth.</strong> In
DRM.jl the term is <code>animal(1 | id)</code> — a
<strong>structured</strong> random effect, one whose levels are
correlated by a matrix you supply — and the matrix arrives as a keyword.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Class 8 spent an hour telling me that variance components want REML. So
I am asking for REML.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You may ask, and the engine will refuse: REML is not implemented for a
structured random effect, so this model is fitted by maximum likelihood
(<a href="appendix-b-engine.html">Where the engine stops</a>). Class 8’s
argument still applies; it is the remedy that is unavailable. A
maximum-likelihood variance component does not pay for the fixed effects
estimated alongside it, so it comes out <strong>too small</strong>, and
Class 8 told you the correction lands on whichever level has
<em>fewer</em> units — not on the residual, where <em>n</em> against
<em>n</em> − <em>p</em> is a factor of 1.003 here and would reassure you
for nothing. Before the hour is out we will measure what ML costs on
this design, in a simulation where the answer is known. Now fit it.</p></div>
<div id="cell-fit-animal" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>naive <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Mass2 <span class="op">~</span> Sex <span class="op">+</span> Cohort <span class="op">+</span> <span class="fu">animal</span>(<span class="fl">1</span> <span class="op">|</span> ChickNo)), <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)),</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">Gaussian</span>(); data <span class="op">=</span> chicks, A <span class="op">=</span> A)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"converged: "</span>, <span class="fu">is_converged</span>(naive))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>naive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>converged: true</code></pre>
</div>
<div id="fit-animal" class="cell-output cell-output-display" data-execution_count="10">
<pre><code>Distributional regression fit (Gaussian)
  nobs = 1675   logLik = -2631.8575   converged = true
  Residual SD (response scale) = 1.0677   dof_residual = 1668

Mean model (μ):
  H0: coefficient = 0
                  Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)    4.0023     0.0962  41.6045          0
  Sex: M        -0.0104     0.0565  -0.1835     0.8544
  Cohort: 2004  -0.3449     0.0995  -3.4682  0.0005239
  Cohort: 2005  -0.4034     0.1004  -4.0160   5.92e-05
  Cohort: 2006  -0.5133     0.1238  -4.1451  3.396e-05

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                Coef.  Std.Error       z  Pr(&gt;|z|)
  (Intercept)  0.0655     0.0273  2.4033   0.01625

Random-effect SD (log σ_b):
  H0: coefficient = 0 on log σ_b
  NOT the σ_b = 0 boundary
             Coef.  Std.Error        z   Pr(&gt;|z|)
  ChickNo  -0.6627     0.1274  -5.2007  1.985e-07</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>There is a <code>resd</code> line with <code>ChickNo</code> on it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is σ_A on the log scale, and Class 6 taught you to read the heading
before the number. Pull the pieces out and make the ratio.</p></div>
<div id="heritability-naive" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sigma_A_naive <span class="op">=</span> <span class="fu">re_sd</span>(naive)[<span class="op">:</span>ChickNo]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>sigma_e_naive <span class="op">=</span> <span class="fu">first</span>(<span class="fu">sigma</span>(naive))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>h2_naive <span class="op">=</span> <span class="fu">heritability</span>(naive)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sigma_A (additive genetic) : %.4f g</span><span class="sc">\n</span><span class="st">"</span>, sigma_A_naive)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sigma   (residual)         : %.4f g</span><span class="sc">\n</span><span class="st">"</span>, sigma_e_naive)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"V_A = %.4f    V_P = V_A + V_R = %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        sigma_A_naive<span class="op">^</span><span class="fl">2</span>, sigma_A_naive<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> sigma_e_naive<span class="op">^</span><span class="fl">2</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"h2 = V_A / V_P      : %.4f</span><span class="sc">\n</span><span class="st">"</span>, h2_naive.estimate)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"bias-corrected      : %.4f   (bias %+.4f, %+.1f%% of the ratio)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        h2_naive.corrected, h2_naive.bias, <span class="fl">100</span> <span class="op">*</span> h2_naive.bias <span class="op">/</span> h2_naive.estimate)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"delta-method SE     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, h2_naive.se)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"95%% CI              : %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>, h2_naive.ci.lower, h2_naive.ci.upper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma_A (additive genetic) : 0.5155 g
sigma   (residual)         : 1.0677 g
V_A = 0.2657    V_P = V_A + V_R = 1.4057

h2 = V_A / V_P      : 0.1890
bias-corrected      : 0.1931   (bias +0.0041, +2.2% of the ratio)
delta-method SE     : 0.0452
95% CI              : 0.1046 to 0.2817</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p><strong>h² = V_A / V_P</strong>, additive genetic variance over
<strong>phenotypic variance</strong> — the total variance in the trait,
additive genetic plus everything else, V_A + V_R printed above — a ratio
of variance components, exactly like Class 6’s repeatability.
“<strong>Narrow-sense</strong>” because only the <em>additive</em> slice
of genetic variance sits in the numerator. Class 6 warned you that a
ratio of estimates is not the estimate of a ratio, and said the
correction would not be tiny here: it is 2% of the estimate, and the
printed interval is centred on the corrected value. Report
<code>corrected</code> and <code>bias</code> beside every ratio. Toto,
say it as a sentence about sparrows.</p></div>
<div class="line"><span class="who toto">Toto</span><p>About 19% of the variation in chick mass is additive genetic, and the
interval runs from 10% to 28%.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>That is a publishable number.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is a publishable number, and it is very probably wrong. Momo has had
her hand up since the matrix went on the board.</p></div>
<h3 id="what-else-do-full-sibs-share" class="anchored">What else do full sibs share</h3>
<div class="line"><span class="who momo">Momo</span><p>They share a nest.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>They share a nest. Say the rest of it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Every entry in that matrix says “these two chicks share half their
genes”. Not one entry says “these two chicks were fed by the same
parents in the same nest on the same days in the same weather”. But that
is also true of them, and it would also make them alike, and the model
has nowhere to put it — so it puts it in σ_A.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is the single most important paragraph in this chapter and Momo
said it, not me. <strong>A relatedness matrix is a hypothesis about why
relatives resemble each other, and it is not the only one.</strong> Full
sibs share genes <em>and</em> a brood. If you fit only the genes, the
brood has nowhere to go, and it goes into the estimate wearing the
genes’ name. Kruuk and Hadfield (2007) is a whole paper on exactly this.</p></div>
<div class="line"><span class="who toto">Toto</span><p>But surely you cannot separate them. Full sibs are in the same nest by
definition.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>In most datasets, that is exactly right, and the honest answer is “this
design cannot tell them apart, so I will not pretend”. In <em>this</em>
file, look what the fieldwork did.</p></div>
<div id="crossing" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>per_brood <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>BroodNo),</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                    <span class="op">:</span>Dad <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>n_sire,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                    <span class="op">:</span>Mum <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>n_dam,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                    nrow <span class="op">=&gt;</span> <span class="op">:</span>k)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>mixed <span class="op">=</span> <span class="fu">count</span>((per_brood.n_sire <span class="op">.&gt;</span> <span class="fl">1</span>) <span class="op">.|</span> (per_brood.n_dam <span class="op">.&gt;</span> <span class="fl">1</span>))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>both  <span class="op">=</span> <span class="fu">count</span>((per_brood.n_sire <span class="op">.&gt;</span> <span class="fl">1</span>) <span class="op">.&amp;</span> (per_brood.n_dam <span class="op">.&gt;</span> <span class="fl">1</span>))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>per_pair <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, [<span class="op">:</span>Dad, <span class="op">:</span>Mum]),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                   <span class="op">:</span>BroodNo <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>n_brood)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>spread <span class="op">=</span> <span class="fu">count</span>(<span class="fu">&gt;</span>(<span class="fl">1</span>), per_pair.n_brood)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods holding chicks of more than one sire-dam pair : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, mixed, n_brood)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"  of those, broods where BOTH sire and dam differ    : %d</span><span class="sc">\n</span><span class="st">"</span>, both)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sire-dam pairs whose chicks appear in &gt;1 brood        : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, spread, n_pair)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"brood sizes present: %s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">string</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(per_brood.k))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>broods holding chicks of more than one sire-dam pair : 195 of 503
  of those, broods where BOTH sire and dam differ    : 195
sire-dam pairs whose chicks appear in &gt;1 brood        : 140 of 208
brood sizes present: [1, 2, 3, 4, 5, 6]</code></pre>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>A brood can contain chicks of two different pairs, and the two chicks
differ in <em>both</em> parents, not just the father.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>In both parents, which is the tell. If this were extra-pair paternity —
and these are house sparrows, so there is plenty of it — the sire would
change and the dam would not, because a female lays her own eggs. Whole
pairs changing means whole chicks were moved between nests. The file
does not say why, and I will not call it a cross-fostering experiment
when the file does not. The consequence is arithmetic, not archaeology:
<strong>140 sire–dam pairs have chicks in more than one brood, and 195
broods hold chicks of more than one pair, so “same parents” and “same
nest” are different partitions of these 1675 chicks.</strong> Two
different partitions can carry two different variance components. One
partition cannot.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So we add the brood.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>We add the brood. It is an ordinary random intercept — no brood is more
related to any other — which is a structured effect whose matrix is the
identity, and beside <code>animal</code> the engine wants it written
that way, as <code>relmat</code> with <code>K = I</code> (<a href="appendix-b-engine.html">Where the engine stops</a>).</p></div>
<div id="cell-fit-both" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>brood_levels <span class="op">=</span> <span class="fu">unique</span>(chicks.BroodNo)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>K_brood <span class="op">=</span> <span class="fu">Matrix</span><span class="dt">{Float64}</span>(I, <span class="fu">length</span>(brood_levels), <span class="fu">length</span>(brood_levels))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>full_model <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Mass2 <span class="op">~</span> Sex <span class="op">+</span> Cohort <span class="op">+</span> <span class="fu">animal</span>(<span class="fl">1</span> <span class="op">|</span> ChickNo) <span class="op">+</span> <span class="fu">relmat</span>(<span class="fl">1</span> <span class="op">|</span> BroodNo)),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                    <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">Gaussian</span>(); data <span class="op">=</span> chicks, A <span class="op">=</span> A, K <span class="op">=</span> K_brood,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                 algorithm <span class="op">=</span> <span class="op">:</span>sparse)     <span class="co"># the same fit, assembled sparsely: minutes become seconds</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"converged: "</span>, <span class="fu">is_converged</span>(full_model))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>full_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>converged: true</code></pre>
</div>
<div id="fit-both" class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Distributional regression fit (Gaussian)
  nobs = 1675   logLik = -2513.5437   converged = true
  Residual SD (response scale) = 0.8844   dof_residual = 1667

Mean model (μ):
  H0: coefficient = 0
                  Coef.  Std.Error        z    Pr(&gt;|z|)
  (Intercept)    4.0246     0.1208  33.3177  2.138e-243
  Sex: M         0.0039     0.0505   0.0778      0.9379
  Cohort: 2004  -0.3550     0.1367  -2.5962    0.009425
  Cohort: 2005  -0.4166     0.1349  -3.0896    0.002005
  Cohort: 2006  -0.5639     0.1621  -3.4785   0.0005043

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -0.1229     0.0282  -4.3564  1.322e-05

Random-effect SD (log σ_b):
  H0: coefficient = 0 on log σ_b
  NOT the σ_b = 0 boundary
             Coef.  Std.Error        z   Pr(&gt;|z|)
  ChickNo  -1.2928     0.3147  -4.1085  3.983e-05
  BroodNo  -0.2949     0.0509  -5.7955  6.812e-09</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p><code>relmat(1 | BroodNo)</code> with an identity matrix is just
<code>(1 | BroodNo)</code>.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is exactly <code>(1 | BroodNo)</code>, written the long way so you
can see the family resemblance. <strong><code>animal</code>,
<code>relmat</code>, <code>phylo</code> and <code>spatial</code> are one
model with four sources for one matrix, and Class 6’s
<code>(1 | g)</code> is the same model with the boring matrix.</strong>
Now the numbers.</p></div>
<div id="partition" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sA <span class="op">=</span> <span class="fu">re_sd</span>(full_model)[<span class="op">:</span>ChickNo]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sB <span class="op">=</span> <span class="fu">re_sd</span>(full_model)[<span class="op">:</span>BroodNo]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sE <span class="op">=</span> <span class="fu">first</span>(<span class="fu">sigma</span>(full_model))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>h2_full    <span class="op">=</span> <span class="fu">heritability</span>(full_model; component <span class="op">=</span> <span class="op">:</span>ChickNo)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>brood_full <span class="op">=</span> <span class="fu">heritability</span>(full_model; component <span class="op">=</span> <span class="op">:</span>BroodNo)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>V_A, V_B, V_R <span class="op">=</span> sA<span class="op">^</span><span class="fl">2</span>, sB<span class="op">^</span><span class="fl">2</span>, sE<span class="op">^</span><span class="fl">2</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>V_P <span class="op">=</span> V_A <span class="op">+</span> V_B <span class="op">+</span> V_R</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-26s %8s %8s</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">""</span>, <span class="st">"SD (g)"</span>, <span class="st">"share"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-26s %8.4f %8.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"additive genetic (A)"</span>, sA, V_A <span class="op">/</span> V_P)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-26s %8.4f %8.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"brood"</span>,                sB, V_B <span class="op">/</span> V_P)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-26s %8.4f %8.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"residual"</span>,             sE, V_R <span class="op">/</span> V_P)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-26s %8.4f %8.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"phenotypic total"</span>,     <span class="fu">sqrt</span>(V_P), <span class="fl">1.0</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"h2 with brood     : %.4f  corrected %.4f (bias %+.1f%%)  SE %.4f  CI %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>        h2_full.estimate, h2_full.corrected, <span class="fl">100</span> <span class="op">*</span> h2_full.bias <span class="op">/</span> h2_full.estimate,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>        h2_full.se, h2_full.ci.lower, h2_full.ci.upper)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"brood share of V_P: %.4f  CI %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>        brood_full.estimate, brood_full.ci.lower, brood_full.ci.upper)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="co"># V_P is CONDITIONAL on the fixed effects: whatever Sex and Cohort explain sits outside it.</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"variance explained by Sex and Cohort : %.4f g^2  (outside V_P)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>        <span class="fu">var</span>(<span class="fu">fitted</span>(full_model)))</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"h2 on a FULL-variance denominator    : %.4f  (against %.4f above)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>        V_A <span class="op">/</span> (V_P <span class="op">+</span> <span class="fu">var</span>(<span class="fu">fitted</span>(full_model))), h2_full.estimate)</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="co"># WHERE the brood variance came from. Not from the genetic block alone.</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>from_A <span class="op">=</span> sigma_A_naive<span class="op">^</span><span class="fl">2</span> <span class="op">-</span> V_A</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>from_R <span class="op">=</span> sigma_e_naive<span class="op">^</span><span class="fl">2</span> <span class="op">-</span> V_R</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"the brood block, %.4f g^2, was taken from</span><span class="sc">\n</span><span class="st">"</span>, V_B)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"  the genetic block : %.4f g^2   (%.1f%% of it)</span><span class="sc">\n</span><span class="st">"</span>, from_A, <span class="fl">100</span> <span class="op">*</span> from_A <span class="op">/</span> V_B)</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"  the residual      : %.4f g^2   (%.1f%% of it)</span><span class="sc">\n</span><span class="st">"</span>, from_R, <span class="fl">100</span> <span class="op">*</span> from_R <span class="op">/</span> V_B)</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a><span class="co"># What each model believes about two full sibs.</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"covariance for a full-sib pair, pedigree-only model      : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fl">0.5</span> <span class="op">*</span> sigma_A_naive<span class="op">^</span><span class="fl">2</span>)</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"two-component model, full sibs in the SAME brood         : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fl">0.5</span> <span class="op">*</span> V_A <span class="op">+</span> V_B)</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"two-component model, full sibs in DIFFERENT broods       : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fl">0.5</span> <span class="op">*</span> V_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             SD (g)    share
additive genetic (A)         0.2745   0.0534
brood                        0.7446   0.3927
residual                     0.8844   0.5539
phenotypic total             1.1882   1.0000

h2 with brood     : 0.0534  corrected 0.0631 (bias +18.2%)  SE 0.0333  CI 0.0000 to 0.1284
brood share of V_P: 0.3927  CI 0.3313 to 0.4463

variance explained by Sex and Cohort : 0.0237 g^2  (outside V_P)
h2 on a FULL-variance denominator    : 0.0525  (against 0.0534 above)

the brood block, 0.5544 g^2, was taken from
  the genetic block : 0.1903 g^2   (34.3% of it)
  the residual      : 0.3580 g^2   (64.6% of it)

covariance for a full-sib pair, pedigree-only model      : 0.1328
two-component model, full sibs in the SAME brood         : 0.5921
two-component model, full sibs in DIFFERENT broods       : 0.0377</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>It went from 0.189 to 0.053.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It lost about 72% of itself, and the brood picked up 39% of the
phenotypic variance — several times what is left over for genes. Eddie,
you said the first number was publishable.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>I did.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is. That is the problem. Nothing about the first fit looked wrong: it
converged, it printed an interval, and the interval was comfortably away
from zero. The only thing wrong with it was a term that was not in it,
and no diagnostic in this book can show you a term that is not in the
model. Draw the two side by side.</p></div>
<div id="cell-fig-partition" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">"genetic (A)"</span>, <span class="st">"brood"</span>, <span class="st">"residual"</span>]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>naive_parts <span class="op">=</span> [sigma_A_naive<span class="op">^</span><span class="fl">2</span>, <span class="fl">0.0</span>, sigma_e_naive<span class="op">^</span><span class="fl">2</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>full_parts  <span class="op">=</span> [V_A, V_B, V_R]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>heights <span class="op">=</span> <span class="fu">vcat</span>(naive_parts, full_parts)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>groups  <span class="op">=</span> <span class="fu">vcat</span>(<span class="fu">fill</span>(<span class="fl">1</span>, <span class="fl">3</span>), <span class="fu">fill</span>(<span class="fl">2</span>, <span class="fl">3</span>))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>stacks  <span class="op">=</span> <span class="fu">vcat</span>(<span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">600</span>, <span class="fl">390</span>))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xticks <span class="op">=</span> (<span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, [<span class="st">"pedigree only"</span>, <span class="st">"pedigree + brood"</span>]),</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    ylabel <span class="op">=</span> <span class="st">"variance (g²)"</span>, title <span class="op">=</span> <span class="st">"where the same variation goes, in two models"</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot!</span>(ax, groups, heights; stack <span class="op">=</span> stacks,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    color <span class="op">=</span> Makie.<span class="fu">wong_colors</span>()[stacks])</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>],</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    [Makie.<span class="fu">PolyElement</span>(color <span class="op">=</span> Makie.<span class="fu">wong_colors</span>()[k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>], labels;</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div id="fig-partition" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk10-relatedness_files/figure-html/fig-partition-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-partition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Stacked bars of the same phenotypic variance split two ways: pedigree-only on the left, pedigree-plus-brood on the right. The two bars stand at nearly the same total height, so the brood block is not new variance — it is variance the pedigree-only model had nowhere to put, drawn mostly from the residual rather than from the genetic block.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The two bars are almost the same height. The genetic block shrank and a
new block appeared in its place.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Almost the same height, because a variance partition is an accounting of
one fixed quantity into named parts. But do not say “in its place”: the
cell measured where the brood block came from, and it is not where you
are looking. Read the two shares.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Only 34% of the brood block came out of the genetic block. 65% of it
came out of the <strong>residual</strong>.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Most of it came out of the residual, and that is this morning’s
two-partitions argument finishing itself. The pedigree-only model has
exactly one number for every full-sib pair — 0.133, half the additive
variance — whether those two chicks shared a nest or not. The
two-component model gives same-brood full sibs 0.592 and different-brood
full sibs 0.038. The first model had to <em>average over that
split</em>, and what would not fit went into the residual, where it sat
looking exactly like noise. So the mixed broods and spread pairs are not
a curiosity about sparrow fieldwork — they are the whole reason the
second model can be fitted at all.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One more word about that denominator, since Objective 3 asks what is in
it. <strong>V_P here is conditional on the fixed effects.</strong>
Whatever Sex and Cohort explain is outside it — 0.0237 g² on this file,
so little that a full-variance denominator gives 0.0525 against 0.0534.
Put in a covariate that explains a third of the variance and it will
matter enormously, and nothing in the output will say so. Which brings
us to the only question that matters.</p></div>
<h3 id="which-of-those-two-numbers-should-you-believe" class="anchored">Which of those two numbers should you believe?</h3>
<div class="line"><span class="who jaro">Jaro</span><p>Neither, until you have shown me the design can tell them apart.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Neither, until we have shown the design can tell them apart, and there
is exactly one way to show that and you have been doing it since Class
2. Compare them properly first, though: both were fitted by maximum
likelihood on the same rows, so they are comparable.</p></div>
<div id="comparison" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A brood effect with NO pedigree at all: Class 6's model, on nests.</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>brood_only <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Mass2 <span class="op">~</span> Sex <span class="op">+</span> Cohort <span class="op">+</span> (<span class="fl">1</span> <span class="op">|</span> BroodNo))), <span class="fu">Gaussian</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fixed_only <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Mass2 <span class="op">~</span> Sex <span class="op">+</span> Cohort)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-26s %10s %10s %6s</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"model"</span>, <span class="st">"logLik"</span>, <span class="st">"AIC"</span>, <span class="st">"dof"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (lab, f) <span class="kw">in</span> ((<span class="st">"fixed effects only"</span>, fixed_only), (<span class="st">"pedigree only (A)"</span>, naive),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                 (<span class="st">"brood only"</span>,         brood_only), (<span class="st">"pedigree + brood"</span>,  full_model))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"%-26s %10.2f %10.2f %6d</span><span class="sc">\n</span><span class="st">"</span>, lab, <span class="fu">loglik</span>(f), <span class="fu">aic</span>(f), <span class="fu">dof</span>(f))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC(A + brood) - AIC(pedigree only) = %.2f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(full_model) <span class="op">-</span> <span class="fu">aic</span>(naive))</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC(A + brood) - AIC(brood only)    = %.2f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(full_model) <span class="op">-</span> <span class="fu">aic</span>(brood_only))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>model                          logLik        AIC    dof
fixed effects only           -2656.20    5324.40      6
pedigree only (A)            -2631.86    5277.71      7
brood only                   -2515.46    5044.93      7
pedigree + brood             -2513.54    5043.09      8

AIC(A + brood) - AIC(pedigree only) = -234.63
AIC(A + brood) - AIC(brood only)    = -1.84</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The model with both is the best of the four.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>By AIC, on these data, yes — and notice how little separates the last
two rows. Before anybody reads a meaning into that gap, say what those
two rows differ by. Eddie.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>One parameter. σ_A.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One parameter, and it is <strong>tested at zero</strong>, which is the
edge of the space a variance lives in. AIC’s two-points-per-parameter
penalty and the usual chi-squared reference are both worked out assuming
the true value sits somewhere in the open middle of its range, and a
variance at zero is on the edge. Class 8 taught the correction and Class
9 used it.</p></div>
<div id="boundary-test" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dropping sigma_A tests a variance component at ZERO: the LR statistic follows a 50:50</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># mixture of a point mass at zero and a chi-squared on 1 df, so the tail p-value is halved.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>bt <span class="op">=</span> <span class="fu">lrt_boundary</span>(full_model, brood_only; q <span class="op">=</span> <span class="fl">1</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"LR statistic for sigma_A = 0, given the brood : %.4f on %d df</span><span class="sc">\n</span><span class="st">"</span>, bt.statistic, bt.q)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"naive chi-squared p-value                     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, bt.pvalue_naive)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"boundary-corrected p-value (Class 8's rule)   : %.4f</span><span class="sc">\n</span><span class="st">"</span>, bt.pvalue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LR statistic for sigma_A = 0, given the brood : 3.8396 on 1 df
naive chi-squared p-value                     : 0.0501
boundary-corrected p-value (Class 8's rule)   : 0.0250</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The naive one is just the wrong side of a twentieth and the corrected
one is comfortably on the other side.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Which is the entire reason the correction exists, and why I will not let
you read a 1.84-point AIC gap as a measurement. Notice what the
corrected <em>p</em>-value does <strong>not</strong> buy you: it says
the additive variance is not zero, not that we know what it is — the
interval ran down to 0.0, which is not a computed bound but the engine
pushing a value that fell below zero back to the edge. Say so when you
report it. Now the residuals, because a variance partition from a model
that does not fit the data is a partition of nothing.</p></div>
<div id="cell-fig-diagnostic" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>qr <span class="op">=</span> <span class="fu">residuals</span>(full_model; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_diagnostic</span>(qr <span class="op">./</span> <span class="fu">std</span>(qr); title <span class="op">=</span> <span class="st">"chick mass, A + brood model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div id="fig-diagnostic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk10-relatedness_files/figure-html/fig-diagnostic-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Worm plot of the A-plus-brood model’s quantile residuals, standardised by their own spread rather than by the residual sigma, because these residuals are marginal — they still carry the breeding values and the brood effects, as Class 6 explained — so the picture reads shape rather than scale. Both ends leave the band upward and the middle sags below it: right skew, from a mass with a hard floor at zero and no ceiling.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Both ends leave the band upwards and the middle sags a little below it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Both ends up and the middle down is a ∪, and a ∪ in a worm plot has one
name: the residuals are <strong>skewed to the right</strong>. A mass has
a hard floor and no ceiling: a chick that weighs nothing is a chick that
is not there, and a well-fed chick can be enormous. A right-skewed
positive response is what a <code>Gamma</code> family is for; this book
does not teach it, and on this file it would change the prediction
intervals a great deal and the variance <em>ratio</em> very little. Not
today. On to Jaro’s question, which we answer the way this book always
answers it: <strong>make data where you know the truth, and see what the
estimator says.</strong></p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One thing first, and you may take it on trust. An animal-model fit takes
the engine about two minutes on this file, and I want fifteen hundred of
them. When every individual has one record there is a shortcut: rotate
the data by the eigenvectors of <em>A</em>, and the model becomes a
search over one number, the heritability. The cell below is that fit —
and because it is the likelihood written out, it can also do the one
thing the engine would not, which is REML.</p></div>
<div id="sim-machinery" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># With A = U diag(lambda) U', the covariance of U'y is diagonal: h2 * lambda_i + (1 - h2),</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># times the total variance. Fixed effects and total variance have closed forms at each h2.</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>E <span class="op">=</span> <span class="fu">eigen</span>(<span class="fu">Symmetric</span>(A))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>lambda, U <span class="op">=</span> E.values, E.vectors</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>Xdes <span class="op">=</span> <span class="fu">hcat</span>(<span class="fu">ones</span>(n), <span class="fu">Float64</span>.(chicks.Sex <span class="op">.==</span> <span class="st">"M"</span>),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>            [<span class="fu">Float64</span>(chicks.Year[i] <span class="op">==</span> y) for i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n, y <span class="kw">in</span> <span class="fu">sort</span>(<span class="fu">unique</span>(chicks.Year))[<span class="fl">2</span><span class="op">:</span><span class="kw">end</span>]])</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>Xrot <span class="op">=</span> U<span class="op">'</span> <span class="op">*</span> Xdes</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>p_fixed <span class="op">=</span> <span class="fu">size</span>(Xrot, <span class="fl">2</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> <span class="fl">0.0</span><span class="op">:</span><span class="fl">0.001</span><span class="op">:</span><span class="fl">0.995</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood at heritability h. `reml = true` divides by n - p instead of n and adds one</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co"># term for the cost of having estimated the fixed effects: that is the whole of REML.</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">profile_ll</span>(yrot, h; reml <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    w  <span class="op">=</span> h <span class="op">.*</span> lambda <span class="op">.+</span> (<span class="fl">1</span> <span class="op">-</span> h)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    XW <span class="op">=</span> Xrot <span class="op">./</span> w</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>    M  <span class="op">=</span> Xrot<span class="op">'</span> <span class="op">*</span> XW</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    b  <span class="op">=</span> M <span class="op">\</span> (XW<span class="op">'</span> <span class="op">*</span> yrot)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    r  <span class="op">=</span> yrot <span class="op">-</span> Xrot <span class="op">*</span> b</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    m  <span class="op">=</span> reml ? n <span class="op">-</span> p_fixed <span class="op">:</span> n</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    s2 <span class="op">=</span> <span class="fu">sum</span>(<span class="fu">abs2</span>.(r) <span class="op">./</span> w) <span class="op">/</span> m</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (m <span class="op">*</span> <span class="fu">log</span>(s2) <span class="op">+</span> <span class="fu">sum</span>(log, w) <span class="op">+</span> m <span class="op">+</span> m <span class="op">*</span> <span class="fu">log</span>(<span class="fl">2</span>π))</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> reml ? ll <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> <span class="fu">logdet</span>(M) <span class="op">:</span> ll</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate: the best grid value. 95% profile interval: every grid value within chi2(1)/2 of it.</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">fit_h2</span>(yrot; reml <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    lls <span class="op">=</span> [<span class="fu">profile_ll</span>(yrot, h; reml <span class="op">=</span> reml) for h <span class="kw">in</span> grid]</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>    inside <span class="op">=</span> lls <span class="op">.&gt;=</span> <span class="fu">maximum</span>(lls) <span class="op">-</span> Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Chisq</span>(<span class="fl">1</span>), <span class="fl">0.95</span>) <span class="op">/</span> <span class="fl">2</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (h2 <span class="op">=</span> grid[<span class="fu">argmax</span>(lls)], lo <span class="op">=</span> grid[<span class="fu">findfirst</span>(inside)], hi <span class="op">=</span> grid[<span class="fu">findlast</span>(inside)])</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>yrot <span class="op">=</span> U<span class="op">'</span> <span class="op">*</span> <span class="fu">Float64</span>.(chicks.Mass2)</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>ml, rml <span class="op">=</span> <span class="fu">fit_h2</span>(yrot), <span class="fu">fit_h2</span>(yrot; reml <span class="op">=</span> <span class="cn">true</span>)</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"h2 by ML   : the engine %.4f, this cell %.3f   (95%% profile interval %.3f to %.3f)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>        h2_naive.estimate, ml.h2, ml.lo, ml.hi)</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"h2 by REML : %.3f   (%+.1f%% of the ML value)</span><span class="sc">\n</span><span class="st">"</span>, rml.h2, <span class="fl">100</span> <span class="op">*</span> (rml.h2 <span class="op">/</span> ml.h2 <span class="op">-</span> <span class="fl">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>h2 by ML   : the engine 0.1890, this cell 0.189   (95% profile interval 0.113 to 0.290)
h2 by REML : 0.194   (+2.6% of the ML value)</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The first line matches the engine. The second is the REML you said we
could not have.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Matching the engine is what earns this cell the right to stand in for
it, and the second line is what REML would have reported: 0.194 where ML
says 0.189. Hold that number; the simulation will tell you whether the
gap is the ML bias or an accident of one dataset. Three worlds, one
estimator: <strong>fit the animal-only model — the model Eddie was ready
to publish — to data whose truth I chose.</strong></p></div>
<div id="recovery" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>L <span class="op">=</span> <span class="fu">cholesky</span>(<span class="fu">Symmetric</span>(A)).L                       <span class="co"># a = sigma_A * L * z has covariance sigma_A^2 A</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>brood_index <span class="op">=</span> <span class="kw">let</span> m <span class="op">=</span> <span class="fu">Dict</span>(b <span class="op">=&gt;</span> k <span class="cf">for</span> (k, b) <span class="kw">in</span> <span class="fu">enumerate</span>(brood_levels))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    [m[b] for b <span class="kw">in</span> chicks.BroodNo]</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>n_rep <span class="op">=</span> <span class="fl">500</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="st">"Draw `n_rep` datasets with the stated truth and refit the ANIMAL-ONLY model to each."</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">recover</span>(sigma_a, sigma_b, sigma_r, rng)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> Xdes <span class="op">\</span> <span class="fu">Float64</span>.(chicks.Mass2)      <span class="co"># any beta will do</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    est <span class="op">=</span> <span class="dt">Float64</span>[]; lo <span class="op">=</span> <span class="dt">Float64</span>[]; hi <span class="op">=</span> <span class="dt">Float64</span>[]</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n_rep</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> sigma_a <span class="op">.*</span> (L <span class="op">*</span> <span class="fu">randn</span>(rng, n))                 <span class="co"># breeding values</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> sigma_b <span class="op">.*</span> <span class="fu">randn</span>(rng, <span class="fu">length</span>(brood_levels))    <span class="co"># brood effects</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> Xdes <span class="op">*</span> beta <span class="op">.+</span> a <span class="op">.+</span> b[brood_index] <span class="op">.+</span> sigma_r <span class="op">.*</span> <span class="fu">randn</span>(rng, n)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>        f <span class="op">=</span> <span class="fu">fit_h2</span>(U<span class="op">'</span> <span class="op">*</span> y)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">push!</span>(est, f.h2); <span class="fu">push!</span>(lo, f.lo); <span class="fu">push!</span>(hi, f.hi)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">end</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (est <span class="op">=</span> est, lo <span class="op">=</span> lo, hi <span class="op">=</span> hi)</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co"># (label, true sigma_A, true sigma_brood, true sigma_residual, generator)</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>worlds <span class="op">=</span> [(<span class="st">"genes only, no brood"</span>, sigma_A_naive, <span class="fl">0.0</span>, sigma_e_naive, <span class="fu">MersenneTwister</span>(<span class="fl">101</span>)),</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"genes and brood"</span>,      sA,            sB,  sE,            <span class="fu">MersenneTwister</span>(<span class="fl">102</span>)),</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"brood only, no genes"</span>, <span class="fl">0.0</span>,           sB,  sE,            <span class="fu">MersenneTwister</span>(<span class="fl">103</span>))]</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> [<span class="fu">recover</span>(w[<span class="fl">2</span>], w[<span class="fl">3</span>], w[<span class="fl">4</span>], w[<span class="fl">5</span>]) for w <span class="kw">in</span> worlds]</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>truths  <span class="op">=</span> [w[<span class="fl">2</span>]<span class="op">^</span><span class="fl">2</span> <span class="op">/</span> (w[<span class="fl">2</span>]<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> w[<span class="fl">3</span>]<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> w[<span class="fl">4</span>]<span class="op">^</span><span class="fl">2</span>) for w <span class="kw">in</span> worlds]</span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-22s %8s %8s %8s %9s %11s</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"world"</span>, <span class="st">"true h2"</span>, <span class="st">"mean"</span>, <span class="st">"SD"</span>, <span class="st">"coverage"</span>, <span class="st">"excludes 0"</span>)</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (w, r, truth) <span class="kw">in</span> <span class="fu">zip</span>(worlds, results, truths)</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>    cover <span class="op">=</span> <span class="fu">count</span>(i <span class="op">-&gt;</span> r.lo[i] <span class="op">&lt;=</span> truth <span class="op">&lt;=</span> r.hi[i], <span class="fl">1</span><span class="op">:</span>n_rep) <span class="op">/</span> n_rep</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>    excl  <span class="op">=</span> <span class="fu">count</span>(<span class="fu">&gt;</span>(<span class="fl">0.0</span>), r.lo) <span class="op">/</span> n_rep</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"%-22s %8.4f %8.4f %8.4f %9.3f %11.3f</span><span class="sc">\n</span><span class="st">"</span>, w[<span class="fl">1</span>], truth, <span class="fu">mean</span>(r.est), <span class="fu">std</span>(r.est), cover, excl)</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>world                   true h2     mean       SD  coverage  excludes 0
genes only, no brood     0.1890   0.1828   0.0408     0.944       1.000
genes and brood          0.0534   0.2134   0.0570     0.036       1.000
brood only, no genes     0.0000   0.1570   0.0501     0.006       0.994</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>In the third world there are no genes at all and it says there are.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>In the third world every chick’s breeding value is exactly zero, the
only thing making siblings alike is the nest they grew up in, and the
animal model — fitted to data with <strong>no additive genetic variance
whatsoever</strong> — returns a mean heritability of 0.157, which is 83%
of the number Eddie was ready to publish, and its interval excludes zero
in 99% of the 500 replicates. Out of a world with no genetics in it at
all.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And the first world?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The first world is the good news, with a bill attached. There the truth
is 0.189 and the interval covers it in a fraction 0.944 of the
replicates, which is what a ninety-five per cent interval is supposed to
do. But the mean estimate sits below the truth by 3.3% of it, and that
is not noise: it is 3.4 Monte Carlo standard errors from zero.
<strong>That is the price of maximum likelihood on this design,
measured</strong>, and it is about the size of the REML-to-ML gap on the
real sparrows, 2.6%. So the sentence for a methods section is:
<em>estimated by maximum likelihood, because REML is not available for a
structured effect in this engine; a simulation from the fitted
animal-only model puts ML’s downward bias at about 3.3% of h².</em> Name
the estimator, and price the limitation. Now draw all three.</p></div>
<div id="cell-fig-recovery" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograms drawn by hand, so the three worlds share the same stated bins.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>edges <span class="op">=</span> <span class="fu">range</span>(<span class="fl">0.0</span>, <span class="fl">0.45</span>, length <span class="op">=</span> <span class="fl">46</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>mids  <span class="op">=</span> (edges[<span class="fl">1</span><span class="op">:</span><span class="kw">end</span><span class="op">-</span><span class="fl">1</span>] <span class="op">.+</span> edges[<span class="fl">2</span><span class="op">:</span><span class="kw">end</span>]) <span class="op">./</span> <span class="fl">2</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">count_in</span>(v) <span class="op">=</span> [<span class="fu">count</span>(x <span class="op">-&gt;</span> edges[b] <span class="op">&lt;=</span> x <span class="op">&lt;</span> edges[b <span class="op">+</span> <span class="fl">1</span>], v) for b <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">length</span>(mids)]</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">620</span>, <span class="fl">400</span>))</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"estimated h² from the animal-only model"</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    ylabel <span class="op">=</span> <span class="st">"replicates"</span>, title <span class="op">=</span> <span class="st">"</span><span class="sc">$</span>(n_rep)<span class="st"> simulated datasets per world, one estimator"</span>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>styles <span class="op">=</span> [<span class="op">:</span>solid, <span class="op">:</span>dash, <span class="op">:</span>dot]</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k, (w, r, truth)) <span class="kw">in</span> <span class="fu">enumerate</span>(<span class="fu">zip</span>(worlds, results, truths))</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    col <span class="op">=</span> Makie.<span class="fu">wong_colors</span>()[k]</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lines!</span>(ax, mids, <span class="fu">Float64</span>.(<span class="fu">count_in</span>(r.est)); color <span class="op">=</span> col, linewidth <span class="op">=</span> <span class="fl">2</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>        linestyle <span class="op">=</span> styles[k], label <span class="op">=</span> w[<span class="fl">1</span>])</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> k <span class="op">==</span> <span class="fl">1</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>        <span class="fu">vlines!</span>(ax, [truth]; color <span class="op">=</span> col, linewidth <span class="op">=</span> <span class="fl">1.5</span>, linestyle <span class="op">=</span> <span class="op">:</span>dashdot, label <span class="op">=</span> <span class="st">"truth"</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">vlines!</span>(ax, [truth]; color <span class="op">=</span> col, linewidth <span class="op">=</span> <span class="fl">1.5</span>, linestyle <span class="op">=</span> <span class="op">:</span>dashdot)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">end</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax, [h2_naive.estimate]; color <span class="op">=</span> <span class="op">:</span>black, linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"real sparrows, h²"</span>)</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div id="fig-recovery" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-recovery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk10-relatedness_files/figure-html/fig-recovery-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-recovery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Histograms of estimated h² from the animal-only model, one per simulated world — no nest effect, a large nest effect, and no heritability at all — each with its truth marked by a dash-dot line in its colour, and the h² the real sparrows gave marked by the solid black line. World 1’s truth is by construction the naive fit’s own estimate, so its dash-dot line sits under the black one. The black line sits inside all three distributions: one variance ratio from one fit cannot tell the worlds apart.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>The dashed lines are the truths — the first world’s sits underneath the
solid black line, because that world was built from the real fit. The
solid black line is the number we actually got from the sparrows. Momo,
look at where it falls.</p></div>
<div class="line"><span class="who momo">Momo</span><p>All three curves are over it. Every one of those worlds could have
produced that number.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Every one of them, and that is Jaro’s question answered. The estimate
from the real sparrows is what you would see if chick mass were 19%
heritable with no nest effect; if it were 5% heritable with a large nest
effect; and with <strong>no heritability whatsoever</strong>.
<strong>One variance ratio from one fit cannot distinguish those three
worlds, and no amount of staring at the fit will make it.</strong> What
distinguishes them is a second variance component, and the model that
has one says brood.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>So the honest report from this file is the second fit: <strong>h² =
0.053, 95% CI 0.0 to 0.128 with the lower bound floored at zero by the
engine, estimated by maximum likelihood with a brood variance in the
model</strong>, and a sentence saying that without the brood term the
same data give 0.189.</p></div>
<div class="line"><span class="who jaro">Jaro</span><p>Is there a design that does better, or is this the human condition?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>There is, and Kruuk and Hadfield name it in their abstract: the animal
model separates genes from shared environment best <em>where pedigrees
contain multiple generations</em>. Ours has <strong>one</strong>. Say
why that matters, Eddie.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>A deep pedigree relates people who never shared a nest. Grandparents.
Cousins. Anything two steps away.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Anything two steps away carries relatedness with <strong>no</strong>
common environment attached, and every such pair is a lever prying the
two apart. The information lives in pairs, so count in pairs.</p></div>
<div id="leverage-pairs" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>brood <span class="op">=</span> chicks.BroodNo</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>n_related <span class="op">=</span> <span class="fu">count</span>(A[i, j] <span class="op">&gt;</span> <span class="fl">0</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n <span class="cf">for</span> j <span class="kw">in</span> (i <span class="op">+</span> <span class="fl">1</span>)<span class="op">:</span>n)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>n_split   <span class="op">=</span> <span class="fu">count</span>(A[i, j] <span class="op">&gt;</span> <span class="fl">0</span> <span class="op">&amp;&amp;</span> brood[i] <span class="op">!=</span> brood[j] <span class="cf">for</span> i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n <span class="cf">for</span> j <span class="kw">in</span> (i <span class="op">+</span> <span class="fl">1</span>)<span class="op">:</span>n)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"related pairs: %d, of which %d (%.1f%%) never shared a brood</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>        n_related, n_split, <span class="fl">100</span> <span class="op">*</span> n_split <span class="op">/</span> n_related)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>related pairs: 21334, of which 19736 (92.5%) never shared a brood</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>92.5% of the related pairs in this file never shared a nest, and that is
why the two components could be separated here. So the rule is not “sib
designs are hopeless”. It is this: <strong>the animal model separates
genes from nest in proportion to how much of your relatedness comes from
pairs who did not share one.</strong> Count that in your own pedigree,
in pairs, before you fit anything.</p></div>
<h3 id="the-ceiling-class-6-gave-you-and-why-it-will-not-help-today" class="anchored">The ceiling Class 6 gave you, and why it will not help today</h3>
<div class="line"><span class="who eddie">Eddie</span><p>Class 6 said repeatability caps heritability. Use that. It is free.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is free and this file will not give it to me: 1675 rows, 1675 chicks,
one weighing each. <strong>A repeatability is the correlation between
two measurements of the same individual, and there is no second
measurement here, so R is not estimable from this file at all.</strong>
Nor will Class 6’s wing repeatability do: the bound h² ≤ R is about one
trait, measured twice, on the same individuals, and a grown sparrow’s
wing says nothing about a two-day-old chick’s mass. Weigh the chicks
twice and you would have an R for chick mass; it would cap today’s h²,
and the <em>gap</em> between the two would be the permanent environment
— which on this file already has a name: the brood. And remember Class
6’s other warning: let maternal and early-life effects enter some
measurements and not others, which is a fair description of a nest, and
even the bound can fail (Dohm 2002).</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>Class 6 promised twice that you would come back to the square root.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>So it did, and it is two sentences. <strong>R caps h² directly, because
both are ratios over the same total variance. R does not cap a
<em>correlation</em>, because a correlation divides by a product of
standard deviations rather than by a variance — so the ceiling there is
the square root, √R,</strong> a much looser cap that is routinely quoted
as though it were the same number. Carry the right bound to the right
problem.</p></div>
<h3 id="four-faces-one-idea" class="anchored">Four faces, one idea</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Last twenty minutes, and it is the reason this is one chapter rather
than four. Everything we did today used <strong>one</strong> property of
<code>A</code>: that it is a known matrix over the levels of a grouping
factor, and a legal covariance. Nothing in the fit knew it was a
pedigree.</p></div>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>marker</th>
<th>what the matrix comes from</th>
<th>keyword</th>
<th>what the variance component means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>animal(1 \| id)</code></td>
<td>a pedigree</td>
<td><code>A =</code></td>
<td>additive genetic variance</td>
</tr>
<tr class="even">
<td><code>relmat(1 \| id)</code></td>
<td>anything you can compute</td>
<td><code>K =</code></td>
<td>whatever your matrix encodes</td>
</tr>
<tr class="odd">
<td><code>phylo(1 \| species)</code></td>
<td>a phylogeny</td>
<td><code>tree =</code></td>
<td>phylogenetic signal</td>
</tr>
<tr class="even">
<td><code>spatial(1 \| site)</code></td>
<td>site coordinates</td>
<td><code>coords =</code></td>
<td>spatial variance, with a range</td>
</tr>
</tbody>
</table>
<div class="line"><span class="who itchy">Itchy</span><p><code>relmat</code> is the general case. <code>phylo</code> and
<code>spatial</code> are conveniences that <em>build</em> the matrix for
you, from a tree or from coordinates; <code>animal</code> builds nothing
today — it names the genetic interpretation and you still hand it
<code>A</code>. Swap a pedigree for a <strong>genomic kinship
matrix</strong> — the same relatedness numbers, read off shared DNA
markers rather than guessed from a family tree — and you have written
the animal model of the last fifteen years. Swap it for a phylogenetic
correlation and “heritability” is called phylogenetic signal, and the
arithmetic does not change. Swap it for <code>exp(-d/ρ)</code> over site
coordinates and nearby sites are correlated — and there the model
estimates the range ρ as well, because nobody hands you the correlation.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Can we fit one?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Not today, and the reason is the whole ethic of this book. <strong>There
is no phylogeny in this repository and there are no site
coordinates.</strong> I could invent a tree in four lines and show you a
fit, and the number would be a number about my four lines. The call
sites are in the table, the tutorials are in the further reading, and
the first time you fit one it should be on your own tree.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>And phylogenetic comparative methods proper? Meta-analysis?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Both are today’s problem — non-independence from a shared history, or
from shared effect sizes — and both need a book rather than an
afternoon. They are not in this one, deliberately.</p></div>
<blockquote>
<p class="scene">↔︎ TRANSLATE: R will build the matrix for you, and Julia will not</p>
<p>In DRM.jl the matrix is a keyword on <code>drm</code>, <code>animal(1 | id)</code> with <code>A = A</code>, and building it is your job — which is why this chapter spent a page doing it in the open. In <code>drmTMB</code> it goes inside the marker, <code>animal(1 | id, A = A)</code>, or the package walks a three-column pedigree of <code>id</code>, <code>dam</code>, <code>sire</code> into <code>A</code> itself: <code>animal(1 | id, pedigree = ped)</code>. A matrix a package built for you is one you should still check, three entries by name, exactly as above.</p>
</blockquote>
<div class="line"><span class="who toto">Toto</span><p>So today’s summary is: tell the model who is related to whom.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Tell the model who is related to whom, and then be extremely careful
about what <em>else</em> is true of the people you just told it about.
The matrix is a hypothesis. Test it like one.</p></div>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>The last constant, freed.</strong> Classes 6, 7 and 9 let groups differ but drew every group’s effect independently, <code>u ~ N(0, σ_u² I)</code>. A structured random effect replaces the <code>I</code> with a <strong>known</strong> matrix: <code>a ~ N(0, σ_A² A)</code>. You supply the matrix; the model estimates one scalar, how much that structure is worth.</li>
<li><strong>The additive relationship matrix.</strong> <em>A</em>ᵢⱼ = ½(<em>A</em>ᵢ,ₛᵢᵣₑ₍ⱼ₎ + <em>A</em>ᵢ,dam₍ⱼ₎), <em>A</em>ᵢᵢ = 1 + <em>F</em>ᵢ. With unrelated non-inbred founders and one generation this collapses to ¼ per shared parent: full sibs ½, half sibs ¼. Build it in a cell and check named entries against the file — a matrix can be the right <em>shape</em> and still be indexed wrongly.</li>
<li><strong>The animal model.</strong> <code>y = Xβ + a + ε</code>, <code>a ~ N(0, σ_A² A)</code>. <strong>h² = V_A / V_P</strong> is a ratio of variance components, exactly like Class 6’s repeatability, and V_P is <strong>conditional on the fixed effects</strong>: whatever your covariates explain is outside it. Negligible on this file, decisive on one where the covariates matter.</li>
<li><strong>The confound that eats heritabilities.</strong> A relatedness matrix says relatives share genes, not that they shared a nest, a mother’s condition, a territory or a year. Anything else that makes relatives alike, and is not in the model, is absorbed by σ_A and reported as heritability (Kruuk &amp; Hadfield 2007). Fitting the brood here cut h² by about 72%, and 65% of the brood variance came out of the <strong>residual</strong>, where the difference between same-brood and different-brood full sibs had been hiding.</li>
<li><strong>Whether you can separate them is a property of the design, not of the software.</strong> If every set of full sibs is one brood, “same parents” and “same nest” are the same partition and no modelling will split them. Cross-fostering, or a <strong>deep</strong> pedigree in which relatives two steps apart never shared an environment, is what makes the two components estimable. Count the related pairs that never shared a group in your own file before you fit.</li>
<li><strong>A simulation answers the question a fit cannot.</strong> Data simulated with <em>no</em> additive genetic variance, in which siblings resemble each other only because they shared a nest, gave a mean heritability of 0.157 from the animal-only model, with an interval excluding zero almost every time. The estimator is not broken; the design is confounded, and only a simulation with a known truth tells you which of those you are looking at.</li>
<li><strong>The Class 6 ceiling needs the same trait, twice.</strong> h² ≤ R holds for one trait measured repeatedly on the same individuals; this file has one weighing per chick, so R is not estimable here, and a repeatability of another trait caps nothing. A <strong>correlation</strong> with a trait of repeatability R is capped by √R, not by R. The gap between R and h² is the permanent environment — here, the brood. Let maternal and early-life effects enter some measurements and not others, and even the bound can fail (Dohm 2002).</li>
<li><strong>Maximum likelihood, because REML is not on offer here — and its price, measured.</strong> A simulation from the fitted animal-only model puts ML’s downward bias on h² at about 3.3%; REML computed from the same likelihood by hand moves the real-data estimate from 0.189 to 0.194. Name the estimator, and price the limitation.</li>
<li><strong>A variance component tested at zero is a boundary test.</strong> Dropping σ_A from the two-component model gives a likelihood-ratio statistic of 3.84 on 1 degree of freedom: <em>p</em> = 0.0501 against an ordinary chi-squared table, <em>p</em> = 0.025 against the halved reference Class 8 taught (Self &amp; Liang 1987; Stram &amp; Lee 1994). The reading flips on the correction.</li>
<li><strong>A ratio of estimates is not the estimate of a ratio.</strong> <code>heritability</code> returns <code>estimate</code>, <code>bias</code> and <code>corrected</code>; on the two-component fit the correction is 18% of the headline number, as Class 6 forecast. Report <code>corrected</code> and <code>bias</code>. A bound of exactly 0 or 1 is the engine pushing a value that fell outside back to the edge; say so when you report it.</li>
<li><strong>Four faces, one model.</strong> <code>animal</code> (pedigree), <code>relmat</code> (any matrix), <code>phylo</code> (a tree), <code>spatial</code> (coordinates): four sources for one matrix. <code>spatial</code> additionally estimates a range, because nobody hands you the correlation between two places.</li>
</ul>
<h3 id="julia-stuff" class="anchored">Julia stuff</h3>
<ul>
<li><code>animal(1 | id)</code> in the mean formula, with <code>A = A</code> as a keyword to <code>drm</code>: the animal model. <code>relmat(1 | id)</code> with <code>K = K</code> is the same term with a matrix you name yourself.</li>
<li><strong>The matrix is indexed by the levels of the grouping factor in the order they first appear in the data.</strong> Get that ordering wrong and you will fit a well-conditioned model of nothing. Build the matrix from the same column you group on, in one cell, and it cannot drift.</li>
<li><code>heritability(fit)</code> and <code>repeatability(fit)</code>: the two ratios, each returning <code>estimate</code>, <code>bias</code>, <code>corrected</code>, <code>se</code> and <code>ci</code>. With more than one structured component, pass <code>component = :name</code> — <code>heritability</code> divides by <em>all</em> the components plus the residual, <code>repeatability</code> by the chosen component plus the residual only.</li>
<li><code>lrt_boundary(full, reduced; q = 1)</code>: the boundary-corrected likelihood-ratio test for a variance component at zero. Both fits must be ML on the same rows.</li>
<li><code>residuals(fit; type = :quantile)</code>: Class 5’s quantile residuals, available on a structured fit like any other.</li>
<li><code>cholesky(Symmetric(A)).L</code>: how you <em>draw</em> a correlated random effect. <code>σ_A * L * randn(rng, n)</code> has covariance σ_A² A.</li>
<li><strong>The simulation thread.</strong> Every chapter ends by asking the fit to invent data; here the cell is a reminder.</li>
</ul>
<div id="simulate-refit" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20261007</span>)     <span class="co"># a seed is a promise: the same draw every time the site is built</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>ysim <span class="op">=</span> <span class="fu">simulate</span>(full_model; nsim <span class="op">=</span> <span class="fl">50</span>, rng <span class="op">=</span> rng_sim)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>dev <span class="op">=</span> ysim <span class="op">.-</span> <span class="fu">fitted</span>(full_model)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"observed SD about the fixed part  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(chicks.Mass2 <span class="op">.-</span> <span class="fu">fitted</span>(full_model)))</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"simulated SD about the fixed part : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(<span class="fu">std</span>(dev[<span class="op">:</span>, k]) <span class="cf">for</span> k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(dev, <span class="fl">2</span>)))</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"residual sigma alone              : %.4f</span><span class="sc">\n</span><span class="st">"</span>, sE)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sqrt(V_A + V_B + V_R)             : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">sqrt</span>(V_P))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>observed SD about the fixed part  : 1.1820
simulated SD about the fixed part : 0.8857
residual sigma alone              : 0.8844
sqrt(V_A + V_B + V_R)             : 1.1882</code></pre>
</div>
</div>
<p>The simulated spread is the residual σ, not the phenotypic total: <code>simulate</code> draws with every random effect at zero, as Class 6 found, which is why the recovery study drew the breeding values itself.</p>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. Details checked on 2026-09-07 against OpenAlex, an open
catalogue of papers.</p>
<ol type="1">
<li><strong>Wilson, A. J., Réale, D., Clements, M. N., Morrissey, M. M., Postma, E., Walling, C. A., Kruuk, L. E. B. &amp; Nussey, D. H. (2010) “An ecologist’s guide to the animal model”, <em>Journal of Animal Ecology</em> 79:13–26.</strong> doi:10.1111/j.1365-2656.2009.01639.x (online 2009). The one to read first: three worked tutorials for ecologists, ending in a list of the pitfalls.</li>
<li><strong>Kruuk, L. E. B. (2004) “Estimating genetic parameters in natural populations using the ‘animal model’”, <em>Philosophical Transactions of the Royal Society B</em> 359:873–890.</strong> doi:10.1098/rstb.2003.1437. The paper that made animal models standard in wild-population ecology, and the one that describes the literature as <strong>restricted</strong> maximum-likelihood animal models — which is why this chapter had to price the ML fit it was given.</li>
<li><strong>Kruuk, L. E. B. &amp; Hadfield, J. D. (2007) “How to separate genetic and environmental causes of similarity between relatives”, <em>Journal of Evolutionary Biology</em> 20:1890–1903.</strong> doi:10.1111/j.1420-9101.2007.01377.x. The whole paper is today’s confound. Read it before you report a heritability from a design where full sibs share a nest, and read it twice if your design has no cross-fostering in it.</li>
<li><strong>Dohm, M. R. (2002) “Repeatability estimates do not always set an upper limit to heritability”, <em>Functional Ecology</em> 16:273–280.</strong> doi:10.1046/j.1365-2435.2002.00621.x. Class 6’s counterweight: its abstract lists the conditions under which the free bound fails, and the one that matters on this page is <strong>maternal effects</strong> — in this chapter’s data, precisely the brood.</li>
<li><strong>Lynch, M. &amp; Walsh, B. (1998) <em>Genetics and Analysis of Quantitative Traits</em>. Sinauer.</strong> The reference work: chapters 7 and 26–27 for the relationship matrix and the mixed-model machinery. A thousand pages you look things up in for the rest of your career.</li>
<li><strong>DRM.jl’s tutorials <code>animal-models.md</code>, <code>relmat-known-matrices.md</code>, <code>phylogenetic-models.md</code> and <code>spatial-models.md</code>.</strong> The four faces, each with a status note saying which families and structures are implemented today. Read the status note before you plan an analysis around a call.</li>
<li><strong>Self, S. G. &amp; Liang, K.-Y. (1987) “Asymptotic properties of maximum likelihood estimators and likelihood ratio tests under nonstandard conditions”, <em>Journal of the American Statistical Association</em> 82(398):605–610.</strong> doi:10.1080/01621459.1987.10478472. <strong>Stram, D. O. &amp; Lee, J. W. (1994) “Variance components testing in the longitudinal mixed effects model”, <em>Biometrics</em> 50(4):1171.</strong> doi:10.2307/2533455. <strong>Patterson, H. D. &amp; Thompson, R. (1971) “Recovery of inter-block information when block sizes are unequal”, <em>Biometrika</em> 58(3):545–554.</strong> doi:10.1093/biomet/58.3.545. Self and Liang for the halved <em>p</em>-value behind <code>lrt_boundary</code>, Stram and Lee for the same rule in a mixed model, and Patterson and Thompson for REML itself — the two lines the simulation cell adds by hand.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Use your own organism where one is named. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Class 6 and not Class 10.</p>
<ol type="1">
<li><p><strong>Build a matrix and check it.</strong> Take any dataset with a grouping factor and invent a relatedness rule you can defend — clonal lines, family blocks, or a pedigree. Build the matrix, print the distinct off-diagonal values, check three entries by name against the raw file, and print its smallest eigenvalue. Then say what your matrix claims about your organism, and whether the eigenvalue check could ever have failed given how you built it.</p></li>
<li><p><strong>Find the confound.</strong> Name one thing, other than genes, that makes relatives in your dataset resemble each other. Decide whether your design can separate it from relatedness — count the related pairs that never shared it — and then either fit it and report what happened to h², or state in two sentences that you cannot, and what would have to change in the fieldwork.</p></li>
<li><p><strong>The third world.</strong> Simulate from your own design with the genetic variance set to <strong>exactly zero</strong> and the confounding effect set to something plausible. Fit the animal-only model to each replicate. Report the mean estimated h² and the proportion of replicates whose interval excludes zero, and state the number of replicates.</p></li>
<li><p><strong>Toto’s water fleas.</strong> <em>(Daphnia)</em> Clonal lines make the relatedness matrix trivial: members of a line are genetically identical, so their entry is 1 and everyone else’s is 0. Write that matrix down, then explain in two sentences why the resulting ratio is a <strong>broad</strong>-sense heritability and not the narrow-sense one this chapter estimated.</p></li>
<li><p><strong>The ceiling, if you can have it.</strong> If your organism can be measured twice, compute the repeatability of your trait as in Class 6 and state the bound on h², and separately the √R bound on any correlation you plan to report. If it cannot, write the paragraph for your discussion explaining why no bound is available and what a second measurement would have bought you.</p></li>
<li><p><strong>Order matters.</strong> Deliberately shuffle the rows of your relatedness matrix without shuffling the data, refit, and report what happens to σ_A and h². Then write one sentence explaining why nothing in the output warned you.</p></li>
<li><p><strong>The other three faces.</strong> Pick whichever of <code>phylo</code>, <code>spatial</code> or <code>relmat</code> is closest to your own work, find or build a real matrix — a published tree, your own site coordinates, a genomic kinship matrix — and fit it. Report the variance component and the ratio, and say what “heritability” is called in your field when the matrix is that one.</p></li>
</ol>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk9-glmms.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 9 · Both at once</span></a><a class="chapter-nav-link next" href="appendix-a-simulation.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Appendix A · Simulation as a way of thinking</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 10 of a planned 13, ten in v1, plus a coda · draft, all code run, 2026-09-12<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>