<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Where you go next – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Where you go next</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Coda</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>Where you go next</h1>
    <p class="deck">A coda, not a rung: no new constant is freed here. One figure below refits a model Class 2 already ran, to show what rung eleven means; the rest is prose, and the constants still waiting are one level up, two of them with chapter numbers already.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>Draft. All ten classes of version 1, Appendix A, the preface and the coda are written and their code runs. This page fits one model, in one code cell, to draw its one figure — the same location-scale model Class 2 fitted, refitted here on the same archived sparrows — and otherwise runs no code and prints no other numbers. The prose is still being revised.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 4d9248f88 (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> This page fits one model, once, in one Julia cell: the location-scale model Class 2 already fitted (Wing ~ Tarsus + Sex, with Sex in σ), refitted here on the same 171 archived Lundy Island sparrows so the rung-eleven figure and the numbers beside it come from this page’s own run. It makes no claim about a model that a chapter of this book has not already fitted. The three references in Further reading were checked on 2026-09-07 against OpenAlex, an open catalogue of research papers.<br>
      <b>Caveat</b> The two rungs described here as version two are an outline, not written chapters; the plan for the whole climb is linked from <a href="../index.html">the landing page</a>. The two engine limitations mentioned below are known and have been reported to the engine’s authors; they may have been fixed by the time you read this, so check the engine’s own page for their current state.
    </p>
  </div>
</header>

<div class="wrap">
<p>This is a coda, not a rung. Every other page in this book freed something the page before it held fixed; this one frees no new constant — the one model behind its one figure is a model Class 2 already fitted. It is here because the climb has a shape, and the shape does not stop where the book does.</p>
<p>What you have been doing for ten chapters is taking a constant out of a model and letting the data have an opinion about it. The noise had one shape; you let the family choose it. The spread was a fixed function of the mean; you let a predictor into it. Rows were strangers; they stopped being strangers. Slopes were shared; they stopped being shared. Groups were independent of one another; you handed the model a matrix saying how they are related.</p>
<p>There are more constants. You have been looking at four of them all book without being told.</p>
<hr>
<h2 id="the-same-constants-reappear" class="anchored">The same constants reappear</h2>
<p><strong>σ — the spread of the noise — held at one number.</strong> In Class 4 you moved the spread — but you moved it to <em>repair</em> something: the family had lied about how much scatter a given mean allows, and letting σ depend on a predictor was the fix. The next rung asks the question the other way round. Suppose the spread is what you actually care about. Suppose the interesting biology is that one group is more variable than another, at the same mean; that a treatment does not shift the average and does tighten the distribution; that predictability is the trait. Then σ is not a nuisance to be repaired, it is the estimand — the quantity you set out to estimate — and it gets a linear predictor (a right-hand side of its own, the sum of predictor effects that every model in this book has had for the mean), standard errors and an interval of its own, exactly as the mean does. That is <strong>rung eleven, modelling the spread itself</strong>, and the family of models it belongs to has been in the literature for two decades under the name location–scale — location is the mean, scale is the spread, and both get a model (Rigby &amp; Stasinopoulos 2005). You already know how to read its output: you have been reading a <code>mu</code> block and a <code>sigma</code> block side by side since Class 4.</p>
<p>Rung eleven is not hypothetical in this book. Class 2 already fit exactly this model on exactly this question, and showed the σ side of it only as a peek. Fit it again here, on the same 171 archived Lundy Island sparrows, so what follows comes from this page’s own run and not from a memory of Class 2’s.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>fit_mu <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows);</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>fit_ls <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex), <span class="pp">@formula</span>(sigma <span class="op">~</span> Sex)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows);</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>.(<span class="fu">coef</span>(fit_ls, <span class="op">:</span>sigma))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>2-element Vector{Float64}:
 1.3757070292392783
 1.056016793235814</code></pre>
</div>
</div>
<p>Females vary by about 1.38 mm around their line; males by about 1.45 mm — a little more, not less, the same finding Class 2 reported. Adding <code>Sex</code> to σ moves the AIC by 1.75 against the mean-only model — it does not pay for itself — and the male:female ratio of spread comes out at 1.056, 95% interval [0.854, 1.306], an interval that still sits on both sides of 1. Refit on the same birds, the verdict has not moved: not disproved, not detected.</p>
<div id="cell-fig-coda-location-scale" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>zspread <span class="op">=</span> <span class="fl">4</span> <span class="op">*</span> <span class="fu">max</span>(sigma_ls[<span class="fl">1</span>], sigma_ls[<span class="fl">1</span>] <span class="op">*</span> sigma_ls[<span class="fl">2</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>zgrid   <span class="op">=</span> <span class="fu">range</span>(coda_center <span class="op">-</span> zspread, coda_center <span class="op">+</span> zspread, length <span class="op">=</span> <span class="fl">400</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>dens_f  <span class="op">=</span> Distributions.<span class="fu">pdf</span>.(Distributions.<span class="fu">Normal</span>(coda_center, sigma_ls[<span class="fl">1</span>]), zgrid)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dens_m  <span class="op">=</span> Distributions.<span class="fu">pdf</span>.(Distributions.<span class="fu">Normal</span>(coda_center, sigma_ls[<span class="fl">1</span>] <span class="op">*</span> sigma_ls[<span class="fl">2</span>]), zgrid)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">760</span>, <span class="fl">420</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"wing length (mm)"</span>, ylabel <span class="op">=</span> <span class="st">"density"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    xticks <span class="op">=</span> <span class="fu">WilkinsonTicks</span>(<span class="fl">4</span>), title <span class="op">=</span> <span class="st">"same mean, different spread"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax1, [coda_center]; color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.6</span>), linestyle <span class="op">=</span> <span class="op">:</span>dash,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"same mean, by construction"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax1, zgrid, dens_f; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"female (σ ≈ </span><span class="sc">$</span>(coda_sigma_f)<span class="st"> mm)"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax1, zgrid, dens_m; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"male (σ ≈ </span><span class="sc">$</span>(coda_sigma_m)<span class="st"> mm)"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>]; xticks <span class="op">=</span> ([<span class="fl">1</span>], [<span class="st">"male : female"</span>]), ylabel <span class="op">=</span> <span class="st">"residual-SD ratio"</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"the ratio"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="fu">xlims!</span>(ax2, <span class="fl">0.5</span>, <span class="fl">1.5</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">hlines!</span>(ax2, [<span class="fl">1.0</span>]; linestyle <span class="op">=</span> <span class="op">:</span>dash, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.6</span>))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="fu">rangebars!</span>(ax2, [<span class="fl">1</span>], [coda_lo], [coda_hi]; whiskerwidth <span class="op">=</span> <span class="fl">14</span>, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">1</span>))</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax2, [<span class="fl">1</span>], [coda_ratio]; markersize <span class="op">=</span> <span class="fl">16</span>, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">1</span>))</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># legend outside both axes, below, so it can never hide a group or crowd either</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># panel (reviewer: pond P05 sat under it)</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">2</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">2</span>], ax1; framevisible <span class="op">=</span> <span class="cn">false</span>, orientation <span class="op">=</span> <span class="op">:</span>horizontal)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div id="fig-coda-location-scale" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-coda-location-scale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk13-coda_files/figure-html/fig-coda-location-scale-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coda-location-scale-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Rung eleven, drawn from a real fit rather than described: the location-scale model Class 2 fitted (Wing ~ Tarsus + Sex, with Sex in σ), refitted on this page on the same 171 archived Lundy Island sparrows. Left: each sex’s fitted residual spread around the line, as Normal curves centred on the same value — the model’s own fitted mean wing length for a female at the sample’s mean tarsus — by construction, so only spread differs in this panel; the real fitted means do differ by sex (males have longer wings on average, carried by the μ side of the model, not shown here), which is a different, separate finding from the one this figure is about. Right: the male:female ratio of that spread, with its 95% interval; the dashed line marks equal dispersion. The interval straddles it: the male curve is a little wider, but this sample cannot tell that apart from no difference at all.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>The second response, set to absent.</strong> Every model in this book has one thing on the left of the tilde, the <code>~</code> in the formula that separates the response from what predicts it. That is a constant too, and it is the one people notice least, because a spreadsheet with two measured columns invites you to fit two models and compare the two answers — which is not the same analysis and does not answer the same question. Fit them jointly and a new parameter appears that neither separate fit contains: the correlation between the two responses, after everything on the right of the tilde has had its say. Then free <em>that</em>: let the correlation itself depend on a predictor, so that two traits can be tightly coupled in one environment and loose in another. That is <strong>rung twelve</strong>, and it is the last one in the plan, because once the correlation between two responses is a thing you model rather than a thing you assume, there is very little left in an introduction that is still nailed down.</p>
<p><strong>The effect-size row.</strong> Here is the same idea in a different building. Change what a row of your data frame <em>is</em>: not an animal, but a published study’s estimate of an effect. The model looks familiar — an intercept, maybe a moderator or two (a predictor that explains why studies differ), a random effect over studies — and one thing is new and changes everything. Each row arrives with its own sampling variance — how uncertain that study’s estimate is — already known, computed from that study’s sample size rather than estimated from the data. So the model has a variance you must not estimate sitting immediately beside variances you must, and every heterogeneity statistic you have ever read — the numbers, such as I², that say how much studies disagree beyond chance — is a statement about the ratio between them. Everything you learned in Class 8 about <em>which</em> estimator produced a variance component (the share of the variation assigned to one source, such as differences between studies) applies with more force here, not less, because the quantity people actually publish is a ratio of variance components.</p>
<p><strong>The phylogeny as a relatedness matrix.</strong> And here is the same idea again. Class 10 hands the model a matrix that says how the levels of a random effect are related, and a phylogeny is one of the four faces that single idea wears — beside a pedigree (a family tree of known parents), a spatial neighbourhood, and a taxonomy. So the <em>machinery</em> of comparative biology is already in your hands when you finish this book. What is not is the discipline built on top of it: which tree, whose tree, what to do when the tree is uncertain or the trait is not continuous or the branch lengths are a guess. That is a field, not a chapter, and it is the same field as the paragraph above it — non-independence from shared ancestry and non-independence from shared effect sizes are one statistical problem in two sets of clothes (Hadfield &amp; Nakagawa 2010). They belong together in a second book, and that is where they are going.</p>
<hr>
<h2 id="what-version-two-adds" class="anchored">What version two adds</h2>
<p>Version two of the book is those first two paragraphs: rung eleven and rung twelve, written the way every other rung was written, with a class, an argument and numbers that come from code that ran. The outline for both is already fixed (it is linked from <a href="../index.html">the landing page</a>), and it is deliberately the <em>end</em> of the ladder rather than the middle — a reader who can model the spread and the correlation between two responses has run out of things an introduction was hiding.</p>
<p>Version two of the <strong>engines</strong> is a shorter and less romantic list, and it is worth naming honestly, because this book’s own chapters ran into it. Two things the Julia engine cannot yet do that its R twin can: fit a random slope — a slope allowed to differ from group to group — when the outcome is yes/no, which is why Class 7 works on a continuous outcome; and take an offset — a known amount of effort or exposure per row, entered with its slope fixed at one — which is why Class 4 carries the exposure as an ordinary predictor in Julia and shows the offset in the R box. Both are known limitations, reported to the engine’s authors. Neither is a design decision; both are work.</p>
<p>There is a general lesson in that list, and it is the one to take away. A capability existing somewhere in a package’s code is not the same as a capability that is tested, documented and safe to teach. This book only teaches the second kind, which is why it is shorter than the engines are, and why a chapter sometimes steps around a feature that technically already runs.</p>
<hr>
<h2 id="what-this-book-did-not-do" class="anchored">What this book did not do</h2>
<p>An introduction earns the word by leaving things out. Here is the list, so that nobody has to discover it the hard way.</p>
<ul>
<li><strong>It taught one engine, not an ecosystem.</strong> You can fit these models; you cannot yet read a colleague’s <code>lme4</code> script fluently, and the day a referee asks why you did not use <code>glmer</code> — the function in <code>lme4</code> that fits these models — you will want more than this book gave you. The comparison boxes were a bridge, not a course.</li>
<li><strong>It is frequentist throughout.</strong> There is no prior anywhere in it — no statement of belief entered before the data, which is the ingredient that makes an analysis Bayesian. A great deal of modern practice in exactly these models is Bayesian, and nothing here argues against that; the book simply does not go there.</li>
<li><strong>It taught models, not designs.</strong> How to fit the thing you measured, not how to decide what to measure, how to randomise it, or when a coefficient is allowed to be called an effect. Those are different books and they are more important than this one.</li>
<li><strong>It stayed linear in the predictors.</strong> A link function — the bend that maps a straight-line predictor onto the scale of the data — bends the curve at the end; nothing here bends it in the middle. Smoothers and splines — curves the data are allowed to bend into — and genuinely non-linear mean functions are absent.</li>
<li><strong>It fenced off meta-analysis and phylogenetic comparative methods</strong> — deliberately, as the preface says, and as the section above explains.</li>
<li><strong>It worked on small data.</strong> Every file behind these chapters is small enough to open in a spreadsheet and read. Nothing in this book will tell you what breaks when a random effect has a hundred thousand levels, or what to do about it.</li>
<li><strong>It used simulation as a habit, not as a subject.</strong> Appendix A is a thread pulled tight, not a course in Monte Carlo methods (answering a question by drawing random numbers many times); there is nothing here about study design by simulation, or about power — the chance a study detects an effect that is really there.</li>
<li><strong>And it freed one constant at a time.</strong> That is the deepest omission, and the one worth thinking about longest. Real data do not present you with one released constant and everything else nailed down. They arrive overdispersed (more scattered than the family allows) <em>and</em> clustered <em>and</em> with a slope that varies <em>and</em> with groups that are related to one another, all at once, and the skill this book cannot teach you in ten chapters is deciding which of those to free first, and which to leave alone because your sample size has not earned it.</li>
</ul>
<hr>
<p class="scene">The last morning. Four chairs, and for once nobody has a laptop open.
TOTO has brought biscuits, which is how everyone knows it is the end of
term. JARO has come up from the floor below without being asked.</p>
<div class="line"><span class="who momo">Momo</span><p>So the honest summary is that you have taught me to take things out of a
model, and now you are telling me there are more things.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The honest summary is that there is always one more constant. That is
not a flaw in the book, it is what modelling <em>is</em>. The difference
between you in Class 1 and you now is not that you know more models. It
is that when somebody hands you a result you can ask which assumption is
doing the work, and then go and check.</p></div>
<div class="line"><span class="who toto">Toto</span><p>I mostly learned to read the error messages.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p><em>(to the room)</em> That is the correct answer and I want it minuted.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>What do we do with the two chapters that are not written?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Wait for them, or beat me to them. Everything in this book is open — the
text, the data, the code that made every number on every page. The point
of building it that way is that you do not have to take my word for any
of it, including the parts I got wrong.</p></div>
<div class="line"><span class="who jaro">Jaro</span><p><em>(standing, taking a biscuit)</em> Then the only thing left to say is
the thing you have been saying since the first hour.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Fit it. Look at it. Say which estimator printed it. Then go and free the
next one.</p></div>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Three, chosen as doors rather than as reading. The details of all three
were checked on 2026-09-07 against OpenAlex, an open catalogue of
research papers.</p>
<ol type="1">
<li><strong>Rigby, R. A. &amp; Stasinopoulos, D. M. (2005) “Generalized Additive Models for Location, Scale and Shape”, <em>Journal of the Royal Statistical Society Series C (Applied Statistics)</em> 54(3):507–554.</strong> doi:10.1111/j.1467-9876.2005.00510.x. The door to rung eleven. The framework in which every parameter of a distribution — not only its mean — gets its own linear predictor. Read the first sections for the idea and skim the rest; what you want from it is the habit of asking what else in a distribution could have a model attached to it.</li>
<li><strong>Hadfield, J. D. (2010) “MCMC Methods for Multi-Response Generalized Linear Mixed Models: The MCMCglmm R Package”, <em>Journal of Statistical Software</em> 33(2).</strong> doi:10.18637/jss.v033.i02. The door to rung twelve, and the clearest widely read account of what a <em>multi-response</em> mixed model is: what the extra parameters — the correlations between the responses — mean and how the model is set up to estimate them. It is Bayesian, which this book is not; read it for the structure of the model rather than for the inference.</li>
<li><strong>Hadfield, J. D. &amp; Nakagawa, S. (2010) “General quantitative genetic methods for comparative biology: phylogenies, taxonomies and multi-trait models for continuous and categorical characters”, <em>Journal of Evolutionary Biology</em> 23(3):494–508.</strong> doi:10.1111/j.1420-9101.2009.01915.x. The door to the second book, and the paper that makes the claim this coda leans on: that a pedigree, a phylogeny and a taxonomy are the same object handed to the same model. Read it once you have finished Class 10 and the four faces have stopped looking like four things.</li>
</ol>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="appendix-a-simulation.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Appendix A · Simulation as a way of thinking</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Coda · the coda to a planned 13 rungs, ten in version 1 · draft, 2026-09-07<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>