<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 2: the linear model – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 2: the linear model</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 2</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>One line through a cloud of sparrows</h1>
    <p class="deck">The linear model, taught in one engine — and the morning a student notices that Julia and R disagree about a number.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>Draft. Every number and figure on this page comes from code that was actually run when the site was built; the prose is still being written.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Everything printed below came from running this chapter’s code from top to bottom when the site was built; nothing is typed from memory. The two errors are real errors, left in on purpose. The R output in the disagreement box was run once by hand, in R, on 2026-09-06, on the same birds, and pasted in.<br>
      <b>Caveat</b> The data are real: 171 house sparrows measured on Lundy Island in the author’s 2012 course, read from data/2012/MBodySize.csv through a copy, data/ch2/sparrows.csv, with the sex column spelled out as female/male (where the file came from is recorded in data/2012/README.md).
    </p>
  </div>
</header>

<div class="wrap">
<blockquote>
<p><strong>The data are real.</strong> The 2012 sparrow morphology file (<code>data/2012/MBodySize.csv</code>) is the one the original 2012 R-book course used — 171 house sparrows measured on Lundy Island, recovered from the author’s own archive folder. This chapter reads a copy of it, <code>data/ch2/sparrows.csv</code>, with the sex column spelled out as female/male and only the four columns it needs kept. Where the file came from, and how to check that your copy is the same, is recorded in <code>data/2012/README.md</code>. Every number in this chapter, spoken or printed, comes from that file.</p>
</blockquote>
<hr>
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>Say what a linear model actually claims about your data, in one sentence, without the word “significant”.</li>
<li>Fit a simple regression in Julia with <code>drm</code> and read every line of what it prints back.</li>
<li>Add a second predictor, and say what the first coefficient now means that it did not mean before.</li>
<li>Compare two models, one inside the other, by likelihood — how well each explains the data you actually saw — and know when that comparison is legitimate.</li>
<li>Explain why the model prints a <strong>second table you did not ask for</strong>, and read the null hypothesis — the “nothing is going on” value being tested — that it states above each row of it.</li>
<li>Recognise that R’s <code>lm()</code> and our engine disagree about one number, and say exactly why.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, 9:00 am. Dunedin, and it is doing that thing where the
rain arrives sideways. TOTO is early, dripping. MOMO arrives at 9:00
exactly, which for Momo counts as early. Two laptops open. Itchy is
drawing a cloud of dots on the whiteboard.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Julia time. Toto, you are damp.</p></div>
<div class="line"><span class="who toto">Toto</span><p>I cycled.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You cycled in that. Good. Then you already understand today’s lesson:
things vary, and some of the variation has a reason. Look at this cloud.
Each dot is a house sparrow. Along the bottom, tarsus length; the bony
part of the foot, and the standard way we say “how big is this bird”
without arguing about how fat it is. Up the side, wing length.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And you want a line through it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>I want a line through it. But I want you to say what the line
<em>is</em> before we draw one, because the line is not the model. Toto,
what is a linear model?</p></div>
<div class="line"><span class="who toto">Toto</span><p>…the best-fitting straight line?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is what it looks like. It is not what it is. Here is what it is,
and I want you to learn this sentence properly because you will re-use
it for the next ten weeks. <strong>A linear model says: every sparrow’s
wing is drawn from its own normal distribution — the familiar
bell-shaped curve, symmetric around its centre; the centre of that
distribution slides along a straight line as tarsus increases; and the
width of that distribution is the same for every bird.</strong></p></div>
<div class="line"><span class="who momo">Momo</span><p>That is three claims.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is three claims, and only the middle one gets a <em>p</em>-value in
most software, which is a scandal we will spend the whole course fixing.
Say them back.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Normal. Centre moves in a line. Width fixed.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p class="aside">(writes on the board)</p></div>
<p class="board"><strong>μ = where the birds are. σ = how spread out they are.</strong></p>
<div class="line"><span class="who itchy">Itchy</span><p>Every model in this course is those two letters. Today μ gets a
predictor and σ does not. In Class 4 σ gets predictors too, and you will
find you already know how to write it, because we never change tools.
Right. Load the data.</p></div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sparrows <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/ch2/sparrows.csv"</span>, DataFrame);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">first</span>(sparrows, <span class="fl">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><div style="float: left;"><span>6×4 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">BirdID</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tarsus</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Wing</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String7">String7</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String7">String7</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">TA14502</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">18.4333</td>
<td style="text-align: right;">71.5667</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">TA14505</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">18.1</td>
<td style="text-align: right;">76.5</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">TA14506</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">18.45</td>
<td style="text-align: right;">75.0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">TA14507</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">18.15</td>
<td style="text-align: right;">75.0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">TA14509</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: right;">78.25</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">TA14513</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">17.3667</td>
<td style="text-align: right;">74.4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>171 birds. Look before you model, always. Toto, means and spreads of the
two columns we need: <code>sparrows[!, [:Tarsus, :Wing]]</code> picks
them out by name, the <code>!</code> in the row slot meaning every row
and the square brackets holding a list of the Symbols you met last week.</p></div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(sparrows[!, [<span class="op">:</span>Tarsus, <span class="op">:</span>Wing]], <span class="op">:</span>mean, <span class="op">:</span>std, <span class="op">:</span>min, <span class="op">:</span>max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><div style="float: left;"><span>2×5 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">std</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">Tarsus</td>
<td style="text-align: right;">18.6146</td>
<td style="text-align: right;">0.75411</td>
<td style="text-align: right;">16.9</td>
<td style="text-align: right;">20.55</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">Wing</td>
<td style="text-align: right;">77.8523</td>
<td style="text-align: right;">2.09324</td>
<td style="text-align: right;">71.5667</td>
<td style="text-align: right;">84.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Wing lengths sit around 78 mm and wander by about 2.09 mm. Hold on to
2.09. It is the number the model has to explain away, and in twenty
minutes I am going to ask you how much of it we managed to explain.</p></div>
<div id="cell-fig-cloud" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_data_cloud</span>(sparrows.Tarsus, sparrows.Wing;</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    xlabel <span class="op">=</span> <span class="st">"Tarsus (mm)"</span>, ylabel <span class="op">=</span> <span class="st">"Wing (mm)"</span>, title <span class="op">=</span> <span class="st">"Wing vs Tarsus"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div id="fig-cloud" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-cloud-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk2-linear-models_files/figure-html/fig-cloud-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cloud-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Wing length against tarsus length, 171 house sparrows (Lundy Island, 2012).
</figcaption>
</figure>
</div>
</div>
</div>
<h3 id="the-fit" class="anchored">The fit</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Here is the whole thing. One line.</p></div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Stop. Why is there a <code>bf</code> in the way? In R I write
<code>lm(Wing ~ Tarsus, sparrows)</code> and I am done. You have added
two words and a semicolon.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Correct, and I am going to defend the two words rather than pretend they
are not there. The semicolon needs no defence: a semicolon at the end of
a line <strong>hides its printout</strong>, and I hid this one because
the next cell shows the fit properly. You will see it on any line whose
output would only be noise. <code>bf</code> stands for
“<strong>b</strong>ig <strong>f</strong>ormula”, and it is a box that
can hold <strong>more than one formula at a time</strong>: one for μ,
one for σ, later one for the correlation between two traits. Today the
box holds one formula, so it looks like packaging with nothing in it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So it is overhead I pay now for a feature I get in Class 4.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Yes. That is exactly the deal, and you should be annoyed about it for
about two more weeks. What you get for it: from here to the summit of
the mountain, <strong>you never change the verb</strong>. Not when the
data are counts, not when the birds are siblings, not when we model the
spread itself. It is always <code>drm</code>, always <code>bf</code>,
always a family — here <code>Gaussian()</code>, which just means the
normal distribution I described a minute ago. You will meet people who
learn six packages to climb the same hill and spend their evenings
translating between them. Let us see what came out.</p></div>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fit1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>Distributional regression fit (Gaussian)
  nobs = 171   logLik = -350.6659   converged = true
  Residual SD (response scale) = 1.8809   dof_residual = 168

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  55.4569     3.5638  15.5613  1.334e-54
  Tarsus        1.2031     0.1913   6.2893  3.188e-10

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  0.6317     0.0541  11.6829  1.559e-31</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>There are two tables. I only asked for one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You asked for one and you were given the model. Sit down, this is the
moment the engine looks strangest to somebody arriving from R, so let me
pay for it properly instead of hurrying past.</p></div>
<p>Two tables came back because I told you there were always two letters. <strong>μ is where the birds are; σ is how spread out they are.</strong> R prints both too, it just hides σ at the bottom of the page under “Residual standard error” and hopes you will not ask questions about it. Ours puts it in a table, because in two weeks you will be putting predictors in it.</p>
<div class="line"><span class="who toto">Toto</span><p>Why “log σ”?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because a spread cannot be negative, and an optimiser — the search
routine that hunts for the best-fitting numbers — that wanders freely
over the number line would eventually try a negative one and fall over.
So the engine works with the logarithm, which is allowed to be any
number at all, and you undo it at the end.</p></div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit1, <span class="op">:</span>sigma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>1-element Vector{Float64}:
 0.6317394537001391</code></pre>
</div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(fit1, <span class="op">:</span>sigma)[<span class="fl">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>1.8808794381239688</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>There it is: <strong>1.88 mm.</strong> That is the residual standard
deviation, in millimetres, on the natural scale. Now look back at the
top of the fit, where it says <strong>Residual SD (response
scale)</strong> — the same spread, in millimetres. The engine prints it
for you. I made you compute it by hand once so that the header means
something when you read it, and so that you never mistake the
<code>sigma:</code> row, which is on the log scale, for the millimetres
it is not. And now answer my earlier question, Toto. The raw wing
lengths wandered by 2.09 mm. After we account for tarsus, they wander by
1.88. Was tarsus worth it?</p></div>
<div class="line"><span class="who toto">Toto</span><p>…a bit? It went down but not loads.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>“A bit” is the honest answer and I want you to notice how much less
exciting it is than a vanishingly small <em>p</em>-value. The
<em>p</em>-value says the slope is not zero. It does not say the slope
is <em>useful</em>. Those are different questions, and only one of them
is about sparrows.</p></div>
<div class="line"><span class="who momo">Momo</span><p>The σ row has a <em>p</em>-value of its own, and it is tiny.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is, and I want you suspicious of it rather than impressed by it.
Every <em>p</em>-value answers a question of the form “how surprised
would I be if this number were really <strong>zero</strong>?” For the
slope, zero is a real, interesting hypothesis: tarsus tells us nothing
about wing. Fine. Now: what would it mean for that σ row to be zero?</p></div>
<div class="line"><span class="who momo">Momo</span><p>…zero log-sigma. Which is sigma equal to one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Which is a residual spread of <strong>exactly one millimetre</strong>.
Not “no spread”. One millimetre. Why on earth would anyone want to test
that?</p></div>
<div class="line"><span class="who momo">Momo</span><p>Nobody would.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Nobody would, and that is exactly why the engine prints the null
<em>above</em> the table instead of leaving you to reconstruct it from a
column of stars. Read the two lines under <strong>Scale model (log
σ)</strong>. The <code>z</code> column is the estimate divided by its
standard error — its uncertainty — so it counts how many standard errors
from zero the estimate sits, and <code>Pr(&gt;|z|)</code> is the
<em>p</em>-value made from it. For the intercept, zero means σ = 1, and
whether that is true depends entirely on whether you measured in
millimetres or metres. Measure the same sparrows in centimetres and that
<em>p</em>-value changes while nothing whatever about the birds does. A
unit-dependent null is almost never a question about your organism.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So I ignore it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You ignore <em>that</em> one, and the same heading tells you when not
to. The second line is about a σ <strong>slope</strong>, where zero
means “these groups vary by the same amount”, and that is a real
question about real animals. We will ask it in Class 4, when σ gets a
predictor. The rule is: read the null, then decide whether you care. A
number the software is willing to compute is not automatically a number
you should report.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Can I see all of it in one table?</p></div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftable</span>(fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="16">
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std.Error</th>
<th style="text-align: right;">z</th>
<th style="text-align: left;">Pr(&gt;|z|)</th>
<th style="text-align: left;">Lower 95%</th>
<th style="text-align: right;">Upper 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mu: (Intercept)</td>
<td style="text-align: right;">55.4569</td>
<td style="text-align: right;">3.56377</td>
<td style="text-align: right;">15.56</td>
<td style="text-align: left;">&lt;1e-53</td>
<td style="text-align: left;">48.472</td>
<td style="text-align: right;">62.4417</td>
</tr>
<tr class="even">
<td style="text-align: left;">mu: Tarsus</td>
<td style="text-align: right;">1.20311</td>
<td style="text-align: right;">0.191294</td>
<td style="text-align: right;">6.29</td>
<td style="text-align: left;">&lt;1e-09</td>
<td style="text-align: left;">0.828182</td>
<td style="text-align: right;">1.57804</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sigma: (Intercept)</td>
<td style="text-align: right;">0.631739</td>
<td style="text-align: right;">0.0540738</td>
<td style="text-align: right;">11.68</td>
<td style="text-align: left;">&lt;1e-30</td>
<td style="text-align: left;">0.525757</td>
<td style="text-align: right;">0.737722</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Better. Confidence intervals included, and I want you reading the
interval before the <em>p</em>-value from now on. <strong>A sparrow with
a tarsus one millimetre longer has a wing about 1.2 mm longer, and the
data are consistent with anything from 0.83 to 1.58.</strong> That is a
sentence about birds. Notice it contains no asterisks.</p></div>
<div class="line"><span class="who momo">Momo</span><p>The intercept is 55.46. A sparrow with a tarsus of zero has a 55 mm
wing.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>A sparrow with a tarsus of zero is not a sparrow, it is a tragedy. The
intercept is where the line crosses a place your data never went; tarsus
ranges from 16.9 to 20.6. It is a bookkeeping number, not biology. You
can make it biology by centring tarsus on its mean, and then the
intercept becomes “the wing of an average-sized sparrow”, which is a
thing that exists. That is one of your exercises.</p></div>
<div id="cell-fig-fit1-ribbon" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_fit_ribbon</span>(sparrows.Tarsus, sparrows.Wing, <span class="fu">fitted</span>(fit1), <span class="fu">sigma</span>(fit1);</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    xlabel <span class="op">=</span> <span class="st">"Tarsus (mm)"</span>, ylabel <span class="op">=</span> <span class="st">"Wing (mm)"</span>, title <span class="op">=</span> <span class="st">"Fitted μ ± σ"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div id="fig-fit1-ribbon" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-fit1-ribbon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk2-linear-models_files/figure-html/fig-fit1-ribbon-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fit1-ribbon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Fitted mean wing length as a function of tarsus, ±σ band.
</figcaption>
</figure>
</div>
</div>
</div>
<h3 id="two-errors-kept-in" class="anchored">Two errors, kept in</h3>
<div class="line"><span class="who toto">Toto</span><p><em>(typing)</em> I wanted to check something and I got a wall of red.</p></div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drm</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<div class="ansi-escaped-output">
<pre>MethodError: no method matching drm(::StatsModels.FormulaTerm{StatsModels.Term, StatsModels.Term}, ::Gaussian; data::DataFrame)

Closest candidates are:
  drm(<span class="ansi-bright-red-fg">::BivariateDrmFormula</span>, ::Gaussian; data, tree, K, A, coords, spatial_range, g_tol, q4_g_tol, q4_iterations, q4_n_newton, q4_vcov, method, V)
  drm(<span class="ansi-bright-red-fg">::DrmFormula</span>, ::Gaussian; data, K, A, tree, coords, g_tol, algorithm, method, profile_ci, phylo_coupled, penalty, sparse, impute, missing)


(stack trace omitted)</pre>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Good. Everybody look at this, because Julia’s error messages are the
thing that makes R users give up in week one, and they are actually the
most useful errors in any language I use once you know the shape.</p></div>
<p>Read it as three parts. <strong>What you asked for</strong>, on the first line: you handed <code>drm</code> a <code>FormulaTerm</code>. <strong>What it knows how to do</strong>, underneath: it takes a <code>DrmFormula</code>, or a <code>BivariateDrmFormula</code>. And the mismatched argument is printed <strong>in red</strong> in each candidate — the same marker appears as the word <code>!Matched</code> where there is no colour — so you do not have to guess which of the four things you typed was the problem.</p>
<div class="line"><span class="who toto">Toto</span><p>So it is telling me I forgot the <code>bf</code>.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is telling you exactly that, in five hundred characters and one
exclamation mark. Momo, this is the honest cost of the <code>bf</code>
wrapper: forget it and you get a method error rather than a fit. It is a
one-token mistake with a loud, informative failure, and I will take that
over a quiet one every time.</p></div>
<div class="line"><span class="who toto">Toto</span><p><em>(typing)</em> And this one is just me.</p></div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsis)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<div class="ansi-escaped-output">
<pre>ArgumentError: There isn't a variable called 'Tarsis' in your data; the nearest names appear to be: Tarsus

(stack trace omitted)</pre>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p><em>(delighted)</em> It spelled it for you. It looked at your typo, went
through your column names, found the closest one, and handed it back.
Toto, you have been misspelling things all year and I have never been so
pleased about it.</p></div>
<h3 id="a-second-predictor" class="anchored">A second predictor</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Now. Males are bigger. Does that matter?</p></div>
<div class="line"><span class="who momo">Momo</span><p>In the model or in general?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>In the model. In general it matters a great deal to a female sparrow.
Add it.</p></div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>Distributional regression fit (Gaussian)
  nobs = 171   logLik = -301.7781   converged = true
  Residual SD (response scale) = 1.4132   dof_residual = 167

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z    Pr(&gt;|z|)
  (Intercept)  57.8218     2.6855  21.5310  7.986e-103
  Tarsus        1.0116     0.1447   6.9917   2.717e-12
  Sex: male     2.5012     0.2178  11.4854   1.562e-30

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                Coef.  Std.Error       z   Pr(&gt;|z|)
  (Intercept)  0.3458     0.0541  6.3958  1.597e-10</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>One term added. Same verb, same wrapper, same family. Notice what the
engine did without being asked: <code>Sex</code> arrived as text, and it
worked out that “female” comes first alphabetically, made it the
baseline, and gave you a coefficient for <code>male</code> measured
<strong>relative to female</strong>. Males have wings about 2.5 mm
longer than females of the same tarsus length.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Tarsus dropped. It was 1.2, now it is 1.01.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p><em>(pleased)</em> That is the most important observation anyone has
made this morning, and if you take one thing home take this. <strong>The
tarsus coefficient did not change because the birds changed. It changed
because the question changed.</strong></p></div>
<p>In <code>fit1</code> it answered: <em>pick two sparrows differing by one millimetre of tarsus; how much do their wings differ?</em> Some of that difference was really about sex, because males have longer tarsi <strong>and</strong> longer wings, so tarsus was quietly carrying sex’s luggage.</p>
<p>In <code>fit2</code> it answers: <em>pick two sparrows of the same sex differing by one millimetre of tarsus.</em> Sex is now carrying its own bag. The slope is smaller because it is doing less work.</p>
<div class="line"><span class="who toto">Toto</span><p>So the first one was wrong?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>No, and I want to be careful here because this is where people get
superstitious. The first one was <strong>a different question, correctly
answered</strong>. Neither is wrong. But if you are trying to say
something about growth, the second is almost certainly the question you
meant. A coefficient without the rest of the model attached to it means
nothing; that is why you never report one on its own.</p></div>
<h3 id="is-the-second-model-better" class="anchored">Is the second model better?</h3>
<div class="line"><span class="who momo">Momo</span><p>Prove it is worth the extra term.</p></div>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aic</span>(fit1), <span class="fu">aic</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>(707.3318715214452, 611.5562817546105)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(fit1, fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>(statistic = 97.77558976683474, dof = 1, pvalue = 4.685886499453756e-23)</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>AIC — the Akaike information criterion, a score that rewards fit and
charges for every extra parameter; lower is better — drops by about 96,
which is enormous — this is not the polite few-points improvement you
learn to shrug at; the likelihood-ratio test, which asks how much more
likely the data are under the bigger model than under the smaller, costs
one parameter and returns a <em>p</em> so small the printer basically
gives up on decimal places: 4.7e-23. Both say the same thing, loudly:
sex earns its place.</p></div>
<p>Two warnings, and they are not decoration. <strong>One:</strong> that test is only legal because <code>fit1</code> is <em>nested</em> inside <code>fit2</code>; you get <code>fit1</code> by setting the sex coefficient to zero. Compare two models that are not nested this way and the number you get is nonsense with a <em>p</em>-value stapled to it. <strong>Two:</strong> this comparison is honest here because both fits used the same recipe for turning data into numbers, on the same birds. In Class 8 you will meet a situation where two perfectly correct fits use <em>different</em> likelihoods and this comparison silently becomes illegal. I am flagging it now so that when I say “you cannot do that” in Class 8 you will remember I warned you.</p>
<div class="line"><span class="who momo">Momo</span><p><em>(typing quietly)</em> I ran it in R while you were talking. R says
my residual standard error is <code>1.426</code> — I have the printout
here. I exponentiated your 0.3458 and got 1.413.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p><em>(stops, genuinely happy)</em> Say that again, louder, so Toto hears
it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Your engine and R disagree.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Good. Everybody stop typing. This is the best thing that has happened
this term.</p></div>
<hr>
<div class="disagree">
<p class="scene">⚠ DISAGREE — the same regression, two residual SDs</p>
<p>Momo fits the identical model in R with <code>lm()</code>. Every slope agrees to five decimal places. The residual spread does not, and neither does the standard error on the slope. Nobody has made a mistake.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run once by hand in R on 2026-09-06 (R 4.6.0, stats::lm) and pasted in;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># not re-run with the page. The same sparrows, from data/ch2/sparrows.csv.</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(Wing <span class="sc">~</span> Tarsus <span class="sc">+</span> Sex, <span class="at">data =</span> sparrows)                                <span class="co"># R</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb23"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)     <span class="co"># Julia</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>quantity</th>
<th>R <code>lm()</code></th>
<th>DRM.jl <code>drm</code></th>
<th>ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tarsus slope</td>
<td>1.011631</td>
<td>1.011631</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td>Sex (male)</td>
<td>2.501172</td>
<td>2.501172</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td>residual SD</td>
<td><strong>1.425747</strong></td>
<td><strong>1.413185</strong></td>
<td><strong>1.008889</strong></td>
</tr>
<tr class="even">
<td>SE of Tarsus slope</td>
<td><strong>0.145977</strong></td>
<td><strong>0.144691</strong></td>
<td><strong>1.008887</strong></td>
</tr>
<tr class="odd">
<td>log-likelihood</td>
<td>-301.778141</td>
<td>-301.778141</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td>reference distribution</td>
<td><em>t</em> on 168 degrees of freedom</td>
<td><em>z</em> (normal)</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>The mechanism.</strong> Both fits maximise the same likelihood and land on the same coefficients. They then divide the squared residuals by different numbers. <code>lm()</code> divides by <strong>n − p</strong>, where <em>p</em> counts only the mean coefficients (here 171 − 3 = 168), which makes the variance estimate — the SD squared — unbiased: its average across repeated samples lands on the true value rather than drifting to one side. Our engine reports the <strong>maximum likelihood</strong> estimate, which divides by <strong>n</strong> (171). The ratio is therefore exactly √(n / (n − p)) = √(171/168) = 1.008889, which is what you see in both the SD and the standard error, to the last digit R’s six-decimal printout can support. It is one arithmetic choice, not a bug in either package. (The <code>dof_residual</code> in the fit’s own header is one smaller, because the engine counts σ among the things it estimated; R does not, and the ratio needs R’s count.)</p>
<div id="cell-fig-disagree" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit2's mu coefficients are [Intercept, Tarsus, Sex:male]; female is the</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># baseline. A smooth grid at Sex = female avoids the zigzag that</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting fitted() at each observation would give once Sex is in the model.</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The scatter on the left is filtered to females too: fit2's ~2.5 mm sex</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># effect is bigger than the ~1.4 mm band, so plotting both sexes around a</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># female-only band would bury the divisor question under an unrelated,</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># unlabelled population offset.</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> <span class="fu">coef</span>(fit2, <span class="op">:</span>mu)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>xs <span class="op">=</span> <span class="fu">range</span>(<span class="fu">minimum</span>(sparrows.Tarsus), <span class="fu">maximum</span>(sparrows.Tarsus); length <span class="op">=</span> <span class="fl">100</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>mu2 <span class="op">=</span> b[<span class="fl">1</span>] <span class="op">.+</span> b[<span class="fl">2</span>] <span class="op">.*</span> xs</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>p_mu <span class="op">=</span> <span class="fu">length</span>(b)                                      <span class="co"># 3: intercept, Tarsus, Sex</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>sigma_ours <span class="op">=</span> <span class="fu">sigma</span>(fit2)[<span class="fl">1</span>]                           <span class="co"># ÷n   (DRM.jl, ML)</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>sigma_r <span class="op">=</span> sigma_ours <span class="op">*</span> <span class="fu">sqrt</span>(<span class="fu">nobs</span>(fit2) <span class="op">/</span> (<span class="fu">nobs</span>(fit2) <span class="op">-</span> p_mu))  <span class="co"># ÷(n−p) (R lm())</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>females <span class="op">=</span> sparrows.Sex <span class="op">.==</span> <span class="st">"female"</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">760</span>, <span class="fl">340</span>))</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"Tarsus (mm)"</span>, ylabel <span class="op">=</span> <span class="st">"Wing (mm)"</span>,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"Fitted line, females only"</span>)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># band and line first, real data drawn LAST so no point is ever painted over</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="fu">band!</span>(ax1, xs, mu2 <span class="op">.-</span> sigma_ours, mu2 <span class="op">.+</span> sigma_ours)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax1, xs, mu2; linewidth <span class="op">=</span> <span class="fl">2</span>, color <span class="op">=</span> <span class="op">:</span>black)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax1, sparrows.Tarsus[females], sparrows.Wing[females]; markersize <span class="op">=</span> <span class="fl">6</span>)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="co"># The two divisors are a deterministic ratio of one another (sqrt(n/(n-p))),</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="co"># not two independent estimates, so no error bars: whiskers sized to the</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a><span class="co"># fit's own sampling SE (~0.076 mm) would be ~6x wider than the 0.013 mm gap</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="co"># between them and would swallow the very difference this panel exists to</span></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="co"># show. Two plain points, y-axis zoomed to just the two of them, is honest.</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>];</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>    xticks <span class="op">=</span> (<span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, [<span class="st">"R lm()</span><span class="sc">\n</span><span class="st">÷(n−p)"</span>, <span class="st">"DRM.jl</span><span class="sc">\n</span><span class="st">÷n"</span>]),</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>    ylabel <span class="op">=</span> <span class="st">"residual SD (mm)"</span>,</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"Same gap, zoomed in"</span>)</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a><span class="fu">xlims!</span>(ax2, <span class="fl">0.5</span>, <span class="fl">2.5</span>)</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax2, [<span class="fl">1</span>], [sigma_r]; markersize <span class="op">=</span> <span class="fl">14</span>, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">1</span>))</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax2, [<span class="fl">2</span>], [sigma_ours]; markersize <span class="op">=</span> <span class="fl">14</span>, marker <span class="op">=</span> <span class="op">:</span>diamond, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">2</span>))</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div id="fig-disagree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-disagree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk2-linear-models_files/figure-html/fig-disagree-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disagree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Left: the fitted line for females (fit2) with DRM.jl’s ±σ band (÷n) — data filtered to females, since that is what the line and band actually describe. Right: the same two residual SDs from the table above, ÷n and ÷(n−p), replotted on a zoomed axis; the gap, which would sit under a fraction of a pixel at wing-length scale (left), is a full-height separation here.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Two habits from Class 1, now doing work.</strong> In the cell above, <code>b[1] .+ b[2] .* xs</code> is the dot doing arithmetic: the intercept is added to, and the slope multiplied into, every point of the grid <code>xs</code> at once, which is how a fitted line is drawn in this book from here on. And <code>females = sparrows.Sex .== "female"</code> followed by <code>sparrows.Tarsus[females]</code> is the true/false vector used to keep rows, exactly as <code>wing_f</code> was picked out last week.</p>
<p><strong>When it stops mattering.</strong> The gap is √(n/(n − p)), so it shrinks as your sample grows relative to the number of things you are estimating: about 0.89% here, and it would fall further still with more birds at the same three parameters — enormous if you ever fit twenty coefficients to thirty birds. It bites hardest exactly where beginners work. R also judges each slope against a <em>t</em> distribution (slightly wider tails, to allow for having estimated the spread) where we use the plain normal; that difference pushes the same way as the larger standard error, not against it, so both make R’s <em>p</em>-value the larger one — on the Tarsus slope, R’s own printout gives <code>Pr(&gt;|t|)</code> = 8.59e-11 against our 2.72e-12, on a slope neither package doubts.</p>
<p><strong>Why this is worth a page in Class 2.</strong> This is the small, tame version of the argument that takes a whole chapter later. Divide by n, or divide by something that accounts for the other numbers you also had to estimate: that same choice, in the models of Class 6 onward — where birds come in families or sites — is the difference between plain maximum likelihood (ML) and restricted maximum likelihood (REML), and there the disagreement is not under one percent on a number you never wanted; it is the spread between groups, the number you came for. Our engine uses ML in both languages. <code>lme4</code>, the usual R package for those models, uses REML. Neither told you. That is Class 8.</p>
</div>
<hr>
<div class="line"><span class="who toto">Toto</span><p>So which one is right?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Both. They answer slightly different questions about the same fit, and
if you had not looked you would never have known there was a question.
That is what I want you frightened of: not software that disagrees, but
software that agrees for reasons you cannot name.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And R prints an R-squared and you do not.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It does — R² is the share of the variation in wing that the model
accounts for, on a scale from 0 to 1 — and before I give you ours I am
going to make you compute it, because the computing is where the lesson
is. Your raw wing spread was 2.093, your residual spread is 1.413, so
the model has taken out 1 − 1.413²/2.093², which is 0.544. Your R
printout says 0.5415. <strong>And no, before you ask, that gap is not
the one we just spent ten minutes on.</strong> I got 2.093 from
<code>describe</code>, which divides by <em>n</em> − 1, and 1.413 from
the engine, which divides by <em>n</em>. I mixed them. R never has to
choose, because R² compares two sums of squares and the divisors cancel
before they can argue. Put the same divisor on both of mine and you get
0.5415 — R’s actual answer. <em>(Beat.)</em> Two different divisor
mistakes in one morning, and the second one was mine.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And the button?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Now you may have the button.</p></div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r2_constant_sigma</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>0.5415360294417806</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>0.5415, which is R’s <code>lm</code> R² to every digit R prints. I made
you do it the long way first because the long way is where the divisor
lives and the button will not teach you that.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And why is the button called <code>r2_constant_sigma</code> and not
<code>r2</code>?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because the name is a promise about when the number means anything. R²
is a share: the residual spread set against the total spread. That is
one number only while there is one residual spread to set against it —
the third claim on the board, the same σ for every bird. Take that claim
away, as we will in Class 4 when σ gets predictors of its own, and “the
variance of the data” is several different quantities; give the model a
count or a yes/no to explain, as in Class 3, and there is no single σ at
all. Every R² you are offered above this rung has quietly picked a
denominator for you, and two papers can quote two different R²s for the
same model with neither being wrong. So the function computes R² where
R² means one thing, and declines everywhere else. Report it today. From
next week, report the residual spread in the units of your organism, and
the comparison between models, and let R² go.</p></div>
<div class="line"><span class="who momo">Momo</span><p><em>(packing up)</em> So the number R prints on every regression is the
one you want me to stop reporting.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>On this rung it is fine. One rung up it stops meaning one thing. Ask me
again in Class 4.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Do water fleas have tarsi?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Toto, water fleas have <em>carapace length</em>, and you are going to
regress something on it before Thursday. Off you go.</p></div>
<p class="scene">Toto and Momo leave into the horizontal rain. Itchy stays, rereads the
two nulls printed above the σ table, and does not close the laptop for
some time.</p>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>Linear model.</strong> Three claims, not one: the response is normally distributed around its own mean; that mean is a straight-line function of the predictors; the spread is constant. Only the second is usually tested.</li>
<li><strong>μ and σ.</strong> The two halves of every model in this book. μ says where the values sit, σ says how far they scatter. R prints σ as “Residual standard error”; we print it as a table because we will later give it predictors.</li>
<li><strong>Intercept.</strong> The fitted mean when every predictor is zero. Often outside the data and therefore not biology. Centre a predictor on its mean and the intercept becomes interpretable.</li>
<li><strong>Slope.</strong> The expected change in the response for a one-unit change in a predictor, <strong>holding the other predictors fixed</strong>. The last clause is why a slope changes when you add a term, and why a coefficient reported without its model is meaningless.</li>
<li><strong>How a text column becomes a number (dummy coding).</strong> A text predictor with two levels becomes one coefficient measured against the alphabetically first level (here, female). More levels means more coefficients, all against the same baseline.</li>
<li><strong>Confidence interval.</strong> The range of parameter values the data are consistent with. Read it before the <em>p</em>-value; it is in the units of your organism.</li>
<li><strong>Nested models.</strong> Model A is nested in B if you can get A by fixing some of B’s parameters (usually to zero). Likelihood-ratio tests and, in spirit, AIC comparisons require this.</li>
<li><strong>AIC.</strong> Log-likelihood penalised for the number of parameters. Lower is better; differences of a few points are worth attending to, differences below about two are not.</li>
<li><strong>Maximum likelihood (ML) versus the unbiased variance.</strong> Maximum likelihood divides the squared residuals by <em>n</em> (the number of birds); the unbiased version divides by <em>n − p</em> (birds minus the number of coefficients). This is the whole of today’s disagreement box, and the seed of Class 8, where the same choice is called ML versus REML.</li>
<li><strong>Residual standard deviation as an effect size.</strong> Raw spread versus residual spread tells you whether a model is <em>useful</em>, which no <em>p</em>-value does.</li>
</ul>
<h3 id="julia-you-used" class="anchored">Julia you used</h3>
<ul>
<li><strong>The trailing semicolon: <code>fit1 = drm(...);</code>.</strong> Hides the printout of that line. The value is still made and kept.</li>
<li><strong><code>df[!, [:Tarsus, :Wing]]</code>.</strong> Columns picked by name: <code>!</code> in the row slot means every row; the vector of Symbols names the columns.</li>
<li><strong>The dot, now for arithmetic: <code>b[1] .+ b[2] .* xs</code>.</strong> Adds the intercept to, and multiplies the slope into, every point of <code>xs</code> at once. <code>sims .- fitted(fit1)</code> does the same to every column of a matrix.</li>
<li><strong>The dot on a function: <code>std.(eachcol(sims))</code>.</strong> Applies <code>std</code> to each thing <code>eachcol</code> hands it, which is one column of the matrix at a time.</li>
<li><strong><code>[rand(rng, Normal(m, s)) for m in mu_hat]</code>.</strong> A <strong>comprehension</strong>: a <code>for</code> loop in one line whose square brackets collect each result into a vector. Class 3 writes the loop out.</li>
<li><strong><code>Normal(m, s)</code>.</strong> A distribution object from <code>Distributions</code>, which <code>rand(rng, ...)</code> draws from; the package also supplies <code>cdf</code> and <code>quantile</code> for it.</li>
<li><strong><code>DataFrame(BirdID = ids, Wing = wing_sim)</code>.</strong> Builds a table from named columns of the same length.</li>
</ul>
<h3 id="calls-you-used" class="anchored">Calls you used</h3>
<ul>
<li><code>using DRM, DataFrames, CSV, Statistics</code>, then <code>using Random, Distributions</code> for the simulation.</li>
<li><code>@formula(y ~ x)</code> inside <code>bf(...)</code>: the formula and the “big formula” box, both <strong>required</strong>. <code>bf(@formula(y ~ x), @formula(sigma ~ z))</code> is the two-formula form Class 4 uses.</li>
<li><code>drm(bf(...), Gaussian(); data = df)</code>: the fit. Verb, box, family, data. The family is <strong>positional</strong> and the data is a <strong>keyword</strong>; this exact shape carries every model in the book.</li>
<li><code>coef(fit, :mu)</code>, <code>coef(fit, :sigma)</code>: one sub-model’s coefficients, as a vector. <code>exp(coef(fit, :sigma)[1])</code> is the residual SD in the response’s units, the same number the header prints as “Residual SD (response scale)”.</li>
<li><code>coeftable(fit)</code>, <code>confint(fit)</code>: the table with 95% intervals, and the intervals alone as named tuples.</li>
<li><code>aic(fit)</code>, <code>loglik(fit)</code>, <code>nobs(fit)</code>, <code>lrtest(fit_small, fit_big)</code>: the comparison toolkit; the test needs nested models on the same rows.</li>
<li><code>fitted(fit)</code>, <code>sigma(fit)</code>, <code>r2_constant_sigma(fit)</code>: fitted means, response-scale σ per bird, and R² where R² means one thing.</li>
<li><code>simulate(fit; nsim = k, rng = rng_sim)</code>: a birds-by-simulations matrix of new responses; the generator is the same <code>rng</code> keyword <code>rand</code> took last week.</li>
<li><strong>Two errors.</strong> Forget <code>bf</code> and you get a <code>MethodError</code> whose red argument is the formula; misspell a column and the <code>ArgumentError</code> names the nearest real one.</li>
</ul>
<p><strong>Simulating from a fitted model.</strong> Every model in this book can generate data as easily as it can fit it, and doing so is the fastest way to check you understand what you fitted.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Random</span>, <span class="bu">Distributions</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">2012</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>mu_hat <span class="op">=</span> <span class="fu">coef</span>(fit1, <span class="op">:</span>mu)[<span class="fl">1</span>] <span class="op">.+</span> <span class="fu">coef</span>(fit1, <span class="op">:</span>mu)[<span class="fl">2</span>] <span class="op">.*</span> sparrows.Tarsus</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>sigma_hat <span class="op">=</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit1, <span class="op">:</span>sigma)[<span class="fl">1</span>])</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>wing_sim <span class="op">=</span> [<span class="fu">rand</span>(rng_sim, <span class="fu">Normal</span>(m, sigma_hat)) for m <span class="kw">in</span> mu_hat]</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>sim_df <span class="op">=</span> <span class="fu">DataFrame</span>(BirdID <span class="op">=</span> sparrows.BirdID, Sex <span class="op">=</span> sparrows.Sex,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                    Tarsus <span class="op">=</span> sparrows.Tarsus, Wing <span class="op">=</span> wing_sim)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>fit1_sim <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sim_df);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit1, <span class="op">:</span>mu)[<span class="fl">2</span>], <span class="fu">coef</span>(fit1_sim, <span class="op">:</span>mu)[<span class="fl">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>(1.2031120353871703, 1.1875405568706943)</code></pre>
</div>
</div>
<p>By hand, one draw at a time: <code>rand(Normal(μ̂, σ̂))</code> for each bird’s fitted mean, refit the same model, and the tarsus slope above wanders from <code>fit1</code>’s to a slightly different number — same data-generating process (the same recipe for making wing lengths), different noise, different estimate. That wander <em>is</em> sampling variability, made visible instead of assumed.</p>
<p>Read the cell line by line, because you will adapt it. <code>mu_hat</code> is the fitted line evaluated at every bird, with the dots from the disagreement box. <code>Normal(m, sigma_hat)</code> is a distribution object from <code>Distributions</code>, and <code>rand(rng_sim, ...)</code> draws one number from it. The line that draws is a <strong>comprehension</strong>: <code>[rand(...) for m in mu_hat]</code> reads “for each fitted mean <code>m</code>, draw one wing, and collect the draws in a vector” — a <code>for</code> loop folded into one line, the square brackets collecting the results; Class 3 writes the same loop out longhand. <code>DataFrame(BirdID = ..., Wing = wing_sim)</code> builds a table from named columns.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">200</span>)   <span class="co"># a seed is a promise: the same draw every time this is run</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>sims <span class="op">=</span> <span class="fu">simulate</span>(fit1; nsim <span class="op">=</span> <span class="fl">200</span>, rng <span class="op">=</span> rng_sim);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">std</span>.(<span class="fu">eachcol</span>(sims <span class="op">.-</span> <span class="fu">fitted</span>(fit1)))), <span class="fu">mean</span>(<span class="fu">std</span>.(<span class="fu">eachcol</span>(sims)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>(1.8703085195848685, 2.0840219108107236)</code></pre>
</div>
</div>
<p><code>simulate(fit; nsim = n)</code> does the same thing two hundred times at once, returning a birds-by-simulations matrix, and the one-line check on it uses the dot on a <em>function</em> for the first time: <code>std.(eachcol(sims))</code> takes the standard deviation of each column, with <code>eachcol</code> walking the matrix one column at a time, and <code>sims .- fitted(fit1)</code> subtracts the vector of fitted means from every column of the matrix. The trap: each simulated column still carries fit1’s fitted mean structure, so its raw spread is close to the <em>raw</em> wing spread, not <code>sigma_hat</code>. Subtract <code>fitted(fit1)</code> from each column first — the first number above, near 1.88 — and only then does it match the model’s own σ; the second number, without the subtraction, does not, and looks like the model cannot reproduce its own residual spread when it can. Appendix A takes this idea further and simulates whole sparrow datasets from a fitted model.</p>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. References checked 2026-09-07.</p>
<ol type="1">
<li><strong>Crawley, M. J. (2007) <em>The R Book</em>. Wiley, Chichester.</strong> Itchy’s own teacher’s book, and the reason there was a 2012 sparrow manual at all. Read the linear-models chapter for the sheer density of worked examples; ignore the software, keep the statistics.</li>
<li><strong>Zuur, A. F., Ieno, E. N. &amp; Elphick, C. S. (2010) “A protocol for data exploration to avoid common statistical problems”, <em>Methods in Ecology and Evolution</em> 1:3–14.</strong> doi:10.1111/j.2041-210X.2009.00001.x. Eight pages on the things you should look at before you fit anything. If you only read one item on this list, read this one; it is the paper version of “look before you model”.</li>
<li><strong>Gelman, A. &amp; Hill, J. (2007) <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge University Press.</strong> Chapters 3 and 4 are the best plain-language account I know of what a regression coefficient means and how badly people misread the intercept. It is also the on-ramp to Class 4.</li>
<li><strong>Rigby, R. A. &amp; Stasinopoulos, D. M. (2005) “Generalized additive models for location, scale and shape”, <em>Journal of the Royal Statistical Society: Series C (Applied Statistics)</em> 54:507–554.</strong> doi:10.1111/j.1467-9876.2005.00510.x. The paper that made “put a model on σ too” a respectable thing to do. Hard, and worth knowing exists; the second formula Class 4 puts in the box is a one-line child of this idea.</li>
<li><strong>DRM.jl documentation, <code>getting-started</code> and <code>capabilities</code>.</strong> The capability page is unusually honest about what the package cannot do and where its own arithmetic is less exact than it would like. Read the warning boxes; they are the interesting part.</li>
<li><strong>The StatsModels.jl <code>@formula</code> documentation.</strong> Everything the formula grammar can express, including interactions, transformations and how contrasts are chosen. This grammar is shared across the Julia statistics ecosystem, so learning it once pays everywhere.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Graded by depth: the first three take ten minutes each. Every exercise names a file under <code>data/</code> that exists; do it on your own organism as well where you have one. A <em>check</em> is a number computed from that file when this page was built — match it before going on. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Class 1 and not Class 2; Class 1’s worked answer is the model.</p>
<ol type="1">
<li><p><strong>Centre the intercept.</strong> Add a column <code>TarsusC = sparrows.Tarsus .- mean(sparrows.Tarsus)</code> and refit <code>Wing ~ TarsusC</code>. Which numbers changed and which did not? Write one sentence saying what the new intercept means, in millimetres, about a real sparrow. <em>Check:</em> the slope is still 1.203, and the intercept is now 77.85, which is also the mean wing length.</p></li>
<li><p><strong>Predict a bird.</strong> Using <code>fit2</code>, compute by hand — from the coefficients, not with a function — the expected wing length of a male sparrow with a 19.0 mm tarsus, then of a female with the same tarsus. Explain in one sentence what the difference between your two answers is, and why it does not depend on the tarsus value you chose. <em>Check:</em> 79.54 mm and 77.04 mm.</p></li>
<li><p><strong>Was the predictor worth it?</strong> Read <code>data/2012/MBodySize.csv</code>, the file this chapter’s sparrows came from, which has four more columns; one of them is <code>Weight</code>. Regress <code>Weight ~ Tarsus</code>. Report the slope with its 95% interval and the residual SD on the natural scale with <code>exp</code>. Then compare that residual SD with the raw SD of <code>Weight</code> and say, in one sentence with both numbers in it, how much of the scatter in mass a sparrow’s tarsus accounts for. <em>Check:</em> slope 1.24 g per mm, interval 0.99 to 1.49; residual SD 1.24 g against a raw SD of 1.56 g.</p></li>
<li><p><strong>Break it deliberately.</strong> Fit <code>Wing ~ Sex</code> alone, then <code>Wing ~ Tarsus + Sex</code>. The sex coefficient changes. Explain why, using the same reasoning Itchy used for the tarsus slope, and say which of the two numbers you would put in a paper about sexual size dimorphism. <em>Check:</em> 2.68 mm alone, 2.5 mm with tarsus in the model.</p></li>
<li><p><strong>Four levels, three coefficients.</strong> <code>data/2012/Anscombe.csv</code> has a <code>Type</code> column with four levels. Fit <code>Drink ~ Type</code>. You get three coefficients for four types. Explain what happened to the fourth, and write down how to get each type’s mean from the coefficients you were given; then check your four means against <code>combine(groupby(df, :Type), :Drink =&gt; mean =&gt; :m)</code>, which you learned in Class 1. <em>Check:</em> the intercept is 7.5 and none of the other three is larger than 0.001 in size — the four types have the same mean, so the three comparisons against the baseline are all nearly zero.</p></li>
<li><p><strong>Simulate and refit, in a comprehension.</strong> Simulate 200 datasets from <code>fit2</code> with <code>simulate(fit2; nsim = 200, rng = MersenneTwister(2))</code>. Write a one-line function that takes a simulated <code>Wing</code> column, builds a <code>DataFrame</code> with the real <code>Tarsus</code> and <code>Sex</code>, refits <code>Wing ~ Tarsus + Sex</code>, and returns the sex coefficient. Collect the 200 refitted sex coefficients with a comprehension over <code>eachcol(sims)</code>, and report their standard deviation next to the standard error <code>fit2</code> printed for the same coefficient. One sentence on why they should agree. <em>Check:</em> SD of the refits 0.203, reported SE 0.218.</p></li>
</ol>
<p><strong>If you have R.</strong> Fit <code>Wing ~ Tarsus + Sex</code> in R with <code>lm</code> on <code>data/ch2/sparrows.csv</code>. Confirm the coefficients match <code>fit2</code> and the residual SDs do not, and verify numerically that the ratio is √(n/(n − p)) for n = 171 and p = 3. Then answer in one sentence: if a referee asked for “the residual standard deviation”, which would you give, and would you say which one it was? <em>Check:</em> the ratio is 1.0089.</p>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk1-base-camp.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 1 · Base camp</span></a><a class="chapter-nav-link next" href="wk3-glms.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Class 3 · The shape of the noise</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 2 of twelve rungs (ten in version 1, plus a coda) · draft · code last run 2026-09-12<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>