<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 3: the shape of the noise – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 3: the shape of the noise</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 3</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>The shape of the noise</h1>
    <p class="deck">A model that gives a chick a better than hundred per cent chance of surviving is not slightly wrong. It is the wrong shape, and the family is how you fix it.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>All ten classes of version 1 are drafted and their code runs end to end (1–10), with Appendix A, the preface and the coda. Every number and figure on this page was produced when the site was built; the book itself is not written.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Every code block and printed result below was actually run when the site was built, and nothing is typed from memory. Every random draw is seeded in the cell that makes it, so the page comes out the same every time.<br>
      <b>Caveat</b> The data are real: the 2012 Lundy Island chick and female records, read directly from data/2012/ChickSurvival.csv and data/2012/FemaleSuccess.csv (provenance in data/2012/README.md). Nothing here is simulated except the one seeded cell that says so.
    </p>
  </div>
</header>

<div class="wrap">
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>Say why a linear model fitted to a yes-or-no response is the wrong <strong>shape</strong>, not merely inaccurate, and show it from the fitted values alone.</li>
<li>Fit a logistic regression with <code>Binomial()</code> and say what a coefficient means on the log-odds scale.</li>
<li>Turn that coefficient into an odds ratio, and turn the model into a probability for a named animal.</li>
<li>Explain what the family decrees about the <strong>variance</strong>, and why a GLM prints no σ table as a result.</li>
<li>Fit a Poisson model to counts, read a rate ratio, and run the one check that tells you the decree is about to fail.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, 9:00 am, and the whiteboard has been wiped for once.
TOTO has a spreadsheet of dead and living chicks and the expression of
somebody who has already tried something. MOMO has brought a different
dataset entirely, which is not how this is supposed to work but is how
it always goes.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Class 2 gave you a line through a cloud. Every response was a length in
millimetres and could be any number at all. Today both of you have
brought me responses that cannot.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Mine is whether a chick survived. It is a one or a zero.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Mine is how many chicks a female fledged. It is a whole number and it is
never negative.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And neither of those is a length in millimetres, so today we free the
thing Class 2 held fixed without telling you: <strong>the shape of the
noise</strong>. Load Toto’s first.</p></div>
<div id="cell-setup" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/figures.jl includes tools/theme_itchy.jl itself, so one include does both.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">include</span>(<span class="st">"../tools/figures.jl"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span>, <span class="bu">Random</span>, <span class="bu">Printf</span>, <span class="bu">CairoMakie</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">Distributions</span>: Normal, cdf   <span class="co"># only these two names: Distributions also has a Binomial and a Poisson, and today those words mean DRM's families</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set_theme!</span>(<span class="fu">theme_itchy</span>(<span class="op">:</span>light))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>chicks <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/ChickSurvival.csv"</span>, DataFrame)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>n_chicks <span class="op">=</span> <span class="fu">nrow</span>(chicks)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>n_lived <span class="op">=</span> <span class="fu">sum</span>(chicks.Survival)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>p_lived <span class="op">=</span> <span class="fu">mean</span>(chicks.Survival)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows: %d   survived: %d   overall survival: %.4f</span><span class="sc">\n</span><span class="st">"</span>, n_chicks, n_lived, p_lived)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(chicks, <span class="op">:</span>mean, <span class="op">:</span>std, <span class="op">:</span>min, <span class="op">:</span>max, <span class="op">:</span>nmissing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows: 1576   survived: 689   overall survival: 0.4372</code></pre>
</div>
<div id="setup" class="cell-output cell-output-display" data-execution_count="2">
<div><div style="float: left;"><span>5×6 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">std</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">nmissing</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Nothing, Float64}">Union…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Union{Nothing, Float64}">Union…</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Any">Any</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Any">Any</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">Survival</td>
<td style="text-align: left;">0.437183</td>
<td style="text-align: left;">0.496196</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">Sex</td>
<td style="text-align: left; font-style: italic;"></td>
<td style="text-align: left; font-style: italic;"></td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">Mass2</td>
<td style="text-align: left;">3.62754</td>
<td style="text-align: left;">1.18806</td>
<td style="text-align: left;">1.2</td>
<td style="text-align: left;">9.6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">BroodSize</td>
<td style="text-align: left;">3.77538</td>
<td style="text-align: left;">1.01871</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">JulianDate</td>
<td style="text-align: left;">79.4023</td>
<td style="text-align: left;">30.3853</td>
<td style="text-align: left;">22</td>
<td style="text-align: left;">141</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>1576 chicks, of which 689 lived. Look before you model, always, and
today look hardest at the response column.</p></div>
<div class="line"><span class="who toto">Toto</span><p>It is only ever zero or one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is only ever zero or one, and there is no third value hiding anywhere
in it. Hold that thought for exactly as long as it takes you to ignore
it, which I am now going to make you do on purpose.</p></div>
<h3 id="the-model-that-is-the-wrong-shape" class="anchored">The model that is the wrong shape</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Fit it the Class 2 way. Same verb, same box, same family as last week.</p></div>
<div id="cell-fit-gaussian" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>wrong <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>wrong</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-gaussian" class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Distributional regression fit (Gaussian)
  nobs = 1576   logLik = -1018.6237   converged = true
  Residual SD (response scale) = 0.4618   dof_residual = 1573

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -0.1159     0.0374  -3.0990   0.001942
  Mass2         0.1525     0.0098  15.5655  1.249e-54

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                 Coef.  Std.Error         z  Pr(&gt;|z|)
  (Intercept)  -0.7726     0.0178  -43.3760         0</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>It worked. It gave me a slope and a <em>p</em>-value with a lot of zeros
in it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It worked, it converged, and nothing in that output is complaining. This
is the most dangerous kind of wrong: the arithmetic is impeccable and
the model is nonsense. Ask it what it believes. Not what it estimated,
what it <strong>believes</strong> about an actual chick.</p></div>
<div id="gaussian-predictions" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lo, hi <span class="op">=</span> <span class="fu">extrema</span>(<span class="fu">fitted</span>(wrong))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>n_impossible <span class="op">=</span> <span class="fu">count</span>(x <span class="op">-&gt;</span> x <span class="op">&lt;</span> <span class="fl">0</span> <span class="op">||</span> x <span class="op">&gt;</span> <span class="fl">1</span>, <span class="fu">fitted</span>(wrong))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"fitted values run from %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>, lo, hi)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"fitted values outside [0, 1]: %d of %d chicks</span><span class="sc">\n</span><span class="st">"</span>, n_impossible, n_chicks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitted values run from 0.0671 to 1.3477
fitted values outside [0, 1]: 4 of 1576 chicks</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The biggest one is bigger than one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The biggest one is 1.348, and it is a probability. This model believes
that a heavy chick has a 135% chance of surviving, which is a sentence
about birds and it is not a true one. And 4 chicks are given a
probability the world does not contain — counted by <code>count</code>,
handed an arrow function as <code>filter</code> was in Class 1, with
<code>||</code> reading <em>or</em>.</p></div>
<div class="line"><span class="who momo">Momo</span><p>But most of the fitted values are legal. It is 4 chicks out of 1576.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Then do not rest the case on those 4. The impossible predictions are the
fault you can see; there is a worse one underneath, and it is wrong for
every row rather than 4 of them. Class 2’s σ was one number for every
bird. Here the response is a coin flip, so its variance is p(1 − p) —
biggest for a chick with an even chance, shrinking towards nothing at
either extreme. Constant σ is violated <strong>by construction</strong>,
before a single chick is weighed. That is why this model’s standard
errors are wrong at every mass, including the masses where its
predictions are legal, and it is exactly the theme of today’s class
turned on today’s wrong model.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So the <em>p</em>-value was tiny and the model was still impossible.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The <em>p</em>-value was tiny and the model was still impossible, and I
want that on the first page of your notes. <strong>A small
<em>p</em>-value is not evidence that the model is the right
shape.</strong> It cannot be, because it is computed <em>inside</em> the
model. You have to look outside it, at the predictions, at your
organism, and ask whether the model believes anything absurd. Draw it.</p></div>
<div id="cell-fig-two-shapes" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A little vertical jitter so a thousand overlapping zeros and ones are visible</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># as a band rather than a line. Seeded, so the picture is the same every time the site is built.</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>jitter <span class="op">=</span> <span class="fl">0.03</span> <span class="op">.*</span> <span class="fu">randn</span>(rng, n_chicks)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>xs <span class="op">=</span> <span class="fu">range</span>(<span class="fu">minimum</span>(chicks.Mass2), <span class="fu">maximum</span>(chicks.Mass2), length <span class="op">=</span> <span class="fl">200</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>b_wrong <span class="op">=</span> <span class="fu">coef</span>(wrong, <span class="op">:</span>mu)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">540</span>, <span class="fl">380</span>))</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"mass at day 2 (g)"</span>, ylabel <span class="op">=</span> <span class="st">"survived (0 / 1)"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"one straight line through a yes-or-no answer"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">hlines!</span>(ax, [<span class="fl">0.0</span>, <span class="fl">1.0</span>]; color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.5</span>), linestyle <span class="op">=</span> <span class="op">:</span>dot)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, chicks.Mass2, chicks.Survival <span class="op">.+</span> jitter;</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    markersize <span class="op">=</span> <span class="fl">4</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.35</span>))</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, xs, b_wrong[<span class="fl">1</span>] <span class="op">.+</span> b_wrong[<span class="fl">2</span>] <span class="op">.*</span> xs; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"Gaussian"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># legend outside the axis so it can never sit over a data point, matching tools/figures.jl</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div id="fig-two-shapes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-two-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-two-shapes-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Chick survival against mass at day two, jittered vertically so the overlapping zeros and ones separate into a band, with dotted lines at 0 and 1 marking the only two answers the world allows. The straight line from the Gaussian fit climbs off the top of that band for the heaviest chicks and would leave through the floor for chicks lighter than these — a shape free to promise a probability the world does not contain.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>The dotted lines are the only two answers the world allows. The straight
line leaves through the ceiling on the right and would leave through the
floor on the left if the chicks were lighter. That is not a line that
fits badly. That is a line that is the <strong>wrong shape</strong> for
the question, and no amount of extra data will bend it.</p></div>
<h3 id="the-model-that-is-the-right-shape" class="anchored">The model that is the right shape</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Momo, you have been waiting to say something for ten minutes.</p></div>
<div class="line"><span class="who momo">Momo</span><p>In R this was <code>glm</code> with <code>family = binomial</code> on
the end, and I typed it because I was told to. What I never got told is
what it actually changes.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Then that is the lesson, and it changes exactly two things. First, it
puts the straight line somewhere the straight line is allowed to go, and
then bends it back. The line lives on the <strong>log-odds</strong>
scale, which runs from minus infinity to plus infinity like a proper
linear predictor — the straight-line sum of intercept and slopes that
every regression builds before anything bends it — and a function called
the <strong>link</strong> squashes it back into nought-to-one before it
meets a chick. Second, and this is the part almost nobody is taught, it
changes what the model claims about the <strong>noise</strong>. Watch
both. One word changes in the call.</p></div>
<div id="cell-fit-logistic" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>logit_fit <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2)), <span class="fu">Binomial</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>logit_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-logistic" class="cell-output cell-output-display" data-execution_count="8">
<pre><code>Distributional regression fit (Binomial)
  nobs = 1576   logLik = -968.7711   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error         z   Pr(&gt;|z|)
  (Intercept)  -2.8152     0.1968  -14.3035  2.081e-46
  Mass2         0.6999     0.0514   13.6096  3.509e-42</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>Same verb, same box. The family is different and the numbers are bigger.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The family is different, the numbers are on a different scale, and
something has <strong>gone missing</strong>. Momo, you were the one who
complained about the second table in Class 2. Where is it?</p></div>
<div class="line"><span class="who momo">Momo</span><p>There is no σ table.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>There is no σ table, and that absence is the whole second half of today.
Park it for five minutes while we read the coefficient, because the
coefficient is on a scale neither of you has met.</p></div>
<div id="logit-scale" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>b_logit <span class="op">=</span> <span class="fu">coef</span>(logit_fit, <span class="op">:</span>mu)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>slope_logodds <span class="op">=</span> b_logit[<span class="fl">2</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>odds_ratio <span class="op">=</span> <span class="fu">exp</span>(slope_logodds)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"slope on the log-odds scale : %.4f</span><span class="sc">\n</span><span class="st">"</span>, slope_logodds)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"exp(slope), the odds ratio  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, odds_ratio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>slope on the log-odds scale : 0.6999
exp(slope), the odds ratio  : 2.0135</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>The number the model estimated is 0.7, and on its own it means nothing
to a biologist, because nobody has ever had an intuition about log-odds.
Exponentiate it and it becomes a sentence you can say to a bird person:
<strong>one extra gram of mass multiplies a chick’s odds of surviving by
2.01.</strong> Odds, not probability. They are not the same thing and I
will make you say the difference out loud.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Odds are the chance it happens divided by the chance it does not.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Exactly that, and the reason the model works in odds is that odds can be
multiplied without ever leaving the space of legal answers. Double them,
double them again, they never reach one. Probabilities do not behave:
add ten per cent to ninety-five per cent twice and you have left the
world. That is why the link exists.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Then give me a probability. That is what I would put in the paper.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Then ask the model for one, at a mass you can point at.</p></div>
<div id="predict-probability" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> (; Mass2 <span class="op">=</span> [<span class="fl">2.0</span>, <span class="fl">3.5</span>, <span class="fl">5.0</span>])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> <span class="fu">predict</span>(logit_fit, grid)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>p_mid <span class="op">=</span> <span class="fu">predict</span>(logit_fit, (; Mass2 <span class="op">=</span> [<span class="fl">3.5</span>]); se <span class="op">=</span> <span class="cn">true</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (m, p) <span class="kw">in</span> <span class="fu">zip</span>(grid.Mass2, p_hat)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"a %.1f g chick: probability of surviving %.4f</span><span class="sc">\n</span><span class="st">"</span>, m, p)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">at 3.5 g, standard error on that probability (delta method): %.4f</span><span class="sc">\n</span><span class="st">"</span>, p_mid.se[<span class="fl">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a 2.0 g chick: probability of surviving 0.1954
a 3.5 g chick: probability of surviving 0.4096
a 5.0 g chick: probability of surviving 0.6647

at 3.5 g, standard error on that probability (delta method): 0.0134</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p><strong>A three-and-a-half gram chick has about a 41% chance of
surviving.</strong> A two-gram chick, 20%. A five-gram chick, 66%. Those
are sentences about chicks, they are in the units the question was asked
in, and not one of them is impossible. The last line puts a standard
error on the middle one, and notice how it was made: the model’s
uncertainty lives on the log-odds scale, so the engine carries it
through the squashing function onto the probability scale. That piece of
arithmetic is called the <strong>delta method</strong>, and whenever
this book says “delta-method standard error” that is all it means.</p></div>
<div class="line"><span class="who toto">Toto</span><p>The grid is not a data frame. It starts with a semicolon.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is a <strong>NamedTuple</strong>, the lightest table Julia has:
<code>(; Mass2 = [2.0, 3.5, 5.0])</code> is one named field holding a
vector, and <code>grid.Mass2</code> reaches it exactly as
<code>chicks.Mass2</code> reaches a column. <code>predict</code> asks
for one because it needs only the predictor values, not a whole frame’s
machinery. And under it is your first <strong>loop written out</strong>.
<code>for (m, p) in zip(grid.Mass2, p_hat)</code> walks two vectors side
by side — <code>zip</code> pairs the first mass with the first
probability, and so on — the body runs once per pair, and
<code>end</code> closes it. Last week’s comprehension was this loop with
the printing replaced by collecting. Now put the two models on the same
picture.</p></div>
<div id="cell-fig-curve" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>p_curve <span class="op">=</span> <span class="fu">predict</span>(logit_fit, (; Mass2 <span class="op">=</span> <span class="fu">collect</span>(xs)))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">540</span>, <span class="fl">380</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"mass at day 2 (g)"</span>, ylabel <span class="op">=</span> <span class="st">"probability of surviving"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"the same data, two shapes"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hlines!</span>(ax, [<span class="fl">0.0</span>, <span class="fl">1.0</span>]; color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.5</span>), linestyle <span class="op">=</span> <span class="op">:</span>dot)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, chicks.Mass2, chicks.Survival <span class="op">.+</span> jitter;</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    markersize <span class="op">=</span> <span class="fl">4</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.35</span>))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, xs, b_wrong[<span class="fl">1</span>] <span class="op">.+</span> b_wrong[<span class="fl">2</span>] <span class="op">.*</span> xs;</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    linewidth <span class="op">=</span> <span class="fl">2</span>, linestyle <span class="op">=</span> <span class="op">:</span>dash, label <span class="op">=</span> <span class="st">"Gaussian"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, xs, p_curve; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"Binomial, logit link"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># legend outside the axis so it can never sit over a data point, matching tools/figures.jl</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div id="fig-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-curve-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The same jittered survival cloud, now with the Gaussian line dashed and the logistic curve solid over it. The curve never crosses either dotted bound. Toward the heavy end it flattens sharply as survival becomes near-certain, so an extra gram buys almost nothing there; toward the light end, within this file’s range, it is still climbing well short of flat, and the most any gram buys is near the steepest point in between.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The curve flattens out at both ends.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Look again before you hand me “both.” It flattens hard on the heavy end,
where survival is already close to certain, and an extra gram buys
almost nothing there. On the light end, in the range these chicks
actually give you, it has not gotten there yet — it is still climbing.
The curve cannot go above one or below zero, so it does run out of room
eventually, but “eventually” is not the same as “in this picture.”
Between the light end and that heavy flattening there is a steepest
point. Where that point falls is a number, not a feeling, so compute it
before you say anything about birds.</p></div>
<div id="where-a-gram-matters" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>gain_low  <span class="op">=</span> p_hat[<span class="fl">2</span>] <span class="op">-</span> p_hat[<span class="fl">1</span>]          <span class="co"># 2.0 g -&gt; 3.5 g</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>gain_high <span class="op">=</span> p_hat[<span class="fl">3</span>] <span class="op">-</span> p_hat[<span class="fl">2</span>]          <span class="co"># 3.5 g -&gt; 5.0 g</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>inflection <span class="op">=</span> <span class="op">-</span>b_logit[<span class="fl">1</span>] <span class="op">/</span> b_logit[<span class="fl">2</span>]    <span class="co"># the mass at which the model says p = 1/2</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>mean_mass <span class="op">=</span> <span class="fu">mean</span>(chicks.Mass2)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>frac_below <span class="op">=</span> <span class="fu">mean</span>(chicks.Mass2 <span class="op">.&lt;</span> inflection)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"2.0 g -&gt; 3.5 g buys         : %.4f of probability</span><span class="sc">\n</span><span class="st">"</span>, gain_low)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"3.5 g -&gt; 5.0 g buys         : %.4f of probability</span><span class="sc">\n</span><span class="st">"</span>, gain_high)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"steepest point (p = 1/2) at : %.4f g</span><span class="sc">\n</span><span class="st">"</span>, inflection)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mean mass in these data     : %.4f g</span><span class="sc">\n</span><span class="st">"</span>, mean_mass)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"proportion lighter than it  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, frac_below)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.0 g -&gt; 3.5 g buys         : 0.2142 of probability
3.5 g -&gt; 5.0 g buys         : 0.2551 of probability
steepest point (p = 1/2) at : 4.0224 g
mean mass in these data     : 3.6275 g
proportion lighter than it  : 0.6459</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The second step buys <em>more</em> than the first.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It does. Two grams to three and a half buys 0.214 of survival
probability; three and a half to five buys 0.255. Across the range where
these chicks actually live, the curve is <strong>accelerating</strong>.
Had I told you a gram matters most to the smallest chick, you would now
be holding a sentence your own output contradicts.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Why that way round?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because a logistic curve is symmetric about a half, and the mass at
which it reaches a half is minus the intercept over the slope: 4.02 g.
The average chick in this file weighs 3.63 g, and 65% of them are
lighter than that steepest point. The majority of this sample, the
average chick included, is still climbing <em>towards</em> the steepest
point rather than coming down the far side. So the honest sentence is
the symmetric one: <strong>a gram matters most to a middling chick —
middling meaning near 4.02 g, where the model gives it an even chance —
and least to a chick already nearly certain to live, or nearly certain
to die.</strong></p></div>
<div class="line"><span class="who momo">Momo</span><p>I have read “diminishing returns” in a dozen papers about exactly this.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And it is true wherever the data sit above the inflection — the steepest
point, where p = 1/2 — and false wherever they sit below it, which is
why it is something you compute rather than something you say. What
holds on both sides is that a gram is <strong>not</strong> worth the
same everywhere, and the straight line insists that it is. When somebody
asks you why not just use a linear model, that is the answer. Not “the
residuals are non-normal”. That.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Can I put brood size in as well?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You can, and the sentence you get is the Class 2 sentence with one extra
clause.</p></div>
<div id="cell-fit-two-predictors" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>logit2 <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2 <span class="op">+</span> BroodSize)), <span class="fu">Binomial</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>logit2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-two-predictors" class="cell-output cell-output-display" data-execution_count="16">
<pre><code>Distributional regression fit (Binomial)
  nobs = 1576   logLik = -964.9841   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error         z   Pr(&gt;|z|)
  (Intercept)  -3.4561     0.3099  -11.1508  7.099e-29
  Mass2         0.7204     0.0523   13.7828  3.236e-43
  BroodSize     0.1495     0.0546    2.7402   0.006141</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Each coefficient is now “what one more of this buys, <strong>holding the
other fixed</strong>”, exactly as in Class 2, and the exponentials are
odds ratios rather than millimetres. A gram of mass multiplies the odds
by 2.06; a chick more in the brood multiplies them by 1.16. And AIC
<strong>fell by</strong> 5.57 when we added it, so the extra predictor
paid for itself.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Bigger broods are <em>better</em> for a chick? I would have guessed the
opposite.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>So would I, and this is where you stop being a statistician and go back
to being a biologist. A brood is big because a parent could afford a big
one. The model has not told you that crowding is good; it has told you
that, in these data, chicks in big broods survive better, and the reason
for that is a question about territories and parents that no coefficient
will answer. This is also exactly the point where Class 9 will tell you
that the chicks in one brood are not independent, so that standard error
is too small. Today we pretend — and on this file we would have to. It
records <code>BroodSize</code>, how many chicks were in the nest, and it
never records <em>which</em> nest. You cannot put a random effect on a
grouping nobody wrote down, so the repair is a dataset that carries a
brood identifier, not a cleverer formula on this one. Class 9 stops
pretending, on a file that can.</p></div>
<h3 id="the-shape-of-the-noise" class="anchored">The shape of the noise</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Now the missing table, which is the actual title of this class. Momo, in
Class 2 what did σ do?</p></div>
<div class="line"><span class="who momo">Momo</span><p>It said how far the birds scattered around the line, and it was the same
number for every bird.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And it was a <strong>free parameter</strong>: the model estimated it
from the data, and in Class 4 you will put predictors on it. Today it is
gone, and it is gone because it is no longer free. Toto, a chick with a
survival probability of one half. How much does it vary?</p></div>
<div class="line"><span class="who toto">Toto</span><p>…it either lives or it dies.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And across many such chicks, the variance of that coin flip is p times
one minus p, which for a half is a quarter. You did not estimate that.
You did not get a choice about it. <strong>The moment you said
<code>Binomial()</code>, you decreed that the variance is p(1 −
p)</strong> — fixed by the mean, with no freedom left in it. Same for
Momo’s counts in twenty minutes: say <code>Poisson()</code> and you have
decreed that the variance equals the mean. Show them.</p></div>
<div id="variance-decree" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>p_fit <span class="op">=</span> <span class="fu">fitted</span>(logit_fit)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>decreed <span class="op">=</span> p_fit <span class="op">.*</span> (<span class="fl">1</span> <span class="op">.-</span> p_fit)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>p_lo, p_hi <span class="op">=</span> <span class="fu">extrema</span>(p_fit)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>v_lo, v_hi <span class="op">=</span> <span class="fu">extrema</span>(decreed)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"fitted probability     : %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>, p_lo, p_hi)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"decreed variance p(1-p): %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>, v_lo, v_hi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fitted probability     : 0.1218 to 0.9802
decreed variance p(1-p): 0.0194 to 0.2500</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Numbers. You said “show”, and I got two ranges.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Fair complaint. Here is the shape those numbers came from, not a
description of it.</p></div>
<div id="cell-fig-variance-decree" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p_grid <span class="op">=</span> <span class="fu">range</span>(<span class="fl">0</span>, <span class="fl">1</span>, length <span class="op">=</span> <span class="fl">200</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>var_grid <span class="op">=</span> p_grid <span class="op">.*</span> (<span class="fl">1</span> <span class="op">.-</span> p_grid)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">480</span>, <span class="fl">360</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"p"</span>, ylabel <span class="op">=</span> <span class="st">"Var(y) = p(1 - p)"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"the noise Binomial() decrees"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted range shaded first, curve drawn on top so it is never hidden by it</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">vspan!</span>(ax, p_lo, p_hi; color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.15</span>), label <span class="op">=</span> <span class="st">"this fit's p_lo–p_hi"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, p_grid, var_grid; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"Var = p(1 - p)"</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, [<span class="fl">0.5</span>], [<span class="fl">0.25</span>]; markersize <span class="op">=</span> <span class="fl">9</span>, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">2</span>), label <span class="op">=</span> <span class="st">"peak: p = 1/2, Var = 1/4"</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># legend outside the axis, matching tools/figures.jl</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div id="fig-variance-decree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-variance-decree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-variance-decree-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-variance-decree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The variance Binomial() decrees, Var = p(1 − p), across every probability the family allows: it peaks at 1/4 when p = 1/2 and is pinned to zero at both ends. The shaded strip is where this chapter’s fitted probabilities sit on that curve.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>That curve is not fitted to anything. It is what <code>Binomial()</code>
commits you to the moment you say the word, for every p from zero to
one, on every dataset that will ever exist. It peaks at a quarter, for
the chick with an even chance, and falls to zero at either end, where
there is nothing left to be unsure about. The shaded strip is where this
chapter’s own chicks sit on it: fitted probabilities from 0.122 to 0.98,
so decreed variances from 0.019 at whichever end sits nearer a wall up
to 0.25 for the chicks nearest an even chance. Every one of those
numbers was fixed by the fitted mean and nothing else. And notice what
the picture cannot show you: no <code>Mass2</code> on either axis, no
<code>BroodSize</code>, no predictor at all. The variance function does
not know what moved the mean. It only knows the mean itself. There is no
σ table to print because there is no σ to estimate: the family has
already spent it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And if the decree is wrong?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>For Toto’s chicks it cannot be, and that is worth saying slowly, because
it is the one place where the word “assumption” misleads. A response
that is only ever zero or one has variance p(1 − p) as a matter of
<strong>arithmetic</strong>: a coin that lands heads with probability p
has that variance and no other is available to it. There is no
overdispersed Bernoulli — the name for exactly that single coin flip —
to go looking for. What <em>can</em> be wrong with binary data is the
other thing — that the rows are not independent draws, because chicks
from one nest share a pair of parents and a territory — and that is
clustering, which is <strong>Class 6</strong>, not Class 4.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And for my counts?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>For your counts the variance really is a separate claim, and data can
contradict it. Then you are in trouble, quietly, in the standard errors,
and you will not see it in the coefficients. That is Class 4, and I am
deliberately not teaching it today. What I <em>will</em> do is give you
the check, at the end of the hour, on Momo’s counts, where it fails in
front of you. One sentence for whenever you read somebody else’s R
output: <code>glm</code> prints the decree out loud, as the line
“(Dispersion parameter for binomial family taken to be 1)”, where this
engine leaves it implicit in the absent σ table — and that line is not
boilerplate, it is the model’s claim about the noise, phrased as an
instruction because nothing was estimated and nothing was checked.</p></div>
<h3 id="is-it-any-good" class="anchored">Is it any good?</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Before anybody writes this down: residuals. And a plain residual is
useless here, because “observed minus fitted” for a chick that lived is
one minus a probability, and those cannot be normally distributed no
matter how right the model is.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So what do I plot?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p><strong>Randomised quantile residuals</strong> (Dunn &amp; Smyth 1996).
Take one chick and make its residual by hand, in three steps, and then
the plot will mean something.</p></div>
<div id="one-chick-residual" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="op">=</span> <span class="fu">fitted</span>(logit2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="fl">1</span>                                   <span class="co"># the first chick in the file</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>y_i, p_i <span class="op">=</span> chicks.Survival[i], p2[i]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1. How much probability does the model put at or below the value we saw?</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Below "died" there is nothing, so a dead chick's answer is anywhere in [0, 1 - p];</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># a survivor's is anywhere in [1 - p, 1]. An interval, not a number.</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>lo_i, hi_i <span class="op">=</span> y_i <span class="op">==</span> <span class="fl">0</span> ? (<span class="fl">0.0</span>, <span class="fl">1</span> <span class="op">-</span> p_i) <span class="op">:</span> (<span class="fl">1</span> <span class="op">-</span> p_i, <span class="fl">1.0</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2. Draw a point uniformly inside that interval. Seeded, like every draw.</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>rng_q <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">31</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>u_i <span class="op">=</span> lo_i <span class="op">+</span> (hi_i <span class="op">-</span> lo_i) <span class="op">*</span> <span class="fu">rand</span>(rng_q)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3. Which standard-normal value has exactly that much probability below it?</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>r_i <span class="op">=</span> <span class="fu">quantile</span>(<span class="fu">Normal</span>(), u_i)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"chick %d: survived = %d, fitted p = %.4f</span><span class="sc">\n</span><span class="st">"</span>, i, y_i, p_i)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"interval of probability it occupies : [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>, lo_i, hi_i)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"uniform draw inside it              : %.4f</span><span class="sc">\n</span><span class="st">"</span>, u_i)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"its randomised quantile residual    : %.4f</span><span class="sc">\n</span><span class="st">"</span>, r_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>chick 1: survived = 1, fitted p = 0.3808
interval of probability it occupies : [0.6192, 1.0000]
uniform draw inside it              : 0.6240
its randomised quantile residual    : 0.3161</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Step one asks the fitted model how much probability it puts at or below
the value you saw. For a chick that survived, that is not one number,
because a yes-or-no answer owns a whole slab of probability rather than
a point: this chick’s slab runs from 0.619 to 1.0. In the cell that is
the line with the question mark:
<code>y_i == 0 ? (0.0, 1 - p_i) : (1 - p_i, 1.0)</code> reads <em>if the
chick died, this pair, otherwise that pair</em> — Julia’s one-line
<code>if</code>, each pair being an interval. Step two draws a point
uniformly inside the slab; that is the <em>randomised</em> part, and it
is why the call takes a seed. Step three looks that draw up on the
standard normal curve and asks which value has exactly that much
probability below it. That value is the residual: 0.32, for a chick the
model gave a 38% chance to. Draw the three steps.</p></div>
<div id="cell-fig-one-chick" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>zs <span class="op">=</span> <span class="fu">range</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>, length <span class="op">=</span> <span class="fl">300</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">480</span>, <span class="fl">360</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"z"</span>, ylabel <span class="op">=</span> <span class="st">"probability below z"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"one chick, three steps"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hspan!</span>(ax, lo_i, hi_i; color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.15</span>), label <span class="op">=</span> <span class="st">"the slab this chick occupies"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, zs, <span class="fu">cdf</span>.(<span class="fu">Normal</span>(), zs); linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"standard normal"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, [<span class="op">-</span><span class="fl">3.5</span>, r_i, r_i], [u_i, u_i, <span class="fl">0.0</span>]; linestyle <span class="op">=</span> <span class="op">:</span>dash, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">2</span>))</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, [r_i], [u_i]; markersize <span class="op">=</span> <span class="fl">9</span>, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">2</span>), label <span class="op">=</span> <span class="st">"the draw, and its residual"</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<div id="fig-one-chick" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-one-chick-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-one-chick-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-one-chick-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: One chick’s randomised quantile residual, made by hand. The curve is the standard normal’s cumulative probability; the shaded band on the vertical axis is the slab of probability the chick’s own outcome occupies under the fitted model; the point is a uniform draw inside that slab, carried across to the curve and down to the residual on the horizontal axis.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Do that for every chick and you have 1576 numbers that are standard
normal draws if the model is right, whatever the family was, so one
diagnostic plot works for every chapter in this book. The plot is a
<strong>worm plot</strong>: sort the residuals, set each beside where it
would sit if the residuals really were standard normal, and draw the
difference. Flat and near zero means there is nothing to find; a tilt or
a curve names what is. The engine makes all 1576 in one call, and
because step two is a draw, the call takes a seed.</p></div>
<div id="cell-fig-diagnostic" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>qres <span class="op">=</span> <span class="fu">residuals</span>(logit2; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">3</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quantile residuals: mean %.4f, SD %.4f  (both should be near 0 and 1)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(qres), <span class="fu">std</span>(qres))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>fig_l <span class="op">=</span> <span class="fu">fig_diagnostic</span>(qres; title <span class="op">=</span> <span class="st">"logistic fit, randomised quantile residuals"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># One fixed vertical window, shared with the Poisson worm plot below, so the</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># two panels are comparable by eye.</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ylims!</span>(fig_l.content[<span class="fl">1</span>], <span class="op">-</span><span class="fl">1.2</span>, <span class="fl">1.2</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>fig_l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>quantile residuals: mean -0.0188, SD 1.0201  (both should be near 0 and 1)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div id="fig-diagnostic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-diagnostic-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Worm plot of the two-predictor logistic fit’s randomised quantile residuals: the residuals lined up from smallest to largest, each compared with where a perfect standard-normal draw would sit, so a good model gives a flat scatter near zero and a bad one wriggles. Here the scatter sits close to the zero line and inside the pale band — the shape a diagnostic takes when there is nothing left to find. The vertical scale is fixed and shared with the Poisson worm plot below, so the two are honestly comparable by eye rather than each stretched to fill its own axis.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>That looks like nothing much is happening.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>“Nothing much is happening” is what a passing diagnostic looks like, and
you should be suspicious of how often the plots in papers look more
interesting than this. The spread is 1.02, which is one, near enough.
But award the model very few marks for it. On a 0/1 response a spread
near one is close to automatic, because p(1 − p) is arithmetic rather
than a promise the data could break. Treat this plot as the
<strong>baseline</strong>: it is what the diagnostic looks like when
there is nothing in it to find. Remember the picture in twenty minutes,
when Momo’s counts give it something.</p></div>
<h3 id="momos-counts" class="anchored">Momo’s counts</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Right. Momo has been patient. Different file, different question, same
two changes.</p></div>
<div id="cell-read-females" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>females <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/FemaleSuccess.csv"</span>, DataFrame)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>n_fem <span class="op">=</span> <span class="fu">nrow</span>(females)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows: %d</span><span class="sc">\n</span><span class="st">"</span>, n_fem)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(females, <span class="op">:</span>mean, <span class="op">:</span>std, <span class="op">:</span>min, <span class="op">:</span>max, <span class="op">:</span>nmissing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows: 163</code></pre>
</div>
<div id="read-females" class="cell-output cell-output-display" data-execution_count="28">
<div><div style="float: left;"><span>3×6 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">std</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">nmissing</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">Fledglings</td>
<td style="text-align: right;">3.20859</td>
<td style="text-align: right;">2.33189</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">EggNo</td>
<td style="text-align: right;">9.77914</td>
<td style="text-align: right;">4.32624</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">Age</td>
<td style="text-align: right;">1.88344</td>
<td style="text-align: right;">0.870594</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>163 females, and how many chicks each one got out of the nest.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And the response is a <strong>count</strong>. Never negative, never a
half, and there is no upper limit written anywhere. That is a different
shape again, and it gets a different family and a different link.</p></div>
<div id="cell-fit-poisson" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pois_fit <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>pois_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-poisson" class="cell-output cell-output-display" data-execution_count="30">
<pre><code>Distributional regression fit (Poisson)
  nobs = 163   logLik = -367.9932   converged = true

Mean model (μ):
  H0: coefficient = 0
                Coef.  Std.Error       z   Pr(&gt;|z|)
  (Intercept)  0.7067     0.1081  6.5379  6.241e-11
  Age          0.2325     0.0478  4.8667  1.135e-06</code></pre>
</div>
</div>
<div id="poisson-scale" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>b_pois <span class="op">=</span> <span class="fu">coef</span>(pois_fit, <span class="op">:</span>mu)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>rate_ratio <span class="op">=</span> <span class="fu">exp</span>(b_pois[<span class="fl">2</span>])</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"slope on the log scale : %.4f</span><span class="sc">\n</span><span class="st">"</span>, b_pois[<span class="fl">2</span>])</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"exp(slope), rate ratio : %.4f</span><span class="sc">\n</span><span class="st">"</span>, rate_ratio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>slope on the log scale : 0.2325
exp(slope), rate ratio : 1.2618</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>The link here is the logarithm rather than the logit, for the same
reason: a count’s mean must stay positive, and a log keeps it there
while the linear predictor roams. Exponentiate and you get a
<strong>rate ratio</strong>: <strong>each extra year of age multiplies a
female’s expected number of fledglings by 1.262.</strong> Not “adds”,
multiplies. Every log link in this book makes coefficients
multiplicative, and reading one additively is the commonest mistake in
the literature.</p></div>
<div class="line"><span class="who toto">Toto</span><p>And no σ table again.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>No σ table again, and now the decree is even stronger than the binomial
one. <strong>Poisson says the variance equals the mean.</strong> One
number for both. That is an extremely strong claim about a real animal
and it is testable in one line, so test it.</p></div>
<div id="mean-vs-variance" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>m_counts <span class="op">=</span> <span class="fu">mean</span>(females.Fledglings)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>v_counts <span class="op">=</span> <span class="fu">var</span>(females.Fledglings)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mean of the counts     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, m_counts)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"variance of the counts : %.4f</span><span class="sc">\n</span><span class="st">"</span>, v_counts)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"variance / mean        : %.4f   (Poisson decrees 1)</span><span class="sc">\n</span><span class="st">"</span>, v_counts <span class="op">/</span> m_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mean of the counts     : 3.2086
variance of the counts : 5.4377
variance / mean        : 1.6947   (Poisson decrees 1)</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>It is not one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is not one, it is 1.69, and the counts are scattering considerably
more than the family says they may. That is called
<strong>overdispersion</strong>, it is the single most common thing
wrong with a Poisson model in ecology, and it is Class 4’s entire
subject. I am not going to fix it today. I am going to make sure you can
<em>see</em> it, from two directions, because seeing it is the skill.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Two directions?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The crude one you just ran, on the raw counts, which mixes up real
variation with variation the predictors explain. And the honest one, on
the residuals of the actual fit, where anything the model explained has
already been taken out.</p></div>
<div id="cell-fig-diagnostic-poisson" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>qres_pois <span class="op">=</span> <span class="fu">residuals</span>(pois_fit; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">4</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"logistic fit, quantile residual SD : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(qres))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Poisson fit,  quantile residual SD : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(qres_pois))</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>fig_p <span class="op">=</span> <span class="fu">fig_diagnostic</span>(qres_pois; title <span class="op">=</span> <span class="st">"Poisson fit, randomised quantile residuals"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Same fixed vertical window as the logistic worm plot above.</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ylims!</span>(fig_p.content[<span class="fl">1</span>], <span class="op">-</span><span class="fl">1.2</span>, <span class="fl">1.2</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>fig_p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>logistic fit, quantile residual SD : 1.0201
Poisson fit,  quantile residual SD : 1.2981</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="35">
<div id="fig-diagnostic-poisson" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-diagnostic-poisson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-diagnostic-poisson-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-poisson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Worm plot of the Poisson fit’s randomised quantile residuals, on the same fixed vertical scale as the logistic worm plot above. The tilt is the overdispersion the variance-to-mean ratio already showed: the residuals are spread wider than a standard normal, so the line of sorted residuals climbs from left to right instead of lying flat inside the pale band — and because both panels now share one axis, that extra spread is something the eye can see, not only the printed standard deviations.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Compare the two lines. The survival residuals have spread 1.02, which is
one, near enough. The count residuals have spread 1.3, which is not:
they are wider than the family says they may be, and wider
<em>after</em> age has been accounted for, so it is not something age
can explain. Two different checks, one verdict, and the verdict is that
the family is claiming a tidiness these females do not have.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So the model is wrong and you are telling me to leave it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>I am telling you that you now know something specific and testable about
how it is wrong, which is a great deal better than most published
models, and that the repair has a name, a chapter and a one-line change
in the same <code>bf</code> box. Draw the fit before you go.</p></div>
<div id="cell-fig-fledglings" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>age_grid <span class="op">=</span> <span class="fu">range</span>(<span class="fu">minimum</span>(females.Age), <span class="fu">maximum</span>(females.Age), length <span class="op">=</span> <span class="fl">100</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>rate_curve <span class="op">=</span> <span class="fu">predict</span>(pois_fit, (; Age <span class="op">=</span> <span class="fu">collect</span>(age_grid)))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>rng2 <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">99</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>age_jit <span class="op">=</span> females.Age <span class="op">.+</span> <span class="fl">0.06</span> <span class="op">.*</span> <span class="fu">randn</span>(rng2, n_fem)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">540</span>, <span class="fl">380</span>))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"age (years)"</span>, ylabel <span class="op">=</span> <span class="st">"fledglings"</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"counts, and the rate the model expects"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, age_jit, females.Fledglings; markersize <span class="op">=</span> <span class="fl">6</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.5</span>))</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, age_grid, rate_curve; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"Poisson, log link"</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co"># legend outside the axis, for the same reason as fig-curve and fig-two-shapes above</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<div id="fig-fledglings" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-fledglings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk3-glms_files/figure-html/fig-fledglings-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fledglings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Fledgling counts against female age, jittered horizontally, with the Poisson fit’s rate curve laid over them bending gently upward on the log scale. The vertical scatter at each age is wider than that curve’s own decree allows — the overdispersion the chapter has already shown by two other routes.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>The curve bends upward because a log link makes it, and gently, because
the coefficient is small. And look at the vertical scatter at each age:
that is what 1.69 looks like. The line is defensible. The claim about
the spread around it is not, and you can say precisely which is which.
That is the whole difference between using a model and believing one.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So today’s summary is: pick the family.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Today’s summary is: the family picks two things for you, and only one of
them is the shape of the curve. The other is the shape of the noise, you
did not choose it, and Class 4 is what happens when it is wrong.</p></div>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>A GLM changes two things, not one.</strong> The <strong>link</strong> puts the linear predictor somewhere it is allowed to roam and squashes it back into the legal range; the <strong>variance function</strong> says how much the response scatters around that mean. Both are decided by the family, together, the moment you name it.</li>
<li><strong>Wrong shape is not the same as bad fit.</strong> A Gaussian model on a 0/1 response converges, reports tiny <em>p</em>-values, and predicts probabilities outside zero and one. No amount of data fixes that, because nothing about a straight line stops at one. Look at the fitted values before you look at the coefficients — and note that the impossible predictions are only the visible fault. Constant σ is violated by construction on a 0/1 response, whose variance p(1 − p) moves with the mean, so the Gaussian model’s standard errors are wrong at every value of the predictor, including the ones where its predictions are legal.</li>
<li><strong>Log-odds, odds ratios, probabilities.</strong> The coefficient is on the log-odds scale, where it is additive and uninterpretable. <code>exp</code> of it is an <strong>odds ratio</strong>, which is multiplicative and speakable. <code>predict</code> gives a <strong>probability</strong>, which is what a biologist actually wanted. Report at least one of the last two, never only the first.</li>
<li><strong>Odds are not probabilities.</strong> Odds are p/(1 − p), and they can be multiplied for ever without leaving the legal range, which is the reason the model works in them.</li>
<li><strong>The curve flattens at both ends and is steepest in the middle.</strong> A logistic curve is symmetric about p = ½, which it reaches at −b₀/b₁ on the predictor’s own scale. An extra unit is therefore worth <strong>most</strong> to an individual sitting near that point and least to one already nearly certain either way. Whether your own data show diminishing or <em>increasing</em> returns depends on which side of that point they lie: most of these chicks sit below it, the mean among them, so over the bulk of the data an extra gram buys more as a chick gets heavier, not less. Compute the inflection; do not assume the shape of the story. What holds on both sides is that a unit is not worth the same everywhere, and the straight line insists that it is.</li>
<li><strong>The variance is decreed, which is why there is no σ table.</strong> Binomial says the variance is p(1 − p); Poisson says it equals the mean. Neither is estimated, so neither is printed. R states this out loud as “dispersion parameter taken to be 1”; our engine states it by having nothing to print. Read the two decrees differently, though: for a 0/1 response, p(1 − p) is an <strong>identity</strong> and there is no overdispersed Bernoulli to find, so what can go wrong in binary data is the independence of the rows (Class 6), not the variance function. For counts, the Poisson decree is a real claim that data can contradict, and that is Class 4.</li>
<li><strong>Rate ratios are multiplicative.</strong> With a log link, a coefficient exponentiates into a factor, not an increment. Reading one additively is a common and serious error.</li>
<li><strong>Check the decree in two places.</strong> The crude check is the variance-to-mean ratio of the raw counts. The honest check is the spread of randomised quantile residuals from the fitted model, which is standard normal if the family is right whatever the family is (Dunn &amp; Smyth 1996): a residual is made by finding the slab of probability the observed value occupies under the fitted model, drawing a point inside it, and looking that point up on the normal curve. Ours came out at one, near enough, for the survivals and wider than one for the counts. Overdispersion, and Class 4 — and only the counts can have it.</li>
<li><strong>This chapter pretends rows are independent.</strong> Chicks share broods; Class 6 frees the correlation between rows on repeated measures of one bird, and Class 9 is where this pretence ends, on a file that records the brood. The link and the variance function survive the repair; the standard errors printed here do not.</li>
</ul>
<h3 id="julia-you-used" class="anchored">Julia you used</h3>
<ul>
<li><strong><code>(; Mass2 = [2.0, 3.5, 5.0])</code>.</strong> A <strong>NamedTuple</strong>: named fields, reached with a dot like columns, and the lightest table Julia has. <code>predict</code> takes one for its new data; <code>predict(...; se = true)</code> returns one, <code>(; prediction, se)</code>.</li>
<li><strong><code>for (m, p) in zip(a, b) ... end</code>.</strong> A loop written out: <code>zip</code> walks two vectors side by side, the body runs once per pair, <code>end</code> closes it. A comprehension is this loop with collecting in place of printing.</li>
<li><strong><code>function name(y) ... end</code>.</strong> The long form of a function definition, for a body of several lines; the last expression is returned.</li>
<li><strong><code>ysim[:, k]</code> and <code>size(ysim, 2)</code>.</strong> The <em>k</em>-th column of a matrix, a colon meaning all of that dimension, and its number of columns.</li>
<li><strong><code>cond ? a : b</code>.</strong> A one-line <code>if</code>: <code>a</code> when the condition holds, otherwise <code>b</code>.</li>
<li><strong><code>count(x -&gt; x &lt; 0 || x &gt; 1, v)</code>.</strong> Counts the elements for which the function is true; <code>||</code> is <em>or</em>, <code>&amp;&amp;</code> is <em>and</em>.</li>
<li><strong><code>collect(xs)</code>.</strong> Turns a range into an ordinary vector, for a function that wants one.</li>
<li><strong><code>using Distributions: Normal, cdf</code>.</strong> Imports two names and no others, because <code>Distributions</code> also has a <code>Binomial</code> and a <code>Poisson</code> and this week those words are DRM’s families.</li>
</ul>
<h3 id="calls-you-used" class="anchored">Calls you used</h3>
<ul>
<li><code>drm(bf(@formula(y ~ x)), Binomial(); data = df)</code> and <code>Poisson()</code>: logistic regression on a 0/1 column, and counts with a log link. Same verb, same box, same positional family and keyword data as Class 2.</li>
<li><code>coef(fit, :mu)</code>: coefficients on the <strong>link</strong> scale — log-odds for <code>Binomial()</code>, log for <code>Poisson()</code>. <code>exp</code> them for an odds ratio or a rate ratio. There is no <code>:sigma</code> block: the family has already spent it.</li>
<li><code>predict(fit, newdata)</code>: response-scale predictions, probabilities or expected counts; <code>se = true</code> adds a delta-method standard error; <code>type = :link</code> stays on the link scale. What the engine accepts as <code>newdata</code> is in <a href="appendix-b-engine.html">Where the engine stops</a>.</li>
<li><code>fitted(fit)</code>: in-sample response-scale predictions. <code>extrema(fitted(fit))</code> on a Gaussian fit to 0/1 data is the fastest proof the model is the wrong shape.</li>
<li><code>residuals(fit; type = :quantile, rng = MersenneTwister(seed))</code>: randomised quantile residuals, standard normal under a correct model for every family. <strong>Pass the <code>rng</code>.</strong></li>
<li><code>fig_diagnostic(resid)</code> from <code>tools/figures.jl</code>: the worm plot, flat near zero when there is nothing left to find.</li>
<li><strong>Seeding.</strong> Every random draw here — the jitter in two figures, the one chick’s residual made by hand, both sets of quantile residuals, and the simulation below — comes from an explicit <code>MersenneTwister</code> handed in as <code>rng</code>.</li>
<li><strong>The simulation thread.</strong> From Class 2 onward, the last thing you do with a fit is ask it to invent data and see what a refit makes of them. Here it is for a logistic model, where the invention is a coin flip per chick. <code>simulate(fit; nsim = k, rng = MersenneTwister(seed))</code> takes the same <code>rng</code> keyword <code>residuals</code> does, and for the same reason.</li>
</ul>
<div id="simulate-refit" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ask the fitted model for new chicks: one Bernoulli draw per row, at that</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># row's fitted probability. Then refit and see how far the slope wanders when</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># nothing at all has changed except the coin flips.</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>ysim <span class="op">=</span> <span class="fu">simulate</span>(logit_fit; nsim <span class="op">=</span> <span class="fl">200</span>, rng <span class="op">=</span> rng_sim)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">refit_slope</span>(y)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> <span class="fu">DataFrame</span>(Survival <span class="op">=</span> y, Mass2 <span class="op">=</span> chicks.Mass2)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coef</span>(<span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2)), <span class="fu">Binomial</span>(); data <span class="op">=</span> d), <span class="op">:</span>mu)[<span class="fl">2</span>]</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>slopes <span class="op">=</span> [<span class="fu">refit_slope</span>(ysim[<span class="op">:</span>, k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim, <span class="fl">2</span>)]</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"the slope we fitted            : %.4f</span><span class="sc">\n</span><span class="st">"</span>, slope_logodds)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"its reported standard error    : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">stderror</span>(logit_fit)[<span class="fl">2</span>])</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mean slope over %d refits     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">length</span>(slopes), <span class="fu">mean</span>(slopes))</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"SD of slopes over those refits : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(slopes))</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"simulated responses seen       : %s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">sort</span>(<span class="fu">unique</span>(ysim)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>the slope we fitted            : 0.6999
its reported standard error    : 0.0514
mean slope over 200 refits     : 0.7032
SD of slopes over those refits : 0.0487
simulated responses seen       : [0.0, 1.0]</code></pre>
</div>
</div>
<p>Two things in the cell are new. <code>function refit_slope(y) ... end</code> is the long form of the definition Class 1 wrote in one line, for a body that needs several lines; the last expression is what it returns. <code>ysim</code> is a matrix with one column per invented world: <code>ysim[:, k]</code> is its <em>k</em>-th column, a colon in a slot meaning <em>all of that dimension</em>, and <code>size(ysim, 2)</code> is how many columns it has, so the comprehension refits every world in turn.</p>
<p>The simulated responses are only ever zero and one, because <code>simulate</code> draws from the family the fit was given rather than adding normal noise. And the spread of the refitted slopes lands close to the standard error the single fit reported, which is what a standard error <strong>is</strong>: a prediction about how much your estimate would move if the world ran again. When those two numbers disagree badly, believe the simulation. That comparison is most of what Class 5 does for a living.</p>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. Details checked on 2026-09-07 against OpenAlex, an open
catalogue of research papers.</p>
<ol type="1">
<li><strong>Warton, D. I. &amp; Hui, F. K. C. (2011) “The arcsine is asinine: the analysis of proportions in ecology”, <em>Ecology</em> 92:3–10.</strong> doi:10.1890/10-0340.1 (published online in 2010). Start here. It is the ecology-specific case for doing exactly what this class did, aimed squarely at readers who were taught to transform a proportion and fit a linear model to it instead. Short, pointed, and it will change what you do on Monday.</li>
<li><strong>Bolker, B. M. (2008) <em>Ecological Models and Data in R</em>, Princeton University Press.</strong> doi:10.1515/9781400840908. The best book-length route from “I know what a linear model is” to “I know what a likelihood is and why the family matters”. Chapters 4 and 6 are the ones that pay for the rest of this course.</li>
<li><strong>Zuur, A. F., Ieno, E. N., Walker, N. J., Saveliev, A. A. &amp; Smith, G. M. (2009) <em>Mixed Effects Models and Extensions in Ecology with R</em>, Springer.</strong> doi:10.1007/978-0-387-87458-6. The chapters on Poisson regression and on overdispersion are the natural bridge from today into Class 4, and they are written for biologists with real, awkward data.</li>
<li><strong>Dunn, P. K. &amp; Smyth, G. K. (1996) “Randomized quantile residuals”, <em>Journal of Computational and Graphical Statistics</em> 5:236–244.</strong> doi:10.1080/10618600.1996.10474708. The source of the diagnostic this class used twice. Worth reading once so that “it is normal if the model is right, whatever the family” stops being a slogan you repeat and becomes a thing you can derive.</li>
<li><strong>McCullagh, P. &amp; Nelder, J. A. (1989) <em>Generalized Linear Models</em>, 2nd edition, Chapman &amp; Hall.</strong> The book that made all of this one framework rather than a list of tricks, and the place the words “link function” and “variance function” come from. Hard, and the right thing to own. Read chapter 2 when you want to know why the family determines both at once.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Graded by depth: the first three take ten minutes each. Every exercise names a file under <code>data/</code> that exists; do it on your own organism as well where you have one. A <em>check</em> is a number computed from that file when this page was built — match it before going on. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Class 2 and not Class 3.</p>
<ol type="1">
<li><p><strong>Break it on purpose, then look outside.</strong> On the chapter’s chicks, fit a Gaussian model of <code>Survival</code> on <code>JulianDate</code>, the hatching date. Report <code>extrema(fitted(fit))</code> and the number of fitted values outside zero and one. Then write one sentence saying what the model believes that the world does not allow — and notice that on this predictor the visible fault does not appear, which makes the invisible one (a constant σ for a 0/1 response) the only fault you have. <em>Check:</em> fitted values run from 0.199 to 0.693, 0 of them outside the legal range.</p></li>
<li><p><strong>Log-odds to biology.</strong> Refit it with <code>Binomial()</code>. Report the slope, the odds ratio per day, and the predicted probability of surviving for a chick hatched on day 50, day 80 and day 120. Then write the single sentence you would put in a paper, and underline the part a reader could check. <em>Check:</em> odds ratio 1.0177 per day; probabilities 0.313, 0.436 and 0.609.</p></li>
<li><p><strong>Where the curve is steep.</strong> From question 2, compute the change in probability between day 50 and day 80 and between day 80 and day 120, and compute <code>-b[1] / b[2]</code> from <code>coef(fit, :mu)</code>: the date at which the model says survival is exactly one half. Say where each of your three dates sits relative to it, and explain which of the two changes is the larger per day and why, without using the word “nonlinear”. The answer is a statement about distance from that one point. <em>Check:</em> the half-way date is day 94.7; the chicks’ hatching dates run from 22 to 141.</p></li>
<li><p><strong>A count of your own.</strong> <code>data/2012/EPPSuccess.csv</code> records, for 76 male sparrows, <code>EPP</code>, the number of extra-pair young each sired, and his <code>Age</code> in years. Fit a Poisson model of <code>EPP</code> on <code>Age</code>. Report the rate ratio, and write its meaning as a multiplication rather than an addition. <em>Check:</em> rate ratio 2.05 per year of age.</p></li>
<li><p><strong>Run the check, both ways.</strong> For question 4, report the variance-to-mean ratio of the raw counts, and the standard deviation of <code>residuals(fit; type = :quantile, rng = MersenneTwister(1))</code>. Say what each check measures that the other does not, whether your SD is one, near enough, or clearly wider, and which check you would trust if they disagreed. <em>Check:</em> variance over mean 5.05; quantile-residual SD 1.5. Neither is near one, and Class 4 is about what to do when that happens.</p></li>
<li><p><strong>Simulate and refit, with a function of your own.</strong> Adapt the chapter’s last cell to the logistic fit of question 2: write <code>refit_slope</code> in the long <code>function ... end</code> form for <code>Survival ~ JulianDate</code>, simulate 200 datasets with <code>MersenneTwister(1)</code>, and collect the refitted slopes with a comprehension over the columns. Report the reported standard error next to the standard deviation of the refitted slopes. If they differ by more than about a tenth of the estimate, say what you would check first. <em>Check:</em> reported SE 0.0018; SD of the refits 0.0019.</p></li>
<li><p><strong>The pretence.</strong> Name the grouping in the chapter’s chick file that this chapter has been pretending away, and find the column that would identify it. This file does not have one; <code>data/2012/SparrowSurvival.csv</code> does. Open it, name the column, and say in one sentence which number on this chapter’s logistic output you expect Class 9 to change, and in which direction.</p></li>
</ol>
<p><strong>If you have R.</strong> Fit the Poisson model of question 4 in R with <code>glm</code> and find the dispersion line in the summary. Quote it. Then answer in one sentence: given your answer to question 5, is that line a finding or an instruction?</p>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk2-linear-models.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 2 · One line through a cloud of sparrows</span></a><a class="chapter-nav-link next" href="wk4-overdispersion.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Class 4 · When the family lies about the spread</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 3 of twelve rungs, ten in v1, plus a coda · draft, all code run, 2026-09-07<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>