<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 4: when the family lies about the spread – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 4: when the family lies about the spread</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 4</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>When the family lies about the spread</h1>
    <p class="deck">Class 3 let the family decree the spread. Today the decree turns out to be false — but only after the column nobody looked at has been ruled out, and the repair is then the same one verb in three families: a second formula in the box.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>All ten classes of version 1 are drafted and their code runs end to end (1–10), with Appendix A, the preface and the coda. Every number and figure on this page was produced when the site was built; the book itself is not written.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 4d9248f88 (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Every code block and printed result below was actually run when the site was built, and nothing is typed from memory. Every random draw is seeded where it is made, so the page comes out the same every time. The one R block was run once by hand, on the date shown, with R against the same file, and is labelled as such.<br>
      <b>Caveat</b> The data are real: the 2012 Lundy Island female-breeding and sparrow-morphology records, read directly from data/2012/FemaleSuccess.csv and data/2012/MBodySize.csv (where the files came from is recorded in data/2012/README.md). Nothing here is simulated except the one block of invented refits at the end, which says so and carries its seed.
    </p>
  </div>
</header>

<div class="wrap">
<blockquote>
<p><strong>What this chapter pretends.</strong> Every model today is fixed effects only. The females breed in the same population and the sparrows were caught on the same island, and no fit here knows it. That is the pretence Class 2 made, Class 3 made, and <strong>Class 6 stops making</strong>. Note what the repair costs: neither file records the grouping — <code>FemaleSuccess.csv</code> carries no female identifier at all, and <code>MBodySize.csv</code> is one row per bird — so ending the pretence needs a <em>different dataset</em> (<code>BodySize.csv</code>, which repeats birds), not a different formula on these. Everything here about modelling the spread survives that repair; the standard errors printed here will move when it arrives.</p>
</blockquote>
<hr>
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>State, in one sentence, what a family decrees about the variance, and compare a crude variance-to-mean ratio against the ratio the fitted model actually implies, rather than against one.</li>
<li>Look for an <strong>exposure</strong> — a denominator already sitting in your data — before you blame the family, and say what an offset is.</li>
<li>Fit a grouped binomial and its overdispersed cousin <code>BetaBinomial()</code>, and say why <em>n</em>·p(1 − p) is a claim data can break where p(1 − p) is not.</li>
<li>Fit <code>NegBinomial2()</code>, say what the dispersion parameter θ means in the units of the variance, and predict what admitting the extra spread will and will not change: the estimate barely, the standard errors a lot.</li>
<li>Judge an overdispersion check against its own error bar, and a ±1 SD band against the coverage — the share of data such a band is meant to hold — the model itself claims for it.</li>
<li>Put a second formula on σ in a Gaussian model, read the null hypothesis printed above the σ table, and report a <strong>not detected</strong> honestly — with the smallest difference the design could have seen. Then say why that is the same move as changing the family, and name the rung where it gets a chapter of its own.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, 9:00 am. MOMO has arrived early with the fledgling file
already open, which is new. TOTO is eating breakfast and has not yet
decided to be here.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Momo, you have been waiting a week to say something.</p></div>
<div class="line"><span class="who momo">Momo</span><p>You told me my Poisson model was wrong, showed me exactly how wrong, and
then made me leave it wrong.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>I did, and today we fix it. Load it back.</p></div>
<div id="setup" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/figures.jl includes tools/theme_itchy.jl itself, so one include does both.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># It also defines erfinv_approx, which the worm-plot arithmetic below reuses so that</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># what we count is exactly what the figure draws.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">include</span>(<span class="st">"../tools/figures.jl"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span>, <span class="bu">Random</span>, <span class="bu">Printf</span>, <span class="bu">CairoMakie</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> <span class="bu">Distributions</span>          <span class="co"># qualified: DRM exports its own Poisson, Binomial, …</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set_theme!</span>(<span class="fu">theme_itchy</span>(<span class="op">:</span>light))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>females <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/FemaleSuccess.csv"</span>, DataFrame)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>n_fem <span class="op">=</span> <span class="fu">nrow</span>(females)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>m_counts <span class="op">=</span> <span class="fu">mean</span>(females.Fledglings)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>v_counts <span class="op">=</span> <span class="fu">var</span>(females.Fledglings)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>ratio_raw <span class="op">=</span> v_counts <span class="op">/</span> m_counts</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows: %d   columns: %s</span><span class="sc">\n</span><span class="st">"</span>, n_fem, <span class="fu">join</span>(<span class="fu">names</span>(females), <span class="st">", "</span>))</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mean of the counts     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, m_counts)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"variance of the counts : %.4f</span><span class="sc">\n</span><span class="st">"</span>, v_counts)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"variance / mean        : %.4f</span><span class="sc">\n</span><span class="st">"</span>, ratio_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows: 163   columns: Fledglings, EggNo, Age
mean of the counts     : 3.2086
variance of the counts : 5.4377
variance / mean        : 1.6947</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Same 163 females, same ratio of 1.69, which is still not one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Still not one. Hold on to that number and hold on to your annoyance with
it, because both are going to be worth less than you think by half past
nine. First, the thing that is genuinely different from last week. Toto,
in Class 3 the Gaussian model on a yes-or-no response was the wrong
<strong>shape</strong>. Its predictions were impossible. Is this one
impossible?</p></div>
<div class="line"><span class="who toto">Toto</span><p><em>(mouth full)</em> No.&nbsp;The counts it predicts are all positive and it
never predicts a half.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>For now. What is false is a claim the model never printed and you never
agreed to: <strong>the variance equals the mean</strong>. That is the
whole of today, and it has a name.</p></div>
<h3 id="the-decree-stated-as-an-equation" class="anchored">The decree, stated as an equation</h3>
<p class="board"><strong>y_i ~ Poisson(μ_i), log μ_i = β0 + β1 x_i, Var(y_i | x_i) =
μ_i</strong></p>
<div class="line"><span class="who itchy">Itchy</span><p>Three lines, and the third one is not something the Poisson family
estimated. It is something the Poisson family <em>is</em>. Now read the
third line carefully, because it has a bar in it that Momo’s crude ratio
does not.</p></div>
<div id="cell-fit-poisson" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pois <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pois</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-poisson" class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Distributional regression fit (Poisson)
  nobs = 163   logLik = -367.9932   converged = true

Mean model (μ):
  H0: coefficient = 0
                Coef.  Std.Error       z   Pr(&gt;|z|)
  (Intercept)  0.7067     0.1081  6.5379  6.241e-11
  Age          0.2325     0.0478  4.8667  1.135e-06</code></pre>
</div>
</div>
<div id="right-benchmark" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mu_p <span class="op">=</span> <span class="fu">fitted</span>(pois)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># What a CORRECT Poisson regression implies for the MARGINAL variance-to-mean ratio:</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># E[Var(y|x)] + Var(E[y|x]), all over E[y].</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ratio_implied <span class="op">=</span> (<span class="fu">mean</span>(mu_p) <span class="op">+</span> <span class="fu">var</span>(mu_p)) <span class="op">/</span> <span class="fu">mean</span>(mu_p)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"crude, from the raw counts            : %.4f</span><span class="sc">\n</span><span class="st">"</span>, ratio_raw)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"what this fitted Poisson implies      : %.4f</span><span class="sc">\n</span><span class="st">"</span>, ratio_implied)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"what a Poisson decrees CONDITIONALLY  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fl">1.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>crude, from the raw counts            : 1.6947
what this fitted Poisson implies      : 1.1491
what a Poisson decrees CONDITIONALLY  : 1.0000</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>So the benchmark for my number was never one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The benchmark for your number was never one, and I let you believe it
was for a week. A Poisson <em>regression</em> says the variance equals
the mean <strong>at a given age</strong>. The raw counts also carry the
variation that age itself creates, so even a perfectly correct Poisson
model would show a <strong>marginal</strong> ratio — marginal meaning
averaged over every age, not held fixed at one — of 1.149 here, not one.
<strong>Compare like with like or you will convict an innocent
model.</strong> Your 1.69 is still too big — but against 1.149, not
against one, and the gap is smaller than you were told.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Then how do you check the thing with the bar in it?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>On the residuals of the fit, where age has already been taken out. Two
ways, built on different arithmetic. The classical one takes each bird’s
squared distance from its own fitted mean, divides by the variance the
model claims <em>there</em>, adds them up and divides by the residual
degrees of freedom. The other is the worm plot’s statistic from Class 3.</p></div>
<div id="checks-poisson" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>X2_pois <span class="op">=</span> <span class="fu">sum</span>((females.Fledglings <span class="op">.-</span> mu_p) <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> mu_p)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>disp_pois <span class="op">=</span> X2_pois <span class="op">/</span> <span class="fu">dof_residual</span>(pois)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>qres_pois <span class="op">=</span> <span class="fu">residuals</span>(pois; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">4</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>mcse_rqr <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> <span class="fu">sqrt</span>(<span class="fl">2</span> <span class="op">*</span> n_fem)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>z_pois <span class="op">=</span> <span class="fu">abs</span>(<span class="fu">std</span>(qres_pois) <span class="op">-</span> <span class="fl">1</span>) <span class="op">/</span> mcse_rqr</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Pearson X2 %.3f on %d df  -&gt;  X2/df = %.4f</span><span class="sc">\n</span><span class="st">"</span>, X2_pois, <span class="fu">dof_residual</span>(pois), disp_pois)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quantile residual SD %.4f  (%.2f Monte Carlo SE of %.4f from 1)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">std</span>(qres_pois), z_pois, mcse_rqr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pearson X2 252.424 on 161 df  -&gt;  X2/df = 1.5679
quantile residual SD 1.2981  (5.38 Monte Carlo SE of 0.0554 from 1)</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>1.57 and 1.3, and the second one is 5.4 of its own Monte Carlo standard
errors — the wobble you would expect in an SD computed from this many
random draws — away from one, so neither is noise. Two checks, different
arithmetic, same verdict. Note that I did not call them
<em>independent</em>: they are two functions of one fitted model on one
residual vector, and a pair of checks that share a model can be wrong
together.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Good. Give me the negative binomial.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>No.</p></div>
<div class="line"><span class="who momo">Momo</span><p>You said we were fixing it today.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>We are. Open the file first. Not the model — the <strong>file</strong>.</p></div>
<h3 id="suspect-the-mean-before-you-blame-the-family" class="anchored">Suspect the mean before you blame the family</h3>
<div id="the-ceiling" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>n_under <span class="op">=</span> <span class="fu">count</span>(females.Fledglings <span class="op">.&lt;=</span> females.EggNo)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>egg_lo, egg_hi <span class="op">=</span> <span class="fu">extrema</span>(females.EggNo)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows where Fledglings &lt;= EggNo : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, n_under, n_fem)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"EggNo runs from %d to %d, with SD %.2f</span><span class="sc">\n</span><span class="st">"</span>, egg_lo, egg_hi, <span class="fu">std</span>(females.EggNo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows where Fledglings &lt;= EggNo : 163 of 163
EggNo runs from 1 to 23, with SD 4.33</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Column two. <code>EggNo</code>, the number of eggs she laid.
<code>Fledglings</code> is at most <code>EggNo</code> in 163 of 163 rows
— which is to say all of them, because a female cannot fledge a chick
she did not lay. And <code>EggNo</code> runs from 1 to 23.</p></div>
<div class="line"><span class="who momo">Momo</span><p class="aside">(silence)</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>A female who laid 1 egg and a female who laid 23 are not being asked the
same question, and the model you have been carrying around for a week
asks them the same question. That is called an
<strong>exposure</strong>: an amount of opportunity that differs between
rows and belongs in the mean structure. Look at what the model believes
without it.</p></div>
<div id="cell-fig-ceiling" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sd_p <span class="op">=</span> <span class="fu">sqrt</span>.(mu_p)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>band_lo, band_hi <span class="op">=</span> <span class="fu">minimum</span>(mu_p <span class="op">.-</span> sd_p), <span class="fu">maximum</span>(mu_p <span class="op">.+</span> sd_p)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Jitter the eggs axis only, and only rightward, so that neither invariant this</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># figure is about can be broken by the jitter: no drawn point falls below zero</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># fledglings, and none is drawn above the ceiling.</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>rng_jit <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>egg_jit <span class="op">=</span> females.EggNo <span class="op">.+</span> <span class="fl">0.45</span> <span class="op">.*</span> <span class="fu">rand</span>(rng_jit, n_fem)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">560</span>, <span class="fl">400</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"eggs laid"</span>, ylabel <span class="op">=</span> <span class="st">"fledglings"</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"the column the model never saw"</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">band!</span>(ax, [egg_lo <span class="op">-</span> <span class="fl">0.5</span>, egg_hi <span class="op">+</span> <span class="fl">0.5</span>], <span class="fu">fill</span>(band_lo, <span class="fl">2</span>), <span class="fu">fill</span>(band_hi, <span class="fl">2</span>);</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.28</span>), label <span class="op">=</span> <span class="st">"Age-only Poisson, mean ± 1 SD"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, [egg_lo <span class="op">-</span> <span class="fl">0.5</span>, egg_hi <span class="op">+</span> <span class="fl">0.5</span>], [egg_lo <span class="op">-</span> <span class="fl">0.5</span>, egg_hi <span class="op">+</span> <span class="fl">0.5</span>];</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    linewidth <span class="op">=</span> <span class="fl">2</span>, linestyle <span class="op">=</span> <span class="op">:</span>dash, label <span class="op">=</span> <span class="st">"ceiling: fledglings = eggs"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, egg_jit, females.Fledglings; markersize <span class="op">=</span> <span class="fl">6</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.6</span>), label <span class="op">=</span> <span class="st">"a female"</span>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div id="fig-ceiling" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-ceiling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk4-overdispersion_files/figure-html/fig-ceiling-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ceiling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Fledglings against eggs laid. Markers are jittered <strong>horizontally only</strong>, and only to the right, by up to 0.45 of an egg, so that repeated (eggs, fledglings) pairs separate; the vertical position is the exact count, so no marker can be drawn below zero or above the ceiling. The diagonal is that ceiling: no bird can sit above it. The horizontal band is everything the Age-only Poisson thinks is ordinary — its fitted mean ± 1 SD, over every female of every age — and it does not know that the ceiling exists, let alone where each bird’s own ceiling is.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The band goes straight through the line.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The band goes straight through the line, and where it does, the model is
assigning ordinary probability to birds that cannot exist. Put a number
on it: for each female, ask the fitted Poisson how much probability it
puts above her own <code>EggNo</code>, and add those up.</p></div>
<div id="impossible-mass" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>over_pois <span class="op">=</span> <span class="fu">sum</span>(<span class="fl">1</span> <span class="op">-</span> Distributions.<span class="fu">cdf</span>(Distributions.<span class="fu">Poisson</span>(mu_p[i]), females.EggNo[i])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n_fem)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"expected rows with more fledglings than eggs, under this Poisson: %.2f</span><span class="sc">\n</span><span class="st">"</span>, over_pois)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>expected rows with more fledglings than eggs, under this Poisson: 8.88</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>About 8.9 females’ worth of impossibility — which is why I said <em>for
now</em> rather than <em>correct</em> when Toto told me the predictions
were all legal. <strong>This model commits exactly the crime Class 3
convicted the Gaussian of</strong>, and it hid it better, because a
prediction of four chicks is only impossible if you know how many eggs
there were. Now put the exposure in.</p></div>
<div class="line"><span class="who momo">Momo</span><p>As an offset. I have read ahead.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>As a covariate first, and I will tell you why in a minute. The right
scale is the log one, because the link is a log: if a female’s expected
brood is proportional to her eggs, then log μ carries log
<code>EggNo</code> with a coefficient of one.</p></div>
<div id="cell-fit-exposure" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>females.logEgg <span class="op">=</span> <span class="fu">log</span>.(females.EggNo)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>poe <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age <span class="op">+</span> logEgg)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>poe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-exposure" class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Distributional regression fit (Poisson)
  nobs = 163   logLik = -323.4104   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -1.1695     0.2546  -4.5931  4.366e-06
  Age           0.0852     0.0507   1.6798    0.09299
  logEgg        0.9503     0.1102   8.6213  6.622e-18</code></pre>
</div>
</div>
<div id="exposure-paid" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mu_e <span class="op">=</span> <span class="fu">fitted</span>(poe)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>X2_poe <span class="op">=</span> <span class="fu">sum</span>((females.Fledglings <span class="op">.-</span> mu_e) <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> mu_e)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>disp_poe <span class="op">=</span> X2_poe <span class="op">/</span> <span class="fu">dof_residual</span>(poe)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>d_aic_exposure <span class="op">=</span> <span class="fu">aic</span>(pois) <span class="op">-</span> <span class="fu">aic</span>(poe)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>ct_e <span class="op">=</span> <span class="fu">coeftable</span>(poe)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>r_egg <span class="op">=</span> <span class="fu">findfirst</span>(<span class="op">==</span>(<span class="st">"mu: logEgg"</span>), ct_e.rownms)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>b_egg <span class="op">=</span> ct_e.cols[<span class="fl">1</span>][r_egg]</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>egg_lo_ci, egg_hi_ci <span class="op">=</span> ct_e.cols[<span class="fl">5</span>][r_egg], ct_e.cols[<span class="fl">6</span>][r_egg]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>over_poe <span class="op">=</span> <span class="fu">sum</span>(<span class="fl">1</span> <span class="op">-</span> Distributions.<span class="fu">cdf</span>(Distributions.<span class="fu">Poisson</span>(mu_e[i]), females.EggNo[i])</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>               <span class="cf">for</span> i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n_fem)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, Age only        : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(pois))</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, Age + log(EggNo): %.4f   (drop of %.4f for one parameter)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aic</span>(poe), d_aic_exposure)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Pearson X2/df        : %.4f  -&gt;  %.4f</span><span class="sc">\n</span><span class="st">"</span>, disp_pois, disp_poe)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"log(EggNo) coefficient: %.4f  [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>, b_egg, egg_lo_ci, egg_hi_ci)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"expected impossible rows: %.2f  -&gt;  %.2f</span><span class="sc">\n</span><span class="st">"</span>, over_pois, over_poe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC, Age only        : 739.9864
AIC, Age + log(EggNo): 652.8208   (drop of 87.1656 for one parameter)
Pearson X2/df        : 1.5679  -&gt;  1.1064
log(EggNo) coefficient: 0.9503  [0.7343, 1.1664]
expected impossible rows: 8.88  -&gt;  0.63</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>That is a much bigger number than I was expecting.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p><strong>87.2 AIC, for one parameter, from a column that was already in
your file.</strong> The Pearson statistic falls from 1.57 to 1.11 — that
is most of the way to a met assumption — and the impossible mass falls
from about 8.9 birds to about 0.6. Now look at the coefficient itself,
because it is the answer to your offset question. It came out at 0.95,
with an interval of 0.73 to 1.17.</p></div>
<div class="line"><span class="who toto">Toto</span><p>That interval contains one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That interval contains one, and <strong>an offset is precisely this
coefficient pinned at one instead of estimated</strong>. It is the
stronger, cheaper model when the proportionality really holds, and here
the data have no complaint about it. Our engine cannot write it yet — a
known limitation, reported to the engine’s authors — so I am teaching
the free coefficient and showing you the version with the coefficient
held at one in R, where it is one word.</p></div>
<blockquote>
<p class="scene">↔︎ TRANSLATE: the same fit to every digit, and one model R can write that
we cannot</p>
<p><code>drmTMB</code> fits <code>Fledglings ~ Age + log(EggNo)</code> and returns the identical estimates and standard errors — 0.9503 on <code>log(EggNo)</code>, and the same log-likelihood — which is the reassuring half. The interesting half is the model above it, <code>offset(log(EggNo))</code>, which pins that coefficient at one and therefore spends <strong>no parameter at all</strong>. R writes it in one word; we cannot write it yet.</p>
<p>Both AICs are printed in the block below. <strong>The offset’s is the lower of the two</strong>, on one parameter fewer than the fit above — and the free coefficient’s is the number printed above, so read it off the Julia output rather than from here. That is the whole argument for an offset: a better AIC <em>and</em> one fewer parameter, because the constraint the offset imposes happens to be true here. If the coefficient had come back at, say, half, the offset would have been a bad model confidently stated, and fitting it free is how you find that out.</p>
<p>The R block below was <strong>run once, by hand</strong>, with R on 2026-09-07 against the same archived file this chapter reads, and pasted in; it is not re-run when the page is built.</p>
</blockquote>
<div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R output, run once by hand on 2026-09-07 and pasted here; not re-run when the page is built.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># drmTMB 0.7.0 / R 4.6.0. Run with Rscript, reading</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># data/2012/FemaleSuccess.csv:</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   m1 &lt;- drmTMB(bf(Fledglings ~ Age + offset(log(EggNo))), family = poisson(), data = d)</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   m2 &lt;- drmTMB(bf(Fledglings ~ Age + log(EggNo)),         family = poisson(), data = d)</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&lt;</span>summary.drmTMB<span class="sc">&gt;</span>                      <span class="co"># m1: the offset</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>estimator<span class="sc">:</span> ML</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                  estimate std_error</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span>(Intercept) <span class="sc">-</span><span class="fl">1.27349825</span> <span class="fl">0.1088804</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span>Age          <span class="fl">0.07809204</span> <span class="fl">0.0481982</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>logLik<span class="sc">:</span> <span class="sc">-</span><span class="fl">323.5</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>convergence<span class="sc">:</span> <span class="dv">0</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>AIC<span class="sc">:</span> <span class="fl">651.0224</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="sc">&lt;</span>summary.drmTMB<span class="sc">&gt;</span>                      <span class="co"># m2: the free coefficient, as fitted above in Julia</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>estimator<span class="sc">:</span> ML</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>                  estimate  std_error</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span>(Intercept) <span class="sc">-</span><span class="fl">1.16947064</span> <span class="fl">0.25461252</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span>Age          <span class="fl">0.08518277</span> <span class="fl">0.05070874</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span><span class="fu">log</span>(EggNo)   <span class="fl">0.95030758</span> <span class="fl">0.11022826</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>logLik<span class="sc">:</span> <span class="sc">-</span><span class="fl">323.4</span></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>convergence<span class="sc">:</span> <span class="dv">0</span></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>AIC<span class="sc">:</span> <span class="fl">652.8208</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="line"><span class="who itchy">Itchy</span><p>Now the part that should frighten you. Momo, what happened to your
biology?</p></div>
<div id="biology-moved" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ct_p <span class="op">=</span> <span class="fu">coeftable</span>(pois)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>r_age_p <span class="op">=</span> <span class="fu">findfirst</span>(<span class="op">==</span>(<span class="st">"mu: Age"</span>), ct_p.rownms)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>r_age_e <span class="op">=</span> <span class="fu">findfirst</span>(<span class="op">==</span>(<span class="st">"mu: Age"</span>), ct_e.rownms)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>rr_naive <span class="op">=</span> <span class="fu">exp</span>(<span class="fu">coef</span>(pois, <span class="op">:</span>mu)[<span class="fl">2</span>])</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>rr_expos <span class="op">=</span> <span class="fu">exp</span>(<span class="fu">coef</span>(poe, <span class="op">:</span>mu)[<span class="fl">2</span>])</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rate ratio on Age, Age only         : %.4f  [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>        rr_naive, <span class="fu">exp</span>(ct_p.cols[<span class="fl">5</span>][r_age_p]), <span class="fu">exp</span>(ct_p.cols[<span class="fl">6</span>][r_age_p]))</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rate ratio on Age, Age + log(EggNo) : %.4f  [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        rr_expos, <span class="fu">exp</span>(ct_e.cols[<span class="fl">5</span>][r_age_e]), <span class="fu">exp</span>(ct_e.cols[<span class="fl">6</span>][r_age_e]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rate ratio on Age, Age only         : 1.2618  [1.1490, 1.3857]
rate ratio on Age, Age + log(EggNo) : 1.0889  [0.9859, 1.2027]</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>It went from 1.26 to 1.09 and the interval covers one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It did. An extra year of age multiplied expected fledglings by 1.26 when
age was the only thing in the model, and by 1.09 once we allowed that
older females lay more eggs — and that second interval is consistent
with no effect at all <em>per egg</em>. Both statements are true and
they are about different things. The first is the total effect of age on
fledgling production; the second is what age does once you have
conditioned on the clutch. Neither is a lie. But if you had gone
straight to the negative binomial, you would have kept the first number,
an interval that excluded one, and a story about ageing females that was
mostly a story about eggs.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So the lesson is not about the family at all.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The lesson today has a first half and a second half, and this is the
first half. <strong>Check the exposure before you blame the
family.</strong> Overdispersion is what a missing mean structure looks
like from the residuals, and a missing mean structure is much commoner
and much cheaper to fix.</p></div>
<h3 id="the-ceiling-taken-seriously" class="anchored">The ceiling, taken seriously</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Second half. We got the impossible mass down to about 0.6 birds, which
is small, and I want it at zero, because it is zero in the world. What
stops it being zero is that we are still modelling a
<strong>count</strong> — a quantity with no upper limit written anywhere
— when the response is a count <em>out of a known number of tries</em>.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Chicks out of eggs.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Chicks out of eggs. Toto, you fitted this family in Class 3, on a
response that was only ever zero or one. This is the same family with
the trials counted.</p></div>
<div id="cell-fit-binomial" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>females.Failures <span class="op">=</span> females.EggNo <span class="op">.-</span> females.Fledglings</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>bin <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(<span class="fu">cbind</span>(Fledglings, Failures) <span class="op">~</span> Age)), <span class="fu">Binomial</span>(); data <span class="op">=</span> females)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>bin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-binomial" class="cell-output cell-output-display" data-execution_count="19">
<pre><code>Distributional regression fit (Binomial)
  nobs = 163   logLik = -333.1155   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -0.9542     0.1324  -7.2085  5.655e-13
  Age           0.1175     0.0595   1.9752    0.04824</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Two columns on the left.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Two columns on the left: successes and failures, so the engine can count
the trials. And now the decree changes in a way that matters more than
it looks. In Class 3 I told you the binomial says the variance is p(1 −
p). For a single trial that is an <strong>identity</strong> — there is
nothing there for data to contradict, which is why Class 3’s logistic
diagnostic was a baseline rather than a test. For <em>n</em> trials the
variance is <strong>n·p(1 − p)</strong>, and that extra factor is a real
claim: it says a female’s chicks succeed or fail independently of one
another. Test it.</p></div>
<div id="check-binomial" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>p_bin <span class="op">=</span> <span class="fu">fitted</span>(bin)                       <span class="co"># success probabilities</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>m_bin <span class="op">=</span> females.EggNo <span class="op">.*</span> p_bin            <span class="co"># expected fledglings</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>v_bin <span class="op">=</span> females.EggNo <span class="op">.*</span> p_bin <span class="op">.*</span> (<span class="fl">1</span> <span class="op">.-</span> p_bin)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>disp_bin <span class="op">=</span> <span class="fu">sum</span>((females.Fledglings <span class="op">.-</span> m_bin) <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> v_bin) <span class="op">/</span> <span class="fu">dof_residual</span>(bin)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The two Pearson statistics are computed on DIFFERENT responses, so most of the</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># jump between them is arithmetic: the binomial divides by n p (1 - p) where the</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co"># count model divides by n p, which is smaller by a factor (1 - p).</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>mech_inflation <span class="op">=</span> <span class="fu">sum</span>(m_bin) <span class="op">/</span> <span class="fu">sum</span>(v_bin)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Binomial: Pearson X2/df = %.4f</span><span class="sc">\n</span><span class="st">"</span>, disp_bin)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"ratio to the exposure Poisson's %.4f : %.4f</span><span class="sc">\n</span><span class="st">"</span>, disp_poe, disp_bin <span class="op">/</span> disp_poe)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"inflation predicted by the change of variance function alone: %.4f</span><span class="sc">\n</span><span class="st">"</span>, mech_inflation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Binomial: Pearson X2/df = 1.6417
ratio to the exposure Poisson's 1.1064 : 1.4838
inflation predicted by the change of variance function alone: 1.4920</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>That is worse than the Poisson one was.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Do not say that, and I am going to forbid the same move for AIC in about
twenty minutes, so let me forbid it here first. Those two statistics are
computed on <strong>different responses</strong>. At the same fitted
mean the binomial divides the same squared deviations by something
smaller, by a factor of one minus p, so it <em>must</em> come out
bigger. Predict the inflation from that alone and you get 1.492; the
ratio you actually saw is 1.484. <strong>They agree, so the jump from
1.11 to 1.64 is not evidence of anything.</strong></p></div>
<div class="line"><span class="who toto">Toto</span><p>Then what is?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>1.64 on its own terms, against the one it is allowed to be compared
with. This model already knows about the eggs, and its own variance
claim is still rejected by its own residuals — a rejection that owes
nothing to the comparison you just drew. <strong>This is the
overdispersion the chapter is named for.</strong> A brood is not
<code>EggNo</code> independent coin flips: a good territory, a good mate
or a good year moves all of a female’s chicks together, and the binomial
has no way to say so. So free the variance, exactly as before — one
verb, a second formula in the box, a different family.</p></div>
<div id="cell-fit-betabinomial" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>bbin <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(<span class="fu">cbind</span>(Fledglings, Failures) <span class="op">~</span> Age), <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">BetaBinomial</span>(); data <span class="op">=</span> females)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>bbin</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-betabinomial" class="cell-output cell-output-display" data-execution_count="22">
<pre><code>Distributional regression fit (BetaBinomial)
  nobs = 163   logLik = -319.6302   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -0.9677     0.1751  -5.5269  3.259e-08
  Age           0.1241     0.0803   1.5461     0.1221

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                 Coef.  Std.Error        z  Pr(&gt;|z|)
  (Intercept)  -1.2312     0.1440  -8.5491  1.24e-17</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The σ table came back.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The σ table came back, and that is the sentence I want you to leave the
room with. In Class 3 there was nothing to print because the family had
already spent the parameter. Say <code>BetaBinomial()</code> — or
<code>NegBinomial2()</code>, in a minute — and the family hands it back,
so the engine has something to estimate and something to print.
<strong>The absent table in Class 3 and the present table today are the
same fact seen from two sides.</strong> The beta-binomial lets each
female have her own success probability, drawn from a beta distribution
with mean p and precision φ, and the σ slot carries φ = 1/σ² the way θ
will carry the negative binomial’s.</p></div>
<div id="betabinomial-paid" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>phi <span class="op">=</span> <span class="fu">exp</span>(<span class="op">-</span><span class="fl">2</span> <span class="op">*</span> <span class="fu">coef</span>(bbin, <span class="op">:</span>sigma)[<span class="fl">1</span>])</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>p_bb <span class="op">=</span> <span class="fu">fitted</span>(bbin)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>m_bb <span class="op">=</span> females.EggNo <span class="op">.*</span> p_bb</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># beta-binomial variance: n p (1 - p) inflated by (1 + (n - 1) / (phi + 1))</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>v_bb <span class="op">=</span> m_bb <span class="op">.*</span> (<span class="fl">1</span> <span class="op">.-</span> p_bb) <span class="op">.*</span> (<span class="fl">1</span> <span class="op">.+</span> (females.EggNo <span class="op">.-</span> <span class="fl">1</span>) <span class="op">./</span> (phi <span class="op">+</span> <span class="fl">1</span>))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>disp_bb <span class="op">=</span> <span class="fu">sum</span>((females.Fledglings <span class="op">.-</span> m_bb) <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> v_bb) <span class="op">/</span> <span class="fu">dof_residual</span>(bbin)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>d_aic_bb <span class="op">=</span> <span class="fu">aic</span>(bin) <span class="op">-</span> <span class="fu">aic</span>(bbin)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"phi = 1 / sigma^2 : %.4f</span><span class="sc">\n</span><span class="st">"</span>, phi)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, Binomial     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(bin))</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, BetaBinomial : %.4f   (drop of %.4f for one parameter)</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(bbin), d_aic_bb)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Pearson X2/df     : %.4f  -&gt;  %.4f</span><span class="sc">\n</span><span class="st">"</span>, disp_bin, disp_bb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>phi = 1 / sigma^2 : 11.7329
AIC, Binomial     : 670.2311
AIC, BetaBinomial : 645.2604   (drop of 24.9706 for one parameter)
Pearson X2/df     : 1.6417  -&gt;  1.0160</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>25.0 AIC for one parameter, and a Pearson statistic of 1.016, which is
where a met assumption sits — off a φ of 11.73, and the smaller φ is,
the more a female’s chicks move together rather than succeeding or
failing independently. <strong>And before anybody puts 645 next to
653:</strong> you may not. AIC compares models of the <em>same</em>
data, and “how many chicks did she fledge” and “how many of
<em>these</em> eggs hatched into fledglings” are different responses
with different likelihoods. The comparison you are allowed is binomial
against beta-binomial, and Poisson against Poisson.</p></div>
<div class="line"><span class="who momo">Momo</span><p>How do I choose between the two responses, then?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>By what you are asking, not by AIC. If the biology is about production —
how many chicks come out of this female — model the count and put the
eggs in as an exposure. If it is about <strong>success rate given the
attempt</strong>, model the proportion, and then the ceiling is built in
rather than negotiated. Now the check I have been putting off, because
it is the one this book has been sloppy about.</p></div>
<h3 id="a-band-is-not-a-promise-that-the-dots-are-inside-it" class="anchored">A band is not a promise that the dots are inside it</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Everybody draws mean ± 1 SD and then says “look, the dots are inside”.
Count them instead, and count them against what the model itself says
the answer should be.</p></div>
<div id="honest-coverage" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many birds sit outside their own model's mean ± 1 SD, and how often does the</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># model itself expect a bird to sit inside? (Sum the fitted pmf over the band.)</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">outside</span>(y, m, v) <span class="op">=</span> <span class="fu">count</span>(<span class="fu">abs</span>.(y <span class="op">.-</span> m) <span class="op">.&gt;</span> <span class="fu">sqrt</span>.(v))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">claimed_coverage</span>(dists, m, v)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(<span class="fu">sum</span>(Distributions.<span class="fu">pdf</span>(dists[i], k)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>             <span class="cf">for</span> k <span class="kw">in</span> <span class="fl">0</span><span class="op">:</span>females.EggNo[i] <span class="cf">if</span> <span class="fu">abs</span>(k <span class="op">-</span> m[i]) <span class="op">&lt;=</span> <span class="fu">sqrt</span>(v[i]))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>         <span class="cf">for</span> i <span class="kw">in</span> <span class="fu">eachindex</span>(dists))</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>dist_bin <span class="op">=</span> [Distributions.<span class="fu">Binomial</span>(females.EggNo[i], p_bin[i]) for i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n_fem]</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>dist_bb <span class="op">=</span> [Distributions.<span class="fu">BetaBinomial</span>(females.EggNo[i], p_bb[i] <span class="op">*</span> phi, (<span class="fl">1</span> <span class="op">-</span> p_bb[i]) <span class="op">*</span> phi)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>           for i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>n_fem]</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>out_bin, out_bb <span class="op">=</span> <span class="fu">outside</span>(females.Fledglings, m_bin, v_bin), <span class="fu">outside</span>(females.Fledglings, m_bb, v_bb)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>cov_bin, cov_bb <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> out_bin <span class="op">/</span> n_fem, <span class="fl">1</span> <span class="op">-</span> out_bb <span class="op">/</span> n_fem</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>claim_bin, claim_bb <span class="op">=</span> <span class="fu">claimed_coverage</span>(dist_bin, m_bin, v_bin), <span class="fu">claimed_coverage</span>(dist_bb, m_bb, v_bb)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Binomial     : %3d of %d outside  -&gt;  coverage %.3f, model claims %.3f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>        out_bin, n_fem, cov_bin, claim_bin)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"BetaBinomial : %3d of %d outside  -&gt;  coverage %.3f, model claims %.3f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>        out_bb, n_fem, cov_bb, claim_bb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Binomial     :  77 of 163 outside  -&gt;  coverage 0.528, model claims 0.672
BetaBinomial :  56 of 163 outside  -&gt;  coverage 0.656, model claims 0.670</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>So a lot of the birds are outside both bands.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>A lot of the birds are outside both bands, <strong>and that is not a
criticism</strong> — a ±1 SD band is not supposed to contain the data.
Its <strong>coverage</strong> is simply the share of birds it actually
holds, and the number to compare it with is the share the model says it
should hold. For these counts the binomial’s own band should hold about
0.67 of the birds and holds 0.53, a shortfall of 14 percentage points.
The beta-binomial claims 0.67 and delivers 0.66. <strong>Compare a band
with its own claim, never with your intuition about what a band should
hold.</strong> Now the plot from Class 3, on the repaired model.</p></div>
<div id="worm-arithmetic" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The ±2SE envelope fig_diagnostic draws, reproduced here so that what we COUNT is</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># exactly what the figure SHOWS. erfinv_approx comes from tools/figures.jl.</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">worm_outside</span>(q)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> <span class="fu">length</span>(q)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> ((<span class="fl">1</span><span class="op">:</span>m) <span class="op">.-</span> <span class="fl">0.5</span>) <span class="op">./</span> m</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    theo <span class="op">=</span> <span class="fu">sqrt</span>(<span class="fl">2</span>) <span class="op">.*</span> <span class="fu">erfinv_approx</span>.(<span class="fl">2</span> <span class="op">.*</span> p <span class="op">.-</span> <span class="fl">1</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    dev <span class="op">=</span> <span class="fu">sort</span>(q) <span class="op">.-</span> theo</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    se <span class="op">=</span> <span class="fu">sqrt</span>.(p <span class="op">.*</span> (<span class="fl">1</span> <span class="op">.-</span> p) <span class="op">./</span> m) <span class="op">./</span> (<span class="fu">exp</span>.(<span class="op">-</span>theo <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> <span class="fl">2</span>) <span class="op">./</span> <span class="fu">sqrt</span>(<span class="fl">2</span>π))</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> <span class="fu">abs</span>.(dev) <span class="op">.&gt;</span> <span class="fl">2</span> <span class="op">.*</span> se</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    longest <span class="op">=</span> <span class="fl">0</span>; run_len <span class="op">=</span> <span class="fl">0</span>; sgn <span class="op">=</span> <span class="fl">0</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>m</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> out[i]</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>            run_len <span class="op">=</span> (run_len <span class="op">&gt;</span> <span class="fl">0</span> <span class="op">&amp;&amp;</span> <span class="fu">sign</span>(dev[i]) <span class="op">==</span> sgn) ? run_len <span class="op">+</span> <span class="fl">1</span> <span class="op">:</span> <span class="fl">1</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>            sgn <span class="op">=</span> <span class="fu">sign</span>(dev[i])</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>            run_len <span class="op">=</span> <span class="fl">0</span>; sgn <span class="op">=</span> <span class="fl">0</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">end</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>        longest <span class="op">=</span> <span class="fu">max</span>(longest, run_len)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">end</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> <span class="fu">findall</span>(out)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    span <span class="op">=</span> <span class="fu">isempty</span>(idx) ? (<span class="cn">NaN</span>, <span class="cn">NaN</span>) <span class="op">:</span> (<span class="fu">minimum</span>(theo[idx]), <span class="fu">maximum</span>(theo[idx]))</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>    (out <span class="op">=</span> <span class="fu">count</span>(out), longest <span class="op">=</span> longest, lo <span class="op">=</span> span[<span class="fl">1</span>], hi <span class="op">=</span> span[<span class="fl">2</span>],</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>     neg_left <span class="op">=</span> <span class="fu">count</span>(dev[<span class="fl">1</span><span class="op">:</span><span class="fu">div</span>(m, <span class="fl">3</span>)] <span class="op">.&lt;</span> <span class="fl">0</span>), third <span class="op">=</span> <span class="fu">div</span>(m, <span class="fl">3</span>))</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-fig-diagnostic" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>qres_bin <span class="op">=</span> <span class="fu">residuals</span>(bin; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">6</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>qres_bb <span class="op">=</span> <span class="fu">residuals</span>(bbin; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">7</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>w_bin, w_bb <span class="op">=</span> <span class="fu">worm_outside</span>(qres_bin), <span class="fu">worm_outside</span>(qres_bb)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Binomial     : quantile residual SD %.4f (%.2f Monte Carlo SE from 1), %d of %d outside the envelope, longest same-sign run %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">std</span>(qres_bin), <span class="fu">abs</span>(<span class="fu">std</span>(qres_bin) <span class="op">-</span> <span class="fl">1</span>) <span class="op">/</span> mcse_rqr, w_bin.out, n_fem, w_bin.longest)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"BetaBinomial : quantile residual SD %.4f (%.2f Monte Carlo SE from 1), %d of %d outside the envelope, longest same-sign run %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">std</span>(qres_bb), <span class="fu">abs</span>(<span class="fu">std</span>(qres_bb) <span class="op">-</span> <span class="fl">1</span>) <span class="op">/</span> mcse_rqr, w_bb.out, n_fem, w_bb.longest)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"BetaBinomial : those %d sit between theoretical quantile %.2f and %.2f, and %d of the lowest %d deviations are negative</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>        w_bb.out, w_bb.lo, w_bb.hi, w_bb.neg_left, w_bb.third)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_diagnostic</span>(qres_bb; title <span class="op">=</span> <span class="st">"beta-binomial fit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Binomial     : quantile residual SD 1.2883 (5.21 Monte Carlo SE from 1), 84 of 163 outside the envelope, longest same-sign run 35
BetaBinomial : quantile residual SD 1.0722 (1.30 Monte Carlo SE from 1), 4 of 163 outside the envelope, longest same-sign run 3
BetaBinomial : those 4 sit between theoretical quantile -1.92 and -1.62, and 49 of the lowest 54 deviations are negative</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div id="fig-diagnostic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk4-overdispersion_files/figure-html/fig-diagnostic-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A <strong>detrended</strong> worm plot of the beta-binomial fit: each randomised quantile residual minus the normal quantile it should have been, against that quantile, inside a pointwise ±2 SE envelope. A correct model gives a flat scatter about <strong>zero</strong> — not a diagonal — so read the horizontal line, not a 45° one.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>From 1.29 down to 1.07.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And read that second number against its error bar rather than its
digits: 1.07 is 1.3 Monte Carlo standard errors from one, which is
noise. The picture mostly agrees: 4 of 163 points leave the envelope,
with a longest same-sign run of 3. Put that next to the Poisson worm
plot at the end of Class 3, which left the envelope for most of its
length in a systematic S. <strong>A scattered handful outside a
pointwise envelope is what an envelope is for; a long one-sided run down
the plot is a diagnosis.</strong> This one has the handful and not the
run.</p></div>
<div class="line"><span class="who toto">Toto</span><p>But it is not flat. It sags on the left and bulges in the middle.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It does, and I am glad you said it rather than me, because that is the
part a caption will not tell you. All 4 of the escaping points sit
between theoretical quantile -1.9 and -1.6 — one short stretch on the
left flank. Now the sag itself, and here I am going to make you do the
thing I told you to do with the SD, because a count of signs is a
randomisation draw exactly as an SD is.</p></div>
<div id="worm-seed-sweep" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many of the lowest third of the deviations are negative? That is one draw</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># from the residual randomiser, so recount it over two hundred rngs. Only the</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># residuals are redrawn; the fitted model never moves.</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>neg_by_seed <span class="op">=</span> [<span class="fu">worm_outside</span>(<span class="fu">residuals</span>(bbin; type <span class="op">=</span> <span class="op">:</span>quantile,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                                      rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(s))).neg_left for s <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">200</span>]</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>neg_med <span class="op">=</span> <span class="fu">median</span>(neg_by_seed)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>neg_lo, neg_hi <span class="op">=</span> <span class="fu">quantile</span>(neg_by_seed, <span class="fl">0.1</span>), <span class="fu">quantile</span>(neg_by_seed, <span class="fl">0.9</span>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>neg_sym <span class="op">=</span> <span class="fu">div</span>(w_bb.third, <span class="fl">2</span>)     <span class="co"># what a symmetric residual would give</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>neg_share_above <span class="op">=</span> <span class="fu">mean</span>(neg_by_seed <span class="op">.&gt;</span> neg_sym)   <span class="co"># share of the 200 draws that clear the symmetric count</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"negatives among the lowest %d deviations, over 200 rngs: median %.1f, 10th to 90th %.1f to %.1f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>        w_bb.third, neg_med, neg_lo, neg_hi)</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"the draw shown above gave: %d;  a symmetric residual would give %d</span><span class="sc">\n</span><span class="st">"</span>, w_bb.neg_left, neg_sym)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>negatives among the lowest 54 deviations, over 200 rngs: median 35.5, 10th to 90th 27.0 to 45.1
the draw shown above gave: 49;  a symmetric residual would give 27</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>The typical count is 35.5 of 54, with an ordinary range of 27 to 45,
against the 27 a symmetric residual would give. <strong>The sag is
real</strong> — 35.5 sits well above 27 in 86% of the two hundred draws,
and only 14% of them fall back to 27 or lower. And the particular draw
shown above gives 49, near the top of that range, so quoting
<em>that</em> number as the evidence would have overstated the shape by
a third. <strong>That is the same lesson as the SD, on a statistic that
looks like a count rather than an estimate.</strong> <strong>The sag is
a shape, it is inside the envelope almost everywhere, and it is honest
to report it as a shape rather than as a pass.</strong> What it is not
is the whole-plot S that convicted the Poisson. Deviations in a worm
plot are <strong>order statistics</strong> — the same residuals sorted
smallest to largest, one per rank — and therefore heavily
<strong>autocorrelated</strong>: sorting pins each one between its
neighbours, so a smooth wander is the ordinary condition; what you
convict on is a run that leaves the envelope and stays out.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So this model is right?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>This model has stopped complaining about the things I know how to ask
it, which is a much weaker sentence and the only one I am entitled to.
It still pretends these females are strangers to one another, and no
diagnostic on this file can see that, because the file does not record
who is who.</p></div>
<h3 id="so-where-does-the-negative-binomial-come-in" class="anchored">So where does the negative binomial come in</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Momo has been patient for the second time this morning. The negative
binomial is the repair everyone reaches for first, it is the one Class 3
promised you, and it deserves ten minutes rather than an hour. It
changes exactly one line of the decree:</p></div>
<p class="board"><strong>y_i ~ NegBinomial2(μ_i, θ), log μ_i = β0 + β1 x_i, Var(y_i |
x_i) = μ_i + μ_i²/θ</strong></p>
<div class="line"><span class="who itchy">Itchy</span><p>Same first line, same second line, and a third line with a free
parameter in it. θ is estimated from the data like any other parameter,
and it buys the variance permission to exceed the mean. When θ is
enormous, μ²/θ vanishes and you are back in Class 3 with the Poisson.
When θ is small, the extra term dominates. <strong>θ is the price of the
lie</strong>, and the smaller it is the bigger the lie was — which is
backwards from what everybody expects, so say it out loud twice. Large
θ, tidy counts. Small θ, messy counts.</p></div>
<div id="cell-fit-nb2" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>nb <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age), <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)),</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">NegBinomial2</span>(); data <span class="op">=</span> females)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>nb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-nb2" class="cell-output cell-output-display" data-execution_count="32">
<pre><code>Distributional regression fit (NegBinomial2)
  nobs = 163   logLik = -356.5665   converged = true

Mean model (μ):
  H0: coefficient = 0
                Coef.  Std.Error       z   Pr(&gt;|z|)
  (Intercept)  0.7044     0.1441  4.8901  1.008e-06
  Age          0.2337     0.0663  3.5235   0.000426

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -0.6914     0.1520  -4.5487  5.397e-06</code></pre>
</div>
</div>
<div id="theta" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>theta <span class="op">=</span> <span class="fu">exp</span>(<span class="op">-</span><span class="fl">2</span> <span class="op">*</span> <span class="fu">coef</span>(nb, <span class="op">:</span>sigma)[<span class="fl">1</span>])</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>d_aic_nb <span class="op">=</span> <span class="fu">aic</span>(pois) <span class="op">-</span> <span class="fu">aic</span>(nb)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>se_pois <span class="op">=</span> <span class="fu">stderror</span>(pois)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>se_nb <span class="op">=</span> <span class="fu">stderror</span>(nb)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>se_ratio <span class="op">=</span> se_nb[<span class="fl">2</span>] <span class="op">/</span> se_pois[<span class="fl">2</span>]</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>quasi_ratio <span class="op">=</span> <span class="fu">sqrt</span>(disp_pois)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"theta = 1 / sigma^2 : %.4f</span><span class="sc">\n</span><span class="st">"</span>, theta)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, Poisson %.4f  -&gt;  NB2 %.4f   (drop of %.4f)</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(pois), <span class="fu">aic</span>(nb), d_aic_nb)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"slope on Age  : %.4f  -&gt;  %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">coef</span>(pois, <span class="op">:</span>mu)[<span class="fl">2</span>], <span class="fu">coef</span>(nb, <span class="op">:</span>mu)[<span class="fl">2</span>])</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"its SE        : %.4f  -&gt;  %.4f   (a factor of %.4f)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>        se_pois[<span class="fl">2</span>], se_nb[<span class="fl">2</span>], se_ratio)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quasi-Poisson would have inflated it by sqrt(X2/df) = %.4f</span><span class="sc">\n</span><span class="st">"</span>, quasi_ratio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>theta = 1 / sigma^2 : 3.9864
AIC, Poisson 739.9864  -&gt;  NB2 719.1331   (drop of 20.8533)
slope on Age  : 0.2325  -&gt;  0.2337
its SE        : 0.0478  -&gt;  0.0663   (a factor of 1.3880)
quasi-Poisson would have inflated it by sqrt(X2/df) = 1.2521</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p><strong>θ is 3.99</strong>, the AIC drops by about 20.9 for one
parameter, the slope on age moves by nothing anybody would notice, and
<strong>the standard error goes up by a factor of 1.39</strong>. Toto,
name what just happened.</p></div>
<div class="line"><span class="who toto">Toto</span><p>The Poisson was lying about the error bar, not the answer.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Written on the board. <strong>Overdispersion is a disease of standard
errors</strong> — and it is not a coincidence, it is a theorem. The
equations a Poisson fit solves to find β have the right answer as their
solution, on average, <em>whatever</em> the true variance is — the
statisticians’ phrase is that the score equations are unbiased
estimating equations — so the estimate stays trustworthy even when the
variance model is wrong; the only thing the wrong variance corrupts is
the standard error. Note the direction, too: the Poisson model does not
shrink the interval because of overdispersion, it shrinks it because it
refuses to admit the overdispersion, which is the worst possible failure
mode. Nobody rejects a paper for being too confident.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And the quasi-Poisson? My old software offered me that.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One line, and it is why Ver Hoef and Boveng are first on the reading
list. The quasi-Poisson keeps the Poisson mean and multiplies every
standard error by the square root of the Pearson statistic: 1.252 here,
against the negative binomial’s 1.388. They are close and they are not
the same, because they weight the birds differently — the quasi-Poisson
inflates every bird equally, the negative binomial downweights the
big-mean birds. On another dataset they disagree about which coefficient
matters. Now, the σ table, and a warning about the line the engine
prints above it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>It says σ = 1 is unit-dependent.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It says that above <strong>every</strong> σ table, and for the Gaussian
sparrows in twenty minutes it will be true: σ = 1 mm is a curiosity
about millimetres. Here it is false. For <code>NegBinomial2()</code> σ
is <strong>dimensionless</strong>, and σ = 1 means θ = 1, that is Var =
μ + μ², which is a real and interpretable dispersion hypothesis. The z
printed on that row is a genuine test of it, and it rejects. The engine
prints that warning without checking which family you asked for, so here
it prints something untrue. That is a fault in the software rather than
something for you to learn. Read the line, then decide whether it
applies to your family.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Can I see the assumption itself rather than its consequences?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You can, and this is the picture I would put in a lecture if I were
allowed only one. Bin the females by age, and for each bin plot the
observed mean against the observed variance. Then draw what each family
claims that relationship must be.</p></div>
<div id="cell-bin-by-age" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>byage <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(females, <span class="op">:</span>Age),</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    nrow <span class="op">=&gt;</span> <span class="op">:</span>n,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>Fledglings <span class="op">=&gt;</span> mean <span class="op">=&gt;</span> <span class="op">:</span>m,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="op">:</span>Fledglings <span class="op">=&gt;</span> var <span class="op">=&gt;</span> <span class="op">:</span>v)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sort!</span>(byage, <span class="op">:</span>Age)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>byage</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="bin-by-age" class="cell-output cell-output-display" data-execution_count="35">
<div><div style="float: left;"><span>4×4 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Age</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">m</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">v</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">2.53846</td>
<td style="text-align: right;">3.8149</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">3.25424</td>
<td style="text-align: right;">5.43425</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">4.09375</td>
<td style="text-align: right;">7.37802</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">2.66667</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="cell-fig-mean-variance" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>mgrid <span class="op">=</span> <span class="fu">collect</span>(<span class="fu">range</span>(<span class="fl">0.9</span> <span class="op">*</span> <span class="fu">minimum</span>(byage.m), <span class="fl">1.1</span> <span class="op">*</span> <span class="fu">maximum</span>(byage.m), length <span class="op">=</span> <span class="fl">100</span>))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">560</span>, <span class="fl">400</span>))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"observed mean count"</span>, ylabel <span class="op">=</span> <span class="st">"observed variance"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"what each family says the variance must be"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, mgrid, mgrid; linewidth <span class="op">=</span> <span class="fl">2</span>, linestyle <span class="op">=</span> <span class="op">:</span>dash,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"Poisson: var = mean"</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, mgrid, mgrid <span class="op">.+</span> mgrid <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> theta; linewidth <span class="op">=</span> <span class="fl">2.5</span>,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"NB2: var = mean + mean²/θ"</span>)</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, byage.m, byage.v; markersize <span class="op">=</span> <span class="fl">3</span> <span class="op">.*</span> <span class="fu">sqrt</span>.(byage.n),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>    color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.75</span>), label <span class="op">=</span> <span class="st">"observed (age bin), area ∝ n"</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<div id="fig-mean-variance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-mean-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk4-overdispersion_files/figure-html/fig-mean-variance-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mean-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Observed mean against observed variance, females binned by age, with marker area showing how many females are in each bin. The Poisson line is the identity; the negative-binomial curve bends above it, and how far it bends is set by 1/θ — the smaller θ, the further the curve climbs above the identity line.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="read-the-bins" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count what the prose would otherwise assert, so the sentence cannot go stale.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>nb_curve <span class="op">=</span> byage.m <span class="op">.+</span> byage.m <span class="op">.^</span> <span class="fl">2</span> <span class="op">./</span> theta</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>n_bins <span class="op">=</span> <span class="fu">nrow</span>(byage)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>n_above <span class="op">=</span> <span class="fu">count</span>(byage.v <span class="op">.&gt;</span> byage.m)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>n_nearer <span class="op">=</span> <span class="fu">count</span>(<span class="fu">abs</span>.(byage.v <span class="op">.-</span> nb_curve) <span class="op">.&lt;</span> <span class="fu">abs</span>.(byage.v <span class="op">.-</span> byage.m))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>n_below_both <span class="op">=</span> <span class="fu">count</span>((byage.v <span class="op">.&lt;</span> byage.m) <span class="op">.&amp;</span> (byage.v <span class="op">.&lt;</span> nb_curve))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>i_small <span class="op">=</span> <span class="fu">argmin</span>(byage.n)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"bins above the identity line : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, n_above, n_bins)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"bins nearer the NB2 curve    : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, n_nearer, n_bins)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"bins below both              : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, n_below_both, n_bins)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"smallest bin: age %d, n = %d, mean %.3f, variance %.3f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>        byage.Age[i_small], byage.n[i_small], byage.m[i_small], byage.v[i_small])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>bins above the identity line : 3 of 4
bins nearer the NB2 curve    : 3 of 4
bins below both              : 1 of 4
smallest bin: age 4, n = 7, mean 5.000, variance 2.667</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>3 of the 4 bins sit above the line and 3 sit nearer the curve. 1 sits
below both, and before anybody builds a theory about it, look at how few
birds are in it: 7. A variance estimated from 7 numbers is a very
unstable thing. That point is not counter-evidence; it is the reason we
fit a model over all 163 females instead of eyeballing four dots, and it
is why the marker sizes are on the plot at all. A figure that hides its
sample sizes will let you believe anything.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So I <em>should</em> have used the negative binomial.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Put it on top of the exposure model and find out.</p></div>
<div id="nb2-on-exposure" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>nbe <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age <span class="op">+</span> logEgg), <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)),</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">NegBinomial2</span>(); data <span class="op">=</span> females)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>theta_e <span class="op">=</span> <span class="fu">exp</span>(<span class="op">-</span><span class="fl">2</span> <span class="op">*</span> <span class="fu">coef</span>(nbe, <span class="op">:</span>sigma)[<span class="fl">1</span>])</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"theta, Age only          : %.4f</span><span class="sc">\n</span><span class="st">"</span>, theta)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"theta, Age + log(EggNo)  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, theta_e)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, Poisson + exposure  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(poe))</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, NB2     + exposure  : %.4f   (difference %.4f)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aic</span>(nbe), <span class="fu">aic</span>(nbe) <span class="op">-</span> <span class="fu">aic</span>(poe))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>theta, Age only          : 3.9864
theta, Age + log(EggNo)  : 29.2025
AIC, Poisson + exposure  : 652.8208
AIC, NB2     + exposure  : 654.1004   (difference 1.2796)</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>θ goes from 4.0 to 29.2 — a number that large is the negative binomial
telling you it has nothing to do — and the extra parameter makes AIC
<strong>worse</strong> by about 1.3. The family repair earned about 21
AIC against a model with a missing covariate, and earns nothing at all
once the covariate is there. <strong>That is the whole of the first half
of today, in one comparison.</strong> The negative binomial is a good
family and it was not what was wrong.</p></div>
<h3 id="the-same-move-in-a-family-that-never-lied" class="anchored">The same move, in a family that never lied</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Right. Toto, you have been quiet, and you are about to see why this
chapter is not called “the negative binomial”.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Because you are going to do it to the sparrows.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because I am going to do it to the sparrows, and the sparrows have a
<strong>Gaussian</strong> response, where nobody ever said the variance
was a function of the mean. Load Class 2 back.</p></div>
<div id="cell-sparrows" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/MBodySize.csv"</span>, DataFrame)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>raw.Sex <span class="op">=</span> <span class="fu">ifelse</span>.(raw.Sex <span class="op">.==</span> <span class="st">"F"</span>, <span class="st">"female"</span>, <span class="st">"male"</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>sparrows <span class="op">=</span> <span class="fu">select</span>(raw, <span class="op">:</span>BirdID, <span class="op">:</span>Sex, <span class="op">:</span>Tarsus, <span class="op">:</span>Wing)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>n_sp <span class="op">=</span> <span class="fu">nrow</span>(sparrows)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows: %d</span><span class="sc">\n</span><span class="st">"</span>, n_sp)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">combine</span>(<span class="fu">groupby</span>(sparrows, <span class="op">:</span>Sex), nrow <span class="op">=&gt;</span> <span class="op">:</span>n, <span class="op">:</span>Wing <span class="op">=&gt;</span> std <span class="op">=&gt;</span> <span class="op">:</span>wing_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows: 171</code></pre>
</div>
<div id="sparrows" class="cell-output cell-output-display" data-execution_count="41">
<div><div style="float: left;"><span>2×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">wing_sd</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="String">String</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">1.54432</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">1.68234</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Class 2 fitted wing on tarsus and sex, and printed a single residual
standard deviation for every bird on the island. Here is that model and
here is the same model with a second formula in the box.</p></div>
<p class="board"><strong>y_i ~ N(μ_i, σ_i²), μ_i = β0 + β1 tarsus_i + β2 male_i, log σ_i
= γ0 + γ1 male_i</strong></p>
<div id="cell-fit-sparrows" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fit_const <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>fit_ls <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex), <span class="pp">@formula</span>(sigma <span class="op">~</span> Sex)),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>fit_ls</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-sparrows" class="cell-output cell-output-display" data-execution_count="42">
<pre><code>Distributional regression fit (Gaussian)
  nobs = 171   logLik = -301.6513   converged = true
  Residual SD (response scale) varies with the σ model: 1.3757 to 1.4528   dof_residual = 166

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z    Pr(&gt;|z|)
  (Intercept)  57.8574     2.6912  21.4985  1.609e-102
  Tarsus        1.0097     0.1450   6.9630   3.332e-12
  Sex: male     2.5015     0.2183  11.4614   2.063e-30

Scale model (log σ):
  H0: coefficient = 0 on log σ
  intercept ⇔ σ = 1 (unit-dependent); slope ⇔ equal dispersion
                Coef.  Std.Error       z   Pr(&gt;|z|)
  (Intercept)  0.3190     0.0750  4.2549  2.092e-05
  Sex: male    0.0545     0.1083  0.5034     0.6147</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>That is the same shape of call as the beta-binomial.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is the identical shape of call, and that is the sentence this whole
class was built to earn. Three families, three very different-looking
problems, <strong>one verb and a second formula in the same
box</strong>. <code>BetaBinomial()</code> freed a variance the family
had pinned to <em>n</em>·p(1 − p). <code>NegBinomial2()</code> freed one
pinned to the mean. <code>sigma ~ Sex</code> frees one pinned to a
single number. Same constant, freed three times, from three directions.</p></div>
<div class="line"><span class="who toto">Toto</span><p>And the header changed.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Read it out. Where Class 2 printed one residual SD, this prints a
<strong>range</strong>, because with <code>Sex</code> in σ there is no
single number to print. This kind of model has a name —
<strong>location-scale</strong>: a formula on the mean, which is the
location, and a second formula on σ, which is the scale. Compute the
ends by hand once, so that the header means something to you.</p></div>
<div id="sigma-by-sex" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>s_hat <span class="op">=</span> <span class="fu">exp</span>.(<span class="fu">coef</span>(fit_ls, <span class="op">:</span>sigma))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>sigma_f <span class="op">=</span> s_hat[<span class="fl">1</span>]</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>sigma_m <span class="op">=</span> s_hat[<span class="fl">1</span>] <span class="op">*</span> s_hat[<span class="fl">2</span>]</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>sd_range <span class="op">=</span> <span class="fu">extrema</span>(<span class="fu">sigma</span>(fit_ls))</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sigma, females : %.4f mm</span><span class="sc">\n</span><span class="st">"</span>, sigma_f)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sigma, males   : %.4f mm</span><span class="sc">\n</span><span class="st">"</span>, sigma_m)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"constant-sigma model, one number : %.4f mm</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">sigma</span>(fit_const)[<span class="fl">1</span>])</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"location-scale model, the range  : %.4f to %.4f mm</span><span class="sc">\n</span><span class="st">"</span>, sd_range[<span class="fl">1</span>], sd_range[<span class="fl">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma, females : 1.3757 mm
sigma, males   : 1.4528 mm
constant-sigma model, one number : 1.4132 mm
location-scale model, the range  : 1.3757 to 1.4528 mm</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Females scatter by about 1.38 mm around their line, males by about 1.45
mm. Males a little <strong>more</strong>, which is not what I would have
guessed. Now the verdicts, and I already know how this ends because we
ran it in Class 2.</p></div>
<div id="sparrow-verdicts" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>ct_ls <span class="op">=</span> <span class="fu">coeftable</span>(fit_ls)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>r_sex <span class="op">=</span> <span class="fu">findfirst</span>(<span class="op">==</span>(<span class="st">"sigma: Sex: male"</span>), ct_ls.rownms)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>g1 <span class="op">=</span> ct_ls.cols[<span class="fl">1</span>][r_sex]</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>se_g1 <span class="op">=</span> ct_ls.cols[<span class="fl">2</span>][r_sex]</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>z_sex <span class="op">=</span> ct_ls.cols[<span class="fl">3</span>][r_sex]</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>p_sex <span class="op">=</span> ct_ls.cols[<span class="fl">4</span>][r_sex]</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>d_aic_sp <span class="op">=</span> <span class="fu">aic</span>(fit_ls) <span class="op">-</span> <span class="fu">aic</span>(fit_const)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>ratio_sex <span class="op">=</span> <span class="fu">exp</span>(g1)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>ratio_lo, ratio_hi <span class="op">=</span> <span class="fu">exp</span>(ct_ls.cols[<span class="fl">5</span>][r_sex]), <span class="fu">exp</span>(ct_ls.cols[<span class="fl">6</span>][r_sex])</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Smallest sigma ratio this design could have detected at 80% power, alpha = 0.05.</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>z_a <span class="op">=</span> Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Normal</span>(), <span class="fl">0.975</span>)</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>z_b <span class="op">=</span> Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Normal</span>(), <span class="fl">0.80</span>)</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>mdr <span class="op">=</span> <span class="fu">exp</span>((z_a <span class="op">+</span> z_b) <span class="op">*</span> se_g1)</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, constant sigma  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(fit_const))</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"AIC, sigma ~ Sex     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">aic</span>(fit_ls))</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"difference           : %.4f  (positive means the extra term did not pay)</span><span class="sc">\n</span><span class="st">"</span>, d_aic_sp)</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">sigma: Sex: male   z = %.4f   p = %.4f</span><span class="sc">\n</span><span class="st">"</span>, z_sex, p_sex)</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"male/female sigma ratio : %.4f  [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>, ratio_sex, ratio_lo, ratio_hi)</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"smallest ratio detectable at 80%% power : %.4f</span><span class="sc">\n</span><span class="st">"</span>, mdr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AIC, constant sigma  : 611.5563
AIC, sigma ~ Sex     : 613.3026
difference           : 1.7464  (positive means the extra term did not pay)

sigma: Sex: male   z = 0.5034   p = 0.6147
male/female sigma ratio : 1.0560  [0.8541, 1.3057]
smallest ratio detectable at 80% power : 1.3544</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>It got worse.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>AIC got worse by about 1.75, and the σ table’s own row agrees: a z of
0.5 and a p of 0.61. Now say what that means, carefully, because this is
where papers go wrong. The estimated ratio is 1.056 — males scattering
about 6% more — with an interval from 0.854 to 1.306. These birds are
consistent with males varying rather less than females and with males
varying rather more.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So the answer is not “no”.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The answer is <strong>not detected</strong>, and the two are not the
same sentence. With 171 birds, the smallest ratio this design could have
caught four times out of five is 1.35. Anything smaller than that was
never going to show up, whether or not it is there. <strong>“We could
not tell them apart, and we could only have seen a 35% difference” is
the honest report; “the answer is no” is an accepted null wearing a lab
coat.</strong> Class 2 reports this identical fit in exactly those
terms, and it is worth turning back to check that it does, because a
book that says “no” in one chapter and “not detected” in another has not
decided what it believes.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So one of your repairs worked and the other did not.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One worked, one did not pay, and I am keeping both, because a chapter
where every experiment succeeds is teaching you a superstition. The
method is the same, the verdict is data, and the only thing that would
have been wrong was not asking. Look at what “did not pay” actually
looks like.</p></div>
<div id="cell-fig-sparrow-bands" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> <span class="fu">coef</span>(fit_ls, <span class="op">:</span>mu)          <span class="co"># [intercept, Tarsus, Sex: male]; female is the baseline</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>tg <span class="op">=</span> <span class="fu">collect</span>(<span class="fu">range</span>(<span class="fu">minimum</span>(sparrows.Tarsus), <span class="fu">maximum</span>(sparrows.Tarsus), length <span class="op">=</span> <span class="fl">100</span>))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>mu_f <span class="op">=</span> b[<span class="fl">1</span>] <span class="op">.+</span> b[<span class="fl">2</span>] <span class="op">.*</span> tg</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>mu_m <span class="op">=</span> b[<span class="fl">1</span>] <span class="op">.+</span> b[<span class="fl">2</span>] <span class="op">.*</span> tg <span class="op">.+</span> b[<span class="fl">3</span>]</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>is_m <span class="op">=</span> sparrows.Sex <span class="op">.==</span> <span class="st">"male"</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">560</span>, <span class="fl">400</span>))</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"tarsus (mm)"</span>, ylabel <span class="op">=</span> <span class="st">"wing (mm)"</span>,</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"two lines, two widths, one of them unearned"</span>)</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Bands and lines share one colour per sex (accent = female, warn = male) so a</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="co"># reader can match a band to its line by hue, not only by which one sits</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="co"># higher; the near-equal alpha keeps the WIDTH comparison — the point of this</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a><span class="co"># figure — the thing that reads as similar, not the shading. Data drawn LAST</span></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a><span class="co"># so no bird is ever painted over by the model on top of it.</span></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a><span class="fu">band!</span>(ax, tg, mu_f <span class="op">.-</span> sigma_f, mu_f <span class="op">.+</span> sigma_f; color <span class="op">=</span> (LIGHT.accent, <span class="fl">0.22</span>),</span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"females, ±σ"</span>)</span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a><span class="fu">band!</span>(ax, tg, mu_m <span class="op">.-</span> sigma_m, mu_m <span class="op">.+</span> sigma_m; color <span class="op">=</span> (LIGHT.warn, <span class="fl">0.22</span>),</span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"males, ±σ"</span>)</span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, tg, mu_f; linewidth <span class="op">=</span> <span class="fl">2.5</span>, color <span class="op">=</span> LIGHT.accent, label <span class="op">=</span> <span class="st">"female mean"</span>)</span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, tg, mu_m; linewidth <span class="op">=</span> <span class="fl">2.5</span>, linestyle <span class="op">=</span> <span class="op">:</span>dash, color <span class="op">=</span> LIGHT.warn, label <span class="op">=</span> <span class="st">"male mean"</span>)</span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, sparrows.Tarsus[.!is_m], sparrows.Wing[.!is_m];</span>
<span id="cb54-23"><a href="#cb54-23" aria-hidden="true" tabindex="-1"></a>    markersize <span class="op">=</span> <span class="fl">6</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.6</span>), label <span class="op">=</span> <span class="st">"female"</span>)</span>
<span id="cb54-24"><a href="#cb54-24" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, sparrows.Tarsus[is_m], sparrows.Wing[is_m];</span>
<span id="cb54-25"><a href="#cb54-25" aria-hidden="true" tabindex="-1"></a>    markersize <span class="op">=</span> <span class="fl">6</span>, marker <span class="op">=</span> <span class="op">:</span>diamond, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.6</span>), label <span class="op">=</span> <span class="st">"male"</span>)</span>
<span id="cb54-26"><a href="#cb54-26" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb54-27"><a href="#cb54-27" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<div id="fig-sparrow-bands" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-sparrow-bands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk4-overdispersion_files/figure-html/fig-sparrow-bands-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sparrow-bands-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Wing on tarsus, with a ±1σ band per sex from the location-scale fit. The bands differ, and not by enough to earn their parameter — nor by enough for this design to have detected the difference if it were real.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Two bands of very nearly the same width. That picture is what a p of
0.61 looks like before anybody computes a p, and you should learn to see
it, because the picture is available to you before the test is.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So when <em>is</em> modelling σ worth it?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>When the spread is genuinely a function of something you measured, and
that is a chapter of its own — <strong>rung 11, modelling the spread
itself, which is held for version two of this book</strong>. Today you
have seen the syntax and one honest not-detected, which is the right
amount for a Tuesday. Class 5 is next and is about nothing but
diagnostics, which is where the worm plot and the coverage arithmetic
get done properly. And every model on this page is still fixed effects
only. Class 6 is where rows stop being strangers, on a file that records
who is who.</p></div>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>Compare like with like.</strong> A Poisson <em>regression</em> decrees Var(y | x) = μ(x); it says nothing about the variance-to-mean ratio of the raw counts, which also carries the variation the predictors create. Here the raw ratio is 1.69 and a perfectly correct Poisson would still imply 1.15. Check overdispersion on residuals, not on the marginal moments.</li>
<li><strong>Look for an exposure before you blame the family.</strong> An offset or denominator sitting unused in your data is the commonest cause of “overdispersion” and the cheapest to fix. Here <code>log(EggNo)</code> bought about 87 AIC for one parameter and moved the age rate ratio from 1.26 to 1.09, interval covering one. <strong>A missing covariate and a wrong variance function look identical in a residual plot.</strong></li>
<li><strong>An offset is a covariate with its coefficient pinned at one.</strong> Fit it free first: if the interval covers one, the offset is the better model; if it does not, the offset would have been a confident mistake.</li>
<li><strong>Successes out of trials is not a count.</strong> For <em>n</em> &gt; 1 the binomial variance is <em>n</em>·p(1 − p), which is a real claim — the trials within a row are independent — and data can break it. For <em>n</em> = 1 it is an identity, which is why Class 3’s logistic diagnostic could not fail.</li>
<li><strong>The beta-binomial frees that claim with one parameter</strong>, as the negative binomial frees Var = μ with θ. Here it bought about 25 AIC and took the Pearson statistic from 1.64 to 1.02.</li>
<li><strong>AIC compares models of the same response.</strong> Counts and proportions-out-of-a-denominator are different data. Choose between them by the question you are asking, not by the smaller number.</li>
<li><strong>Overdispersion is a disease of standard errors, and that is a theorem.</strong> The Poisson score equations are unbiased estimating equations for β whatever the true variance, so the point estimate stays consistent; only its standard error was wrong. Here it was wrong by a factor of 1.39, against the quasi-Poisson’s 1.25 — close, not identical, because the two weight observations differently.</li>
<li><strong>Read the null the engine prints above the σ table, then check it applies to your family.</strong> For a Gaussian, σ = 1 is unit-dependent and rarely interesting. For <code>NegBinomial2()</code> and <code>BetaBinomial()</code>, σ is dimensionless and σ = 1 is a real dispersion hypothesis that the printed z genuinely tests.</li>
<li><strong>Judge a band against its own claim.</strong> A ±1 SD band is not supposed to contain the data. Ask the model what coverage it claims and compare: 0.53 against 0.67 for the binomial, 0.66 against 0.67 for the beta-binomial.</li>
<li><strong>“Not detected” is not “no”.</strong> The sparrows’ σ ratio is 1.06 with an interval of 0.85 to 1.31, and the smallest ratio this design could have caught at 80% power is 1.35. Report the interval and the detectable size, not a verdict.</li>
<li><strong>A model comparison that goes against you is a result.</strong> The counts earned their beta-binomial parameter and the sparrows lost their σ term by about 1.7 AIC. Reporting only the one that worked is how a literature goes wrong.</li>
<li><strong>Plot the assumption, not only its consequences.</strong> Mean against variance, binned, with the family’s claim drawn as a curve and marker area showing sample size, is the fastest way to see a variance assumption fail or hold.</li>
<li><strong>This chapter still pretends rows are independent</strong>, and these files cannot stop it. <code>FemaleSuccess.csv</code> carries no female identifier at all; <code>MBodySize.csv</code> does carry <code>BirdID</code>, but one row per bird, so there is nothing for a random intercept to group. The repeated-measures file is <code>BodySize.csv</code>. Class 6 removes the pretence there, and Class 9 puts today’s freed variance and Class 6’s freed correlation into the same model.</li>
</ul>
<h3 id="julia-stuff" class="anchored">Julia stuff</h3>
<ul>
<li><code>drm(bf(@formula(cbind(k, n - k) ~ x)), Binomial(); data = df)</code>: a <strong>grouped</strong> binomial. The response is two columns — successes and failures — and <code>cbind</code> is DRM’s own marker, not R’s function.</li>
<li><code>drm(bf(@formula(cbind(k, n - k) ~ x), @formula(sigma ~ 1)), BetaBinomial(); data = df)</code>: the overdispersed version. <code>coef(fit, :sigma)</code> is log σ and the precision is φ = 1/σ², so <code>exp(-2 * coef(fit, :sigma)[1])</code>.</li>
<li><code>drm(bf(@formula(y ~ x), @formula(sigma ~ 1)), NegBinomial2(); data = df)</code>: overdispersed counts, with θ = 1/σ² by the same arithmetic. Neither engine prints θ or φ for you.</li>
<li><strong>There is no <code>offset</code> in DRM.jl 0.7.1</strong> — a known limitation, reported to the engine’s authors. Add <code>log(exposure)</code> as an ordinary covariate and check whether its interval covers one; <code>drmTMB</code> writes <code>offset(log(exposure))</code> directly.</li>
<li><code>drm(bf(@formula(y ~ x + g), @formula(sigma ~ g)), Gaussian(); data = df)</code>: a location-scale Gaussian fit. <code>coef(fit, :sigma)</code> is on the log scale; exponentiate for millimetres.</li>
<li><code>sigma(fit)</code>: the response-scale σ per observation for a Gaussian fit. On a constant-σ fit every element is the same number; on a modelled σ it is a range, which is what the fit header prints. On <code>BetaBinomial()</code> it returns the σ <strong>and</strong> the trial counts, so read θ or φ off <code>coef(fit, :sigma)</code> instead.</li>
<li><code>coeftable(fit)</code>: row names are prefixed by block, so <code>"mu: Age"</code> and <code>"sigma: Sex: male"</code>. Columns 5 and 6 are the confidence limits, on the <strong>link</strong> scale, so exponentiate them for a rate ratio or a σ ratio.</li>
<li><code>dof_residual(fit)</code>: exported and needed for a Pearson dispersion statistic, which the engine does not compute for you.</li>
<li><code>residuals(fit; type = :quantile, rng = MersenneTwister(seed))</code>: standard normal under a correct model for every family here. <strong>Pass the <code>rng</code></strong> — and know that <em>which</em> rng you pass moves the second decimal, so quote the SD against its Monte Carlo standard error of 1/√(2n) rather than reading its digits.</li>
<li><code>import Distributions</code>: needed here because DRM exports its own <code>Poisson</code>, <code>Binomial</code> and <code>BetaBinomial</code>. Qualify the distribution as <code>Distributions.Poisson(μ)</code> when you want a pmf or a cdf.</li>
<li><strong>Marker size as sample size.</strong> <code>markersize = 3 .* sqrt.(n)</code> in a binned plot. Area, not radius, is what the eye reads.</li>
<li><strong>The simulation thread.</strong> Ask the negative-binomial fit to invent two hundred new sets of females, refit each, and watch which parameter is well pinned down and which is not.</li>
</ul>
<div id="simulate-refit" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw new counts from the fitted NB2 model, refit the same model to each,</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and collect two things: the slope on Age, and the dispersion theta.</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>ysim <span class="op">=</span> <span class="fu">simulate</span>(nb; nsim <span class="op">=</span> <span class="fl">200</span>, rng <span class="op">=</span> rng_sim)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">refit_pair</span>(y)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> <span class="fu">DataFrame</span>(Fledglings <span class="op">=</span> y, Age <span class="op">=</span> females.Age)</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age), <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)),</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">NegBinomial2</span>(); data <span class="op">=</span> d)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>    (<span class="fu">coef</span>(f, <span class="op">:</span>mu)[<span class="fl">2</span>], <span class="fu">exp</span>(<span class="op">-</span><span class="fl">2</span> <span class="op">*</span> <span class="fu">coef</span>(f, <span class="op">:</span>sigma)[<span class="fl">1</span>]))</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>pairs_out <span class="op">=</span> [<span class="fu">refit_pair</span>(ysim[<span class="op">:</span>, k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim, <span class="fl">2</span>)]</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>slopes <span class="op">=</span> <span class="fu">first</span>.(pairs_out)</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>thetas <span class="op">=</span> <span class="fu">last</span>.(pairs_out)</span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Monte-Carlo SE of a median, so the "bias" claim carries its own error bar.</span></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a><span class="co"># The textbook 1.2533 * SD / sqrt(n) is a LARGE-SAMPLE formula and runs wide for a</span></span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a><span class="co"># statistic this skewed, so resample the refits themselves and use that instead.</span></span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a>rng_boot <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">4321</span>)</span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a>n_ref <span class="op">=</span> <span class="fu">length</span>(thetas)</span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a>boot_med <span class="op">=</span> [<span class="fu">median</span>(thetas[<span class="fu">rand</span>(rng_boot, <span class="fl">1</span><span class="op">:</span>n_ref, n_ref)]) for _ <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">2000</span>]</span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>mcse_median <span class="op">=</span> <span class="fu">std</span>(boot_med)</span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a>mcse_asymptotic <span class="op">=</span> <span class="fl">1.2533</span> <span class="op">*</span> <span class="fu">std</span>(thetas) <span class="op">/</span> <span class="fu">sqrt</span>(n_ref)</span>
<span id="cb55-25"><a href="#cb55-25" aria-hidden="true" tabindex="-1"></a>bias_pct <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> (<span class="fu">median</span>(thetas) <span class="op">-</span> theta) <span class="op">/</span> theta</span>
<span id="cb55-26"><a href="#cb55-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-27"><a href="#cb55-27" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"slope on Age    : fitted %.4f, reported SE %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">coef</span>(nb, <span class="op">:</span>mu)[<span class="fl">2</span>], se_nb[<span class="fl">2</span>])</span>
<span id="cb55-28"><a href="#cb55-28" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"                  refits: mean %.4f, SD %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(slopes), <span class="fu">std</span>(slopes))</span>
<span id="cb55-29"><a href="#cb55-29" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">theta           : fitted %.4f</span><span class="sc">\n</span><span class="st">"</span>, theta)</span>
<span id="cb55-30"><a href="#cb55-30" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"                  refits: mean %.4f, median %.4f, SD %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb55-31"><a href="#cb55-31" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(thetas), <span class="fu">median</span>(thetas), <span class="fu">std</span>(thetas))</span>
<span id="cb55-32"><a href="#cb55-32" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"                  median is %+.1f%% of the generating value, %.2f Monte Carlo SE (bootstrap Monte Carlo SE %.4f;</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb55-33"><a href="#cb55-33" aria-hidden="true" tabindex="-1"></a>        bias_pct, <span class="fu">abs</span>(<span class="fu">median</span>(thetas) <span class="op">-</span> theta) <span class="op">/</span> mcse_median, mcse_median)</span>
<span id="cb55-34"><a href="#cb55-34" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"                  the large-sample formula would have said %.4f, which is wider)</span><span class="sc">\n</span><span class="st">"</span>, mcse_asymptotic)</span>
<span id="cb55-35"><a href="#cb55-35" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"                  refits: 10th pct %.4f, 90th pct %.4f, max %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb55-36"><a href="#cb55-36" aria-hidden="true" tabindex="-1"></a>        <span class="fu">quantile</span>(thetas, <span class="fl">0.1</span>), <span class="fu">quantile</span>(thetas, <span class="fl">0.9</span>), <span class="fu">maximum</span>(thetas))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>slope on Age    : fitted 0.2337, reported SE 0.0663
                  refits: mean 0.2361, SD 0.0678

theta           : fitted 3.9864
                  refits: mean 4.2842, median 4.0946, SD 1.2401
                  median is +2.7% of the generating value, 1.12 Monte Carlo SE (bootstrap Monte Carlo SE 0.0966;
                  the large-sample formula would have said 0.1099, which is wider)
                  refits: 10th pct 2.8967, 90th pct 5.9290, max 9.2220</code></pre>
</div>
</div>
<p>The numbers above say “strongly asymmetric” six ways; here is the shape itself, so you can see it rather than assemble it from percentiles.</p>
<div id="cell-fig-theta-refits" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">560</span>, <span class="fl">360</span>))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"θ (refit)"</span>, ylabel <span class="op">=</span> <span class="st">"count of refits (of 200)"</span>,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"two hundred refits of one parameter"</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist!</span>(ax, thetas; bins <span class="op">=</span> <span class="fl">25</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.55</span>))</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax, [theta]; linewidth <span class="op">=</span> <span class="fl">2.5</span>, linestyle <span class="op">=</span> <span class="op">:</span>dash, color <span class="op">=</span> LIGHT.accent,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"fitted θ"</span>)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax, [<span class="fu">median</span>(thetas)]; linewidth <span class="op">=</span> <span class="fl">2.5</span>, linestyle <span class="op">=</span> <span class="op">:</span>dot, color <span class="op">=</span> LIGHT.warn,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"median of refits"</span>)</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<div id="fig-theta-refits" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-theta-refits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk4-overdispersion_files/figure-html/fig-theta-refits-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-theta-refits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: The sampling distribution of θ across the 200 parametric refits: two hundred counts of a single fitted parameter, from data the fitted model itself generated. The dashed line marks the θ the one real fit reported; the dotted line marks the median of the 200 refits. A symmetric standard error would draw a bell centred on the dashed line — this is not that.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The slope behaves itself: the spread of refitted slopes lands close to the standard error the single fit reported, which is what a standard error promises. θ does not. Its refits are strongly <strong>asymmetric</strong> — the mean printed above sits higher than the median, the largest refit is 2.3 times the estimate, and the tenth and ninetieth percentiles are nowhere near symmetric about 3.99. The median itself is 2.7% off the generating value, which is 1.12 Monte-Carlo standard errors. Read that as <strong>two hundred refits cannot resolve a bias of a few per cent</strong>, not as <em>there is no bias</em>: the two sentences are different, and only the first one is what these two hundred refits measured. Note also which error bar it is measured against. The textbook Monte-Carlo standard error of a median, 1.2533 × SD/√n, is a large-sample approximation, and on a distribution this skewed it comes out at 0.11 where resampling the refits themselves gives 0.097 — so the formula understates the evidence by being too generous with the error bar, which is a nice inversion of the usual complaint. The asymmetry, though, is unmistakable, and it is why an interval read off the likelihood itself beats the plain estimate-plus-or-minus-two-standard-errors kind — the <strong>Wald</strong> interval, which assumes the uncertainty is the same size on both sides — for this parameter, and why quoting a dispersion to three decimal places is theatre. Appendix A takes that apart properly.</p>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. Details checked on 2026-09-07 against OpenAlex, an open
catalogue of research papers.</p>
<ol type="1">
<li><strong>Ver Hoef, J. M. &amp; Boveng, P. L. (2007) “Quasi-Poisson vs.&nbsp;negative binomial regression: how should we model overdispersed count data?”, <em>Ecology</em> 88:2766–2772.</strong> doi:10.1890/07-0043.1. Start here, and read it before you choose. It sets the negative binomial against the other standard repair, the quasi-Poisson, and the difference is not cosmetic: they weight observations differently, so they can disagree about which coefficient matters. This class computed both inflation factors in one line; the paper is why they are not the same number.</li>
<li><strong>Lindén, A. &amp; Mäntyniemi, S. (2011) “Using the negative binomial distribution to model overdispersion in ecological count data”, <em>Ecology</em> 92:1414–1421.</strong> doi:10.1890/10-1831.1. The ecologist’s companion to the equation on the board, and the paper that would have caught this chapter’s first mistake: its abstract is about the <strong>mechanisms</strong> that generate overdispersion — sampling, flocking, aggregation, environmental variability — which is exactly the question “is the family wrong, or is something missing from the mean?”.</li>
<li><strong>Harrison, X. A. (2014) “Using observation-level random effects to model overdispersion in count data in ecology and evolution”, <em>PeerJ</em> 2:e616.</strong> doi:10.7717/peerj.616. The repair this chapter deliberately did not use, because it needs machinery from Class 6. Read it after Class 6 and then come back: it is a third route to the same problem, and knowing three routes is what stops you believing any one of them is the definition of the problem.</li>
<li><strong>Rigby, R. A. &amp; Stasinopoulos, D. M. (2005) “Generalized additive models for location, scale and shape”, <em>Journal of the Royal Statistical Society Series C</em> 54:507–554.</strong> doi:10.1111/j.1467-9876.2005.00510.x. The framework the last part of this class belongs to, and where rung 11 goes. This is the paper that says out loud that every parameter of a distribution can have a linear predictor, not only the mean. Long, and the introduction alone repays the afternoon.</li>
<li><strong>Hilbe, J. M. (2011) <em>Negative Binomial Regression</em>, 2nd edition, Cambridge University Press.</strong> doi:10.1017/cbo9780511973420. The reference book, for when you need the parameterisation you were handed rather than the one you like. Own it if counts are your day job; borrow it otherwise, and read the chapters on model selection and on the varieties of negative binomial.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Use your own organism where one is named. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Class 3 and not Class 4.</p>
<ol type="1">
<li><p><strong>Read the file before the model.</strong> Take any count response of your own and list every other column. For each one, answer in a sentence: is this a predictor, an exposure, or neither? An exposure is anything that changes how much opportunity a row had — area searched, hours observed, eggs laid, individuals at risk. If you find one, you have found this chapter’s first lesson in your own data.</p></li>
<li><p><strong>Find the lie, honestly.</strong> Report the variance-to-mean ratio of your raw counts. Then fit a Poisson model and report the Pearson X²/df and the standard deviation of <code>residuals(fit; type = :quantile, rng = MersenneTwister(1))</code> against its Monte Carlo standard error of 1/√(2n). Say which of the three you would put in a paper, and why the other two are still worth having computed.</p></li>
<li><p><strong>The wrong benchmark.</strong> From your fitted Poisson, compute <code>(mean(fitted(fit)) + var(fitted(fit))) / mean(fitted(fit))</code> — the marginal variance-to-mean ratio a <em>correct</em> Poisson regression implies for your data. Compare it with the raw ratio from question 2 and with one. Then write two sentences: one naming which of the two comparisons is like-for-like, and one saying how much of your apparent overdispersion survives it.</p></li>
<li><p><strong>Pay the exposure first.</strong> If question 1 found an exposure, add <code>log(exposure)</code> to the mean model. Report both AICs, the coefficient on <code>log(exposure)</code> with its interval, and whether that interval covers one. Then report what happened to the coefficient you actually care about, and say in one sentence whether you would now write a different result.</p></li>
<li><p><strong>Pay the price.</strong> Refit with <code>NegBinomial2()</code>, with and without the exposure. Report the coefficient, the standard error and the rate ratio in a four-row table, and report θ in both. Then write one sentence naming what changed and one naming what did not.</p></li>
<li><p><strong>Out of how many?</strong> If your response is a success count out of a known denominator, refit it as <code>cbind(successes, failures)</code> with <code>Binomial()</code> and then <code>BetaBinomial()</code>. Report both AICs, the Pearson X²/df under each, and φ. Then answer in one sentence why you may not compare either AIC with the count models from question 5.</p></li>
<li><p><strong>The referee.</strong> Report the AIC difference for the repair you kept. Then answer: if it had gone the other way, what would you have done, and would you have reported the comparison at all? Two sentences, and be honest in the second one.</p></li>
<li><p><strong>Momo’s tadpoles.</strong> Count something per pond and fit both families. Draw the mean-against-variance figure from this class, binning by a predictor of your choice, with marker area showing bin sample size. Name the bin you distrust most, say why, and give its n.</p></li>
<li><p><strong>Eddie’s dunnocks.</strong> Fit <code>Wing ~ Tarsus</code> on Eddie’s data, then add <code>@formula(sigma ~ Sex)</code> to the <code>bf</code>. Report both AICs, the z and p on the σ slope row, <strong>the σ ratio with its interval</strong>, and the smallest ratio your sample size could have detected at 80% power (<code>exp((1.96 + 0.84) * se)</code>). Then write the result as a “not detected, and we could only have seen X” sentence rather than a “no”.</p></li>
<li><p><strong>Count the band.</strong> Take any fit from this class’s exercises, draw its mean ± 1 SD band, and count how many of your observations fall outside it. Then ask the fitted distribution what fraction it <em>expects</em> to fall inside. Report both. One sentence on which of the two numbers a reader can interpret without the other.</p></li>
<li><p><strong>The two faces.</strong> Write one paragraph, no code, explaining to a labmate why <code>BetaBinomial()</code>, <code>NegBinomial2()</code> and <code>sigma ~ x</code> are the same move. Your paragraph must contain the phrase “held fixed” and must name what is held fixed in each case.</p></li>
<li><p><strong>Simulate and watch it wander.</strong> Adapt this class’s last block of code to your own overdispersed fit, with your own seed. Report the SD of the refitted slopes against the reported standard error, and the 10th and 90th percentiles of the refitted dispersion parameter, with the Monte-Carlo standard error of the median. Say which of the two parameters you would be comfortable quoting a symmetric interval for.</p></li>
<li><p><strong>The pretence, again.</strong> Name the grouping this chapter is pretending away in your own data, and say whether your file actually records it — if it does not, say what a file that did would have to contain. Then say which number on today’s output you expect Class 6 to change, in which direction.</p></li>
</ol>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk3-glms.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 3 · The shape of the noise</span></a><a class="chapter-nav-link next" href="wk5-diagnostics.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Class 5 · Is the model any good?</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 4 of a planned 13, ten in v1, plus a coda · draft, all code run, 2026-09-07<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>