<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 5a: is the model any good? – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 5a: is the model any good?</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 5a</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>Is the model any good?</h1>
    <p class="deck">A residual plot tells you whether the model is embarrassed by the data you have. Simulating from the model tells you what the model believes about data you have not seen, and that is where the embarrassing beliefs live.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>Draft. Every number and figure on this page was produced when the site was built.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Every code block and printed result below was actually run when the site was built, and nothing is typed from memory. Every random draw is seeded where it is made, so the page comes out the same every time.<br>
      <b>Caveat</b> The data are real: the 2012 Lundy Island sparrow and female records, read directly from data/2012/MBodySize.csv and data/2012/FemaleSuccess.csv (where the files came from is recorded in data/2012/README.md). Nothing here is invented; the simulated quantities are drawn from models fitted to those files, from stated seeds.
    </p>
  </div>
</header>

<div class="wrap">
<hr>
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>Say what a <strong>response</strong>, a <strong>Pearson</strong> and a <strong>randomised quantile</strong> residual each divide by, why all three coincide in a Gaussian model, and why only the third can be judged against the same picture in every family.</li>
<li>Read a <strong>worm plot</strong>: say what is on each axis, what a correct model looks like, and what the envelope drawn round it does and does not promise.</li>
<li>Calibrate a diagnostic by <strong>simulating its own null</strong> rather than by eye, and say how many points outside an envelope is a lot.</li>
<li>Check a model by <strong>simulating from it</strong>: draw new data with an explicit generator, recompute a statistic you care about, and place the observed value in the simulated distribution — and say why a check you pass is much weaker than a check you fail.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, Friday, and there are two laptops open on the desk
instead of one. TOTO has the sparrow model from Class 2 and a printed
page of coefficients he is rather pleased with. MOMO has her fledgling
counts, the ones the family lied about, and the expression of somebody
who has stopped trusting output. EDDIE will arrive halfway through and
ask the question the first half is for.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Four classes in, you can fit almost anything. Nobody has yet asked me
the only question a referee will ask, which is whether the thing you
fitted is any good. Today is that question, and it is a service class:
no new rung, no new constant freed, just the machinery you will use in
every chapter after this. It takes two hours, and they are two different
activities. This hour is one model on its own — <em>is it any good?</em>
Next hour is two models side by side — <em>which one?</em> People run
those together constantly, and the second cannot do the first’s job,
which is why the first comes first.</p></div>
<div class="line"><span class="who momo">Momo</span><p>In R I would have called <code>residuals</code> on the fit and plotted
them.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And in a Gaussian model you would have been right, which is the trap.
Load both files.</p></div>
<div id="setup" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/diagnostics.jl includes tools/figures.jl, which includes</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/theme_itchy.jl itself, so one include does all three.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">include</span>(<span class="st">"../tools/diagnostics.jl"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span>, <span class="bu">Random</span>, <span class="bu">Printf</span>, <span class="bu">CairoMakie</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> <span class="bu">Distributions</span>          <span class="co"># qualified: DRM exports its own Poisson, Binomial, …</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set_theme!</span>(<span class="fu">theme_itchy</span>(<span class="op">:</span>light))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/MBodySize.csv"</span>, DataFrame)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>raw.Sex <span class="op">=</span> <span class="fu">ifelse</span>.(raw.Sex <span class="op">.==</span> <span class="st">"F"</span>, <span class="st">"female"</span>, <span class="st">"male"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>sparrows <span class="op">=</span> <span class="fu">select</span>(raw, <span class="op">:</span>BirdID, <span class="op">:</span>Sex, <span class="op">:</span>Tarsus, <span class="op">:</span>Wing)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>females <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/FemaleSuccess.csv"</span>, DataFrame)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>n_sp <span class="op">=</span> <span class="fu">nrow</span>(sparrows)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>n_fem <span class="op">=</span> <span class="fu">nrow</span>(females)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sparrows: %d rows   females: %d rows</span><span class="sc">\n</span><span class="st">"</span>, n_sp, n_fem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sparrows: 171 rows   females: 163 rows</code></pre>
</div>
</div>
<h3 id="three-residuals-and-why-you-were-only-taught-one" class="anchored">Three residuals, and why you were only taught one</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Toto’s model first, because it is the one where nothing goes wrong.</p></div>
<div id="fit-sparrows" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>gauss <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Wing <span class="op">~</span> Tarsus <span class="op">+</span> Sex)), <span class="fu">Gaussian</span>(); data <span class="op">=</span> sparrows)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>r_response_g <span class="op">=</span> <span class="fu">residuals</span>(gauss; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>response)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>sigma_g <span class="op">=</span> <span class="fu">sigma</span>(gauss)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>r_pearson_g <span class="op">=</span> r_response_g <span class="op">./</span> sigma_g</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>r_quantile_g <span class="op">=</span> <span class="fu">residuals</span>(gauss; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">1</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"residual SD, response scale : %.4f mm</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_response_g))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"fitted sigma                : %.4f mm</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">first</span>(sigma_g))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Pearson residual SD         : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_pearson_g))</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quantile residual SD        : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_quantile_g))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"largest |Pearson - quantile|: %.3e</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">maximum</span>(abs, r_pearson_g <span class="op">.-</span> r_quantile_g))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>residual SD, response scale : 1.4173 mm
fitted sigma                : 1.4132 mm
Pearson residual SD         : 1.0029
quantile residual SD        : 1.0029
largest |Pearson - quantile|: 2.620e-14</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Three names, three definitions, one vector. The
<strong>response</strong> residual is observed minus fitted, in
millimetres. The <strong>Pearson</strong> residual divides that by the
standard deviation the family decrees for that row — here σ, the same
1.413 mm for every bird, so it is just a change of units. The
<strong>randomised quantile</strong> residual asks the fitted model what
probability it puts below the value you actually saw and maps that
probability through a normal.</p></div>
<div class="line"><span class="who toto">Toto</span><p>And the last two are the same number.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>To 3e-14 millimetres, which is arithmetic noise and not a coincidence.
In a Gaussian model the response is normal by assumption, so mapping it
into a normal and back does nothing at all. <strong>In the one model
everybody is taught, all three residuals are the same object.</strong>
That is exactly why “the residual” feels like one word, and it is why
the habits you brought from that model do not survive contact with a
count.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So do it to mine.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Same three definitions, and this time write out what each one divides
by, because the family has an opinion now. The engine does not offer a
Pearson residual, and that is no loss: writing (y − μ̂)/√V(μ̂) yourself
forces you to say which variance function the family decreed, which is
Class 3’s whole lesson turned into arithmetic.</p></div>
<div id="fit-poisson" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pois <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>mu_p <span class="op">=</span> <span class="fu">fitted</span>(pois)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>r_response <span class="op">=</span> <span class="fu">residuals</span>(pois; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>response)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson decrees Var(y) = mu, so the Pearson divisor is sqrt(mu), row by row.</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>r_pearson <span class="op">=</span> r_response <span class="op">./</span> <span class="fu">sqrt</span>.(mu_p)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>r_quantile <span class="op">=</span> <span class="fu">residuals</span>(pois; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">1</span>))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm, r) <span class="kw">in</span> ((<span class="st">"response"</span>, r_response), (<span class="st">"Pearson"</span>, r_pearson), (<span class="st">"quantile"</span>, r_quantile))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    skew <span class="op">=</span> <span class="fu">mean</span>(((r <span class="op">.-</span> <span class="fu">mean</span>(r)) <span class="op">./</span> <span class="fu">std</span>(r)) <span class="op">.^</span> <span class="fl">3</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"%-9s : SD %.4f   skew %+.4f   distinct values %3d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            nm, <span class="fu">std</span>(r), skew, <span class="fu">length</span>(<span class="fu">unique</span>(<span class="fu">round</span>.(r, digits <span class="op">=</span> <span class="fl">8</span>))))</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"fitted counts run from %.4f to %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">extrema</span>(mu_p)<span class="op">...</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>response  : SD 2.2282   skew +0.2115   distinct values  32
Pearson   : SD 1.2483   skew +0.2159   distinct values  32
quantile  : SD 1.3067   skew -0.2095   distinct values 163
fitted counts run from 2.5580 to 5.1389</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The first two take only 32 different values each and the third takes
163.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Which is 163, one per female, and that is the whole point. (The three
rows came from one loop over a list of name-and-vector pairs, and the
<code>...</code> after <code>extrema(mu_p)</code>
<strong>splats</strong> its two values into <code>@printf</code>’s two
slots.) A count is a whole number, so observed minus fitted lands on a
lattice: at a given fitted value there are only so many residuals
available. Dividing by the square root of the mean rescales the lattice;
it does not dissolve it. Look at all three.</p></div>
<div id="cell-fig-three-residuals" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">780</span>, <span class="fl">300</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>panels <span class="op">=</span> ((<span class="st">"response (chicks)"</span>, r_response), (<span class="st">"Pearson"</span>, r_pearson),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"randomised quantile"</span>, r_quantile))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j, (nm, r)) <span class="kw">in</span> <span class="fu">enumerate</span>(panels)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, j]; xlabel <span class="op">=</span> <span class="st">"fitted count"</span>, title <span class="op">=</span> nm,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        ylabel <span class="op">=</span> j <span class="op">==</span> <span class="fl">1</span> ? <span class="st">"residual"</span> <span class="op">:</span> <span class="st">""</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">hlines!</span>(ax, [<span class="fl">0.0</span>]; linestyle <span class="op">=</span> <span class="op">:</span>dash, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.7</span>))</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scatter!</span>(ax, mu_p, r; markersize <span class="op">=</span> <span class="fl">5</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.6</span>))</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div id="fig-three-residuals" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-three-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk5-diagnostics_files/figure-html/fig-three-residuals-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-three-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The same fit, three definitions of ‘residual’. Response and Pearson residuals fall on stripes, because a count can only miss its mean by a whole number; only the randomised quantile residual has a continuous distribution that a normal reference can be laid against.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>All three are four columns, because age only takes four values. But the
first two columns are a few dots stacked with gaps between them, and the
third is filled in.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is the right way to look at it — and the three panels came from the
same loop with <code>enumerate</code>, which hands you a counter
alongside each item so that panel <code>j</code> lands in column
<code>j</code>. It is not the columns that matter — those are the four
ages. It is what is inside a column. The first two are stripes and there
is nothing wrong with them; they are telling you the truth about a
discrete response. What they cannot do is be compared with a normal
distribution, because they are not one and never will be, however right
the model is. Notice also that the response residuals have a
<strong>floor that moves</strong>: a female cannot fledge fewer than
none, so her residual cannot be more negative than minus her own fitted
value, and the most negative one in this file is -4.073.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So the third one is the one I plot.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The third one is the one you plot, in every family in this book.
<strong>Randomised quantile residuals</strong> are Dunn and Smyth’s idea
(1996) and the sentence that makes them work is short: if the model is
right, the probability it assigns below your observation is uniform, and
a uniform pushed through the inverse normal is standard normal. Whatever
the family. For a discrete response the probability is not a single
number but an interval, so you draw uniformly inside it — hence
<em>randomised</em>, hence a generator, hence a seed, every single time.</p></div>
<h3 id="the-picture-and-what-its-envelope-promises" class="anchored">The picture, and what its envelope promises</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Now the plot. It is the one <code>fig_diagnostic</code> draws, and
before anybody looks at it I am going to tell you what is on the axes,
because the commonest failure in this room is reading a picture whose
meaning you have assumed. The horizontal axis is the quantile a standard
normal would have put at that rank. The vertical axis is <strong>the
deviation from it</strong> — sorted residual minus expected quantile. So
a correct model does not give you a diagonal line. It gives you a
<strong>flat line at zero</strong>. This is a detrended quantile plot, a
worm plot, and van Buuren and Fredriks (2001) named it that because a
wrong model makes it wriggle. The band is a pointwise two-standard-error
envelope on each order statistic under normality.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So five per cent of the points should fall outside it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is the sentence I want to kill. Draw it first, then we will find
out.</p></div>
<div id="cell-fig-worm-poisson" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>out_p <span class="op">=</span> <span class="fu">n_outside</span>(r_quantile)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quantile residual SD : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_quantile))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"points outside the +/-2SE envelope : %d of %d  (%d below the band, %d above)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        out_p, n_fem, <span class="fu">n_below</span>(r_quantile), out_p <span class="op">-</span> <span class="fu">n_below</span>(r_quantile))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_diagnostic</span>(r_quantile; title <span class="op">=</span> <span class="st">"fledglings ~ age, quantile residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>quantile residual SD : 1.3067
points outside the +/-2SE envelope : 107 of 163  (49 below the band, 58 above)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div id="fig-worm-poisson" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-worm-poisson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk5-diagnostics_files/figure-html/fig-worm-poisson-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-worm-poisson-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Worm plot of the fledgling-count model’s randomised quantile residuals, at randomisation seed 1. The vertical axis is deviation from the normal quantile, so a correct model gives a flat line at zero inside the band. This one leaves the band on both sides — below it at the low ranks and above it at the high ranks — and that pair of opposite-sign excursions is what a residual spread wider than one looks like: the worm tilts.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>107 out of 163 are outside. That is more than half.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is — <code>n_outside</code> counted them, with the same arithmetic
the plot is drawn from, and <code>n_below</code> counted the ones under
the band. And Toto has told you it should be about five per cent, and I
have told you not to believe him, and neither of us has done anything
but assert. The envelope is <strong>pointwise</strong>: each ribbon is
drawn at two standard errors, so the rate per <em>point</em> really is
the normal’s own two-sigma tail and Toto has not invented it. What
breaks is the step from a rate to a <em>count</em>, and two things break
it.</p></div>
<div class="line"><span class="who toto">Toto</span><p>The points are not independent.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is the first. They are the same residuals sorted from smallest to
largest, one per rank, so when the curve drifts it drifts together and
dozens cross at once. The second is worse: these residuals are not a
fresh normal sample. They came out of a model <strong>fitted to these
very data</strong>, which is the caveat Dunn and Smyth put in their own
abstract — normal apart from the sampling variability in the estimated
parameters. So the reference everybody carries in their head, plain
normal samples, is the wrong null for a picture of a fit. The right one
is the recipe this whole class is about: <strong>simulate from the
fitted model, refit, recompute the residuals, count.</strong> I will
print the wrong null once beside it, so you can see the size of the
mistake.</p></div>
<div id="null-envelope" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) the WRONG null, printed once: plain standard normal samples, no model anywhere;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) the RIGHT null: simulate from the fit, REFIT the same formula, recompute the</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#     residuals, count -- a thousand times over.</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">refit_age</span>(y) <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)), <span class="fu">Poisson</span>();</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                   data <span class="op">=</span> <span class="fu">DataFrame</span>(Fledglings <span class="op">=</span> y, Age <span class="op">=</span> females.Age))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>rng_naive <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">10</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>naive_out <span class="op">=</span> [<span class="fu">n_outside</span>(<span class="fu">randn</span>(rng_naive, n_fem)) for _ <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">1000</span>]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>rng_null <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">11</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>ynull <span class="op">=</span> <span class="fu">simulate</span>(pois; nsim <span class="op">=</span> <span class="fl">1000</span>, rng <span class="op">=</span> rng_null)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>null_out <span class="op">=</span> <span class="dt">Int</span>[]; null_sd <span class="op">=</span> <span class="dt">Float64</span>[]</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ynull, <span class="fl">2</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    r <span class="op">=</span> <span class="fu">residuals</span>(<span class="fu">refit_age</span>(ynull[<span class="op">:</span>, k]); <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> rng_null)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">push!</span>(null_out, <span class="fu">n_outside</span>(r)); <span class="fu">push!</span>(null_sd, <span class="fu">std</span>(r))</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>q95 <span class="op">=</span> <span class="fu">quantile</span>(null_out, <span class="fl">0.95</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"(a) normal samples, no fit : median %.0f, mean %.2f, 95th pct %.0f  (%.0f%% of %d)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">median</span>(naive_out), <span class="fu">mean</span>(naive_out), <span class="fu">quantile</span>(naive_out, <span class="fl">0.95</span>),</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        <span class="fl">100</span> <span class="op">*</span> <span class="fu">quantile</span>(naive_out, <span class="fl">0.95</span>) <span class="op">/</span> n_fem, n_fem)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"    the pointwise two-sigma rate alone predicts a mean of %.2f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        <span class="fl">2</span> <span class="op">*</span> Distributions.<span class="fu">cdf</span>(Distributions.<span class="fu">Normal</span>(), <span class="op">-</span><span class="fl">2</span>) <span class="op">*</span> n_fem)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"(b) simulate -&gt; refit -&gt; residuals, outside : median %.0f, mean %.2f, 95th pct %.0f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        <span class="fu">median</span>(null_out), <span class="fu">mean</span>(null_out), q95)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"(b) residual SD of a correct fitted model   : mean %.4f, SD %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(null_sd), <span class="fu">std</span>(null_sd))</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"draws of %d with at least %d points outside : %d of %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>        n_fem, out_p, <span class="fu">count</span>(null_out <span class="op">.&gt;=</span> out_p), <span class="fu">length</span>(null_out))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(a) normal samples, no fit : median 1, mean 6.86, 95th pct 37  (23% of 163)
    the pointwise two-sigma rate alone predicts a mean of 7.42
(b) simulate -&gt; refit -&gt; residuals, outside : median 0, mean 1.46, 95th pct 8
(b) residual SD of a correct fitted model   : mean 0.9974, SD 0.0555
draws of 163 with at least 107 points outside : 0 of 1000</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p><code>push!</code> is new, and so is the exclamation mark.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The mark is a convention: a function that changes what you hand it wears
one, which is why <code>scatter!</code> and <code>hlines!</code> above
add to a figure that already exists. <code>push!</code> changes a vector
by appending one value to its end. <code>Int[]</code> and
<code>Float64[]</code> are empty vectors that know what they will hold;
<code>simulate</code> hands back a thousand invented response vectors
from the fit, one per column; and every pass through the loop fits one
of them, computes its residuals, and pushes one count and one spread.
That is the loop form of a comprehension, for a body that does several
things; the comprehension above it, with an underscore for a counter
whose value is never wanted, is the same idea for a body that does one.
And <code>refit_age(y) = ...</code> defines a function in one line: hand
it a response vector and it fits the same formula to it, with the real
ages beside.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Which line do I read first?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The wrong one, because it is the one everybody’s intuition draws. Plain
normal samples: a mean of 6.86 outside against the 7.42 the pointwise
rate predicts — so Toto was very nearly right on average, and useless
about any one picture, because the ninety-fifth percentile is 37, 23% of
the sample. That long tail <em>is</em> the correlation made countable:
the whole worm is free to sit above or below zero, and when it does,
everything crosses at once. Now the null that applies to the picture on
the screen. Fit the model to each invented world and that freedom
disappears, because the intercept is estimated from the very numbers it
is then judged against — the worm is pinned through the middle by
construction. Median 0, ninety-fifth percentile 8. <strong>A correct
model, fitted, puts almost nothing outside this band.</strong> The null
everybody draws is too generous by a factor of about 5, because it
answers a different question: it calibrates a picture of <em>data</em>,
and this is a picture of a <em>fit</em>.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Then most of the worm plots I have squinted at were not fine.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Most of them were not, and you had no way of knowing which. Which is why
the verdict on Momo’s plot is not “it looks bad”. It is that 107 points
outside turned up in 0 of 1000 correct-model draws — and none is not
never: with a thousand draws and no hits the most you may say is
“smaller than about three in a thousand”.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And the spread of the residuals is 1.307 when it should be one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And the same thousand draws say a correct model’s residual SD wanders
only about 0.055 either side of one, so that is far out. Now do not make
the mistake I have watched a hundred people make and count the spread,
the count outside and the tilt as three pieces of evidence. One thing is
wrong with these residuals, they are too widely spread; the tilt, the
two opposite-sign excursions and the count outside are that one thing
seen three ways. But there is one more thing to check before you believe
any of them, and it is the thing almost nobody checks.</p></div>
<div class="line"><span class="who toto">Toto</span><p>The seed.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The seed. You handed a random generator to a residual function, so a
different seed gives a different residual vector from the same fit: at
seed 2 instead of seed 1 the SD is 1.269 rather than 1.307 and the count
outside is 92 rather than 107 — the digits move with the seed and the
verdict does not, which is the form a verdict has to take: report one
seed and name it, or report a range, and never a third decimal from a
single draw. What a seed does and does not promise gets a room of its
own in <a href="appendix-a-simulation.html">Appendix A</a>.</p></div>
<h3 id="ask-the-model-what-it-believes" class="anchored">Ask the model what it believes</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Now the part I actually brought you here for, and Eddie has arrived at
the right moment. Everything so far has been the model marking its own
homework: residuals are computed <em>inside</em> the fit. Eddie.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>So how do I catch it believing something absurd, rather than fitting
badly?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You make it invent a world and you look at the world. That is the whole
idea. <strong>Simulate from the fitted model with an explicit generator,
recompute a statistic you care about, and see where the observed value
falls in the simulated pile.</strong> The recipe is three lines and it
works for every model in this book. The art is entirely in choosing the
statistic, so choose one that is a question about your animal.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Then I will use the one I already know the answer to, to see whether the
recipe finds it. Is it inventing females who fledge more chicks than
they laid eggs?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Testing a new tool on a case you have already settled is exactly the
right instinct, and it is a superb statistic besides: it is checkable in
the world, and the model has never been told it is impossible. Your file
has the eggs in the second column, and the model has never seen that
column.</p></div>
<div id="simulate-impossible" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n_egg_col <span class="op">=</span> <span class="fu">count</span>(females.Fledglings <span class="op">.&gt;</span> females.EggNo)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>ysim <span class="op">=</span> <span class="fu">simulate</span>(pois; nsim <span class="op">=</span> <span class="fl">1000</span>, rng <span class="op">=</span> rng_sim)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>imposs <span class="op">=</span> [<span class="fu">count</span>(ysim[<span class="op">:</span>, k] <span class="op">.&gt;</span> females.EggNo) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim, <span class="fl">2</span>)]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"observed females fledging more chicks than eggs laid : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, n_egg_col, n_fem)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"simulated worlds, count of such females: mean %.2f, min %d, max %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(imposs), <span class="fu">minimum</span>(imposs), <span class="fu">maximum</span>(imposs))</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"proportion of simulated worlds at or below the observed count : %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(imposs <span class="op">.&lt;=</span> n_egg_col))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>observed females fledging more chicks than eggs laid : 0 of 163
simulated worlds, count of such females: mean 8.83, min 3, max 16
proportion of simulated worlds at or below the observed count : 0.0000</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Not one of the thousand.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Not one. The fittest world the model can imagine still has 3 females
raising more chicks than they laid eggs, and it averages 8.8. The real
file has 0, because it cannot have any. <strong>This is Class 3’s beat
arriving by a different road.</strong> There we caught a model believing
in a probability above one by looking at
<code>extrema(fitted(fit))</code>; here the impossibility is not in the
fitted mean at all, it is in the spread the family decreed round it, and
no summary of the coefficients would ever have shown you. You had to
make the model invent birds.</p></div>
<div class="line"><span class="who momo">Momo</span><p>This is last week. I convicted this model in Class 4 and I put
<code>log(EggNo)</code> in the mean to fix it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You did, and Class 4 owns that repair. What is new today is the
<strong>route</strong>: Class 4’s arithmetic on the Poisson’s tail works
only because that tail has a formula; inventing a thousand worlds and
counting works for any statistic — a maximum, a number of ties, a
longest run.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>So why refit it here at all?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because the model I want to interrogate for the rest of this hour is the
repaired one, and because you should never take a fit on trust from a
previous chapter. Same formula as Class 4, refitted here, printed here.</p></div>
<div id="cell-fit-repaired" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>females.logEgg <span class="op">=</span> <span class="fu">log</span>.(females.EggNo)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>pois2 <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age <span class="op">+</span> logEgg)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>pois2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-repaired" class="cell-output cell-output-display" data-execution_count="17">
<pre><code>Distributional regression fit (Poisson)
  nobs = 163   logLik = -323.4104   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -1.1695     0.2546  -4.5931  4.366e-06
  Age           0.0852     0.0507   1.6798    0.09299
  logEgg        0.9503     0.1102   8.6213  6.622e-18</code></pre>
</div>
</div>
<div id="repaired-coefficients" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>b2 <span class="op">=</span> <span class="fu">coef</span>(pois2, <span class="op">:</span>mu)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>se2 <span class="op">=</span> <span class="fu">stderror</span>(pois2)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>lo_egg, hi_egg <span class="op">=</span> b2[<span class="fl">3</span>] <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se2[<span class="fl">3</span>], b2[<span class="fl">3</span>] <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se2[<span class="fl">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Class 4’s numbers to the last digit. The coefficient on log-eggs is
0.95, interval 0.734 to 1.166, covering one, the value an offset would
have pinned it at; the engine cannot write an offset (see <a href="appendix-b-engine.html">Where the engine stops</a>), so the
coefficient is fitted free. <strong>Today’s question is Eddie’s: is the
repaired model any good?</strong> Run Momo’s check again on it, and
change nothing else.</p></div>
<div id="cell-fig-simcheck" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>rng_sim2 <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ysim2 <span class="op">=</span> <span class="fu">simulate</span>(pois2; nsim <span class="op">=</span> <span class="fl">1000</span>, rng <span class="op">=</span> rng_sim2)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>imposs2 <span class="op">=</span> [<span class="fu">count</span>(ysim2[<span class="op">:</span>, k] <span class="op">.&gt;</span> females.EggNo) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim2, <span class="fl">2</span>)]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"with eggs laid in the model: mean %.2f, min %d, max %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(imposs2), <span class="fu">minimum</span>(imposs2), <span class="fu">maximum</span>(imposs2))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"proportion of simulated worlds at or below the observed count : %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(imposs2 <span class="op">.&lt;=</span> n_egg_col))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">700</span>, <span class="fl">320</span>))</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j, (nm, v)) <span class="kw">in</span> <span class="fu">enumerate</span>(((<span class="st">"fledglings ~ age"</span>, imposs), (<span class="st">"fledglings ~ age + log(eggs)"</span>, imposs2)))</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, j]; xlabel <span class="op">=</span> <span class="st">"impossible females in a simulated world"</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>        ylabel <span class="op">=</span> j <span class="op">==</span> <span class="fl">1</span> ? <span class="st">"simulated worlds"</span> <span class="op">:</span> <span class="st">""</span>, title <span class="op">=</span> nm)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">hist!</span>(ax, v; bins <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span><span class="op">:</span><span class="fl">1</span><span class="op">:</span><span class="fl">16.5</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.55</span>))</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">vlines!</span>(ax, [n_egg_col]; linestyle <span class="op">=</span> <span class="op">:</span>dash, linewidth <span class="op">=</span> <span class="fl">2</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlims!</span>(ax, <span class="op">-</span><span class="fl">1</span>, <span class="fl">17</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>with eggs laid in the model: mean 0.61, min 0, max 5
proportion of simulated worlds at or below the observed count : 0.5390</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div id="fig-simcheck" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-simcheck-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk5-diagnostics_files/figure-html/fig-simcheck-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simcheck-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Simulation-based check. Each histogram is 1000 worlds drawn from a fitted model; the bar counts how many females in that world fledged more chicks than they laid eggs. The dashed line is the real file, which has none. The age-only model cannot imagine a world as tidy as the real one; the model with eggs laid in it can.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The second one sits on top of the real answer.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>54% of its worlds are at least as tidy as the real file, which is as
consistent as a check can be. Note carefully what that does
<strong>not</strong> say. It does not say the model is true. A check you
pass tells you the model is not embarrassed by <em>that statistic</em>;
it is silent about every statistic you did not compute. Passing checks
is not evidence in the way failing them is.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>Can I use any statistic?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Any statistic, and the art is in the choosing, so before you choose,
look at the repaired model the way you looked at the first one. A worm
plot of a fit you have just passed is a habit worth keeping, because the
picture cannot tell you <em>what</em> is wrong but it is rather good at
telling you <em>where</em>.</p></div>
<div id="cell-fig-worm-repaired" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>r_quantile2 <span class="op">=</span> <span class="fu">residuals</span>(pois2; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">1</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>out_p2 <span class="op">=</span> <span class="fu">n_outside</span>(r_quantile2)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>w2 <span class="op">=</span> <span class="fu">worm_parts</span>(r_quantile2)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>below_left2 <span class="op">=</span> <span class="fu">count</span>((w2.dev <span class="op">.&lt;</span> <span class="op">-</span><span class="fl">2</span> <span class="op">.*</span> w2.se) <span class="op">.&amp;</span> (w2.theo <span class="op">.&lt;</span> <span class="fl">0</span>))   <span class="co"># below the band AND at a negative quantile</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quantile residual SD : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_quantile2))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"points outside : %d of %d (%d below the band, %d above)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        out_p2, n_fem, <span class="fu">n_below</span>(r_quantile2), out_p2 <span class="op">-</span> <span class="fu">n_below</span>(r_quantile2))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"of those below the band, at a negative theoretical quantile : %d</span><span class="sc">\n</span><span class="st">"</span>, below_left2)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_diagnostic</span>(r_quantile2; title <span class="op">=</span> <span class="st">"age + log(eggs), quantile residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>quantile residual SD : 1.1121
points outside : 13 of 163 (7 below the band, 6 above)
of those below the band, at a negative theoretical quantile : 7</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div id="fig-worm-repaired" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-worm-repaired-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk5-diagnostics_files/figure-html/fig-worm-repaired-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-worm-repaired-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The same worm plot after eggs laid enters the mean structure, at the same randomisation seed as the first. The tilt is much reduced, but this is not a clean picture: the points that remain below the band sit at negative theoretical quantiles, the end of the distribution where a count model keeps its zeros.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>From 107 points outside to 13, at the same seed. That looks fixed.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It looks better, and I am not going to call it fixed, because you have
just learned what a correct fitted model puts outside this band — almost
nothing — and 13 is not nothing. Look where the damage is instead of how
much there is, which is what the last line of that cell counts.</p></div>
<div class="line"><span class="who toto">Toto</span><p>I could not read that line.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Three new things in it. <code>worm_parts</code> hands back the three
columns the plot is drawn from, as named fields you read with a dot, the
way you read a column of a data frame: <code>theo</code> is the normal
quantile on the horizontal axis, <code>dev</code> the deviation on the
vertical, <code>se</code> the half-width of the band.
<code>.&amp;</code> is <em>and</em>, element by element, so each point
is asked two questions at once — below the band, and left of zero — and
<code>count</code> counts the points that answer yes to both. So: 7 of
the 13 points outside are below the band, and 7 of those sit at negative
theoretical quantiles, the bottom of the distribution — which, for a
count, is where the zeros live.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Then what is it getting wrong? The worm plot will not tell me.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>No, but the recipe will. Count the zeros.</p></div>
<div id="simcheck-zeros" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The same 1000 worlds as the figure above; one line of the recipe changed.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>z_obs <span class="op">=</span> <span class="fu">count</span>(<span class="op">==</span>(<span class="fl">0</span>), females.Fledglings)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>mu_p2 <span class="op">=</span> <span class="fu">fitted</span>(pois2)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>z_exp <span class="op">=</span> <span class="fu">sum</span>(<span class="fu">exp</span>.(<span class="op">-</span>mu_p2))                 <span class="co"># a Poisson puts exp(-mu) on zero</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>z_sim <span class="op">=</span> [<span class="fu">count</span>(<span class="op">==</span>(<span class="fl">0</span>), ysim2[<span class="op">:</span>, k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim2, <span class="fl">2</span>)]</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"females fledging nothing, observed : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, z_obs, n_fem)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"the repaired model expects         : %.2f</span><span class="sc">\n</span><span class="st">"</span>, z_exp)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"simulated worlds: mean %.2f, SD %.2f, largest of the %d : %d</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(z_sim), <span class="fu">std</span>(z_sim), <span class="fu">length</span>(z_sim), <span class="fu">maximum</span>(z_sim))</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"worlds with at least %d zeros : %d of %d   (observed is %.1f simulated SDs out)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>        z_obs, <span class="fu">count</span>(z_sim <span class="op">.&gt;=</span> z_obs), <span class="fu">length</span>(z_sim), (z_obs <span class="op">-</span> <span class="fu">mean</span>(z_sim)) <span class="op">/</span> <span class="fu">std</span>(z_sim))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>females fledging nothing, observed : 30 of 163
the repaired model expects         : 15.49
simulated worlds: mean 15.70, SD 3.32, largest of the 1000 : 26
worlds with at least 30 zeros : 0 of 1000   (observed is 4.3 simulated SDs out)</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Not one of the thousand. Again.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Not one, and the most generous world it managed had 26 zeros against the
real file’s 30. The model expects 15.5 females to fledge nothing; 30 of
them did, 4.3 simulated standard deviations out. <strong>Now put the two
checks side by side, on the same model, from the same thousand
worlds.</strong> Females fledging more chicks than they laid: 54% of
worlds at least as tidy as the real one, a comfortable pass. Number of
zeros: none of a thousand. That is the bullet I gave you at the start —
<em>a check you pass is much weaker than a check you fail</em> —
demonstrated on one model, in two short computations. And notice which
check it passed: the one about the ceiling, which is the very thing the
repair put into the mean. A model will usually clear the check that
motivated its last repair. A statistic that asks a fresh question about
the animal found the fresh failure.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>So what does an excess of zeros mean here?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Do not name a cause yet, because two quite different failures both put
extra zeros on a page, and the zeros alone cannot tell you which. Ask
the same thousand worlds where <em>else</em> they differ from the file,
and add one fit: Class 4’s negative binomial with eggs in the mean,
refitted here, because it is the check that tells the two failures
apart.</p></div>
<div id="simcheck-shape" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The same 1000 worlds again: where, apart from the zeros, does the file differ from them?</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>y_obs <span class="op">=</span> females.Fledglings</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>mid_obs <span class="op">=</span> <span class="fu">count</span>(x <span class="op">-&gt;</span> <span class="fl">1</span> <span class="op">&lt;=</span> x <span class="op">&lt;=</span> <span class="fl">3</span>, y_obs)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>mid_sim <span class="op">=</span> <span class="fu">mean</span>([<span class="fu">count</span>(x <span class="op">-&gt;</span> <span class="fl">1</span> <span class="op">&lt;=</span> x <span class="op">&lt;=</span> <span class="fl">3</span>, ysim2[<span class="op">:</span>, k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim2, <span class="fl">2</span>)])</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>big_obs <span class="op">=</span> <span class="fu">count</span>(<span class="op">&gt;=</span>(<span class="fl">7</span>), y_obs)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>big_sim <span class="op">=</span> <span class="fu">mean</span>([<span class="fu">count</span>(<span class="op">&gt;=</span>(<span class="fl">7</span>), ysim2[<span class="op">:</span>, k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim2, <span class="fl">2</span>)])</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># the broods that fledged anything at all, real and simulated</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>nz_obs <span class="op">=</span> y_obs[y_obs <span class="op">.&gt;</span> <span class="fl">0</span>]</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>nz_sim_mean <span class="op">=</span> <span class="fu">mean</span>([<span class="fu">mean</span>(ysim2[ysim2[<span class="op">:</span>, k] <span class="op">.&gt;</span> <span class="fl">0</span>, k]) for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim2, <span class="fl">2</span>)])</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>nz_sim_var  <span class="op">=</span> <span class="fu">mean</span>([<span class="fu">var</span>(ysim2[ysim2[<span class="op">:</span>, k] <span class="op">.&gt;</span> <span class="fl">0</span>, k])  for k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ysim2, <span class="fl">2</span>)])</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Class 4's negative binomial on the same mean model: theta prices any extra spread</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>nb2 <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age <span class="op">+</span> logEgg), <span class="pp">@formula</span>(sigma <span class="op">~</span> <span class="fl">1</span>)), <span class="fu">NegBinomial2</span>(); data <span class="op">=</span> females)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>theta2 <span class="op">=</span> <span class="fu">exp</span>(<span class="op">-</span><span class="fl">2</span> <span class="op">*</span> <span class="fu">coef</span>(nb2, <span class="op">:</span>sigma)[<span class="fl">1</span>])</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods of one to three chicks : observed %d, simulated mean %.1f</span><span class="sc">\n</span><span class="st">"</span>, mid_obs, mid_sim)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods of seven or more       : observed %d, simulated mean %.1f</span><span class="sc">\n</span><span class="st">"</span>, big_obs, big_sim)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods that fledged anything  : observed mean %.2f, variance %.2f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(nz_obs), <span class="fu">var</span>(nz_obs))</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"                                simulated mean %.2f, variance %.2f</span><span class="sc">\n</span><span class="st">"</span>, nz_sim_mean, nz_sim_var)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"negative binomial, eggs in the mean : theta %.1f</span><span class="sc">\n</span><span class="st">"</span>, theta2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>broods of one to three chicks : observed 56, simulated mean 83.2
broods of seven or more       : observed 13, simulated mean 14.5
broods that fledged anything  : observed mean 3.93, variance 3.81
                                simulated mean 3.54, variance 4.68
negative binomial, eggs in the mean : theta 29.2</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The zeros came out of the middle.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Out of the middle, and from nowhere else. Broods of one to three chicks:
56 in the file against 83.2 in a typical world. Broods of seven or more:
13 against 14.5 — the top of the distribution is exactly where the model
put it. And the broods that fledged anything at all have mean 3.93 and
variance 3.81, a variance sitting on its mean, which is the Poisson’s
own signature. Now the story everybody reaches for first, so that you
can see why it is wrong here. Variation between females the model is not
allowed to know about — some birds simply worse at this than others —
would put extra zeros on the page, but it could never put them there
alone: a Poisson averaged over females who differ spreads out at
<em>both</em> ends, more zeros and more big broods together, with the
variance above the mean everywhere. That extra spread is precisely what
a negative binomial buys, and Class 4 has already priced it on this mean
model: θ is 29.2 here, the same number Class 4 printed, the family
telling you there is no extra spread to be had. So this is not a mixed
Poisson, and a <strong>random effect</strong> for the female — Class 6 —
is not the repair: it would buy the spread this file does not show and
leave the zeros where they are.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Then what makes a zero?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>A brood that failed whole. 30 females fledged nothing and the rest
fledged a Poisson number, and those are two processes — whether the nest
was lost, to a predator or a storm or desertion, and how many chicks
survived when it was not — that one count family cannot write. The
family that can is a count model with a separate zero process, a
<strong>zero-inflated</strong> or a <strong>hurdle</strong> model, and
the engine at this version has no such family built in (<a href="appendix-b-engine.html">Where the engine stops</a>). The other
repair is a column: a record of whether the nest was lost would let you
fit the two processes one at a time, with families you already own, and
<code>FemaleSuccess.csv</code> does not have it. <strong>That is the
honest ending of a diagnostic — not “the model is fine”, not “the model
is wrong”, but “here is the thing it does not believe, here is what the
pattern points at, and here is what you would need to fit it”.</strong>
And that is where this hour stops: one model, interrogated on its own.
Everything on this page — residuals computed inside the fit, worlds it
invented, a statistic that was a question about the bird — needed no
second model in the room. Next hour, <a href="wk5b-comparison.html">Class 5b</a>, puts one there and asks which
to prefer, and Eddie has been waiting all hour to ask for the number.</p></div>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>Three residuals, one of which travels.</strong> Response: observed minus fitted. Pearson: that divided by the family’s standard deviation for the row, √V(μ̂). Randomised quantile: the model’s own cumulative probability at the observation, pushed through the inverse normal. In a Gaussian model all three are the same vector up to units, which is why “residual” feels like one word, and why habits learned there do not transfer.</li>
<li><strong>Only quantile residuals are standard normal under a correct model, whatever the family</strong> (Dunn &amp; Smyth 1996). Response and Pearson residuals of a count fall on a lattice however right the model is.</li>
<li><strong>The randomisation is real and has to be reported.</strong> Two seeds on the same broken fit put 107 and 92 points outside the envelope: the digits move, the verdict does not. Report one seed and name it, or report a range. A verdict that changes with the seed is not a verdict.</li>
<li><strong>A worm plot is a detrended quantile plot</strong>: a correct model is a flat line at zero, <strong>not</strong> a diagonal (van Buuren &amp; Fredriks 2001). A tilt, a pair of opposite-sign excursions and a wide residual spread are one finding, not three.</li>
<li><strong>Calibrate a diagnostic against its own null, and the null must include the fitting.</strong> Plain normal samples put a ninety-fifth percentile of 37 points outside the envelope; simulating from the fit and <strong>refitting</strong> gives 8. The null everybody’s intuition draws is too generous by a factor of about 5, because estimating the parameters removes the freedom of the whole worm to shift — quantile residuals are normal <em>apart from the sampling variability in the estimated parameters</em> (Dunn &amp; Smyth 1996).</li>
<li><strong>Simulation-based checking.</strong> Simulate from the fitted model with an explicit generator, recompute a statistic that is a question about your organism, and place the observed value in the simulated distribution. It is the only tool here that can catch a model believing something impossible, because it looks at data the model invents rather than at data it was fitted to. It is the frequentist relative of the posterior predictive check (Gelman, Meng &amp; Stern 1996). When the statistic depends on a fit, refit each invented world before scoring it.</li>
<li><strong>A check you pass is much weaker than a check you fail</strong>, shown on one model: the repaired fit passes the impossible-bird check and is convicted by the number of zeros, which not one of a thousand simulated worlds reached. A model usually clears the check that motivated its last repair; a statistic chosen as a fresh fact about your organism is the one that can still fail.</li>
<li><strong>A diagnostic ends by naming what the model does not believe, and where the pattern points.</strong> The extra zeros here came out of the middle of the distribution, not the top: broods of seven or more matched the simulated worlds (13 against 14.5) and the broods that fledged anything were Poisson-shaped (mean 3.93, variance 3.81). Variation between females would have inflated the top and the variance along with the zeros, and Class 4’s negative binomial on the same mean model, θ = 29.2, had already found no such spread — so a female-level random effect (Class 6) is not the repair. Whole broods failed: the repair is a count family with a separate zero process, which the engine does not offer, or a column recording nest fate, which <code>FemaleSuccess.csv</code> lacks. Sometimes the repair is a different family; sometimes it is a different file.</li>
<li><strong>Checking is not comparing.</strong> Everything on this page was one model against itself. Putting a second model beside it is <a href="wk5b-comparison.html">Class 5b</a>.</li>
</ul>
<h3 id="julia-you-used" class="anchored">Julia you used</h3>
<ul>
<li><strong><code>Int[]</code>, <code>Float64[]</code> and <code>push!</code>.</strong> An empty vector that knows its type, grown one value at a time inside a loop: the loop form of a comprehension, for a body that does more than one thing. The <code>!</code> marks a function that changes what it is handed, as <code>scatter!</code> and <code>hlines!</code> change a figure.</li>
<li><strong><code>refit_age(y) = drm(...)</code>.</strong> A function defined in one line, called later by name.</li>
<li><strong><code>for (nm, r) in (("response", r1), ("Pearson", r2))</code>.</strong> Looping over a list of pairs, each unpacked into two names. <code>enumerate(list)</code> adds a counter: <code>for (j, (nm, r)) in enumerate(panels)</code>.</li>
<li><strong><code>[... for _ in 1:1000]</code>.</strong> An underscore for a counter whose value is never used.</li>
<li><strong><code>extrema(mu_p)...</code>.</strong> The splat: spreads a pair into two separate arguments.</li>
<li><strong><code>w2.theo</code>, <code>w2.dev</code>, <code>w2.se</code>.</strong> Named fields of a result, read with a dot as a column of a data frame is. The worm-plot arithmetic that fills them is not on this page: <code>worm_parts</code>, <code>n_outside</code> and <code>n_below</code> live in <code>tools/figures.jl</code> beside <code>fig_diagnostic</code>, and the chapter calls them.</li>
<li><strong><code>.&amp;</code>.</strong> <em>And</em>, element by element: two yes-or-no vectors in, one out.</li>
<li><strong><code>-0.5:1:16.5</code>.</strong> A range with a step: from, step, to.</li>
<li><strong><code>maximum(abs, v)</code>, <code>count(==(0), v)</code>, <code>count(&gt;=(7), v)</code>.</strong> A function in the first slot is applied to each element first; <code>count(x -&gt; 1 &lt;= x &lt;= 3, v)</code> is the same with Class 1’s anonymous function in that slot.</li>
</ul>
<h3 id="calls-you-used" class="anchored">Calls you used</h3>
<ul>
<li><code>residuals(fit; type = :response)</code> and <code>residuals(fit; type = :quantile, rng = MersenneTwister(seed))</code>: observed minus fitted, and randomised quantile residuals. <strong>Pass the <code>rng</code>.</strong> There is no Pearson type: write <code>(y .- fitted(fit)) ./ sqrt.(V.(fitted(fit)))</code> yourself, with <code>V</code> the family’s variance function.</li>
<li><code>simulate(fit; nsim = k, rng = MersenneTwister(seed))</code>: an <code>nobs × k</code> matrix of new responses in the family’s own support.</li>
<li><code>fig_diagnostic(resid)</code>, <code>worm_parts(r)</code>, <code>n_outside(r)</code> and <code>n_below(r)</code> from <code>tools/figures.jl</code>: the worm plot, and the arithmetic that lets you count what it shows rather than just look at it.</li>
<li><strong>The simulation thread.</strong> Every chapter asks the fit to invent data. This hour’s thread ran in the middle, three times: a thousand worlds from the age-only model to calibrate the worm plot’s own null, a thousand more from it to ask what it believed about the ceiling, and a thousand from the repaired model to ask about the ceiling, then the zeros, then the shape of everything that was not a zero. Appendix A takes the same move one step further and asks whether a reported standard error predicts the spread of the refits.</li>
</ul>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. Details checked on 2026-09-07 against OpenAlex, an open
catalogue of research papers.</p>
<ol type="1">
<li><strong>Dunn, P. K. &amp; Smyth, G. K. (1996) “Randomized quantile residuals”, <em>Journal of Computational and Graphical Statistics</em> 5:236–244.</strong> doi:10.1080/10618600.1996.10474708. Start here. The source of the one residual in this class that works in every family; the randomisation step for discrete responses — the reason a seed is involved at all — is set out there and nowhere shorter.</li>
<li><strong>van Buuren, S. &amp; Fredriks, M. (2001) “Worm plot: a simple diagnostic device for modelling growth reference curves”, <em>Statistics in Medicine</em> 20:1259–1277.</strong> doi:10.1002/sim.746. The plot this class draws twice, in the setting it was invented for. Read it for the reading of the <em>shape</em>: offset, slope and curvature each answer to a different defect in the model.</li>
<li><strong>Gelman, A., Meng, X.-L. &amp; Stern, H. (1996) “Posterior predictive assessment of model fitness via realized discrepancies”, <em>Statistica Sinica</em> 6:733–760.</strong> The origin of the idea in this chapter’s second half. A Bayesian paper in a frequentist book, so read it for the idea and not for the reference distribution.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Graded by depth: the first is short, the second and third each run a loop of a few hundred fits, so start the loop and read on while it runs. Every exercise names a file under <code>data/</code> that exists; do it on your own organism as well where you have one. A <em>check</em> is a number computed from that file when this page was built — match it before going on. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Class 4 and not this class.</p>
<ol type="1">
<li><p><strong>Three residuals, twice.</strong> On <code>data/2012/MBodySize.csv</code> fit <code>Weight ~ Tarsus + Sex</code> with <code>Gaussian()</code>. Compute <code>residuals(fit; type = :response)</code> divided by <code>sigma(fit)</code>, and <code>residuals(fit; type = :quantile, rng = MersenneTwister(1))</code>. Report the largest absolute difference between the two and say in one sentence why they agree. Then fit <code>EPP ~ Age</code> on <code>data/2012/EPPSuccess.csv</code> with <code>Poisson()</code> and report, for the response, Pearson and quantile residuals, the SD, the skewness and the number of distinct values of each, as the chapter’s table did. Say which of the three you would put on a normal reference plot and why the other two cannot go there however right the model is. <em>Check:</em> the Gaussian gap, rounded to ten decimals, is 0.0; the Poisson response residuals take 20 distinct values and the quantile residuals 76.</p></li>
<li><p><strong>A check you fail, then one you pass.</strong> Draw the worm plot of the Poisson quantile residuals from question 1 with <code>fig_diagnostic</code>, and count the points outside its band with <code>n_outside(r)</code>. Then build the null that applies to that picture, as the chapter did: simulate 200 worlds from the fit with <code>MersenneTwister(3)</code>, refit <code>EPP ~ Age</code> to each, recompute the quantile residuals with the same generator, and push each world’s <code>n_outside</code> into an <code>Int[]</code>. Report the ninety-fifth percentile of those counts and how many worlds reach the observed one. Then refit with <code>NegBinomial2()</code> as in Class 4, and do all of it again. Two sentences: what the first model got wrong, and what the second model’s passing the same check does and does not establish. <em>Check:</em> 60 of 76 outside under the Poisson, whose own null has a ninety-fifth percentile of 4 and reaches the observed count in 0 of 200 worlds; 0 outside under the negative binomial, against a null ninety-fifth percentile of 3.</p></li>
<li><p><strong>The seed is part of the answer.</strong> The chapter compared two seeds and said the verdict survives. Make it survive two hundred: recompute the quantile residuals of both fits from question 2 under <code>MersenneTwister(k)</code> for <code>k in 1:200</code>, with a comprehension, and report the range of the residual SD for each. Then state your verdict on each model in a form that survives the seed, and say which digits you would refuse to print. <em>Check:</em> the Poisson SD runs from 1.42 to 1.63; the negative binomial’s from 0.85 to 1.15.</p></li>
<li><p><strong>Ask the model what it believes.</strong> The Poisson model of question 1 was never told how many of the 76 males sired no extra-pair young at all. Count the zeros in <code>EPP</code>. Then simulate 1000 datasets from the Poisson fit with <code>MersenneTwister(5)</code>, count the zeros in each column, and report the mean count and the proportion of simulated worlds with at least as many zeros as the real one. Do the same from the negative-binomial fit. Two sentences: what the first model believes that the sparrows do not allow, and what you would change in the model rather than in the data. <em>Check:</em> 50 real zeros; the Poisson worlds average 33.1 and reach the real count in a proportion 0.0 of them; the negative-binomial worlds average 49.9, proportion 0.55.</p></li>
</ol>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk4-overdispersion.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 4 · When the family lies about the spread</span></a><a class="chapter-nav-link next" href="wk5b-comparison.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Class 5b · Which model?</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 5a of twelve rungs, ten in v1, plus a coda · draft, all code run, 2026-09-13<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>