<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 5b: which model? – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 5b: which model?</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 5b</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>Which model?</h1>
    <p class="deck">Two models fitted to the same rows can be ranked to four decimals, and the winner can still be inventing birds that cannot exist. Comparison ranks; it never validates. This hour is about what the ranking does say, what a difference of two is and is not, and the one thing no comparison can see.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>Draft. Every number and figure on this page was produced when the site was built.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Every code block and printed result below was actually run when the site was built, and nothing is typed from memory. Every random draw is seeded where it is made, so the page comes out the same every time.<br>
      <b>Caveat</b> The data are real: the 2012 Lundy Island female breeding records, read directly from data/2012/FemaleSuccess.csv, and the chick-survival records in data/2012/ChickSurvival.csv for the exercises (where the files came from is recorded in data/2012/README.md). Nothing here is invented; the simulated quantities are drawn from models fitted to those files, from stated seeds.
    </p>
  </div>
</header>

<div class="wrap">
<hr>
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>Say what <strong>AIC</strong> is made of, why the parameter count is in it, and why only differences between models fitted to the same rows mean anything.</li>
<li>Run a <strong>likelihood-ratio test</strong> on two nested models, say what its reference distribution is and where the number of degrees of freedom comes from.</li>
<li>Simulate the ΔAIC of a <strong>parameter that does nothing</strong>, say how often it wins anyway, and say why “two units” is the ceiling of a useless parameter’s damage rather than its usual size.</li>
<li>Tell a <strong>marginal</strong> coefficient from a <strong>conditional</strong> one, and report a null result with the interval as the bound on the effect and the smallest effect the design could have seen as its sensitivity, rather than with the words “no effect”.</li>
<li>Say why two models can only be compared when they were fitted to the <strong>same rows</strong>, what the arithmetic does when they were not, and why the winner of any comparison still has to be checked on its own.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, the second hour. Nobody has left. MOMO’s repaired
fledgling model is still on her screen, convicted of its zeros. TOTO
has, unprompted, fitted a third model while nobody was looking. EDDIE
has waited a whole hour to ask for a number.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Last hour, one model at a time: three residuals, one picture, one
recipe. Momo’s repaired model passed the check about the ceiling and
failed the check about the zeros, and we ended by naming what the
pattern pointed at — whole broods lost, which no single count family
writes — and the family or the column it would take to fit it. Every one
of those verdicts came from a model interrogated on its own, and that is
what <em>is it any good?</em> means. Eddie has been waiting to ask for
something else.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>You have shown me one model is worse than another by eye. Give me the
number.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Two numbers, and they answer different questions, and neither of them
answers Eddie’s. That is this hour. Given two candidate models for the
same rows, how do you prefer one, what does the preference mean, and
what can it never tell you. Toto, you have been quiet.</p></div>
<div class="line"><span class="who toto">Toto</span><p>I fitted a third model. I took age out and kept eggs laid. It seemed to
be what the last hour was saying.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is exactly what the last hour was saying, and it is the model the
whole of this one turns on, so fit all three here. Never take a fit on
trust from a previous page, even one that is an hour old.</p></div>
<div id="setup" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/diagnostics.jl includes tools/figures.jl, which includes</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/theme_itchy.jl itself, so one include does all three.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">include</span>(<span class="st">"../tools/diagnostics.jl"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span>, <span class="bu">Random</span>, <span class="bu">Printf</span>, <span class="bu">CairoMakie</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> <span class="bu">Distributions</span>          <span class="co"># qualified: DRM exports its own Poisson, Binomial, …</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set_theme!</span>(<span class="fu">theme_itchy</span>(<span class="op">:</span>light))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>females <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/FemaleSuccess.csv"</span>, DataFrame)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>females.logEgg <span class="op">=</span> <span class="fu">log</span>.(females.EggNo)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>n_fem <span class="op">=</span> <span class="fu">nrow</span>(females)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>pois     <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)),          <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>pois_egg <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> logEgg)),       <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>pois2    <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age <span class="op">+</span> logEgg)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"females: %d rows; the three fits used %d, %d and %d of them</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>        n_fem, <span class="fu">nobs</span>(pois), <span class="fu">nobs</span>(pois_egg), <span class="fu">nobs</span>(pois2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>females: 163 rows; the three fits used 163, 163 and 163 of them</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Three models, three formulas, one file, and I printed the row count of
each fit on purpose. Hold on to that line; it is the last thing on this
page and the thing you will forget first.</p></div>
<h3 id="two-numbers-two-questions" class="anchored">Two numbers, two questions</h3>
<div class="line"><span class="who itchy">Itchy</span><p>The first number is <strong>AIC</strong>, which is Akaike’s (1974):
minus twice the log-likelihood, plus twice the number of parameters.
Both halves need saying. The <strong>log-likelihood</strong> is the
number the engine climbed to find the coefficients — the logarithm of
the probability the fitted model assigns to the rows you gave it — so a
higher one means the model finds your data less surprising. Left to
itself it would always prefer the model with more parameters, because a
fitted model has been tuned to the very data you are judging it on, so
its likelihood flatters it, and the parameter count is the charge for
that flattery. Lower is better, and only <strong>differences</strong>
mean anything: the absolute value depends on the file, on the family,
even on the units you measured the response in, so an AIC quoted on its
own is a number with no reader.</p></div>
<div id="compare-aic" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm, f) <span class="kw">in</span> ((<span class="st">"Fledglings ~ Age"</span>, pois), (<span class="st">"Fledglings ~ logEgg"</span>, pois_egg),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"Fledglings ~ Age + logEgg"</span>, pois2))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"%-28s  k = %d   logLik %10.4f   AIC %9.4f</span><span class="sc">\n</span><span class="st">"</span>, nm, <span class="fu">dof</span>(f), <span class="fu">loglik</span>(f), <span class="fu">aic</span>(f))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>daic_egg <span class="op">=</span> <span class="fu">aic</span>(pois2) <span class="op">-</span> <span class="fu">aic</span>(pois)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>daic_age <span class="op">=</span> <span class="fu">aic</span>(pois2) <span class="op">-</span> <span class="fu">aic</span>(pois_egg)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">adding log(eggs) to the age model : dAIC %+.4f</span><span class="sc">\n</span><span class="st">"</span>, daic_egg)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"adding age to the eggs-only model : dAIC %+.4f</span><span class="sc">\n</span><span class="st">"</span>, daic_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fledglings ~ Age              k = 2   logLik  -367.9932   AIC  739.9864
Fledglings ~ logEgg           k = 2   logLik  -324.8066   AIC  653.6131
Fledglings ~ Age + logEgg     k = 3   logLik  -323.4104   AIC  652.8208

adding log(eggs) to the age model : dAIC -87.1656
adding age to the eggs-only model : dAIC -0.7923</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Why is k two for a model with one covariate in it?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because the intercept is the other one. k counts everything the engine
estimated to get its log-likelihood, not the terms you typed after the
tilde: the intercept, every slope, and any parameter the family carries
— Class 4’s negative binomial would count θ, and the Gaussian’s σ counts
too, which is why <code>dof</code> is a call and not something you work
out by reading the formula. It is also why swapping a family costs a
parameter in exactly the way adding a covariate does, and why the two
are compared on the same footing.</p></div>
<div class="line"><span class="who toto">Toto</span><p>One of those is enormous and one is nearly nothing.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>One parameter each, and that is what makes the pair worth putting side
by side. Log-eggs buys 87.2 AIC. Age, once log-eggs is already in, buys
0.79. Now the rule everybody half-remembers: a difference of about two
is the usual line, and it comes from Burnham and Anderson, who treat
models within two units of the best as having substantial support. The
line sits where it does because a parameter that buys no likelihood
<strong>at all</strong> still costs exactly that much: two times one
parameter, and nothing back. But that is the worst a useless parameter
can do, not what it typically does, and the gap between those two is
where people get hurt. Do not take it from me.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Simulate it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>In a moment. Take the other number first, because the simulation you are
about to write turns out to <em>be</em> it. The second number is the
<strong>likelihood-ratio test</strong>: twice the gap in log-likelihood
between the smaller model and the larger, referred to a chi-squared
distribution with as many degrees of freedom as parameters added. It
needs the two models to be <strong>nested</strong> — the smaller one is
the larger one with some coefficients pinned at zero — and it says this:
if those pinned coefficients really are zero, twice the gap behaves, in
large samples, like a chi-squared with that many degrees of freedom
(Wilks 1938). Age added to the eggs-only model is one coefficient pinned
at zero, so one degree of freedom. It gives you a reference distribution
rather than a ranking, and that is the difference between the two
numbers. AIC tells you which model it prefers and by how much. The test
tells you how surprising the gap would be if the extra parameters did
nothing.</p></div>
<div id="compare-lrt" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lr_egg <span class="op">=</span> <span class="fu">lrtest</span>(pois, pois2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>lr_age <span class="op">=</span> <span class="fu">lrtest</span>(pois_egg, pois2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"adding log(eggs) : statistic %9.4f on %d df, p = %.3e</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        lr_egg.statistic, lr_egg.dof, lr_egg.pvalue)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"adding age       : statistic %9.4f on %d df, p = %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        lr_age.statistic, lr_age.dof, lr_age.pvalue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>adding log(eggs) : statistic   89.1656 on 1 df, p = 3.631e-21
adding age       : statistic    2.7923 on 1 df, p = 0.0947</code></pre>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>How large is “large samples”?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Nobody can tell you from the formula, which is the honest answer and the
reason the simulation is coming: Wilks’s result is a statement about
what happens as the rows go to infinity, and your file has 163 of them.
Whether 163 is close enough to infinity for this model is a question you
can answer only by drawing the reference distribution yourself and
seeing whether it matches the one you looked up.</p></div>
<div class="line"><span class="who momo">Momo</span><p>The second p-value is the kind I would have called “not significant” and
moved on.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And we will come back to what you may say instead, because “moved on” is
where most of the damage in the literature is done. Log-eggs is
overwhelming and age, given eggs, is not: 0.095, on one degree of
freedom. <code>lrtest</code> hands back three named fields —
<code>statistic</code>, <code>dof</code>, <code>pvalue</code> — and you
read them with a dot, as you read a column of a data frame.</p></div>
<h3 id="what-a-useless-parameter-costs" class="anchored">What a useless parameter costs</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Now Toto’s simulation, and it is the same recipe as last hour with one
line changed. Last hour we simulated from a fit to ask what the fit
believed about the world. This hour we simulate from a fit to ask what a
<em>comparison</em> does in a world where we know the answer. Draw
worlds from the model <strong>without</strong> age in it — worlds where
age genuinely does nothing once eggs are accounted for — and in each one
fit both models and take the difference in AIC. The loop is the
empty-vector-and-<code>push!</code> shape from last hour, with two fits
inside it instead of one.</p></div>
<div id="null-daic" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A world in which age is useless: simulate from the reduced fit, then refit</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># BOTH models to each invented world and watch what AIC does with a parameter</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># that has nothing in it.</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>rng_null_aic <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">777</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ynull <span class="op">=</span> <span class="fu">simulate</span>(pois_egg; nsim <span class="op">=</span> <span class="fl">10000</span>, rng <span class="op">=</span> rng_null_aic)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>null_daic <span class="op">=</span> <span class="dt">Float64</span>[]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu">size</span>(ynull, <span class="fl">2</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> <span class="fu">DataFrame</span>(Fledglings <span class="op">=</span> ynull[<span class="op">:</span>, k], Age <span class="op">=</span> females.Age, logEgg <span class="op">=</span> females.logEgg)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    a_red  <span class="op">=</span> <span class="fu">aic</span>(<span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> logEgg)),       <span class="fu">Poisson</span>(); data <span class="op">=</span> d))</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    a_full <span class="op">=</span> <span class="fu">aic</span>(<span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age <span class="op">+</span> logEgg)), <span class="fu">Poisson</span>(); data <span class="op">=</span> d))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">push!</span>(null_daic, a_full <span class="op">-</span> a_red)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"dAIC when the extra parameter is useless: median %+.4f, mean %+.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">median</span>(null_daic), <span class="fu">mean</span>(null_daic))</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"proportion of useless-parameter worlds where dAIC is negative : %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(null_daic <span class="op">.&lt;</span> <span class="fl">0</span>))</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"proportion where the useless parameter wins by more than 3     : %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(null_daic <span class="op">.&lt;</span> <span class="op">-</span><span class="fl">3</span>))</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"proportion at or below our observed dAIC of %+.4f : %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>        daic_age, <span class="fu">mean</span>(null_daic <span class="op">.&lt;=</span> daic_age))</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co"># For ONE extra parameter on the SAME data, dAIC = 2k_extra - LR = 2 - LR, exactly.</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">our dAIC %+.4f   versus  2 - LR statistic %+.4f</span><span class="sc">\n</span><span class="st">"</span>, daic_age, <span class="fl">2</span> <span class="op">-</span> lr_age.statistic)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"simulated tail probability %.4f   versus  the chi-squared p above %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mean</span>(null_daic <span class="op">.&lt;=</span> daic_age), lr_age.pvalue)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="co"># The chi-squared's own 5% line, applied to the same worlds: how often does the</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="co"># test reject a parameter that does nothing? It promises one world in twenty.</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>crit <span class="op">=</span> Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Chisq</span>(<span class="fl">1</span>), <span class="fl">0.95</span>)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>size_lrt <span class="op">=</span> <span class="fu">mean</span>((<span class="fl">2</span> <span class="op">.-</span> null_daic) <span class="op">.&gt;</span> crit)</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a><span class="co"># how well this many worlds pin a rate of 5%: the binomial SE of that proportion</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>mc_se <span class="op">=</span> <span class="fu">sqrt</span>(<span class="fl">0.05</span> <span class="op">*</span> <span class="fl">0.95</span> <span class="op">/</span> <span class="fu">length</span>(null_daic))</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"useless-parameter worlds where the test rejects at 5%% : %.3f  (%.1f simulation SEs above 0.05)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>        size_lrt, (size_lrt <span class="op">-</span> <span class="fl">0.05</span>) <span class="op">/</span> mc_se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dAIC when the extra parameter is useless: median +1.5421, mean +0.9930
proportion of useless-parameter worlds where dAIC is negative : 0.1608
proportion where the useless parameter wins by more than 3     : 0.0258
proportion at or below our observed dAIC of -0.7923 : 0.0952

our dAIC -0.7923   versus  2 - LR statistic -0.7923
simulated tail probability 0.0952   versus  the chi-squared p above 0.0947
useless-parameter worlds where the test rejects at 5% : 0.052  (0.9 simulation SEs above 0.05)</code></pre>
</div>
</div>
<div id="cell-fig-null-daic" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">600</span>, <span class="fl">320</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"ΔAIC (age added to eggs-only model)"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    ylabel <span class="op">=</span> <span class="st">"simulated worlds"</span>, title <span class="op">=</span> <span class="st">"ΔAIC when the extra parameter is useless"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist!</span>(ax, null_daic; bins <span class="op">=</span> <span class="fl">40</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.55</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax, [<span class="fl">0.0</span>]; linestyle <span class="op">=</span> <span class="op">:</span>dash, linewidth <span class="op">=</span> <span class="fl">2</span>, label <span class="op">=</span> <span class="st">"0 = no change"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax, [daic_age]; linewidth <span class="op">=</span> <span class="fl">2</span>, color <span class="op">=</span> <span class="fu">Cycled</span>(<span class="fl">2</span>), label <span class="op">=</span> <span class="st">"observed ΔAIC"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># legend outside the axis so it can never hide a group (house rule: tools/figures.jl)</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div id="fig-null-daic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-null-daic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk5b-comparison_files/figure-html/fig-null-daic-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-daic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: ΔAIC for adding age to the eggs-only model, across 10,000 worlds simulated from a fit where age is genuinely useless. The dashed line at 0 marks equal AIC; the solid line marks the ΔAIC actually observed on the real data. Part of the bar sits left of 0 — a useless parameter still wins by chance sometimes — and the observed value sits inside that same bulk, not out past it.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>It goes negative sometimes.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It goes negative in 16% of worlds where the parameter is worth nothing,
because the likelihood always improves a little by chance and now and
then improves by more than the parameter cost. Its typical value is
1.54, not two — so “two units” is the ceiling on a useless parameter’s
damage, not its usual size. And 3% of worlds have a useless parameter
winning by more than three AIC. Our own 0.79 turns up in 10% of worlds
where age does nothing at all. That is Arnold’s (2010) point about
uninformative parameters, computed on our own data rather than borrowed
from his: a model within two units of the best has usually bought a
parameter and nothing else.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>Those two printed lines near the bottom are the same test twice.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>They are. For one extra parameter on the same rows, ΔAIC is two minus
the likelihood-ratio statistic, exact to every digit, so the null I have
just simulated <strong>is</strong> the chi-squared null, drawn rather
than looked up: my simulated 0.095 is <code>lrtest</code>’s printed
0.0947 by brute force.</p></div>
<div class="line"><span class="who toto">Toto</span><p>Then why simulate it, if it is the same number?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Because <strong>the simulation does not buy a second opinion; it buys
the calibration of the first one</strong> — how far the chi-squared
approximation can be trusted at this sample size, which Wilks’s formula
cannot tell you and ten thousand worlds can. The last printed line is
that calibration in one number: the test’s five-per-cent line rejected
in a proportion 0.052 of the worlds where age did nothing, against the
one in twenty it promises. Before you read that as a gap, ask how well
the worlds can measure it: ten thousand of them pin a rate of one in
twenty to about 0.002 either way, and the difference is 0.9 of those
widths — chance, and nothing else. So at 163 rows, for this model, the
reference distribution you would have drawn is the one you looked up,
and the simulation’s verdict is that the lookup is honest. Notice what
decided that. A thousand worlds would have pinned the same rate only to
about 0.007, and a rate that wanders that far from one seed to the next
can look like a finding when it is noise; the number of worlds is what
decides whether a simulation can answer the question you put to it, so
report the simulation’s own error bar beside its answer, every time.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Can I live with it?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Here, yes, and you now know why rather than hoping. Ours is 0.09, and a
lookup this well calibrated is worth reading wherever it lands, near the
line included. What you may not do is carry that verdict to another
model or another file: calibration is a property of the model, the
family and the rows, not of the test, and it is a two-line simulation
each time. In Class 8 the looked-up number is not worth reading at all,
because testing a variance at zero puts the null on a boundary and the
same chi-squared is wrong by a factor you can compute — and the recipe
you have just run is what shows it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So age does not matter.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>No.&nbsp;Say what the data say, which is narrower and more useful, and it
takes the next ten minutes.</p></div>
<h3 id="two-questions-not-two-answers" class="anchored">Two questions, not two answers</h3>
<div class="line"><span class="who itchy">Itchy</span><p>You have two estimates of the effect of age on the table, one from each
model, and the temptation is to read the second as the correction of the
first. Put them side by side, on the scale the biology lives on.</p></div>
<div id="rate-ratios" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>b1, se1 <span class="op">=</span> <span class="fu">coef</span>(pois, <span class="op">:</span>mu),  <span class="fu">stderror</span>(pois)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>b2, se2 <span class="op">=</span> <span class="fu">coef</span>(pois2, <span class="op">:</span>mu), <span class="fu">stderror</span>(pois2)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># a Poisson coefficient is a log rate ratio; exp() puts it back in chicks per chick</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>rr_age1 <span class="op">=</span> <span class="fu">exp</span>(b1[<span class="fl">2</span>]); lo_age1, hi_age1 <span class="op">=</span> <span class="fu">exp</span>(b1[<span class="fl">2</span>] <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se1[<span class="fl">2</span>]), <span class="fu">exp</span>(b1[<span class="fl">2</span>] <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se1[<span class="fl">2</span>])</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>rr_age2 <span class="op">=</span> <span class="fu">exp</span>(b2[<span class="fl">2</span>]); lo_age2, hi_age2 <span class="op">=</span> <span class="fu">exp</span>(b2[<span class="fl">2</span>] <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se2[<span class="fl">2</span>]), <span class="fu">exp</span>(b2[<span class="fl">2</span>] <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se2[<span class="fl">2</span>])</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the smallest rate ratio this design could detect four times in five, at the 5% line.</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The normal's 97.5th percentile (1.96) is the two-sided 5% line; its 80th (0.84) is</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># the power. A true effect that many SEs from zero clears the line four times in five.</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>z_mde <span class="op">=</span> Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Normal</span>(), <span class="fl">0.975</span>) <span class="op">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Normal</span>(), <span class="fl">0.80</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>mde_age <span class="op">=</span> <span class="fu">exp</span>(z_mde <span class="op">*</span> se2[<span class="fl">2</span>])</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># a true effect sitting exactly on the 5% line clears it only half the time</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>rr_line <span class="op">=</span> <span class="fu">exp</span>(Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Normal</span>(), <span class="fl">0.975</span>) <span class="op">*</span> se2[<span class="fl">2</span>])</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># and the thing that connects the two questions: how eggs laid moves with age</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>eggfit <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(EggNo <span class="op">~</span> Age)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>rr_egg_age <span class="op">=</span> <span class="fu">exp</span>(<span class="fu">coef</span>(eggfit, <span class="op">:</span>mu)[<span class="fl">2</span>])</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rate ratio for a year of age, age alone      : %.4f  [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        rr_age1, lo_age1, hi_age1)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rate ratio for a year of age, eggs also in   : %.4f  [%.4f, %.4f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        rr_age2, lo_age2, hi_age2)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"smallest rate ratio this design could detect at 80%% power : %.4f</span><span class="sc">\n</span><span class="st">"</span>, mde_age)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rate ratio that would clear the 5%% line half the time      : %.4f</span><span class="sc">\n</span><span class="st">"</span>, rr_line)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rate ratio for eggs laid per year of age                  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, rr_egg_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rate ratio for a year of age, age alone      : 1.2618  [1.1490, 1.3857]
rate ratio for a year of age, eggs also in   : 1.0889  [0.9859, 1.2027]
smallest rate ratio this design could detect at 80% power : 1.1527
rate ratio that would clear the 5% line half the time      : 1.1045
rate ratio for eggs laid per year of age                  : 1.1688</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Read them together, because separately each one lies to you. Age on its
own multiplies expected fledglings by 1.262 per year, with an interval
clear of one. Age with eggs laid in the model multiplies them by 1.089,
interval from 0.986 to 1.203, which contains one. The honest sentence is
not “age stopped mattering”. It is this: <strong>these are two different
questions</strong>, and the answers are not in conflict. The first is
the <strong>marginal</strong> effect of a year of age on chicks fledged
— what a year does, letting everything that comes with a year come with
it. The second is the <strong>conditional</strong> effect of a year of
age <em>at a fixed number of eggs</em> — what is left of the year once
the eggs are held still. Older females lay more eggs, 1.169 times as
many per year, so most of what age does to fledgling number, it does by
laying more. The first model was not wrong about age; it was answering
the question you asked it.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Then which one do I report?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Whichever one is your question, and you say which. If the question is
“do older females fledge more?”, the marginal one, and eggs laid is the
mechanism, not a nuisance. If the question is “are older females better
at turning an egg into a fledgling?”, the conditional one, and it says:
not detectably. Reporting the conditional coefficient as the refutation
of the marginal one is the commonest misreading of a regression table
there is, and every extra column you add to a model changes the question
every other column is answering.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>And the part that is left, once eggs are held still?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Is the part we cannot pin down, and there I will give you two numbers
rather than a shrug, because they do two different jobs. The first you
already have: the interval. At a fixed clutch size the rate ratio per
year of age lies between 0.99 and 1.20, and that is the only bound the
data put on the effect: ratios above the one I am about to compute sit
inside it, and have not been ruled out. The second is what the design
could see. The smallest rate ratio it could have detected four times in
five is 1.153. <code>z_mde</code> in the cell is where it comes from,
and it is two normal percentiles added together: the
ninety-seven-and-a-half-th, which is the two-sided five-per-cent line,
and the eightieth, which is the power. A true coefficient that many
standard errors from zero — about two and four-fifths — clears the line
four times in five; one sitting on the line, a ratio of 1.10, clears it
only half the time, and anything smaller than that would have been
missed more often than not. So the detectable effect bounds the
<em>design</em>, not the effect: even a true ratio of 1.15 slips past
this test one time in five, and a non-rejection rules nothing out on its
own. The sentence for the paper is not “no effect of age”, and it is not
“the effect is smaller than 1.15” either. It is: “at a fixed clutch size
the rate ratio per year of age lies between 0.99 and 1.20; the design
had eighty per cent power to detect a ratio of 1.15 or larger, so a
smaller effect could easily have been missed”.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Can I at least say the conditional effect is smaller than the marginal
one? The second interval does not even reach the first estimate.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>No, and that is the trap I wanted you to walk into before you wrote
anything down. The interval on one of those rate ratios excluding the
other one’s point estimate is not a test of the difference between them.
Both come from the same 163 females and the same variation in age, so
the two estimates are strongly correlated, and an interval built for one
knows nothing about that. <strong>An interval that excludes another
estimate’s point value is not a test of the difference.</strong> To say
in print that the conditional effect is smaller than the marginal one
you would need an error bar on the difference itself, and you do not
have one.</p></div>
<h3 id="the-refusal-and-the-hole" class="anchored">The refusal, and the hole</h3>
<div class="line"><span class="who eddie">Eddie</span><p>Last thing. What stops me doing this wrong?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Less than you would like, and knowing exactly how much less is the point
of the next five minutes. Start with what it does stop. Toto, you were
about to.</p></div>
<div class="line"><span class="who toto">Toto</span><p>I was going to check the eggs result the other way round, to see whether
it came out the same.</p></div>
<div id="guard-order" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(pois2, pois)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<div class="ansi-escaped-output">
<pre>ArgumentError: lrtest: `full` must have more parameters than `reduced` (dof(full) = 2, dof(reduced) = 3; did you pass the arguments as (reduced, full)?)

(stack trace omitted)</pre>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>It refused and it told me which argument was which.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It refused, it named the rule, and it named the fix, which is what an
error message is for: reduced model first, full model second, and the
engine checks that the second has more parameters than the first. That
is the mistake everybody makes once, and the engine is the right place
to catch it, because it can see the two fits. There are other refusals
in there, all of them about models with random effects, and Class 8 is
where you meet them and learn why a refusal can be a kindness.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And what does it not stop?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The one that will actually get you. It cannot see your data. Nobody fits
two models to different rows on purpose; it happens because the reduced
model was fitted on an earlier version of the file, or on the rows that
were complete for the columns <em>it</em> named and not for the extra
column the full model adds, or by a co-author who filtered something and
did not say. Class 6 meets a file where one column has holes in it and
<code>dropmissing</code> is the first thing done to it; fit one model
before that line and one after it, and you have done what I am about to
do deliberately. <code>females[1:150, :]</code> is rows one to one
hundred and fifty and every column, a colon in the column slot as in
Class 3’s matrix slices.</p></div>
<div id="cell-guard-silence" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A nested pair fitted to DIFFERENT ROWS: reduced on the first 150 females, full on all.</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>first150 <span class="op">=</span> females[<span class="fl">1</span><span class="op">:</span><span class="fl">150</span>, <span class="op">:</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>pois_sub <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)), <span class="fu">Poisson</span>(); data <span class="op">=</span> first150)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows in the first fit : %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">nobs</span>(pois_sub))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"rows in the second    : %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">nobs</span>(pois2))</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>lr_sub <span class="op">=</span> <span class="fu">lrtest</span>(pois_sub, pois2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows in the first fit : 150
rows in the second    : 163</code></pre>
</div>
<div id="guard-silence" class="cell-output cell-output-display" data-execution_count="13">
<pre><code>(statistic = 21.96374053819227, dof = 1, pvalue = 2.778504632397899e-6)</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>It gave me a p-value.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It gave you a p-value, it is a small one, and it is meaningless. 13 rows
are in one likelihood and not the other, so the difference in
log-likelihoods is partly a difference in how much data each one is
summing over. The same hole is in every AIC comparison you will ever
run: <strong>AIC differences are only interpretable between models
fitted to identical observations</strong>, and nothing in
<code>aic(fit)</code> knows what those observations were. The nasty part
is that this one came out <em>plausible</em>: the honest comparison on
all the rows gives 89.2, so dropping 13 rows understated a real effect
about 4-fold and still returned a decisive answer. You would never look
twice. Drop ten more rows and the arithmetic stops pretending.</p></div>
<div id="guard-silence-worse" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pois_sub2 <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Fledglings <span class="op">~</span> Age)), <span class="fu">Poisson</span>(); data <span class="op">=</span> females[<span class="fl">1</span><span class="op">:</span><span class="fl">140</span>, <span class="op">:</span>])</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>bad <span class="op">=</span> <span class="fu">lrtest</span>(pois_sub2, pois2)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"reduced fit on %d rows, full on %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">nobs</span>(pois_sub2), <span class="fu">nobs</span>(pois2))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"statistic %+.4f on %d df, p = %.4f</span><span class="sc">\n</span><span class="st">"</span>, bad.statistic, bad.dof, bad.pvalue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>reduced fit on 140 rows, full on 163
statistic -28.1070 on 1 df, p = 1.0000</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>The statistic is negative. A likelihood ratio cannot be negative.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It cannot, not for nested models on the same rows, which is why this is
the number I wanted you to see. The larger model can always do at least
as well as the smaller one on the same data, because it can set the
extra coefficient to zero and <em>be</em> the smaller one; that is what
nesting means, and it is why the statistic has a floor at zero. Here the
reduced model is summing over less data, so its log-likelihood is
<em>higher</em> — fewer terms — and the difference comes out the wrong
way round. Then look at the p-value: exactly one, because the test takes
the larger of the statistic and zero before referring it to a
chi-squared, so an impossible statistic is reported as the most
reassuring result the test can give. <strong>That p-value is not a
warning; it is what a broken assumption looks like once the arithmetic
can no longer tell you so.</strong> The comparison is quiet only inside
the narrow window where the contamination is small enough to pass for
biology. Count your rows. Every time. It is one call to
<code>nobs</code>, and it is the line I printed at the top of this hour
before we had done anything else.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>So the summary is: check the model, then compare it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The summary is that those are two different activities and people
conflate them constantly, which is why they got an hour each.
<strong>Comparison ranks; it never validates.</strong> The three models
on this page can be ranked to four decimals, and the winner — age and
eggs laid together — is the model last hour convicted of not believing
in its own zeros. If you only ever compare, the best model in a bad set
wins and nothing on this page tells you the set was bad. Last hour’s
tools are the only ones that can: simulate from the winner, and look at
what it believes.</p></div>
<p>So the order of work, and it is three lines. Count the rows of every fit you are about to compare, and stop if they differ. Rank, with the number and with its reference distribution, and say what the winning parameter is worth against what a useless one usually costs. Then take the winner back to last hour and ask it what it believes, because nothing on this page has looked at a residual or invented a bird, and the ranking is only as good as the set you handed it.</p>
<p>One thing both hours swept under the rug: every model on them treats each female as a stranger to every other, the pretence Classes 2 to 4 also made and the one Class 6 stops making. Last hour’s residual and simulation tools survive that repair unchanged. The way you compare two models does not — a likelihood with random effects in it can be computed two ways, and only one of them may be compared — and Class 8 is where that is put right.</p>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>AIC ranks; it does not validate.</strong> Minus twice the log-likelihood plus twice the parameter count; the count is the charge for having tuned the model to the data it is judged on. Lower is better and only differences mean anything. A parameter that buys no likelihood at all costs exactly two units, which is where the familiar threshold comes from (Burnham &amp; Anderson 2002) — the <strong>worst</strong> a useless parameter does, not the usual case.</li>
<li><strong>What a useless parameter usually costs, simulated.</strong> From a fit in which the extra term was worth nothing, the median ΔAIC was 1.54, negative in 16% of worlds, and 3% had the useless parameter winning by more than three units (Arnold 2010). <strong>Calibrating a threshold by simulation is a two-line job that beats quoting it.</strong></li>
<li><strong>The likelihood-ratio test is a reference distribution, not a ranking.</strong> Twice the gap in log-likelihood between nested models, against a chi-squared with as many degrees of freedom as parameters were added (Wilks 1938). Nested means the smaller model is the larger with some coefficients pinned at zero, which is also why the statistic can never be negative on the same rows.</li>
<li><strong>A simulated ΔAIC null and the likelihood-ratio test are the same thing.</strong> For one extra parameter on the same rows, ΔAIC = 2 − LR <em>exactly</em>. What the simulation buys is the <strong>calibration</strong> of the chi-squared approximation at your own sample size: here the five-per-cent line rejected in a proportion 0.052 of ten thousand worlds where the parameter did nothing, 0.9 simulation standard errors from the one in twenty it promises — so at 163 rows the lookup is honest for this model. Report the simulation’s own error bar with its answer; too few worlds turn noise into findings. Calibration belongs to the model and the rows, not to the test, so check it again for a new one — and in Class 8, where a boundary makes the approximation wrong, the same recipe is what shows the size of the error.</li>
<li><strong>A marginal and a conditional coefficient are different questions, not two estimates of one thing.</strong> Age alone gave a rate ratio clear of one; age at a fixed clutch size gave one that covers it, because older females lay more eggs. Report whichever answers your question, say which, and do not report the second as a refutation of the first.</li>
<li><strong>Never accept a null.</strong> Report the interval as the bound on the effect — at a fixed clutch size, a rate ratio between 0.99 and 1.20 per year of age — and the design’s sensitivity beside it: eighty per cent power to detect a ratio of 1.15 or larger, so a smaller effect could easily have been missed. The detectable effect bounds the design, not the effect; a non-rejection rules nothing out on its own. And <strong>an interval that excludes another estimate’s point value is not a test of the difference</strong>, because the two estimates come from the same data and are correlated.</li>
<li><strong>The engine refuses what it can see and is silent about what it cannot.</strong> The arguments in the wrong order are refused with the fix named. Two fits on different rows are not: the statistic goes negative, which nesting forbids, and the p-value comes back as exactly one. <strong>AIC differences are only interpretable across models fitted to identical observations.</strong> Count your rows first; it is one call to <code>nobs</code>.</li>
<li><strong>Comparison ranks; it never validates.</strong> The winner of a ranking can still be inventing birds that cannot exist. Checking a model against itself is <a href="wk5-diagnostics.html">Class 5a</a>, and no ranking replaces it: the best model in a bad set still wins.</li>
</ul>
<h3 id="julia-you-used" class="anchored">Julia you used</h3>
<ul>
<li><strong>Two fits inside one loop.</strong> The <code>Float64[]</code>-and-<code>push!</code> shape from Class 5a, with a data frame built from the simulated column and both models fitted to it before one number is pushed.</li>
<li><strong><code>lr.statistic</code>, <code>lr.dof</code>, <code>lr.pvalue</code>.</strong> A result with named fields, read with a dot, exactly as a column of a data frame is.</li>
<li><strong><code>2 .- null_daic</code>.</strong> The dot on a minus: one number minus every element of a vector.</li>
<li><strong><code>females[1:150, :]</code>.</strong> Rows one to one hundred and fifty, every column.</li>
</ul>
<h3 id="calls-you-used" class="anchored">Calls you used</h3>
<ul>
<li><code>aic(fit)</code>, <code>dof(fit)</code>, <code>loglik(fit)</code>, <code>nobs(fit)</code>: the number, its two halves, and the row count that decides whether two of them may be subtracted.</li>
<li><code>lrtest(reduced, full)</code>: the likelihood-ratio test, returning <code>(; statistic, dof, pvalue)</code>. It throws when the order is wrong and cannot see whether the two fits used the same rows; call <code>nobs</code> on both first.</li>
<li><code>simulate(fit; nsim = k, rng = MersenneTwister(seed))</code>: as in Class 5a. Here the invented worlds come from the <strong>reduced</strong> model, so that the extra parameter is useless by construction.</li>
<li><code>Distributions.quantile(Distributions.Chisq(1), 0.95)</code>: the chi-squared’s own five-per-cent line, for checking the test’s promise against the simulated worlds. <code>Distributions.quantile(Distributions.Normal(), 0.975)</code> and <code>0.80</code>: the two percentiles whose sum is the smallest detectable effect, in standard errors.</li>
<li>In the figure, <code>Cycled(2)</code> takes the second colour of the theme’s own cycle, so a line matches the palette without naming a colour, and <code>Legend(fig[1, 2], ax; framevisible = false)</code> puts the legend in its own grid cell beside the axis, where it can never sit on top of the data.</li>
<li><strong>The simulation thread.</strong> Every chapter asks the fit to invent data. This hour’s thread ran in the middle rather than at the end: ten thousand worlds from the eggs-only model, both models refitted to each, and the comparison’s own null drawn rather than looked up. Appendix A takes the same move further, into coverage.</li>
</ul>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. Details checked against OpenAlex, an open catalogue of
research papers.</p>
<ol type="1">
<li><strong>Arnold, T. W. (2010) “Uninformative parameters and model selection using Akaike’s Information Criterion”, <em>Journal of Wildlife Management</em> 74:1175–1178.</strong> doi:10.2193/2009-367. Start here; it is the shortest paper on this list. A model within two AIC units of the best has usually bought a parameter and nothing else. Two units is what an <em>entirely</em> useless parameter costs at worst; this class simulates its typical cost, which is less.</li>
<li><strong>Wilks, S. S. (1938) “The large-sample distribution of the likelihood ratio for testing composite hypotheses”, <em>Annals of Mathematical Statistics</em> 9:60–62.</strong> doi:10.1214/aoms/1177732360. Three pages, and the origin of the chi-squared reference distribution this class looks up and then simulates. Read it for the two conditions the result needs — nested models, and a null that is not on a boundary — because Class 8 breaks the second one.</li>
<li><strong>Burnham, K. P. &amp; Anderson, D. R. (2002) <em>Model Selection and Multimodel Inference: A Practical Information-Theoretic Approach</em>, 2nd edition, Springer.</strong> doi:10.1007/b97636. The book that taught ecology to use AIC, including the rules of thumb about differences of two and of ten that get quoted far more often than read. Item 1 is the counterweight.</li>
<li><strong>Akaike, H. (1974) “A new look at the statistical model identification”, <em>IEEE Transactions on Automatic Control</em> 19:716–723.</strong> doi:10.1109/TAC.1974.1100705. Short, hard, and worth an afternoon once.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Graded by depth: the first is short, the second runs a loop of a few hundred fits, so start it and read on while it runs. Every exercise names a file under <code>data/</code> that exists; do it on your own organism as well where you have one. A <em>check</em> is a number computed from that file when this page was built — match it before going on. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Class 5a and not this class.</p>
<ol type="1">
<li><p><strong>Two comparisons, one parameter each.</strong> On <code>data/2012/ChickSurvival.csv</code>, fit <code>Survival ~ Mass2</code> with <code>Binomial()</code>, then two models that each add one term: <code>JulianDate</code>, which you expect to matter, and <code>Sex</code>, which you may not. Report <code>aic</code>, <code>dof</code> and <code>nobs</code> for all three and both <code>lrtest</code> results. Then answer: which of your two ΔAIC values is smaller than the cost of a parameter that explains nothing, and what does that let you say and not say? <em>Check:</em> adding hatching date changes AIC by -80.7; adding sex by 1.72, and the likelihood-ratio p-value for sex is 0.596.</p></li>
<li><p><strong>What a useless parameter costs, on your own file.</strong> Simulate 200 datasets from the mass-only fit of question 1 with <code>MersenneTwister(7)</code>; in each, fit both the mass-only and the mass-plus-sex model and push the difference in AIC into a <code>Float64[]</code>, exactly as the chapter’s loop did (build each world’s data frame from the simulated column and the real <code>Mass2</code> and <code>Sex</code>). Report the proportion of worlds where the useless parameter wins, the proportion where it wins by more than three, and where your observed ΔAIC for sex sits among them. One sentence: what does that do to the sentence you wrote for question 1? <em>Check:</em> sex wins in a proportion 0.1 of the worlds where it does nothing, and by more than three in 0.01; the observed ΔAIC sits at or above a proportion 0.57 of them.</p></li>
<li><p><strong>Never accept the null.</strong> The sex coefficient from question 1 has an interval that covers zero. Compute the smallest effect this design could have detected at eighty per cent power, <code>exp(z_mde * se)</code> on the log-odds coefficient with <code>z_mde</code> the two normal percentiles the chapter added together, and write the sentence you would put in a paper, in the chapter’s shape: the interval as the bound on the effect, and the detectable ratio as the sensitivity of the design, so that a smaller effect could easily have been missed. It must not contain the words “no effect”, and it must not claim the effect is smaller than the detectable one. <em>Check:</em> the odds ratio for males runs from 0.76 to 1.17, and the smallest detectable ratio is 1.36 — or its reciprocal.</p></li>
<li><p><strong>Two questions, not two answers.</strong> On <code>data/2012/ChickSurvival.csv</code> again, fit <code>Survival ~ Mass2</code> and <code>Survival ~ Mass2 + BroodSize</code> and report the odds ratio for a gram of mass from each, <code>exp</code> of the coefficient, with its interval. Then fit <code>Mass2 ~ BroodSize</code> with <code>Gaussian()</code> and report the slope. Write two sentences: which question each mass coefficient answers, and why the second is not a correction of the first. <em>Check:</em> the odds ratio per gram is 2.01 with mass alone and 2.06 with brood size held still; a chick in a brood one larger is 0.15 g lighter on average.</p></li>
<li><p><strong>Trigger the refusal, and find the hole.</strong> Call <code>lrtest</code> on the two models of question 1 with the arguments the wrong way round and paste the error. Then fit the <strong>reduced</strong> model to the first 1500 rows only, <code>df[1:1500, :]</code>, compare it with the full model on all the rows using <code>lrtest</code>, and paste the number it returns. Explain why the engine can catch the first and cannot catch the second, and name the one call you should have made first. <em>Check:</em> the second comparison returns a statistic of -17.8 and a p-value of 1.0, on 1500 rows against 1576, and nothing in the output objects to the sign.</p></li>
</ol>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk5-diagnostics.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 5a · Is the model any good?</span></a><a class="chapter-nav-link next" href="wk6-random-intercepts.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Class 6 · Rows are not strangers</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 5b of twelve rungs, ten in v1, plus a coda · draft, all code run, 2026-09-13<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>