<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Class 9: both at once – Stats Hours with Itchy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-html-5276476b5bdb9cfe1f92c505466e0bf3.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../tools/theme/stats-hours.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">Class 9: both at once</h1>

</header>


<header class="mast">
  <div class="mast-inner">
    <p class="kicker">
      <span><a href="../index.html">Stats Hours with Itchy</a></span><span class="sep">/</span>
      <span>Class 9</span><span class="sep">/</span>
      <span>Draft</span>
    </p>
    <h1>Both at once</h1>
    <p class="deck">Class 3 promised a repair it could not perform, because the file it was given never recorded which nest a chick came from. Here is the file that did — and the standard error the same model prints on it turns out to be answering a different question, with an interval that is wrong for either.</p>
    <div class="status">
      <span class="tag">Draft</span>
      <p>All ten classes of version 1 run end to end (1–10), with Appendix A, the preface and the coda. Every number and figure on this page was computed when the site was built; the book itself is still being written.</p>
    </div>
    <p class="meta">
      <b>Engines</b> DRM.jl 0.7.1 at 26f4c4ddc (Julia 1.10.0) · drmTMB 0.7.0 (R 4.6.0)<br>
      <b>Provenance</b> Every block of Julia code on this page ran when the site was built, including the one that fails. Nothing is pasted from a session you cannot see. The one R box was run once by hand, on the date shown (2026-09-07): all four of its blocks come from a single Rscript run against the same archived file, and the box says so; the script is kept at data/ch9/ch9-r-box.R.<br>
      <b>Caveat</b> The data are real. These are the Lundy Island house sparrow chicks of the author’s 2012 course, read directly from the archived data/2012/SparrowSurvival.csv, which is the brood-identified version of the file Class 3 used (where the file comes from is recorded in data/2012/README.md). Nothing here is invented; the simulated quantities are drawn from a model fitted to that file, from random-number generators set up in the code you can see.
    </p>
  </div>
</header>

<div class="wrap">
<blockquote>
<p><strong>A note on the data, and it is the note Class 3 promised.</strong> Class 3 fitted chick survival with <code>Binomial()</code> on <code>data/2012/ChickSurvival.csv</code> and said, in writing, that the chicks in a nest are not strangers and that the file could not be repaired, because it recorded how <em>big</em> each brood was and never <em>which</em> brood. Class 6 then freed the correlation between rows on <code>data/2012/BodySize.csv</code>, where the repeated thing was a recapture. This chapter is what happens when the same population is handed over with the nest written down. Same birds, same island, same question, one more column.</p>
</blockquote>
<hr>
<h2 id="objectives" class="anchored">Objectives</h2>
<p>By the end of this class you should be able to:</p>
<ol type="1">
<li>Fit a generalised linear mixed model — a family <em>and</em> a grouping in the same call — and say which constant each of the two is freeing.</li>
<li>Predict, before you fit, what adding the grouping will do to a standard error, and say by how much it was wrong to leave it out.</li>
<li>Read a variance component that lives on the link scale — the scale of the model’s straight-line part, before it is turned back into a probability — and turn it into an intraclass correlation, saying out loud which scale that correlation lives on and why the scale had to be invented.</li>
<li>Say why a GLMM’s coefficient is a <strong>conditional</strong> odds ratio, why averaging over groups shrinks it towards zero, and which of the two your reader wanted.</li>
<li>Decide from the data file itself whether a second grouping is nested, crossed or neither, and whether it has enough levels to be treated as random at all.</li>
</ol>
<hr>
<h2 id="the-class" class="anchored">The class</h2>
<p class="scene">Itchy’s office, 9:00 am. TOTO has brought the same chick file he brought
to Class 3 and the grudge that goes with it. MOMO has read ahead and is
suspicious of the word “both”. EDDIE is here for the part where the two
halves of the course meet. JARO, who is a statistician and turns up for
the hard weeks, has been promised coffee.</p>
<div class="line"><span class="who itchy">Itchy</span><p>Class 3 gave you the shape of the noise. Class 6 gave you the
correlation between rows. Every constant either of those classes freed
is still free today, and today you free both in one call. Toto, remind
the room what I told you in Class 3 and could not deliver.</p></div>
<div class="line"><span class="who toto">Toto</span><p>That the chicks in one nest are not independent, that my standard error
was too small, and that the file could not be fixed because it never
said which nest.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And here is the file that says. Load it the way Class 6 taught you.</p></div>
<div id="cell-setup" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tools/figures.jl includes tools/theme_itchy.jl itself, so one include does both.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">include</span>(<span class="st">"../tools/figures.jl"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">DRM</span>, <span class="bu">DataFrames</span>, <span class="bu">CSV</span>, <span class="bu">Statistics</span>, <span class="bu">Random</span>, <span class="bu">Printf</span>, <span class="bu">CairoMakie</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> <span class="bu">Distributions</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set_theme!</span>(<span class="fu">theme_itchy</span>(<span class="op">:</span>light))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Class 6's recipe, applied without thinking about it. Watch what it does.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/SparrowSurvival.csv"</span>, DataFrame; missingstring <span class="op">=</span> <span class="st">"NA"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"rows, columns: "</span>, <span class="fu">size</span>(raw))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(raw, <span class="op">:</span>eltype, <span class="op">:</span>nmissing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows, columns: (1950, 12)</code></pre>
</div>
<div id="setup" class="cell-output cell-output-display" data-execution_count="2">
<div><div style="float: left;"><span>12×3 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">eltype</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">nmissing</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Symbol">Symbol</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="DataType">DataType</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: left;">ChickNo</td>
<td style="text-align: left;">String7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: left;">Sex</td>
<td style="text-align: left;">String1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: left;">Survival</td>
<td style="text-align: left;">String1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: left;">Mass2</td>
<td style="text-align: left;">String7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">5</td>
<td style="text-align: left;">BroodSize</td>
<td style="text-align: left;">String1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">6</td>
<td style="text-align: left;">HatchingSuccess</td>
<td style="text-align: left;">String1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">7</td>
<td style="text-align: left;">EggNo</td>
<td style="text-align: left;">String1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">8</td>
<td style="text-align: left;">JulianDate</td>
<td style="text-align: left;">String3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">9</td>
<td style="text-align: left;">Dad</td>
<td style="text-align: left;">String7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">10</td>
<td style="text-align: left;">Mum</td>
<td style="text-align: left;">String7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">11</td>
<td style="text-align: left;">BroodNo</td>
<td style="text-align: left;">String7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">12</td>
<td style="text-align: left;">Year</td>
<td style="text-align: left;">Int64</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Every column is text and nothing is missing.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Every column is text and nothing is missing, which is two lies for the
price of one. Fit it anyway, because I want the engine to be the one who
tells you.</p></div>
<div id="first-attempt" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2 <span class="op">+</span> (<span class="fl">1</span><span class="op">|</span>BroodNo))), <span class="fu">Binomial</span>(); data <span class="op">=</span> raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<div class="ansi-escaped-output">
<pre>MethodError: no method matching Float64(::String1)

Closest candidates are:
  Float64(<span class="ansi-bright-red-fg">::IrrationalConstants.Sqrt4π</span>)
  Float64(<span class="ansi-bright-red-fg">::UInt8</span>)
  Float64(<span class="ansi-bright-red-fg">::IrrationalConstants.Quartπ</span>)
  ...


(stack trace omitted)</pre>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>That is the Class 6 error again.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is the same error with a different cause, which is why you get it
twice in one book. In Class 6 the file said <code>NA</code>, so we told
the reader that <code>NA</code> means missing. This file, written by the
same person in the same decade, leaves the cell <strong>empty</strong>
instead. And <code>missingstring = "NA"</code> does not <em>add</em>
<code>NA</code> to the list of missing markers. It
<strong>replaces</strong> the list, and the empty string was on the list
we just threw away. Name both.</p></div>
<div id="read-clean" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/SparrowSurvival.csv"</span>, DataFrame;</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>               missingstring <span class="op">=</span> [<span class="st">"NA"</span>, <span class="st">""</span>])</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"missing values per column:"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="fu">describe</span>(raw, <span class="op">:</span>nmissing))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>chicks <span class="op">=</span> <span class="fu">dropmissing</span>(raw, [<span class="op">:</span>Survival, <span class="op">:</span>Mass2, <span class="op">:</span>BroodNo])</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mkpath</span>(<span class="st">"../data/ch9"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>CSV.<span class="fu">write</span>(<span class="st">"../data/ch9/chicks-broods.csv"</span>, chicks)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="fu">nrow</span>(chicks)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>broods <span class="op">=</span> <span class="fu">sort</span>(<span class="fu">unique</span>(chicks.BroodNo))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>J <span class="op">=</span> <span class="fu">length</span>(broods)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>class3 <span class="op">=</span> CSV.<span class="fu">read</span>(<span class="st">"../data/2012/ChickSurvival.csv"</span>, DataFrame)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"kept %d of %d rows on %d broods</span><span class="sc">\n</span><span class="st">"</span>, n, <span class="fu">nrow</span>(raw), J)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"survived: %d of %d (%.4f)</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">sum</span>(chicks.Survival), n, <span class="fu">mean</span>(chicks.Survival))</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"Class 3's file, for comparison: %d rows, %d columns, no brood identifier</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">nrow</span>(class3), <span class="fu">ncol</span>(class3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>missing values per column:
12×2 DataFrame
 Row │ variable         nmissing 
     │ Symbol           Int64    
─────┼───────────────────────────
   1 │ ChickNo                 0
   2 │ Sex                     0
   3 │ Survival               75
   4 │ Mass2                 275
   5 │ BroodSize             135
   6 │ HatchingSuccess        80
   7 │ EggNo                  97
   8 │ JulianDate             74
   9 │ Dad                     0
  10 │ Mum                     0
  11 │ BroodNo                 0
  12 │ Year                    0
kept 1600 of 1950 rows on 484 broods
survived: 696 of 1600 (0.4350)
Class 3's file, for comparison: 1576 rows, 5 columns, no brood identifier</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>1600 chicks in 484 broods, once we keep the rows that have a survival, a
mass and a nest. Class 3 had 1576 rows and no way of knowing which of
them shared a mother. Count the nests properly before you model them,
exactly as Class 6 counted birds.</p></div>
<div id="per-brood" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>per_brood <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>BroodNo), nrow <span class="op">=&gt;</span> <span class="op">:</span>k)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ks <span class="op">=</span> <span class="fu">sort</span>(<span class="fu">unique</span>(per_brood.k))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> ks</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="pp">@printf</span>(<span class="st">"%3d broods with %d chick%s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">count</span>(<span class="op">==</span>(k), per_brood.k), k, k <span class="op">==</span> <span class="fl">1</span> ? <span class="st">""</span> <span class="op">:</span> <span class="st">"s"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>mean_k <span class="op">=</span> <span class="fu">mean</span>(per_brood.k)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">mean chicks per brood: %.4f</span><span class="sc">\n</span><span class="st">"</span>, mean_k)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># How much of a brood's fate is shared? Count the broods that went one way entirely.</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>by_brood <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>BroodNo), <span class="op">:</span>Survival <span class="op">=&gt;</span> mean <span class="op">=&gt;</span> <span class="op">:</span>p)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>n_all_died  <span class="op">=</span> <span class="fu">count</span>(by_brood.p <span class="op">.==</span> <span class="fl">0</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>n_all_lived <span class="op">=</span> <span class="fu">count</span>(by_brood.p <span class="op">.==</span> <span class="fl">1</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>n_mixed     <span class="op">=</span> <span class="fu">count</span>(<span class="fl">0</span> <span class="op">.&lt;</span> by_brood.p <span class="op">.&lt;</span> <span class="fl">1</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>n_unanimous <span class="op">=</span> n_all_died <span class="op">+</span> n_all_lived</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">broods where every chick died : %d</span><span class="sc">\n</span><span class="st">"</span>, n_all_died)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods where every chick lived: %d</span><span class="sc">\n</span><span class="st">"</span>, n_all_lived)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods that went both ways    : %d</span><span class="sc">\n</span><span class="st">"</span>, n_mixed)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="co"># "You would not see that many" is a claim, so compute it rather than assert it.</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># If every chick were an independent flip at the overall rate, a brood of k is</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="co"># unanimous with probability p^k + (1 - p)^k. Sum that over the broods this file has.</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>p_bar <span class="op">=</span> <span class="fu">mean</span>(chicks.Survival)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>exp_unanimous <span class="op">=</span> <span class="fu">sum</span>(p_bar<span class="op">^</span>k <span class="op">+</span> (<span class="fl">1</span> <span class="op">-</span> p_bar)<span class="op">^</span>k <span class="cf">for</span> k <span class="kw">in</span> per_brood.k)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">unanimous broods, observed                    : %d</span><span class="sc">\n</span><span class="st">"</span>, n_unanimous)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"expected under independent flips at p = %.4f : %.1f</span><span class="sc">\n</span><span class="st">"</span>, p_bar, exp_unanimous)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 35 broods with 1 chick
 86 broods with 2 chicks
133 broods with 3 chicks
159 broods with 4 chicks
 68 broods with 5 chicks
  3 broods with 6 chicks

mean chicks per brood: 3.3058

broods where every chick died : 179
broods where every chick lived: 91
broods that went both ways    : 214

unanimous broods, observed                    : 270
expected under independent flips at p = 0.4350 : 140.7</code></pre>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>More than half the broods went one way entirely.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>More than half, and that is the clustering staring at you out of the raw
counts before a model has been fitted. 270 of 484 broods had no
disagreement inside them at all, and independent coin flips at the
population rate would have given you about 141. Hold the number; it
comes back, and when it does it will be the best argument for a random
effect you have met.</p></div>
<div class="line"><span class="who momo">Momo</span><p>In Class 6 you made us predict what the grouping would do to the
standard error before fitting anything.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>And you are going to do it again, with Class 6’s rule, on this file.
Class 6’s rule is about the <strong>predictor</strong>, so ask where the
predictor varies.</p></div>
<div id="predict-the-se" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A Gaussian random-intercept model on mass itself splits mass's own variance into a</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># between-brood part and a within-brood part. That split is what Class 6's rule needs.</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>mass_fit   <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Mass2 <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> (<span class="fl">1</span><span class="op">|</span>BroodNo))), <span class="fu">Gaussian</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>sd_between <span class="op">=</span> <span class="fu">re_sd</span>(mass_fit)[<span class="op">:</span>BroodNo]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>sd_within  <span class="op">=</span> <span class="fu">first</span>(<span class="fu">sigma</span>(mass_fit))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>icc_mass   <span class="op">=</span> sd_between<span class="op">^</span><span class="fl">2</span> <span class="op">/</span> (sd_between<span class="op">^</span><span class="fl">2</span> <span class="op">+</span> sd_within<span class="op">^</span><span class="fl">2</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mass, between-brood SD : %.4f g</span><span class="sc">\n</span><span class="st">"</span>, sd_between)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mass, within-brood SD  : %.4f g</span><span class="sc">\n</span><span class="st">"</span>, sd_within)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mass is %.1f%% between broods and %.1f%% within them</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        <span class="fl">100</span> <span class="op">*</span> icc_mass, <span class="fl">100</span> <span class="op">*</span> (<span class="fl">1</span> <span class="op">-</span> icc_mass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>mass, between-brood SD : 0.7886 g
mass, within-brood SD  : 0.9104 g
mass is 42.9% between broods and 57.1% within them</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>Mostly within. In Class 6 tarsus was almost entirely <em>between</em>
birds, and the standard error was too small. Mass is the other way
round, so by that rule the standard error should not go up much.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is Class 6’s rule applied correctly, and that is its honest
prediction. Write it on the board. In twenty minutes the standard error
will have gone up sharply, and finding out what the rule does not cover
on a nonlinear link is worth more to you than a rule that was never
wrong.</p></div>
<h3 id="the-model-class-3-could-fit" class="anchored">The model Class 3 could fit</h3>
<div class="line"><span class="who itchy">Itchy</span><p>First, Class 3’s model, on Class 9’s file. Same family, same formula, no
grouping. I want the comparison to be like for like, so both fits get
the same 1600 chicks.</p></div>
<div id="cell-fit-glm" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>glm_fit <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2)), <span class="fu">Binomial</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>glm_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-glm" class="cell-output cell-output-display" data-execution_count="10">
<pre><code>Distributional regression fit (Binomial)
  nobs = 1600   logLik = -986.8062   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error         z   Pr(&gt;|z|)
  (Intercept)  -2.7570     0.1934  -14.2521  4.351e-46
  Mass2         0.6798     0.0504   13.4938    1.7e-41</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>One block, <code>mu</code>, and no σ table. That is Class 3 exactly.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>That is Class 3 exactly, and everything Class 3 told you about it is
still true. The link is still the logit, the variance is still decreed
to be p(1 − p), and for a nought-or-one response that decree is
arithmetic rather than a promise. Nothing about the <em>shape</em> is
wrong here. What is wrong is the sentence Class 3 warned you about and
could not repair.</p></div>
<h3 id="both-at-once" class="anchored">Both at once</h3>
<div class="line"><span class="who itchy">Itchy</span><p>One term. The same term as Class 6, in a call with a different family.</p></div>
<blockquote>
<p class="scene">logit(p_ij) = β0 + β1 x_ij + u_j, with u_j ~ N(0, σ_b²) and y_ij ~
Bernoulli(p_ij)</p>
</blockquote>
<div class="line"><span class="who itchy">Itchy</span><p>Chick <em>i</em> in brood <em>j</em>. Read it against Class 6’s line and
notice what moved. β0, β1 and u_j are the same three symbols doing the
same three jobs. The random effect is still normal, still centred on
zero, still summarised by one spread. Two things changed: there is a
<strong>link</strong> wrapped around the left-hand side, so the brood’s
nudge is a nudge in log-odds; and there is <strong>no σ</strong>,
because the family already spent it. Momo.</p></div>
<div class="line"><span class="who momo">Momo</span><p>So the random effect is on the log-odds scale and not on the scale of
anything I can see.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Not on the scale of anything you can see, and that is the price of the
hour. Write it down now, because in fifteen minutes I am going to hand
you a number that looks like a correlation and it will live on that
invisible scale too.</p></div>
<div id="cell-fit-glmm" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>glmm_fit <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2 <span class="op">+</span> (<span class="fl">1</span><span class="op">|</span>BroodNo))), <span class="fu">Binomial</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>glmm_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-glmm" class="cell-output cell-output-display" data-execution_count="11">
<pre><code>Distributional regression fit (Binomial)
  nobs = 1600   logLik = -903.2167   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error         z   Pr(&gt;|z|)
  (Intercept)  -3.9485     0.3327  -11.8697    1.7e-32
  Mass2         0.9399     0.0812   11.5690  5.917e-31

Random-effect SD (log σ_b):
  H0: coefficient = 0 on log σ_b
  NOT the σ_b = 0 boundary
            Coef.  Std.Error       z   Pr(&gt;|z|)
  BroodNo  0.6210     0.0874  7.1063  1.192e-12</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>Same verb, same box. And the block at the bottom is back, but the σ
table is still gone.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Both of those are the point. The random-effect block is Class 6’s second
variance component; the absent σ is Class 3’s decree. This is the first
fit in the book that carries both, and the heading on the new block is
the same warning it carried in Class 6. Read it, Momo.</p></div>
<div class="line"><span class="who momo">Momo</span><p>“NOT the σ_b = 0 boundary.”</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Same engine, same refusal, same reason, and Class 8 gave it its hour.
Now put the two fits side by side and watch which numbers move.</p></div>
<div id="side-by-side" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>b_glm,  b_glmm  <span class="op">=</span> <span class="fu">coef</span>(glm_fit, <span class="op">:</span>mu), <span class="fu">coef</span>(glmm_fit, <span class="op">:</span>mu)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>se_glm, se_glmm <span class="op">=</span> <span class="fu">stderror</span>(glm_fit)[<span class="fl">1</span><span class="op">:</span><span class="fl">2</span>], <span class="fu">stderror</span>(glmm_fit)[<span class="fl">1</span><span class="op">:</span><span class="fl">2</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-14s %12s %12s %12s</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">""</span>, <span class="st">"no brood"</span>, <span class="st">"with brood"</span>, <span class="st">"ratio"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-14s %12.4f %12.4f %12.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"beta0"</span>,     b_glm[<span class="fl">1</span>],  b_glmm[<span class="fl">1</span>],  b_glmm[<span class="fl">1</span>] <span class="op">/</span> b_glm[<span class="fl">1</span>])</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-14s %12.4f %12.4f %12.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"beta1"</span>,     b_glm[<span class="fl">2</span>],  b_glmm[<span class="fl">2</span>],  b_glmm[<span class="fl">2</span>] <span class="op">/</span> b_glm[<span class="fl">2</span>])</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-14s %12.4f %12.4f %12.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"SE(beta0)"</span>, se_glm[<span class="fl">1</span>], se_glmm[<span class="fl">1</span>], se_glmm[<span class="fl">1</span>] <span class="op">/</span> se_glm[<span class="fl">1</span>])</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"%-14s %12.4f %12.4f %12.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"SE(beta1)"</span>, se_glm[<span class="fl">2</span>], se_glmm[<span class="fl">2</span>], se_glmm[<span class="fl">2</span>] <span class="op">/</span> se_glm[<span class="fl">2</span>])</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">%-14s %12.2f %12.2f %12.2f</span><span class="sc">\n</span><span class="st">"</span>, <span class="st">"AIC"</span>, <span class="fu">aic</span>(glm_fit), <span class="fu">aic</span>(glmm_fit),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aic</span>(glmm_fit) <span class="op">-</span> <span class="fu">aic</span>(glm_fit))</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>se_ratio    <span class="op">=</span> se_glmm[<span class="fl">2</span>] <span class="op">/</span> se_glm[<span class="fl">2</span>]</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>slope_ratio <span class="op">=</span> b_glmm[<span class="fl">2</span>] <span class="op">/</span> b_glm[<span class="fl">2</span>];</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   no brood   with brood        ratio
beta0               -2.7570      -3.9485       1.4322
beta1                0.6798       0.9399       1.3827
SE(beta0)            0.1934       0.3327       1.7196
SE(beta1)            0.0504       0.0812       1.6128

AIC                 1977.61      1812.43      -165.18</code></pre>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The standard error went up by more than half.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>By a factor of 1.61, with Momo’s prediction on the board saying it
should not have. Hold that too; the reason is Jaro’s, in ten minutes.
And AIC fell by 165, which is not a close call by anybody’s rule of
thumb, so this is not a term you can argue your way out of on grounds of
parsimony.</p></div>
<div class="line"><span class="who toto">Toto</span><p>In Class 3 you told me <em>my</em> interval was too narrow.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>I did, and it was, and no number here is Class 3’s number: that fit was
on a different file, with 1576 rows and no brood column. What you have
is Class 3’s <strong>model</strong> refitted on Class 9’s chicks, which
is why both fits got the same 1600.</p></div>
<div class="line"><span class="who momo">Momo</span><p>In Class 6 the slope barely moved and only the standard error did. This
slope moved.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Momo has found the difference between Class 6 and today, and it is the
most important sentence of the hour, so Jaro gets ten minutes on it
after the variance component. Note the size for now: the coefficient is
a factor of 1.38 larger once broods are in the model. In a Gaussian
mixed model that essentially does not happen. In a GLMM it happens
<strong>every time</strong>, and it is not a bias, a bug or an
improvement.</p></div>
<h3 id="what-the-brood-variance-says" class="anchored">What the brood variance says</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Get the two pieces out and give them the scale they live on.</p></div>
<div id="variance-components" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sigma_b <span class="op">=</span> <span class="fu">re_sd</span>(glmm_fit)[<span class="op">:</span>BroodNo]   <span class="co"># brood SD, on the LOG-ODDS scale</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>V_brood <span class="op">=</span> sigma_b<span class="op">^</span><span class="fl">2</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>V_link  <span class="op">=</span> <span class="cn">pi</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="fl">3</span>                    <span class="co"># variance of a standard logistic distribution</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>icc <span class="op">=</span> V_brood <span class="op">/</span> (V_brood <span class="op">+</span> V_link)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"sigma_b, brood SD on the logit scale : %.4f</span><span class="sc">\n</span><span class="st">"</span>, sigma_b)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"brood variance                       : %.4f</span><span class="sc">\n</span><span class="st">"</span>, V_brood)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"logistic latent variance, pi^2 / 3   : %.4f</span><span class="sc">\n</span><span class="st">"</span>, V_link)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"latent-scale ICC                     : %.4f</span><span class="sc">\n</span><span class="st">"</span>, icc)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">vc(glmm_fit): "</span>, <span class="fu">vc</span>(glmm_fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma_b, brood SD on the logit scale : 1.8609
brood variance                       : 3.4628
logistic latent variance, pi^2 / 3   : 3.2899
latent-scale ICC                     : 0.5128

vc(glmm_fit): Dict(:BroodNo =&gt; [3.462767833538609;;])</code></pre>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>Where did π² over three come from? Nothing in the data has a π in it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Nothing in the data does, and that is exactly why the number needs a
label. Class 6 divided the between-bird variance by the between-bird
variance plus σ², and σ was a real spread in real millimetres. Here
there is no σ. The family spent it. So to get a ratio at all you have to
invent a denominator, and the standard move is to imagine a
<strong>latent</strong> continuous variable underneath the coin flip:
the chick has a hidden propensity, it survives if the propensity clears
a threshold, and a logit link is what you get when that hidden
propensity has a standard logistic distribution. A standard logistic
distribution has variance π²/3. That is the whole derivation, and
Nakagawa and Schielzeth (2010) work it through properly along with the
alternatives.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>I still cannot picture “hidden propensity” from a sentence.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Then stop trying to picture the coin flip and picture what is underneath
it. Same shape every time — a standard logistic curve, the one that gave
you π²/3 — just slid sideways by however far that brood’s own u_j pushes
it. Slide it far enough and the whole curve ends up on one side of the
line.</p></div>
<div id="cell-fig-latent-threshold" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>eta_bar <span class="op">=</span> <span class="fu">mean</span>(b_glmm[<span class="fl">1</span>] <span class="op">.+</span> b_glmm[<span class="fl">2</span>] <span class="op">.*</span> chicks.Mass2)   <span class="co"># an average chick, fixed part only</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mus      <span class="op">=</span> eta_bar <span class="op">.+</span> [<span class="op">-</span><span class="fl">1.5</span>, <span class="fl">0.0</span>, <span class="fl">1.5</span>] <span class="op">.*</span> sigma_b</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>labels_u <span class="op">=</span> [<span class="st">"1.5 σ_b below average"</span>, <span class="st">"an average brood"</span>, <span class="st">"1.5 σ_b above average"</span>]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>zgrid    <span class="op">=</span> <span class="fu">range</span>(<span class="fu">minimum</span>(mus) <span class="op">-</span> <span class="fl">5</span>, <span class="fu">maximum</span>(mus) <span class="op">+</span> <span class="fl">5</span>, length <span class="op">=</span> <span class="fl">400</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">680</span>, <span class="fl">380</span>))</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"latent propensity to survive (log-odds scale)"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    ylabel <span class="op">=</span> <span class="st">"density"</span>, title <span class="op">=</span> <span class="st">"a threshold on a hidden scale"</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">vlines!</span>(ax, [<span class="fl">0.0</span>]; color <span class="op">=</span> <span class="op">:</span>black, linestyle <span class="op">=</span> <span class="op">:</span>dash, linewidth <span class="op">=</span> <span class="fl">2</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"threshold: survives above, dies below"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (mu, lab) <span class="kw">in</span> <span class="fu">zip</span>(mus, labels_u)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    dens <span class="op">=</span> Distributions.<span class="fu">pdf</span>.(Distributions.<span class="fu">Logistic</span>(mu, <span class="fl">1.0</span>), zgrid)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lines!</span>(ax, zgrid, dens; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> lab)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div id="fig-latent-threshold" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-latent-threshold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk9-glmms_files/figure-html/fig-latent-threshold-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-latent-threshold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The logit link as a threshold on a hidden scale. Each curve is the same standard logistic density — one chick’s own luck, the assumed distribution behind π²/3 — centred at a different brood’s linear predictor: an average-mass chick in an average brood (middle), and the same chick in a brood pushed one and a half population standard deviations of σ_b to either side. A chick survives if its point on this scale clears the dashed threshold at zero, and the area of a curve to the right of that line is its brood’s survival probability. A random effect only slides the curve; it never changes its shape — which is why a brood pushed far enough ends up almost entirely on one side of the line, the mechanism behind the unanimous broods counted at the top of this chapter.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>So the number is a ratio of one thing we estimated to one thing we
assumed.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is a ratio of one thing we estimated to one thing the <strong>link
function</strong> assumed on your behalf, which is worse than assuming
it yourself, because you were not asked. Say it out loud every time:
<strong>latent-scale</strong>. About 51% of the variation in the latent
propensity to survive is differences between broods, and the rest is a
chick differing from its own siblings. Choose a <strong>probit</strong>
link instead — the same idea as logit, a threshold on a hidden
propensity, but built from the normal curve instead of the logistic one
— and the denominator becomes one rather than π²/3, and the number
changes without a single chick changing. It is a real quantity and it is
scale-bound, and a repeatability quoted without its scale is not a
repeatability, it is a rumour.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>Is there a version on the data scale?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>There is more than one, which is the honest answer and the reason I am
not computing one today. Nakagawa, Johnson and Schielzeth (2017) set out
the family of them and when each applies; the latent-scale one is the
one that is comparable across studies with the same link, and it is the
one to report first. What you may not do is compute the latent one and
describe it as “the proportion of variation in survival between broods”,
because survival is a nought or a one and its variation is not what you
just divided.</p></div>
<div class="line"><span class="who toto">Toto</span><p>And can I test whether broods differ at all?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You can ask, and the engine will answer and then take part of the answer
back. Watch.</p></div>
<div id="lrt" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The test, on its own, so that what the engine says comes back on its own too.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>lr  <span class="op">=</span> <span class="fu">lrtest</span>(glm_fit, glmm_fit)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>lrb <span class="op">=</span> <span class="fu">lrt_boundary</span>(glmm_fit, glm_fit; q <span class="op">=</span> <span class="fl">1</span>);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>┌ Warning: lrtest: `full` adds variance-component block(s) [:resd] that `reduced` lacks, so this compares a variance component against 0 — a BOUNDARY null. The reported χ²(1) p-value is INVALID there (conservative: too large, so the test loses power); the correct reference is a chi-bar-square mixture. Use `lrt_boundary(full, reduced; q = &lt;#components&gt;)` (or a parametric bootstrap) for a boundary-correct p-value.</code></pre>
</div>
</div>
<div id="lrt-read" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"lrtest        : chi2 = %.2f on %d df, p = %.3e</span><span class="sc">\n</span><span class="st">"</span>, lr.statistic, lr.dof, lr.pvalue)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"lrt_boundary  : chi2 = %.2f, q = %d, p = %.3e (naive p = %.3e)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>        lrb.statistic, lrb.q, lrb.pvalue, lrb.pvalue_naive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lrtest        : chi2 = 167.18 on 1 df, p = 3.057e-38
lrt_boundary  : chi2 = 167.18, q = 1, p = 1.529e-38 (naive p = 3.057e-38)</code></pre>
</div>
</div>
<div class="line"><span class="who momo">Momo</span><p>It warned us before it answered.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It warned you that the null you asked about sits on the edge of the
space the parameter lives in — a variance cannot be negative — so the
ordinary chi-squared reference is the wrong one, and it named the
function that uses the right one. Here the two p-values differ by a
factor of two and both are far past any threshold anybody uses, so the
correction changes nothing you would do. That is the <em>lucky</em>
case; Class 8 was the hour where the same correction is the difference
between a result and no result. Meanwhile: notice that the interesting
number is not the p-value at all. It is 0.51, and no p-value in this
chapter tells you that.</p></div>
<h3 id="jaros-ten-minutes-whose-odds-ratio-is-it" class="anchored">Jaro’s ten minutes: whose odds ratio is it?</h3>
<div class="line"><span class="who jaro">Jaro</span><p>May I have the slope back, please. Both slopes.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Take them.</p></div>
<div id="odds-ratios" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>or_glmm <span class="op">=</span> <span class="fu">exp</span>(b_glmm[<span class="fl">2</span>])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>or_glm  <span class="op">=</span> <span class="fu">exp</span>(b_glm[<span class="fl">2</span>])</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"GLMM slope  %.4f  -&gt;  odds ratio %.4f</span><span class="sc">\n</span><span class="st">"</span>, b_glmm[<span class="fl">2</span>], or_glmm)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"GLM  slope  %.4f  -&gt;  odds ratio %.4f</span><span class="sc">\n</span><span class="st">"</span>, b_glm[<span class="fl">2</span>],  or_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>GLMM slope  0.9399  -&gt;  odds ratio 2.5598
GLM  slope  0.6798  -&gt;  odds ratio 1.9734</code></pre>
</div>
</div>
<div class="line"><span class="who jaro">Jaro</span><p>Two odds ratios, both correct, and they answer different questions. The
mixed one says: take <strong>one brood</strong>, hand it a chick a gram
heavier, and that chick’s odds of surviving are multiplied by 2.56. It
is a statement about a comparison <em>inside</em> a nest, with the nest
held where it is. That is a <strong>conditional</strong> odds ratio.</p></div>
<div class="line"><span class="who toto">Toto</span><p>And the other one?</p></div>
<div class="line"><span class="who jaro">Jaro</span><p>The other one is closer to a statement about the population as a whole:
take all the chicks at one mass and all the chicks at a mass one gram
higher, average over whatever nests they happen to be in, and compare.
That is a <strong>marginal</strong> odds ratio, and it is smaller. It is
always smaller on a <strong>logit</strong> link, and the same holds for
probit and <strong>complementary log-log</strong> — a third link, built
from a lopsided curve rather than the symmetric ones logit and probit
use. The effect has a name: non-collapsibility.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>Any nonlinear link, then.</p></div>
<div class="line"><span class="who jaro">Jaro</span><p>No — and I am glad you said it, because that is the sentence people get
wrong. The <strong>log</strong> link, the one this book taught you in
Classes 3 to 5, is collapsible for the rate ratio. Write the Poisson
mean out: E[Y | x, u] = exp(β0 + β1 x + u). Averaging over u multiplies
the whole thing by one constant, which moves the
<strong>intercept</strong> and leaves β1 exactly where it was. So
“nonlinear” is not the criterion. Logit is.</p></div>
<div class="line"><span class="who momo">Momo</span><p>Always smaller. Prove it rather than saying it.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>We will not prove it, we will make the model prove it, which is this
book’s method. The fit believes a distribution of broods. Draw broods
from it, draw chicks in those broods, fit the model that ignores broods,
and see what that model recovers.</p></div>
<div id="marginal-by-simulation" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logistic</span>(z) <span class="op">=</span> <span class="fl">1</span> <span class="op">/</span> (<span class="fl">1</span> <span class="op">+</span> <span class="fu">exp</span>(<span class="op">-</span>z))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>bidx       <span class="op">=</span> <span class="fu">Dict</span>(bn <span class="op">=&gt;</span> i <span class="cf">for</span> (i, bn) <span class="kw">in</span> <span class="fu">enumerate</span>(broods))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>row_brood  <span class="op">=</span> [bidx[bn] for bn <span class="kw">in</span> chicks.BroodNo]</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>eta_fixed  <span class="op">=</span> b_glmm[<span class="fl">1</span>] <span class="op">.+</span> b_glmm[<span class="fl">2</span>] <span class="op">.*</span> chicks.Mass2   <span class="co"># the fixed part, u = 0</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># One replicate: draw a brood effect for every brood, flip every chick's coin at</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># its own probability, then fit the model that pretends broods do not exist.</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>rng_marg <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>marg_slopes <span class="op">=</span> <span class="dt">Float64</span>[]</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">1000</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    u <span class="op">=</span> sigma_b <span class="op">.*</span> <span class="fu">randn</span>(rng_marg, J)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> <span class="fu">logistic</span>.(eta_fixed <span class="op">.+</span> u[row_brood])</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="fu">Int</span>.(<span class="fu">rand</span>(rng_marg, n) <span class="op">.&lt;</span> p)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    naive <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2)), <span class="fu">Binomial</span>();</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>                data <span class="op">=</span> <span class="fu">DataFrame</span>(Survival <span class="op">=</span> y, Mass2 <span class="op">=</span> chicks.Mass2))</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">push!</span>(marg_slopes, <span class="fu">coef</span>(naive, <span class="op">:</span>mu)[<span class="fl">2</span>])</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="cf">end</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>marg_slope  <span class="op">=</span> <span class="fu">mean</span>(marg_slopes)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>marg_mcse   <span class="op">=</span> <span class="fu">std</span>(marg_slopes) <span class="op">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(marg_slopes))</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>attenuation <span class="op">=</span> marg_slope <span class="op">/</span> b_glmm[<span class="fl">2</span>]</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="co"># The SPREAD of those slopes is the naive estimator's true sampling SD -- the only</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="co"># ruler that measures the naive interval against the target the naive fit is aiming at.</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>se_true     <span class="op">=</span> <span class="fu">std</span>(marg_slopes)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>naive_short <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> se_glm[<span class="fl">2</span>] <span class="op">/</span> se_true</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>gap_in_se   <span class="op">=</span> (b_glm[<span class="fl">2</span>] <span class="op">-</span> marg_slope) <span class="op">/</span> se_true</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"conditional slope (the GLMM)          : %.4f   OR %.4f</span><span class="sc">\n</span><span class="st">"</span>, b_glmm[<span class="fl">2</span>], or_glmm)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"marginal slope, %d simulated worlds : %.4f   OR %.4f   MC SE %.4f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>        <span class="fu">length</span>(marg_slopes), marg_slope, <span class="fu">exp</span>(marg_slope), marg_mcse)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"what the real naive fit gave          : %.4f   OR %.4f</span><span class="sc">\n</span><span class="st">"</span>, b_glm[<span class="fl">2</span>], or_glm)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">attenuation, marginal / conditional   : %.4f</span><span class="sc">\n</span><span class="st">"</span>, attenuation)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"naive slope, the SE it printed        : %.4f</span><span class="sc">\n</span><span class="st">"</span>, se_glm[<span class="fl">2</span>])</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"naive slope, its TRUE sampling SD     : %.4f  -&gt; what it printed is %.1f%% too small</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>        se_true, <span class="fl">100</span> <span class="op">*</span> naive_short)</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"real naive fit minus simulated mean, in units of that true SD: %.2f</span><span class="sc">\n</span><span class="st">"</span>, gap_in_se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>conditional slope (the GLMM)          : 0.9399   OR 2.5598
marginal slope, 1000 simulated worlds : 0.6073   OR 1.8355   MC SE 0.0018
what the real naive fit gave          : 0.6798   OR 1.9734

attenuation, marginal / conditional   : 0.6461
naive slope, the SE it printed        : 0.0504
naive slope, its TRUE sampling SD     : 0.0574  -&gt; what it printed is 12.2% too small
real naive fit minus simulated mean, in units of that true SD: 1.26</code></pre>
</div>
</div>
<div class="line"><span class="who jaro">Jaro</span><p>There it is, and it did not need a theorem. Averaging over broods keeps
65% of the conditional slope and throws the rest away. And look at the
third line: the slope the fixed-effects fit got on the real chicks sits
1.26 standard deviations from what the mixed model predicts that
estimator would give. That is inside noise. <strong>The naive fit was
not estimating the wrong thing badly. It was estimating a different
thing, roughly correctly, with a standard error that was wrong for
either.</strong></p></div>
<div class="line"><span class="who momo">Momo</span><p>You measured that gap against the last line and not against the standard
error the fit printed.</p></div>
<div class="line"><span class="who jaro">Jaro</span><p>Because the standard error the fit printed is the thing under
investigation, and a suspect ruler cannot check itself. The simulation
has handed you the honest one: 0.0574, against the 0.0504 the fit
reported.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So the fixed-effects coefficient was not a mistake.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The <em>coefficient</em> was a defensible marginal estimate. The
<em>interval</em> was a fiction. Those are separable and you must keep
them separate, because the fix for the second is not the fix for the
first. And now Momo’s prediction on the board can be read properly. The
standard error went up by a factor of 1.61, and that is two things at
once: the coefficient changed size, because the mixed model’s slope is
conditional and the naive one is marginal, so its standard error changed
size with it; and siblings were being treated as strangers, which is the
part Class 6’s rule covers — measured against its own target, the naive
standard error is short by 12.2%, modest, exactly as a predictor that
varies mostly <em>within</em> broods would lead you to expect. Momo’s
rule was right about the part it covers. On a nonlinear link there is a
second part, and it is usually the larger one. Draw the two curves and
the distinction stops being a word.</p></div>
<div id="cell-fig-two-curves" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mass_grid <span class="op">=</span> <span class="fu">range</span>(<span class="fu">minimum</span>(chicks.Mass2), <span class="fu">maximum</span>(chicks.Mass2), length <span class="op">=</span> <span class="fl">120</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Conditional: a brood sitting exactly at the population average, u = 0.</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>p_cond <span class="op">=</span> <span class="fu">logistic</span>.(b_glmm[<span class="fl">1</span>] <span class="op">.+</span> b_glmm[<span class="fl">2</span>] <span class="op">.*</span> mass_grid)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Marginal: average the CURVE over the distribution of broods the fit believes.</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>rng_curve <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">31415</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>u_draw <span class="op">=</span> sigma_b <span class="op">.*</span> <span class="fu">randn</span>(rng_curve, <span class="fl">20_000</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>p_marg <span class="op">=</span> [<span class="fu">mean</span>(<span class="fu">logistic</span>.(b_glmm[<span class="fl">1</span>] <span class="op">+</span> b_glmm[<span class="fl">2</span>] <span class="op">*</span> m <span class="op">.+</span> u_draw)) for m <span class="kw">in</span> mass_grid]</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>rng_jit <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">77</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>jit <span class="op">=</span> <span class="fl">0.03</span> <span class="op">.*</span> <span class="fu">randn</span>(rng_jit, n)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> <span class="fu">Figure</span>(size <span class="op">=</span> (<span class="fl">680</span>, <span class="fl">380</span>))</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> <span class="fu">Axis</span>(fig[<span class="fl">1</span>, <span class="fl">1</span>]; xlabel <span class="op">=</span> <span class="st">"mass at day 2 (g)"</span>, ylabel <span class="op">=</span> <span class="st">"probability of surviving"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> <span class="st">"one fit, two curves"</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="fu">hlines!</span>(ax, [<span class="fl">0.0</span>, <span class="fl">1.0</span>]; color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.5</span>), linestyle <span class="op">=</span> <span class="op">:</span>dot)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter!</span>(ax, chicks.Mass2, chicks.Survival <span class="op">.+</span> jit; markersize <span class="op">=</span> <span class="fl">3</span>, color <span class="op">=</span> (<span class="op">:</span>grey, <span class="fl">0.3</span>))</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, mass_grid, p_cond; linewidth <span class="op">=</span> <span class="fl">2.5</span>, label <span class="op">=</span> <span class="st">"one average brood (u = 0)"</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="fu">lines!</span>(ax, mass_grid, p_marg; linewidth <span class="op">=</span> <span class="fl">2.5</span>, linestyle <span class="op">=</span> <span class="op">:</span>dash,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> <span class="st">"averaged over broods"</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="fu">Legend</span>(fig[<span class="fl">1</span>, <span class="fl">2</span>], ax; framevisible <span class="op">=</span> <span class="cn">false</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>fig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<div id="fig-two-curves" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-two-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk9-glmms_files/figure-html/fig-two-curves-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-curves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Chick survival, jittered, with two logistic curves from the same GLMM: solid for one average brood sitting at the population mean, dashed for the curve averaged over the fit’s own distribution of broods. The dashed curve is flatter everywhere and never gets as close to either edge, because averaging steep curves shifted sideways from one another smooths out the steepness any one brood has.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who eddie">Eddie</span><p>The dashed one is flatter.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Flatter everywhere, and it never gets as close to either edge. Averaging
a set of steep curves that are shifted sideways from one another gives
you a shallow curve, because at any mass some broods are already nearly
all dead and some are nearly all alive, and neither of those is moving
much. <strong>Both lines come from the same fit and neither is a
compromise.</strong> Ask which one your sentence needs. “A gram of mass
multiplies a chick’s odds of surviving within its nest” wants the solid
line. “Heavier chicks in this population survive at a rate of” wants the
dashed one.</p></div>
<h3 id="the-second-grouping-and-why-it-is-not-year" class="anchored">The second grouping, and why it is not Year</h3>
<div class="line"><span class="who momo">Momo</span><p>The file has a <code>Year</code> column. Chicks in one year share a
summer as much as chicks in one nest share a mother.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>They do, and that instinct is right, and the file will not let you act
on it. Look at the <em>design</em> before you look at a fit.</p></div>
<div id="cell-year-check" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>spanning <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>BroodNo), <span class="op">:</span>Year <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>nyear)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>n_years  <span class="op">=</span> <span class="fu">length</span>(<span class="fu">unique</span>(chicks.Year))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>n_mums   <span class="op">=</span> <span class="fu">length</span>(<span class="fu">unique</span>(chicks.Mum))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods appearing in more than one year : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">count</span>(spanning.nyear <span class="op">.&gt;</span> <span class="fl">1</span>), J)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"distinct years                         : %d</span><span class="sc">\n</span><span class="st">"</span>, n_years)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"distinct mothers                       : %d</span><span class="sc">\n</span><span class="st">"</span>, n_mums)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the same test to the OTHER candidate grouping, which is the one set as homework.</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>mums_per_brood <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>BroodNo), <span class="op">:</span>Mum <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>nmum)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>broods_per_mum <span class="op">=</span> <span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>Mum), <span class="op">:</span>BroodNo <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>nb)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>n_split_broods <span class="op">=</span> <span class="fu">count</span>(mums_per_brood.nmum <span class="op">.&gt;</span> <span class="fl">1</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods carrying more than one Mum      : %d of %d</span><span class="sc">\n</span><span class="st">"</span>, n_split_broods, J)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"broods per mother                      : %d to %d, median %.0f</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">minimum</span>(broods_per_mum.nb), <span class="fu">maximum</span>(broods_per_mum.nb), <span class="fu">median</span>(broods_per_mum.nb))</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="fu">println</span>()</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="fu">combine</span>(<span class="fu">groupby</span>(chicks, <span class="op">:</span>Year),</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>        nrow <span class="op">=&gt;</span> <span class="op">:</span>chicks,</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>        <span class="op">:</span>BroodNo <span class="op">=&gt;</span> (x <span class="op">-&gt;</span> <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="op">=&gt;</span> <span class="op">:</span>broods,</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>        <span class="op">:</span>Survival <span class="op">=&gt;</span> mean <span class="op">=&gt;</span> <span class="op">:</span>survived)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>broods appearing in more than one year : 0 of 484
distinct years                         : 4
distinct mothers                       : 126
broods carrying more than one Mum      : 184 of 484
broods per mother                      : 1 to 17, median 4
</code></pre>
</div>
<div id="year-check" class="cell-output cell-output-display" data-execution_count="25">
<div><div style="float: left;"><span>4×4 DataFrame</span></div><div style="clear: both;"></div></div><div class="data-frame" style="overflow-x: scroll;">
<table class="data-frame caption-top" data-quarto-postprocess="true" style="margin-bottom: 6px;">
<thead>
<tr class="columnLabelRow header">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;">Row</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Year</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">chicks</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">broods</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">survived</th>
</tr>
<tr class="columnLabelRow even">
<th class="stubheadLabel" data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold;"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Int64">Int64</th>
<th style="text-align: left;" data-quarto-table-cell-role="th" title="Float64">Float64</th>
</tr>
</thead>
<tbody>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">1</td>
<td style="text-align: right;">2003</td>
<td style="text-align: right;">213</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0.633803</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">2</td>
<td style="text-align: right;">2004</td>
<td style="text-align: right;">538</td>
<td style="text-align: right;">168</td>
<td style="text-align: right;">0.340149</td>
</tr>
<tr class="dataRow odd">
<td class="rowLabel" style="text-align: right; font-weight: bold;">3</td>
<td style="text-align: right;">2005</td>
<td style="text-align: right;">612</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">0.433007</td>
</tr>
<tr class="dataRow even">
<td class="rowLabel" style="text-align: right; font-weight: bold;">4</td>
<td style="text-align: right;">2006</td>
<td style="text-align: right;">237</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">0.476793</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Read the first line. <strong>No brood appears in two years</strong>, so
<code>BroodNo</code> is not <em>crossed</em> with <code>Year</code>, it
is <strong>nested inside</strong> it. A crossed design is one where the
same brood turns up in several years and the same year holds several
broods; you have half of that and only half. And read the second line: 4
years. Eddie, you have fitted things.</p></div>
<div class="line"><span class="who eddie">Eddie</span><p>You cannot estimate the spread of four numbers.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>You cannot usefully estimate the spread of 4 numbers, no. Software will
often fit it and print a standard deviation, and the standard deviation
of four draws is not a quantity you would report. Bolker et al.&nbsp;(2009)
put a working floor at around five or six levels and say plainly what to
do below it: put the factor in the mean model as a fixed effect and stop
pretending you are estimating a distribution. So do that.</p></div>
<div id="cell-fit-year-fixed" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>chicks.YearF <span class="op">=</span> <span class="fu">string</span>.(chicks.Year)   <span class="co"># a factor must be text, or the formula treats it as a number</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>year_fixed <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2 <span class="op">+</span> YearF <span class="op">+</span> (<span class="fl">1</span><span class="op">|</span>BroodNo))), <span class="fu">Binomial</span>(); data <span class="op">=</span> chicks)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>year_fixed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-year-fixed" class="cell-output cell-output-display" data-execution_count="27">
<pre><code>Distributional regression fit (Binomial)
  nobs = 1600   logLik = -890.2099   converged = true

Mean model (μ):
  H0: coefficient = 0
                 Coef.  Std.Error        z   Pr(&gt;|z|)
  (Intercept)  -2.8936     0.4269  -6.7776  1.222e-11
  Mass2         0.9308     0.0807  11.5304  9.276e-31
  YearF: 2004  -1.6270     0.3589  -4.5335  5.801e-06
  YearF: 2005  -1.0196     0.3507  -2.9073   0.003646
  YearF: 2006  -0.4504     0.4112  -1.0954     0.2733

Random-effect SD (log σ_b):
  H0: coefficient = 0 on log σ_b
  NOT the σ_b = 0 boundary
            Coef.  Std.Error       z  Pr(&gt;|z|)
  BroodNo  0.5646     0.0904  6.2435  4.28e-10</code></pre>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Three more rows in the <code>mu</code> table, one per year beyond the
first, and nobody had to estimate a distribution from four points. If
you want a second <em>random</em> grouping in this file, there is a
candidate with 126 levels in the <code>Mum</code> column — and two
things stand between you and it. One is the engine: it cannot yet fit a
second grouping beside the brood on a binomial response, and <a href="appendix-b-engine.html">Where the engine stops</a> records that.
The other is the design, which comes first whatever the engine can do.
184 of the 484 broods carry more than one mother, and a mother holds up
to 17 broods. So <code>Mum</code> is not nested above
<code>BroodNo</code> and it is not cleanly crossed with it either: it is
<strong>partially crossed</strong>, and the honest answer to “which is
it” is that neither word fits. That is question six.</p></div>
<h3 id="what-a-random-effect-is-when-you-cannot-see-it" class="anchored">What a random effect is, when you cannot see it</h3>
<div class="line"><span class="who eddie">Eddie</span><p>In Class 6 you answered “what is a random intercept” with the shrinkage
picture. Do it again here.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Not today: the engine does not yet return the per-brood effects for a
binomial fit, so there is no caterpillar to draw (<a href="appendix-b-engine.html">Where the engine stops</a>). But the
picture would be Class 6’s picture, every diamond closer to zero than
its circle, and the thing Class 6 could not show you needs no picture.
It needs the number I told you to hold. On 270 of these 484 broods every
chick died or every chick lived. Toto, what does a fixed effect for one
of those broods look like?</p></div>
<div class="line"><span class="who toto">Toto</span><p>Very negative, or very positive.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Not very. <strong>Infinite.</strong> A nest whose chicks all died has a
likelihood that keeps climbing as that nest’s own effect goes to minus
infinity: there is no best value, only “further”. A model with a fixed
effect per brood has no finite estimate for more than half the nests in
this file. Now, what did the mixed model give those broods?</p></div>
<div class="line"><span class="who toto">Toto</span><p>Something finite, because they are in the fit.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Something finite, and something <em>different</em> for each of them,
because the population pulls every brood back towards zero and pulls a
unanimous nest of one harder than a unanimous nest of five. That is not
a technicality; it is the strongest argument for random effects anybody
will ever show you. Class 6 said a random intercept is the decision to
treat groups as draws from one population. Today that decision is the
difference between an estimate and no estimate at all.</p></div>
<div class="line"><span class="who momo">Momo</span><p>And is it right, or merely finite?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>It is right in the sense that it is the value the model considers most
likely for that nest, given everything the model believes. Whether the
<em>model</em> is right is the next section.</p></div>
<h3 id="is-the-model-any-good" class="anchored">Is the model any good?</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Quantile residuals, as in Class 3, with a seed, as in Class 3. And then
a trap that Class 3 did not have.</p></div>
<div id="cell-fig-diagnostic" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>qres <span class="op">=</span> <span class="fu">residuals</span>(glmm_fit; <span class="kw">type</span> <span class="op">=</span> <span class="op">:</span>quantile, rng <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">909</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"quantile residuals: mean %.4f, SD %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(qres), <span class="fu">std</span>(qres))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_diagnostic</span>(qres; title <span class="op">=</span> <span class="st">"GLMM, randomised quantile residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>quantile residuals: mean 0.0916, SD 1.0538</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div id="fig-diagnostic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk9-glmms_files/figure-html/fig-diagnostic-output-2.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Worm plot of the GLMM’s randomised quantile residuals, at randomisation seed 909, judged against a brood sitting at the population average. The body of the worm sits above the identity line while both tails dip back below it, and the spread printed above the plot is above one.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who toto">Toto</span><p>The spread is above one.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Above one — compared with what? A quantile residual is standard normal
when each observation is compared with <strong>its own</strong> correct
distribution, and for a chick that means its own probability of
surviving. So before you read the spread as a verdict, ask which
probability each chick was judged against. Class 6 made you ask exactly
this about a residual, and the answer was marginal-or-conditional. Same
question, one level harder.</p></div>
<div id="qres-reference" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A randomised quantile residual for a 0/1 response is Phi^-1 of</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   u = 1 - p + p*U   if y = 1,      u = (1 - p)*U   if y = 0,   U ~ Uniform(0,1).</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The only free choice is WHICH p. Reproduce the engine first, so the recipe is verified.</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">Phi_inv</span>(u) <span class="op">=</span> Distributions.<span class="fu">quantile</span>(Distributions.<span class="fu">Normal</span>(), u)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">qresid</span>(y, p, rng)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    U <span class="op">=</span> <span class="fu">rand</span>(rng, <span class="fu">length</span>(p))</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    pit <span class="op">=</span> [yi <span class="op">==</span> <span class="fl">1</span> ? (<span class="fl">1</span> <span class="op">-</span> pi_) <span class="op">+</span> pi_ <span class="op">*</span> ui <span class="op">:</span> (<span class="fl">1</span> <span class="op">-</span> pi_) <span class="op">*</span> ui</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>           for (yi, pi_, ui) <span class="kw">in</span> <span class="fu">zip</span>(y, p, U)]</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">Phi_inv</span>.(<span class="fu">clamp</span>.(pit, <span class="fl">1e-12</span>, <span class="fl">1</span> <span class="op">-</span> <span class="fl">1e-12</span>))</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>p_cond_row <span class="op">=</span> <span class="fu">fitted</span>(glmm_fit)                                    <span class="co"># u = 0: a typical brood</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>p_marg_row <span class="op">=</span> [<span class="fu">mean</span>(<span class="fu">logistic</span>.(<span class="cn">e</span> <span class="op">.+</span> u_draw)) for <span class="cn">e</span> <span class="kw">in</span> eta_fixed]   <span class="co"># averaged over broods</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>r_cond <span class="op">=</span> <span class="fu">qresid</span>(chicks.Survival, p_cond_row, <span class="fu">MersenneTwister</span>(<span class="fl">909</span>))</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>r_marg <span class="op">=</span> <span class="fu">qresid</span>(chicks.Survival, p_marg_row, <span class="fu">MersenneTwister</span>(<span class="fl">909</span>))</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"engine                      : SD %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(qres))</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"by hand, p from fitted()    : SD %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_cond))</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"by hand, p averaged over u  : SD %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">std</span>(r_marg))</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">mean fitted probability, u = 0 : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(p_cond_row))</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"mean probability over broods   : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(p_marg_row))</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"chicks that actually survived  : %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">mean</span>(chicks.Survival))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>engine                      : SD 1.0538
by hand, p from fitted()    : SD 1.0538
by hand, p averaged over u  : SD 1.0144

mean fitted probability, u = 0 : 0.3907
mean probability over broods   : 0.4236
chicks that actually survived  : 0.4350</code></pre>
</div>
</div>
<div id="cell-fig-diagnostic-marginal" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fig_diagnostic</span>(r_marg; title <span class="op">=</span> <span class="st">"same chicks, marginal reference"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div id="fig-diagnostic-marginal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-diagnostic-marginal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wk9-glmms_files/figure-html/fig-diagnostic-marginal-output-1.svg" class="img-fluid">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-marginal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The same chicks’ quantile residuals, recomputed against probabilities averaged over the fit’s own distribution of broods instead of a single average brood. The body of the worm now lies close to the identity line, though both tails still dip below it, and its spread, printed above, is close to one: the first plot’s excess was the reference probability, not the model.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="line"><span class="who itchy">Itchy</span><p>Line two reproduces line one exactly, so the recipe is not a guess. Line
three changes one thing — the probability each chick is judged against
is averaged over the broods the model believes in, instead of being the
probability for a brood sitting at the average — and the spread comes
down from 1.054 to 1.014. Look at the second worm plot and then at the
first. Momo, say what that means.</p></div>
<div class="line"><span class="who momo">Momo</span><p>The residuals were not too wide. The yardstick was too narrow.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The yardstick was the wrong one, which is a different diagnosis with a
different action. <code>fitted</code> sets every brood’s own effect to
zero. In Class 6 that was the same as averaging over birds, because the
model was a straight line and the average of a straight line is the line
at the average. Here there is a link function in the way, and a brood
set to zero is <em>not</em> the average over broods: read the three
probabilities at the bottom of the cell. A chick is not, on average, a
chick from an average brood.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So is the model good or not?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>What you may write is what this shows: against the reference the model
itself implies, the per-chick residuals land about where a correct model
would put them. Two cautions, both cheap. That spread is one draw of a
randomisation, so report the seed, as Class 5 taught you. And this check
looks at each chick’s residual <strong>on its own</strong>, and the
thing we spent the hour on is that chicks in a nest are not on their
own; a per-observation check cannot see a correlation it has already
averaged out. How to simulate what a model predicts for its own
diagnostic, and how many draws that honestly takes, is <a href="appendix-a-simulation.html">Appendix A</a>’s subject, not this
hour’s.</p></div>
<h3 id="one-box-and-it-is-earned" class="anchored">One box, and it is earned</h3>
<div class="line"><span class="who itchy">Itchy</span><p>Last thing, and it is the reason Momo will get an email from a
collaborator. Somebody will fit this in R, and they will get a different
brood standard deviation from ours. A GLMM’s likelihood contains an
integral, one per brood, over that brood’s unobserved effect, and for a
binomial response it has no closed form; every package approximates it,
and the printed variance component depends on which approximation. Ours
spreads a fixed grid of thirty-two points around zero and adds up. That
is not the only rule in the room.</p></div>
<blockquote>
<p class="scene">↔︎ TRANSLATE: the same GLMM in R, and a disagreement that is not about R</p>
<p><strong>Three</strong> rules meet on this page:</p>
<ul>
<li><strong>Laplace</strong> — one quadratic approximation at the mode. Fast, and the default in both <code>lme4::glmer</code> (<code>nAGQ = 1</code>) and <code>drmTMB</code>.</li>
<li><strong>Non-adaptive Gauss–Hermite</strong> — a fixed grid of thirty-two nodes centred at <strong>zero</strong>, the expected value of the random effect. This is our engine’s binomial <code>(1|g)</code> path, and it produced every Julia number in this chapter; the appendix <a href="appendix-b-engine.html">Where the engine stops</a> records what it does and does not offer.</li>
<li><strong>Adaptive Gauss–Hermite</strong> — the same quadrature, but re-centred and re-scaled at each group’s <strong>conditional mode</strong>, the value of that group’s own effect the model finds most likely. <code>glmer</code> with <code>nAGQ &gt; 1</code>. Pinheiro and Bates (1995) is where the rules are compared.</li>
</ul>
<p>Read the four blocks below against the Julia output above. Laplace and one-point quadrature give the same brood SD, well away from the other two. Our number and <code>nAGQ = 25</code> are <strong>two different approximations that agree</strong>, not one integral computed twice. And read <code>nAGQ = 9</code> against <code>nAGQ = 25</code>: the log-likelihood at nine is slightly <strong>higher</strong>, and twenty-five is the converged one. Quadrature error is not signed, so “higher log-likelihood means closer to the integral” is not a rule; the evidence that you have arrived is that two different rules agree and that pushing one of them further stops moving it. Name the approximation with the number.</p>
<p>The R block below was run once by hand, on the date shown: all four blocks come from one <code>Rscript</code> run on 2026-09-07 against the same archived file this chapter reads, and none of it re-runs when the page is built. The script is kept at <code>data/ch9/ch9-r-box.R</code>.</p>
</blockquote>
<div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run once by hand on 2026-09-07; this block does not re-run when the page is built.</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># All four blocks produced together by a single run of:</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   Rscript data/ch9/ch9-r-box.R</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   R 4.6.0, drmTMB 0.7.0, lme4 2.0.1, reading data/2012/SparrowSurvival.csv and</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   dropping rows missing Survival, Mass2 or BroodNo (1600 rows, 484 broods)</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span> <span class="fu">drmTMB</span> (Laplace) <span class="sc">---</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                 estimate std_error</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span>(Intercept) <span class="sc">-</span><span class="fl">3.9153478</span> <span class="fl">0.3263290</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>mu<span class="sc">:</span>Mass2        <span class="fl">0.9341965</span> <span class="fl">0.0797836</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>                    estimate std_error</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>sd<span class="sc">:</span>mu<span class="sc">:</span>(<span class="dv">1</span> <span class="sc">|</span> BroodNo)  <span class="fl">1.70008</span> <span class="fl">0.1509664</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>logLik<span class="sc">:</span> <span class="sc">-</span><span class="fl">912.4</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span> lme4<span class="sc">::</span>glmer, nAGQ <span class="ot">=</span> <span class="dv">1</span> (Laplace, the default) <span class="sc">---</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error  z value</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>(Intercept)  <span class="sc">-</span><span class="fl">3.9152</span>     <span class="fl">0.3262</span> <span class="sc">-</span><span class="fl">12.0028</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>Mass2         <span class="fl">0.9342</span>     <span class="fl">0.0798</span>  <span class="fl">11.7127</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  brood SD <span class="ot">=</span> <span class="fl">1.700013</span>   logLik <span class="ot">=</span> <span class="sc">-</span><span class="fl">912.3729611</span>   AIC <span class="ot">=</span> <span class="fl">1830.745922</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span> lme4<span class="sc">::</span>glmer, nAGQ <span class="ot">=</span> <span class="dv">9</span> (adaptive GHQ) <span class="sc">---</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error  z value</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>(Intercept)  <span class="sc">-</span><span class="fl">3.9493</span>     <span class="fl">0.3328</span> <span class="sc">-</span><span class="fl">11.8670</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>Mass2         <span class="fl">0.9401</span>     <span class="fl">0.0813</span>  <span class="fl">11.5671</span></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>  brood SD <span class="ot">=</span> <span class="fl">1.861659</span>   logLik <span class="ot">=</span> <span class="sc">-</span><span class="fl">903.2083452</span>   AIC <span class="ot">=</span> <span class="fl">1812.41669</span></span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span> lme4<span class="sc">::</span>glmer, nAGQ <span class="ot">=</span> <span class="dv">25</span> (adaptive GHQ) <span class="sc">---</span></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>            Estimate Std. Error  z value</span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>(Intercept)  <span class="sc">-</span><span class="fl">3.9485</span>     <span class="fl">0.3326</span> <span class="sc">-</span><span class="fl">11.8704</span></span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>Mass2         <span class="fl">0.9399</span>     <span class="fl">0.0812</span>  <span class="fl">11.5691</span></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>  brood SD <span class="ot">=</span> <span class="fl">1.860915</span>   logLik <span class="ot">=</span> <span class="sc">-</span><span class="fl">903.2165109</span>   AIC <span class="ot">=</span> <span class="fl">1812.433022</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="line"><span class="who momo">Momo</span><p>The last block is our fit.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>The last block <strong>agrees with</strong> our fit, to four decimals on
the brood standard deviation and on both slopes, and to two on the AIC.
It is not our fit: ours prints a log-likelihood of -903.2167 and that
block prints <code>-903.2165109</code>. Two rules, four decimals of
agreement, and no further.</p></div>
<div class="line"><span class="who toto">Toto</span><p>And the first two blocks?</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Also correct, and they are <code>glmer</code>’s default and
<code>drmTMB</code>’s default, and neither of them asked you. Toto, what
is the size of the thing that was hiding in a default?</p></div>
<div class="line"><span class="who toto">Toto</span><p>The brood standard deviation.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Which is the number the whole hour was about, and the numerator of the
intraclass correlation, and the thing you were going to call
repeatability in a paper. Laplace says <code>1.700</code>, from the box.
The other two say 1.8609 — ours, computed above — and
<code>glmer</code>’s <code>1.860915</code>, from the box. That is not a
rounding difference and it is not a language difference — it is how much
arithmetic each package spent on the same integral, chosen for you at
install time. <strong>This is Class 8 with a different
mechanism.</strong> There the default you never chose was ML against
REML. Here it is which approximation your package picked. Same sentence
fixes both: name it, in the methods, with the number.</p></div>
<div class="line"><span class="who toto">Toto</span><p>So today’s summary is: use a GLMM.</p></div>
<div class="line"><span class="who itchy">Itchy</span><p>Today’s summary is that “GLMM” is two decisions wearing one word, that
the coefficient it gives you answers a narrower question than the one it
replaced, and that everything Class 6 taught about groups is still true
on a scale you cannot see.</p></div>
<hr>
<h2 id="summary" class="anchored">Summary</h2>
<h3 id="stats-stuff" class="anchored">Stats stuff</h3>
<ul>
<li><strong>A GLMM frees two constants at once.</strong> The family decrees the link and the variance function (Class 3); the grouping term frees the correlation between rows (Class 6). Neither repair changes what the other does, and the call is one line.</li>
<li><strong>The standard error was the thing most wrong, and it was wrong in two separable ways.</strong> On this file the brood term multiplied the slope’s standard error by 1.61. Part of that is the coefficient changing size, because the mixed slope is conditional and the naive one marginal; part is siblings treated as strangers, and that part — the naive standard error against its own target, by simulation — is a shortfall of 12.2%. Class 6’s rule covers the second part and not the first.</li>
<li><strong>σ_b lives on the link scale.</strong> For a logit link the brood standard deviation is in log-odds, and there is no σ to divide it by, because the family spent it. To get a ratio you must supply a denominator, and the usual one is <strong>latent</strong>: the standard logistic distribution’s variance, π²/3. Report the resulting ICC as <strong>latent-scale</strong>, always (Nakagawa &amp; Schielzeth 2010). Switch to a probit link and the denominator becomes 1 and the number changes with no change to any bird. Data-scale alternatives exist and are not the same quantity (Nakagawa, Johnson &amp; Schielzeth 2017).</li>
<li><strong>Conditional and marginal odds ratios are different quantities, and both are correct.</strong> The GLMM coefficient is <strong>conditional</strong>: it compares two chicks in the same brood. Averaging the fitted curve over the distribution of broods gives a <strong>marginal</strong> curve that is flatter, and a marginal odds ratio closer to one. This is non-collapsibility, and it is not bias. It holds for logit, probit and complementary log-log, not for the log link, which is collapsible for the rate ratio. On this file the marginal slope keeps 65% of the conditional one; the naive fit was estimating a different, defensible quantity, with an interval that was wrong for either.</li>
<li><strong>A likelihood-ratio test for a variance component stands on a boundary.</strong> The engine says so in a warning and names the corrected entry point. Here the correction changes nothing anybody would act on; Class 8 is where it changes everything. The interesting number in this section was never the p-value.</li>
<li><strong>Levels, not significance, decide whether a grouping can be random.</strong> Bolker et al.&nbsp;(2009) put the working floor near five or six levels and say to use a fixed effect below it; <code>Year</code> has 4, so it went into the mean model.</li>
<li><strong>Check nesting from the data, and be willing to answer “neither”.</strong> No brood in this file spans two years, so brood is nested inside year rather than crossed with it. <code>Mum</code> is not so tidy: 184 of the 484 broods carry more than one mother, and a mother holds up to 17 broods, which makes the two <strong>partially crossed</strong>. Counting in the file is what settles this; the formula never will.</li>
<li><strong>Shrinkage is not a refinement on a binary response; it is often the only estimate there is.</strong> 270 of the 484 broods in this file are unanimous — every chick died, or every chick lived — and for those a fixed effect per brood has no finite estimate. The mixed model returns a finite, different number for each of them, pulled less the more chicks the nest had. That is the population supplying what the nest could not.</li>
<li><strong>Ask which distribution a residual is judged against.</strong> Randomised quantile residuals are standard normal under a correct model only if each observation is compared with its own correct probability. <code>fitted</code> on a GLMM sets every group effect to zero, and on a nonlinear link that is <em>not</em> the average over groups: judged against the u = 0 probabilities the spread was 1.054, and against the probability averaged over broods it was 1.014. A per-observation check cannot see the correlation the model was fitted to handle.</li>
<li><strong>The likelihood has an integral in it, and packages approximate it differently.</strong> <code>glmer</code> and <code>drmTMB</code> default to <strong>Laplace</strong> (brood SD 1.700, from the box); ours is a fixed thirty-two-node Gauss–Hermite grid (1.8609); <code>glmer</code> at <code>nAGQ &gt; 1</code> re-centres that grid at each group’s own mode (1.860915 from the box). Name the approximation next to the number, as Class 8 taught you to name the estimator.</li>
</ul>
<h3 id="julia-stuff" class="anchored">Julia stuff</h3>
<ul>
<li><code>CSV.read(path, DataFrame; missingstring = ["NA", ""])</code>: <code>missingstring</code> <strong>replaces</strong> the list of missing markers rather than adding to it, and the empty string is on the default list. A file that uses both conventions needs both spelled out, or every column silently becomes text with nothing missing in it.</li>
<li><code>drm(bf(@formula(y ~ x + (1|g))), Binomial(); data = df)</code>: the whole of a GLMM. The family is Class 3’s and the grouping term is Class 6’s; nothing else about the call changes.</li>
<li><code>re_sd(fit)[:g]</code>: the group SD, here on the <strong>log-odds</strong> scale. <code>vc(fit)</code> gives the variance instead. There is no <code>sigma(fit)</code> on a binomial fit, and its absence is the family’s decree, not an omission.</li>
<li><code>lrtest(reduced, full)</code> warns when the added block is a variance component and points at <code>lrt_boundary(full, reduced; q = k)</code>, which uses the chi-bar-squared mixture — a blend of chi-squared distributions that is the right reference when a variance is tested at zero. Class 8.</li>
<li><code>fitted(fit)</code> on a mixed fit is the prediction with every group effect <strong>set to zero</strong>, which on a nonlinear link is not the average over groups. Average the curve yourself if what you want is marginal.</li>
<li><code>residuals(fit; type = :quantile, rng = MersenneTwister(seed))</code>: as in Class 3, and pass the <code>rng</code>. Check what probability it is judging each observation against before you read the spread as a verdict on the model.</li>
<li>A grouping or factor variable that is stored as a number should be converted to text first (<code>string.(df.Year)</code>), or the formula will treat it as a covariate.</li>
<li><strong>Seeding.</strong> Every random draw on this page — the jitter, both sets of quantile residuals, and the brood draws in every simulation — comes from an explicit <code>MersenneTwister</code> handed to the function that needs it. Never the global generator, and never <code>Random.seed!</code>.</li>
<li><strong>The simulation thread.</strong> One cell, and it is the trap Class 6 met, on a new family.</li>
</ul>
<div id="simulate-refit" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>rng_sim <span class="op">=</span> <span class="fu">MersenneTwister</span>(<span class="fl">20260907</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ysim <span class="op">=</span> <span class="fu">simulate</span>(glmm_fit; nsim <span class="op">=</span> <span class="fl">1</span>, rng <span class="op">=</span> rng_sim)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>one_rep <span class="op">=</span> <span class="fu">DataFrame</span>(Survival <span class="op">=</span> <span class="fu">Int</span>.(ysim[<span class="op">:</span>, <span class="fl">1</span>]), Mass2 <span class="op">=</span> chicks.Mass2,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                    BroodNo <span class="op">=</span> chicks.BroodNo)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>zero_refit <span class="op">=</span> <span class="fu">drm</span>(<span class="fu">bf</span>(<span class="pp">@formula</span>(Survival <span class="op">~</span> Mass2 <span class="op">+</span> (<span class="fl">1</span><span class="op">|</span>BroodNo))), <span class="fu">Binomial</span>(); data <span class="op">=</span> one_rep);</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>┌ Warning: Hessian is numerically singular at the optimum — using a pseudo-inverse.
│ The fit is at a variance/dispersion boundary, so standard errors for the
│ flagged coordinates are NOT trustworthy. Prefer `confint(fit, method = :profile)`
│ or the bootstrap entry points for those targets.
│   context = ""
│   flat_coordinates =
│    1-element Vector{Int64}:
│     3
│   rcond = 6.24321165338485e-20</code></pre>
</div>
</div>
<div id="simulate-read" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"responses simulate() produced   : %s</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">sort</span>(<span class="fu">unique</span>(ysim)))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"brood SD refitted from that draw: %.4f</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">re_sd</span>(zero_refit)[<span class="op">:</span>BroodNo])</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="pp">@printf</span>(<span class="st">"brood SD in the fit it came from: %.4f</span><span class="sc">\n</span><span class="st">"</span>, sigma_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>responses simulate() produced   : [0.0, 1.0]
brood SD refitted from that draw: 0.0000
brood SD in the fit it came from: 1.8609</code></pre>
</div>
</div>
<p><code>simulate</code> gives back nought-and-one responses, because it draws from the family the fit was given; and the refit puts the brood standard deviation on the boundary at zero, because — as Class 6 found — <code>simulate</code> draws with every group effect set to zero. To ask whether the brood variance is recoverable, draw the brood effects yourself, as the marginal simulation above did; how to turn that into a recovery or coverage study, and how many refits one honestly needs, is <a href="appendix-a-simulation.html">Appendix A</a>.</p>
<hr>
<h2 id="further-reading" class="anchored">Further reading</h2>
<p class="aside">Graded by depth. Checked on 2026-09-07 against OpenAlex, an open
catalogue of research papers.</p>
<ol type="1">
<li><strong>Bolker, B. M., Brooks, M. E., Clark, C. J., Geange, S. W., Poulsen, J. R., Stevens, M. H. H. &amp; White, J.-S. S. (2009) “Generalized linear mixed models: a practical guide for ecology and evolution”, <em>Trends in Ecology &amp; Evolution</em> 24:127–135.</strong> doi:10.1016/j.tree.2008.10.008. Start here: the paper that put this chapter in front of biologists, including the estimation choices that make packages disagree and how many levels a random effect needs.</li>
<li><strong>Nakagawa, S. &amp; Schielzeth, H. (2010) “Repeatability for Gaussian and non-Gaussian data: a practical guide for biologists”, <em>Biological Reviews</em> 85:935–956.</strong> doi:10.1111/j.1469-185X.2010.00141.x. Class 6’s source, and the reason this chapter’s ICC has the word “latent” attached to it: where π²/3 comes from and what the alternatives are.</li>
<li><strong>Harrison, X. A., Donaldson, L., Correa-Cano, M. E., Evans, J., Fisher, D. N., Goodwin, C. E. D., Robinson, B. S., Hodgson, D. J. &amp; Inger, R. (2018) “A brief introduction to mixed effects modelling and multi-model inference in ecology”, <em>PeerJ</em> 6:e4794.</strong> doi:10.7717/peerj.4794. The practical companion to item 1: small numbers of levels, singular fits, and the model-selection habits that go wrong around random effects.</li>
<li><strong>Nakagawa, S., Johnson, P. C. D. &amp; Schielzeth, H. (2017) “The coefficient of determination R² and intra-class correlation coefficient from generalized linear mixed-effects models revisited and expanded”, <em>Journal of the Royal Society Interface</em> 14:20170213.</strong> doi:10.1098/rsif.2017.0213. Where the latent-scale ratio sits among the alternatives, and how to get a data-scale version when that is the quantity you want.</li>
<li><strong>Zuur, A. F., Ieno, E. N., Walker, N. J., Saveliev, A. A. &amp; Smith, G. M. (2009) <em>Mixed Effects Models and Extensions in Ecology with R</em>, Springer.</strong> doi:10.1007/978-0-387-87458-6. The GLMM chapters are written for biologists with awkward nested data, and take the time on what a random effect buys that this chapter had to compress.</li>
<li><strong>Pinheiro, J. C. &amp; Bates, D. M. (1995) “Approximations to the log-likelihood function in the nonlinear mixed-effects model”, <em>Journal of Computational and Graphical Statistics</em> 4:12–35.</strong> doi:10.1080/10618600.1995.10474663. The source for the box: what Laplace and the two Gauss–Hermite rules do to the integral, and why the answers differ by an amount that depends on the data.</li>
<li><strong>Dunn, P. K. &amp; Smyth, G. K. (1996) “Randomized quantile residuals”, <em>Journal of Computational and Graphical Statistics</em> 5:236–244.</strong> doi:10.1080/10618600.1996.10474708. Class 3’s diagnostic; reread it asking “which distribution is F_i?”, because in a mixed model that is a choice and not a given.</li>
</ol>
<hr>
<h2 id="exercises" class="anchored">Exercises</h2>
<p>Use your own organism where one is named. <strong>For every question, paste your code and then explain in your own words what each line does</strong>, as if to somebody who has done Classes 3 and 6 and not Class 9.</p>
<ol type="1">
<li><p><strong>Find the grouping, then break the file.</strong> Take a binary response of your own with a grouping column. Report the number of rows, the number of groups, and the distribution of observations per group. Then read the file once with the wrong <code>missingstring</code> and once with the right one, and report how many rows each version gives you. One sentence on what would have happened if you had never checked.</p></li>
<li><p><strong>Both fits, both standard errors, one dataset.</strong> Fit your response with and without <code>(1 | group)</code>, on the same rows. Report both slopes and both standard errors and the two ratios. Before you look, predict the direction of the standard-error change from how much your predictor varies within groups versus between them — <strong>compute</strong> that split with a Gaussian random-intercept model on the predictor itself, do not eyeball it. Afterwards say whether you were right, and which part of the change your prediction could not have covered.</p></li>
<li><p><strong>Name the scale.</strong> Compute the latent-scale ICC from <code>re_sd(fit)</code> and π²/3. Then write the single sentence you would put in a paper, containing the word “latent” and the name of your link function. Now refit with a probit link if your engine offers one, recompute, and say in one sentence why the two numbers differ although the birds did not.</p></li>
<li><p><strong>Conditional or marginal?</strong> Report your fit’s odds ratio. Then adapt the chapter’s thousand-worlds simulation — your own seed — to get the marginal one. Report both. Then find a sentence in a paper in your field that reports an odds ratio from a mixed model and decide which of the two the sentence is claiming. If you cannot tell, that is the answer, and say so.</p></li>
<li><p><strong>Too few levels.</strong> Add a random intercept for a factor in your data with four or fewer levels, and report the variance component it prints and its standard error. Then refit with the same factor as a fixed effect instead. In three sentences: what did the random version claim to estimate, why would you not report it, and what does the fixed version report in its place?</p></li>
<li><p><strong>Count the design before you trust the formula.</strong> <code>data/2012/SparrowSurvival.csv</code> carries a <code>Mum</code> column with 126 levels. Count how many of the 484 broods carry more than one <code>Mum</code>, and how many broods a mother holds; the chapter makes it 184 and up to 17. Say which of “nested”, “crossed” and “neither” describes <code>Mum</code> against <code>BroodNo</code>, and why the formula could never have told you. Then fit <code>(1|BroodNo)</code> and <code>(1|MumF)</code> <strong>separately</strong> on the same rows and say which grouping the chicks share more of their fate through.</p></li>
<li><p><strong>The broods with no answer.</strong> For your own grouped binary data, count the groups in which the response is unanimous. Report the number and the fraction. Then explain in two sentences why a fixed-effect-per-group model cannot give those groups a finite estimate, and what the mixed model used instead.</p></li>
</ol>
<p><strong>If you have R.</strong> Fit the same model with <code>glmer</code> at <code>nAGQ = 1</code>, <code>nAGQ = 9</code> and <code>nAGQ = 25</code>, and report all three group standard deviations and all three log-likelihoods. Then write the methods sentence you would use, containing both the estimator and the integral approximation. In the chapter’s box the log-likelihood at nine is higher than at twenty-five, and twenty-five is the converged answer, so “believe the higher log-likelihood” is not available to you: say in two sentences what evidence you would use instead.</p>

<div id="3ade8a4a-fb1d-4a6c-8409-ac45482d5fc9" class="hidden">

</div>
<nav class="chapter-nav" aria-label="Chapter">
  <a class="chapter-nav-link prev" href="wk8-reml-vs-ml.html"><span class="chapter-nav-dir">Previous</span><span class="chapter-nav-dest">Class 8 · Same model, two answers</span></a><a class="chapter-nav-link next" href="wk10-relatedness.html"><span class="chapter-nav-dir">Next</span><span class="chapter-nav-dest">Class 10 · Not even the groups are strangers</span></a>
</nav>
<footer>
  Stats Hours with Itchy · Class 9 of a planned 13, ten in v1, plus a coda · draft, built 2026-09-07<br>
  Text, figures and data are <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>; code is GPL-3.
</footer>
</div>

<script>
// Highlight REPL prompts and error lines without shipping a syntax highlighter.
document.querySelectorAll('pre code').forEach(function (block) {
  if (block.querySelector('span')) return; // hand-marked blocks stay as authored
  var html = block.innerHTML
    .replace(/^(julia&gt; )/gm, '<span class="p">$1</span>')
    .replace(/^(ERROR: .*)$/gm, '<span class="err">$1</span>');
  block.innerHTML = html;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
  tabsets.forEach(function(tabset) {
    const tabby = new Tabby('#' + tabset.id);
  });
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>




</body></html>